/**
 * OG / Pinterest image URL helper.
 *
 * The 1000x1500 OG images are generated by `scripts/generate-og.ts` and served
 * from an external host (Cloudflare R2, e.g. https://img.pickly.blog) so they
 * do NOT count against Cloudflare Pages' 20,000-files-per-deployment Free-plan
 * limit. Set NEXT_PUBLIC_OG_BASE_URL to that host in CI. When unset (local dev),
 * it falls back to the site itself.
 */
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "https://pickly.blog";

/** Base host serving the generated OG images (no trailing slash). */
export const OG_BASE_URL = process.env.NEXT_PUBLIC_OG_BASE_URL || SITE_URL;

/** Absolute URL of an article's auto-generated 1000x1500 OG image. */
export function ogImageUrl(slug: string, locale: string): string {
  return `${OG_BASE_URL}/og/${slug}-${locale}.png`;
}

/**
 * Site-wide default OG image (1200x630), used by every non-article page.
 * Generated by `scripts/generate-brand-og.ts` and committed under public/ —
 * one file, so it doesn't move the needle on the Pages file-count limit.
 * Article pages override this with their own 1000x1500 pin.
 */
export const DEFAULT_OG_IMAGE = `${SITE_URL}/images/og-default.png`;

export const DEFAULT_OG_IMAGES = [
  { url: DEFAULT_OG_IMAGE, width: 1200, height: 630, alt: "Pickly" },
];
