import json, os, re

DIR = "/tmp/pickly-deploy/site/src/articles/best-sunscreen-2026/messages"

def setp(d, path, val):
    o=d; parts=path.strip('/').split('/')
    for part in parts[:-1]:
        m=re.match(r'(\w+)\[(\d+)\]$',part)
        o=o[m.group(1)][int(m.group(2))] if m else o[part]
    last=parts[-1]; m=re.match(r'(\w+)\[(\d+)\]$',last)
    if m: o[m.group(1)][int(m.group(2))]=val
    else: o[last]=val

# path -> {locale: full new text}
FIX = {
 "sections[5]/paragraphs[2]": {
  "en": "Indoor UV awareness became a mainstream skincare talking point in 2026. Research on UVA penetration through window glass — UVB is almost entirely blocked by standard glass, but UVA (particularly long-wave UVA) penetrates at 50-75% transmission through typical window glass — has driven an increase in SPF-on-non-beach-days adoption. Office workers and remote workers who previously skipped sunscreen on indoor-only days are increasingly applying SPF as a daily base step. This behavioral shift is the primary growth driver for lightweight, makeup-compatible formulas like CeraVe Hydrating Mineral Sunscreen and La Roche-Posay Anthelios Tinted Mineral Sunscreen, which are well-suited to indoor daily wear where outdoor-sport water resistance is irrelevant.",
  "ko": "실내 UV 인식이 2026년 스킨케어의 주류 이야기 주제가 되었습니다. 유리창을 통한 UVA 침투에 관한 연구 — UVB는 표준 유리에 의해 거의 완전히 차단되지만, UVA(특히 장파장 UVA)는 일반 유리창을 통해 50-75% 투과율로 침투합니다 — 는 해변이 아닌 날의 SPF 사용 증가를 이끌었습니다. 이전에 실내 전용 날에 선크림을 건너뛰던 사무직 및 재택 근무자들이 점점 더 일일 기본 단계로 SPF를 바르고 있습니다. 이 행동 변화는 야외 스포츠 내수성이 관련 없는 실내 일상 착용에 적합한 세라비 하이드레이팅 미네랄 선크림 및 라 로슈 포제 안텔리오스 틴티드 미네랄 선크림과 같은 가볍고 메이크업 호환 포뮬러의 1차 성장 동인입니다.",
 },
 "sections[7]/paragraphs[2]": {
  "en": "For acne-prone or sensitive skin where ingredient profile matters as much as protection level: EltaMD UV Clear. The niacinamide is doing real skincare work beyond UV protection, and the zinc oxide base is among the most sensitive-skin-appropriate UV filters available. The SPF46 is the only honest reason to hesitate — in practice, the difference between SPF46 and SPF50 in real-world conditions (where most people apply 25-50% of the recommended amount anyway) is small, but if maximum protection is the priority, Anessa technically exceeds it.",
  "ko": "성분 프로파일이 보호 수준만큼 중요한 여드름 또는 민감성 피부에: EltaMD UV Clear. 나이아신아마이드는 UV 보호 외에도 실질적인 스킨케어 작업을 하고 있으며, 산화아연 베이스는 민감한 피부에 가장 적합한 UV 필터 중 하나입니다. SPF46은 망설일 유일한 정직한 이유입니다 — 실제로 대부분의 사람들이 권장량의 25-50%를 바르는 실제 조건에서 SPF46과 SPF50의 차이는 작지만, 최대 보호가 우선이라면 Anessa가 기술적으로 이를 초과합니다.",
 },
 "faqs[4]/a": {
  "en": "Yes. Sunscreen has a shelf life, and expired sunscreen is a real concern — not a marketing gimmick. In the EU, sunscreens must carry a PAO (Period After Opening) symbol (an open jar with a number, typically 12M or 24M) indicating how many months the product remains effective after opening, plus a best-before date printed on the packaging. The SPF actives — both chemical UV filters and physical mineral particles — can degrade, separate, or lose efficacy over time, particularly after opening, exposure to heat, and temperature cycling. Practical indicators that sunscreen has gone off: visible separation that does not re-homogenize when shaken, change in texture from original consistency, unusual or rancid odor, or a date past the PAO on the packaging. All five products in this comparison are formulated with preservative systems appropriate for their PAO ratings, but Anessa's squeeze-tube format and CeraVe's tube packaging are more resistant to oxidation than jar or pump formats — if you decant any sunscreen into a separate container, reduce the assumed shelf life.",
  "ko": "네. 선크림은 유효 기간이 있으며, 만료된 선크림은 실질적인 우려입니다 — 마케팅 상술이 아닙니다. EU에서 선크림은 PAO(개봉 후 사용 기간) 기호(숫자가 있는 열린 항아리, 일반적으로 12M 또는 24M)를 표시해야 하며, 이는 개봉 후 제품이 효과적으로 유지되는 개월 수를 나타내며, 포장에 인쇄된 유통 기한도 있습니다. SPF 활성 성분 — 화학 UV 필터와 물리적 미네랄 입자 모두 — 은 특히 개봉 후, 열 노출, 온도 순환 후 시간이 지남에 따라 분해되거나 분리되거나 효능을 잃을 수 있습니다. 선크림이 상했다는 실용적인 지표: 흔들어도 재균질화되지 않는 가시적인 분리, 원래 일관성에서 텍스처 변화, 비정상적이거나 부패한 냄새, 또는 포장의 PAO를 지난 날짜. 이 비교의 5가지 제품 모두 PAO 등급에 적합한 보존 시스템으로 포뮬러되어 있지만, Anessa의 압착 튜브 형식과 CeraVe의 튜브 포장은 항아리나 펌프 형식보다 산화에 더 강합니다 — 선크림을 별도의 용기로 옮기면 예상 유효 기간을 줄이세요.",
 },
 "sections[3]/paragraphs[1]": {
  "fr": "La conséquence pratique est que le Japon a approuvé des filtres UV que les États-Unis n'ont pas approuvés — dont la famille Tinosorb, des filtres Mexoryl avancés et des combinaisons qui produisent des textures plus légères à protection SPF50+ équivalente. C'est pourquoi Anessa Perfect UV a la sensation de l'eau à l'application mais réussit quand même les tests PA++++ et SPF50+ : il utilise des combinaisons de filtres haute performance que les formulateurs américains ne peuvent pas utiliser légalement dans les produits réglementés par la FDA.",
  "it": "La conseguenza pratica e che il Giappone ha approvato filtri UV che gli USA non hanno — inclusa la famiglia Tinosorb, i filtri Mexoryl avanzati e combinazioni che producono texture piu leggere a protezione SPF50+ equivalente rispetto a qualsiasi formula ottenibile solo con i filtri attivi approvati dalla FDA. Ecco perche Anessa Perfect UV sembra acqua quando applicato ma supera ancora i test PA++++ e SPF50+: usa combinazioni di filtri ad alte prestazioni che i formulatori statunitensi non possono legalmente usare nei prodotti regolamentati dalla FDA.",
  "ko": "실제적인 결과는 일본이 미국이 승인하지 않은 UV 필터를 승인했다는 것입니다 — Tinosorb 계열, 고급 Mexoryl 필터, 그리고 FDA 승인 활성 성분만으로 달성 가능한 어떤 포뮬러보다 동등한 SPF50+ 보호에서 더 가벼운 텍스처를 생성하는 조합들. 이것이 Anessa Perfect UV가 도포 시 물처럼 느껴지지만 PA++++ 및 SPF50+ 테스트를 통과하는 이유입니다: 미국 포뮬러 개발자가 FDA 규제 제품에서 합법적으로 사용할 수 없는 고성능 필터 조합을 사용합니다. 결과적으로 이렇게 일본에서 승인된 선크림은 많은 미국 프리미엄 가격 선크림보다 텍스처에서, 그리고 종종 UVA 커버리지에서도 우월합니다 — 일본 브랜드가 R&D에 더 많이 투자해서가 아니라 더 넓은 승인 성분 팔레트에 접근할 수 있기 때문입니다.",
  "pt-BR": "A consequência prática é que o Japão aprovou filtros UV que os EUA não aprovaram — incluindo a família Tinosorb, filtros Mexoryl avançados e combinações que produzem texturas mais leves a proteção SPF50+ equivalente. É por isso que o Anessa Perfect UV se sente como água quando aplicado mas ainda passa nos testes PA++++ e SPF50+: ele usa combinações de filtros de alto desempenho que formuladores americanos não podem usar legalmente em produtos regulados pelo FDA.",
 },
 "sections[4]/paragraphs[0]": {
  "es": "La sombra blanca del protector solar no es una experiencia uniforme en todos los tonos de piel, y la mayoría de las reseñas de protectores solares escritas desde una perspectiva de piel clara subestiman sistemáticamente cuánto importa para los tonos de piel medios a oscuros. En esta comparación: Anessa Perfect UV usa principalmente un sistema de filtro químico que produce mínima a ninguna sombra blanca. CeraVe Hydrating Mineral Sunscreen, al ser 100 % mineral, puede dejar un ligero velo blanco en tonos de piel más oscuros. La Roche-Posay Anthelios UVMune 400 usa filtros Mexoryl y produce esencialmente ninguna sombra blanca.",
 },
 "sections[4]/paragraphs[1]": {
  "es": "EltaMD UV Clear contiene óxido de zinc, y aunque la concentración es más baja que una fórmula puramente mineral, varios comentarios de piel media a oscura notan específicamente un acabado ceniciento en la aplicación. La Roche-Posay Anthelios Tinted Mineral Sunscreen está diseñado para dejar un tono universal suave: unifica la piel y difumina rojeces en lugar de igualar exactamente cada complexión, por lo que un único tono se ve ligeramente distinto según el tono de piel. Es la limitación de ajuste más clara de la comparación y conviene hacer una prueba rápida antes de comprarlo.",
  "fr": "Dans cette comparaison : Anessa Perfect UV utilise principalement un système de filtres chimiques qui produit un voile blanc minimal à nul sur la plupart des carnations. CeraVe Hydrating Mineral Sunscreen, étant 100 % minéral, peut laisser un léger voile blanc sur les carnations plus foncées. La Roche-Posay Anthelios UVMune 400 utilise des filtres Mexoryl plutôt que des composants minéraux et ne produit pratiquement aucun voile blanc. EltaMD UV Clear contient de l'oxyde de zinc, et plusieurs avis de personnes à carnation moyenne à foncée notent spécifiquement un fini grisâtre à l'application. La Roche-Posay Anthelios Tinted Mineral Sunscreen est conçu pour laisser une teinte universelle douce : il unifie le teint et floute les rougeurs plutôt que de correspondre exactement à chaque carnation, si bien qu'une teinte unique apparaît légèrement différente selon les peaux.",
  "it": "In questo confronto: Anessa Perfect UV utilizza un sistema di filtri prevalentemente chimici che produce un alone minimo a zero sulla maggior parte delle carnagioni. CeraVe Hydrating Mineral Sunscreen, essendo 100 % minerale, può lasciare un leggero velo bianco sulle carnagioni più scure. La Roche-Posay Anthelios UVMune 400 usa filtri Mexoryl anziche componenti minerali e produce essenzialmente nessun alone nella formulazione UE. EltaMD UV Clear contiene ossido di zinco, e sebbene la concentrazione sia inferiore a una formula puramente minerale, le recensioni di pelle da media a scura notano specificamente una finitura grigiastra sull'applicazione.",
  "ko": "이 비교에서: Anessa Perfect UV는 주로 화학적 필터 시스템을 사용하여 대부분의 피부 톤에서 최소한에서 거의 없는 백탁 현상을 생성합니다 — 하지만 Anessa의 스마트 반응 포뮬러는 매우 따뜻한 언더톤에서 약간 차가워 보일 수 있는 약간의 밝아지는 마감을 남깁니다. 세라비 하이드레이팅 미네랄 선크림은 100% 미네랄이라 어두운 피부 톤에서는 블렌딩이 필요한 약간의 백탁이 남을 수 있습니다. La Roche-Posay Anthelios UVMune 400은 미네랄 성분 대신 Mexoryl 필터를 사용하며 EU 포뮬러에서는 사실상 백탁 현상이 없습니다. EltaMD UV Clear에는 산화아연이 포함되어 있으며, 농도가 순수 미네랄 포뮬러보다 낮지만, 여러 중간에서 어두운 피부 리뷰들은 도포 시 블렌딩이 필요한 재 빛 마감을 구체적으로 지적합니다. 라 로슈 포제 안텔리오스 틴티드 미네랄 선크림은 은은한 유니버설 틴트를 남기도록 설계되었습니다: 모든 피부 톤에 정확히 맞추기보다 피부 톤을 고르게 하고 붉은기를 가리므로, 단일 색조는 피부 톤에 따라 약간 다르게 보입니다. 이것은 비교에서 가장 분명한 적합성 관련 주의점이며 구매 전에 스와치로 확인하는 것이 좋습니다.",
  "pt-BR": "Nesta comparação: Anessa Perfect UV usa predominantemente um sistema de filtros químicos que produz efeito branco mínimo a nulo na maioria dos tons de pele. O CeraVe Hydrating Mineral Sunscreen, por ser 100 % mineral, pode deixar um leve véu branco em tons de pele mais escuros. La Roche-Posay Anthelios UVMune 400 usa filtros Mexoryl em vez de componentes minerais e produz essencialmente nenhum efeito branco. EltaMD UV Clear contém óxido de zinco, e várias avaliações de tons médios a escuros especificamente notam um acabamento acinzentado na aplicação. O La Roche-Posay Anthelios Tinted Mineral Sunscreen é projetado para deixar um tom universal suave: uniformiza a pele e disfarça vermelhidões em vez de igualar exatamente cada pele, então um único tom aparece ligeiramente diferente conforme o tom de pele.",
 },
 "sections[4]/paragraphs[2]": {
  "fr": "Pour la photographie au flash, le classement du voile blanc change : même des formules sans voile visible dans des conditions normales peuvent produire un reflet blanc brillant en photographie au flash si elles contiennent des ingrédients qui réfléchissent fortement les UV ou les longueurs d'onde proches de l'UV. Les formules minérales comme CeraVe Hydrating Mineral Sunscreen peuvent montrer un léger flashback sur les photos, car l'oxyde de zinc et le dioxyde de titane réfléchissent la lumière, malgré un faible voile en lumière du jour standard.",
  "it": "Per la fotografia con flash, la classifica dell'alone bianco cambia: anche le formule senza alone visibile in luce normale possono produrre un forte bagliore bianco nella fotografia con flash se contengono ingredienti che riflettono fortemente le lunghezze d'onda UV o vicino-UV. Le formule minerali come CeraVe Hydrating Mineral Sunscreen possono mostrare un leggero flashback nelle foto, perche ossido di zinco e biossido di titanio riflettono la luce, nonostante il basso alone alla luce diurna standard.",
  "ko": "플래시 사진의 경우 백탁 현상 순위가 달라집니다: 일반 빛에서 가시적인 백탁 현상이 없는 포뮬러도 UV 또는 근자외선 파장을 강하게 반사하는 성분이 포함되어 있으면 플래시 사진에서 밝은 흰색 번쩍임을 생성할 수 있습니다. 세라비 하이드레이팅 미네랄 선크림 같은 미네랄 포뮬러는 산화아연과 이산화티타늄이 빛을 반사하기 때문에, 낮의 표준 조건에서 백탁이 낮더라도 사진에서 약간의 플래시백이 나타날 수 있습니다. 플래시로 자주 촬영된다면, 촬영 20-30분 전에 선크림을 도포하고 잉여분을 블로팅(SPF 층을 문질러 제거하지 말고 — 표면 과잉 포뮬러만 제거)하면 이 효과가 줄어듭니다.",
  "pt-BR": "Para fotografia com flash, o ranking do efeito branco muda: mesmo fórmulas sem efeito branco visível em condições normais podem produzir um reflexo branco brilhante em fotografia com flash se contiverem ingredientes que refletem UV ou comprimentos de onda próximos ao UV. Fórmulas minerais como o CeraVe Hydrating Mineral Sunscreen podem mostrar um leve flashback nas fotos, porque óxido de zinco e dióxido de titânio refletem a luz, apesar do baixo efeito branco em luz do dia padrão.",
 },
 "sections[7]/paragraphs[1]": {
  "es": "Para actividad al aire libre, días de playa o cualquier contexto donde vayas a sudar significativamente: Anessa Perfect UV. La fórmula de respuesta inteligente y la resistencia genuina al agua la hacen adecuada para contextos donde CeraVe Hydrating Mineral Sunscreen se queda corto.",
  "fr": "Pour l'activité de plein air, les jours de plage ou tout contexte où vous transpirerez significativement : Anessa Perfect UV. La formule à réponse intelligente et la résistance à l'eau réelle la rendent adaptée aux contextes où CeraVe Hydrating Mineral Sunscreen est insuffisant. Acceptez la nécessité d'un double nettoyage complet et le potentiel de légère irritation oculaire lors de sport intense.",
  "it": "Per le attivita all'aperto, le giornate in spiaggia o qualsiasi contesto in cui si sudi significativamente: Anessa Perfect UV. La formula smart-response e la vera resistenza all'acqua la rendono appropriata per i contesti in cui CeraVe Hydrating Mineral Sunscreen non e all'altezza. Accettare la necessita di un doppio detergente accurato e il potenziale di una leggera puntura agli occhi durante lo sport intenso.",
  "ko": "야외 활동, 해변 나들이, 또는 크게 땀을 흘릴 상황에: Anessa Perfect UV. 스마트 반응 포뮬러와 진정한 내수성은 세라비 하이드레이팅 미네랄 선크림이 부족한 상황에 적합합니다. 철저한 이중 클렌징의 필요성과 격렬한 스포츠 중 가벼운 눈 따가움 가능성을 받아들이고, 해변 가기 전에 특정 피부 톤에서 백탁 현상을 패치 테스트하세요.",
  "pt-BR": "Para atividade ao ar livre, dias de praia ou qualquer contexto onde você transpirará significativamente: Anessa Perfect UV. A fórmula de resposta inteligente e a resistência genuína à água a tornam adequada para contextos onde o CeraVe Hydrating Mineral Sunscreen fica aquém. Aceite a necessidade de limpeza dupla completa e o potencial de leve irritação ocular durante esportes intensos.",
 },
}

for loc in ["en","es","fr","it","ko","pt-BR"]:
    fp=os.path.join(DIR, loc+".json")
    d=json.load(open(fp, encoding="utf-8"))
    for path, perloc in FIX.items():
        if loc in perloc:
            setp(d, path, perloc[loc])
    json.dump(d, open(fp,"w",encoding="utf-8"), ensure_ascii=False, indent=2)
    print("fixed:", loc)
