import json, os

DIR = "/tmp/pickly-deploy/site/src/articles/best-slow-cooker-2026/messages"

# Per-locale content. Keys map to the JSON paths we overwrite.
# Product names kept in Latin script across locales.
HB = "Hamilton Beach Set & Forget 33967"
CP = "Crock-Pot 2-Quart Mini (SCCPMC225)"

T = {}

T["de"] = {
  "description": "Fünf Slow Cooker im Vergleich 2026: Crock-Pot 6-Quart, Instant Pot Duo, Cuisinart CSC-800, Hamilton Beach Set & Forget 33967 und der Crock-Pot 2-Quart Mini. Fassungsvermögen, Programmierbarkeit und welcher zu deinem Kochstil passt.",
  "lede": "Fünf Slow Cooker – vom einfachen Drei-Stufen-Gerät über eine sondengesteuerte programmierbare Variante bis zum kompakten 2-Quart-Mini. Nicht die Rezeptvielfalt, sondern die wöchentliche Nutzungshäufigkeit entscheidet, welche Spezifikation wirklich zählt.",
  "s0p1": "Es gibt auch einen zweiten Strang in der Geschichte des Slow Cookers. Manche Modelle ergänzen eine Sonde, um das Rätselraten bei langen Garzeiten zu beenden: ein Braten, der eine Zieltemperatur im Kern statt einer Uhr braucht, ein Schmorgericht, das genau bei Erreichen der Temperatur auf Warmhalten umschalten soll, ein Topf Bohnen, den man lieber nicht übergart. Andere schrumpfen das ganze Format auf einen 2-Quart-Mini für Beilagen, Dips und kleine Mengen, die in einem 6-Quart-Topf umständlich sind.",
  "s3p2": "Die ehrliche Einschränkung: Das Fassungsvermögen von 3,5 Quart des Cuisinart CSC-800 ist für eine vierköpfige Familie mit einem ganzen Braten klein. Wer einen größeren Topf plus eine Temperatursonde will, die selbsttätig auf Warmhalten umschaltet, für den ist der Hamilton Beach Set & Forget 33967 die Alternative.",
  "s4h": "Hamilton Beach Set & Forget 33967 – sondengesteuert und programmierbar",
  "s4p0": "Der Hamilton Beach Set & Forget 33967 ist um ein Merkmal herum gebaut: eine einsteckbare Temperatursonde. Statt eine feste Stundenzahl zu garen und auf das richtige Ergebnis zu hoffen, stellst du eine Zielkerntemperatur ein, und das Gerät schaltet genau dann auf Warmhalten, wenn die Speise sie erreicht. Bei einem Braten oder einem großen Stück, bei dem der Garpunkt wichtiger ist als die verstrichene Zeit, beseitigt das die Hauptfehlerquelle beim Slow Cooking.",
  "s4p1": "Er bietet auch herkömmliches programmierbares Garen – stelle eine Garzeit auf High oder Low ein, und er zählt herunter und wechselt automatisch ins Warmhalten. Der 6-Quart-Steinguttopf ist groß genug für einen Familienbraten mit Gemüse, und der Deckel klemmt fest, was ihn praktisch zum Transport zu einem Mitbringbuffet macht, ohne dass der Inhalt schwappt.",
  "s4p2": "Der Kompromiss: Sonde und Programmlogik fügen gegenüber einem einfachen Drei-Stufen-Gerät einen Schritt hinzu, und das Gerät nimmt mehr Platz auf der Arbeitsfläche ein. Für alle, die nur am einfachen Drehregler einstellen und weggehen, ist diese Komplexität unnötig – aber für jeden, der Temperaturgenauigkeit bei langen Garzeiten will, ist sie der Grund, dieses Modell zu wählen.",
  "s5h": "Crock-Pot 2-Quart Mini – kompakt und einfach",
  "s5p0": "Der Crock-Pot 2-Quart Mini (SCCPMC225) ist die Option für kleine Mengen – für Haushalte, die Dips, Beilagen, Saucen oder eine Mahlzeit für ein bis zwei Personen wollen, ohne einem 6-Quart-Topf Arbeitsfläche zu opfern. Er nutzt dieselben drei Stufen wie seine größeren Geschwister – High, Low und Warm – an einem einfachen Drehregler, und der herausnehmbare Steinguttopf lässt sich zum Servieren und Reinigen entnehmen.",
  "s5p1": "Die Einschränkung gegenüber dem Hamilton Beach 33967 ist das Fehlen von Timer und Temperatursonde: Er ist rein manuell ein/aus, du steuerst den Garpunkt also, indem du High oder Low wählst und selbst auf die Uhr schaust. Für einen großen Braten, der Präzision braucht, ist der Hamilton Beach die bessere Wahl. Der Anwendungsfall des Mini ist enger und klarer: der kleinste, günstigste Einstieg ins Slow Cooking für alle, die meist kleine Mengen zubereiten und keine programmierbare Steuerung brauchen.",
  "s6p3": "Küche und Strom: Alle fünf werden an eine normale Steckdose angeschlossen und ziehen im Vergleich zu Hochleistungsgeräten wenig Strom, eine Überlastung des Stromkreises ist also kein Thema. Keines hat einen induktionsfähigen Boden. Der Platz auf der Arbeitsfläche ist in kleinen Küchen der entscheidende Engpass: der Crock-Pot 6-Quart und der Hamilton Beach 33967 sind im Stellmaß einem großen Wasserkocher ähnlich. Der Cuisinart CSC-800 und der Crock-Pot 2-Quart Mini sind kompakt genug, um neben anderen Geräten auf einer normalen Arbeitsfläche zu stehen.",
  "faq2": "5–6 Quart (etwa 4,7–5,7 Liter) für eine vierköpfige Familie mit normalen Portionen. Der 6-Quart-Crock-Pot ist hier richtig – er fasst eine 2-kg-Schweineschulter mit Gemüse und lässt Raum für zirkulierende Flüssigkeit, und gefüllt auf 4 Quart reicht er für eine Familienmahlzeit, ohne so viel Leerraum zu lassen, dass ungleichmäßig gart. Kleinere Modelle (3,5-L-Cuisinart, der 2-Quart-Crock-Pot-Mini) sind 1-2-Personen- oder Beilagengeräte. Der 6-Quart Hamilton Beach 33967 entspricht dem Crock-Pot beim Fassungsvermögen und ergänzt eine Temperatursonde für große Stücke, bei denen du eine präzise Kerntemperatur willst.",
  "faq5": "Beim einfachen Slow Cooking (Eintöpfe, Schmorgerichte, Suppen) ist der Unterschied zwischen einem günstigen und einem hochwertigen Slow Cooker kleiner, als das Marketing andeutet. Das grundlegende Garprinzip ist dasselbe: Keramik- oder Edelstahleinsatz, Deckel, Heizelement mit geringer Leistung. Mehr zahlst du für: einen programmierbaren Timer und Warmhalte-Übergang (lohnt sich bei unregelmäßigem Zeitplan), eine Temperatursonde wie die des Hamilton Beach 33967 (lohnt sich, wenn du Braten machst, bei denen der Garpunkt wichtiger ist als die Zeit), dickere Keramik für gleichmäßigere Wärmeverteilung bei langen Garzeiten und Verarbeitungsqualität, die die Langlebigkeit beeinflusst. Der Aufpreis des Instant Pot gilt dem Schnellkochmodus, der die Kategorie völlig verändert. Wenn du nur slow cookst, erledigt der Crock-Pot die Kernaufgabe im unteren Preissegment kompetent.",
  "note_pana": "Sondengesteuerter, programmierbarer 6-Quart-Slow-Cooker – eine einsteckbare Temperatursonde schaltet auf Warmhalten, wenn die Speise eine eingestellte Kerntemperatur erreicht, plus herkömmliches zeitgesteuertes Garen auf High oder Low.",
  "note_twin": "Kompakter 2-Quart-Slow-Cooker mit manueller Bedienung – High, Low und Warm an einem einfachen Drehregler mit herausnehmbarem Steinguttopf. Kein Timer, keine Sonde; ideal für Dips, Beilagen und kleine Mengen.",
  "pin": "Fünf Slow Cooker im Vergleich 2026 – Crock-Pot 6-Quart, Instant Pot Duo 7-in-1, Cuisinart CSC-800, Hamilton Beach Set & Forget 33967 und der Crock-Pot 2-Quart Mini. Welcher meistert Schmorgerichte über Nacht, große Braten und kleine Beilagen, ohne dass man danebenstehen muss?",
  "p3_badge": "Beste Wahl für präzise lange Garzeiten",
  "p3_review": "Der Hamilton Beach Set & Forget 33967 ist um eine einsteckbare Temperatursonde herum gebaut, die das Gerät in dem Moment auf Warmhalten schaltet, in dem die Speise eine Zielkerntemperatur erreicht. Bei Braten und großen Stücken, bei denen der Garpunkt wichtiger ist als die verstrichene Zeit, beseitigt das die Hauptfehlerquelle beim Slow Cooking. Er bietet zudem herkömmliche programmierbare Garzeiten auf High oder Low.",
  "p3_pros": ["Temperatursonde hält die Speise auf einer eingestellten Kerntemperatur", "Programmierbarer Timer wechselt automatisch ins Warmhalten", "6-Quart-Topf mit fest klemmendem Deckel zum Transport"],
  "p3_cons": ["Sonde und Programme bedeuten mehr Schritte als ein einfaches Drei-Stufen-Gerät"],
  "p3_specs": {"Fassungsvermögen": "6 Quart", "Sonde": "Ja (Temperatur)", "Timer": "Ja (programmierbar)", "Einsatz": "Steinguttopf", "Deckel": "Fest klemmend", "Warmhalten": "Automatisch"},
  "p4_badge": "Beste kompakte Budget-Wahl",
  "p4_review": "Der Crock-Pot 2-Quart Mini (SCCPMC225) besetzt eine enge Nische: ein Slow Cooker für kleine Mengen – Dips, Beilagen und Mahlzeiten für ein bis zwei Personen zu einem Preis weit unter dem eines großen Geräts. Der herausnehmbare Steinguttopf lässt sich zum Servieren und Reinigen entnehmen, und ein einfacher High/Low/Warm-Drehregler hält ihn idiotensicher. Das Fehlen von Timer oder Sonde ist der Grund, warum die meisten Käufer, die Präzision brauchen, stattdessen den Hamilton Beach 33967 wählen.",
  "p4_pros": ["Kompaktes 2-Quart-Stellmaß für kleine Küchen", "Herausnehmbarer Steinguttopf für einfaches Servieren und Reinigen", "Einfacher Drehregler mit High, Low und Warm"],
  "p4_cons": ["Kein Timer und keine Temperatursonde – nur manuell ein/aus"],
  "p4_specs": {"Fassungsvermögen": "2 Quart", "Stufen": "High / Low / Warm", "Timer": "Keiner", "Einsatz": "Steinguttopf", "Deckel": "Glas", "Steuerung": "Manueller Drehregler"},
  "rf3_label": "Für präzise Braten und große Stücke",
  "rf3_reason": "Die Temperatursonde hält die Speise auf einer eingestellten Kerntemperatur und schaltet selbsttätig auf Warmhalten, sodass der Garpunkt nicht mehr von der Uhr abhängt.",
  "rf4_label": "Für kleine Mengen und Beilagen",
  "rf4_reason": "Der 2-Quart-Topf ist der günstigste, unkomplizierteste Einstieg ins Slow Cooking für Dips, Saucen und Mahlzeiten für ein bis zwei Personen.",
}

T["fr"] = {
  "description": "Cinq mijoteuses comparées en 2026 : Crock-Pot 6 quarts, Instant Pot Duo, Cuisinart CSC-800, Hamilton Beach Set & Forget 33967 et le Crock-Pot 2 quarts Mini. Capacité, programmabilité et celle qui convient à votre façon de cuisiner.",
  "lede": "Cinq mijoteuses, du simple modèle à trois positions à un appareil programmable piloté par sonde, jusqu'au mini compact de 2 quarts. C'est la fréquence d'utilisation hebdomadaire, et non la variété des recettes, qui détermine la caractéristique qui compte vraiment.",
  "s0p1": "Il existe aussi un second volet à l'histoire de la mijoteuse. Certains modèles ajoutent une sonde pour supprimer les approximations des cuissons longues : un rôti qui demande une température à cœur cible plutôt qu'une horloge, un braisé que l'on veut basculer en maintien au chaud dès qu'il atteint la température, une casserole de haricots que l'on préfère ne pas trop cuire. D'autres réduisent tout le format à un mini de 2 quarts pour les accompagnements, les sauces à tremper et les petites quantités qu'une cocotte de 6 quarts rend malcommodes.",
  "s3p2": "La contrainte honnête : la capacité de 3,5 quarts du Cuisinart CSC-800 est petite pour une famille de quatre cuisinant un rôti entier. Pour qui veut une plus grande cuve et une sonde de température qui bascule seule en maintien au chaud, le Hamilton Beach Set & Forget 33967 est l'alternative.",
  "s4h": "Hamilton Beach Set & Forget 33967 — programmable et piloté par sonde",
  "s4p0": "Le Hamilton Beach Set & Forget 33967 est conçu autour d'une fonction : une sonde de température enfichable. Au lieu de cuire un nombre d'heures fixe en espérant le bon résultat, vous réglez une température à cœur cible, et l'appareil bascule en maintien au chaud dès que l'aliment l'atteint. Pour un rôti ou une grosse pièce où la cuisson compte plus que le temps écoulé, cela supprime la principale source d'erreur de la mijoteuse.",
  "s4p1": "Il propose aussi une cuisson programmable classique : réglez une durée en High ou Low, et il décompte puis passe automatiquement en maintien au chaud. La cuve en grès de 6 quarts est assez grande pour un rôti familial avec des légumes, et le couvercle se clipse fermement, ce qui le rend pratique à transporter à un repas partagé sans que le contenu ne déborde.",
  "s4p2": "Le compromis : la sonde et la logique programmable ajoutent une étape par rapport à une simple mijoteuse à trois positions, et l'appareil occupe plus de place sur le plan de travail. Pour qui ne fait que régler et s'éloigner avec un simple cadran, cette complexité est inutile — mais pour qui veut de la précision de température sur les cuissons longues, c'est la raison de choisir ce modèle.",
  "s5h": "Crock-Pot 2 quarts Mini — compact et simple",
  "s5p0": "Le Crock-Pot 2 quarts Mini (SCCPMC225) est l'option petites quantités pour les foyers qui veulent des sauces à tremper, des accompagnements, des sauces ou un repas pour une à deux personnes sans consacrer de plan de travail à une cocotte de 6 quarts. Il utilise les mêmes trois positions que ses grands frères — High, Low et Warm — sur un simple cadran manuel, et la cuve en grès amovible se retire pour servir et nettoyer.",
  "s5p1": "La limite par rapport au Hamilton Beach 33967 est l'absence de minuteur ou de sonde : il est purement manuel marche/arrêt, vous contrôlez donc la cuisson en réglant High ou Low et en surveillant l'horloge vous-même. Pour un gros rôti qui demande de la précision, le Hamilton Beach est le meilleur choix. Le cas du Mini est plus étroit et plus clair : la façon la plus petite et la moins chère d'aborder la mijoteuse pour qui prépare surtout de petites quantités et n'a pas besoin de commande programmable.",
  "s6p3": "Cuisine et alimentation : les cinq se branchent sur une prise standard et consomment peu par rapport aux appareils à forte puissance, la charge du circuit n'est donc pas un souci. Aucun n'a de base compatible induction. La place sur le plan de travail est la vraie contrainte dans les petites cuisines : le Crock-Pot 6 quarts et le Hamilton Beach 33967 ont un encombrement proche d'une grande bouilloire électrique. Le Cuisinart CSC-800 et le Crock-Pot 2 quarts Mini sont assez compacts pour coexister avec d'autres appareils sur un plan de travail standard.",
  "faq2": "5 à 6 quarts (environ 4,7 à 5,7 litres) pour une famille de quatre avec des portions standard. Le Crock-Pot de 6 quarts convient ici — il accueille une épaule de porc de 2 kg avec des légumes en laissant de la place pour que le liquide circule, et rempli à 4 quarts il suffit pour un repas familial sans laisser tant de vide que la cuisson devienne inégale. Les modèles plus petits (Cuisinart 3,5 L, le Crock-Pot Mini de 2 quarts) sont des appareils pour 1-2 personnes ou pour accompagnements. Le Hamilton Beach 33967 de 6 quarts égale le Crock-Pot en capacité et ajoute une sonde de température pour les grosses pièces où vous voulez une température à cœur précise.",
  "faq5": "Pour la mijotée de base (ragoûts, braisés, soupes), l'écart entre une mijoteuse économique et une haut de gamme est plus faible que le marketing ne le laisse entendre. Le principe de cuisson fondamental est le même : cuve en céramique ou en inox, couvercle, élément chauffant de faible puissance. Vous payez plus pour : un minuteur programmable et un passage en maintien au chaud (utile si votre emploi du temps est irrégulier), une sonde de température comme celle du Hamilton Beach 33967 (utile si vous cuisinez des rôtis où la cuisson compte plus que le temps), une céramique plus épaisse pour une répartition plus homogène de la chaleur sur les cuissons longues, et une qualité de fabrication qui influe sur la longévité. Le surcoût de l'Instant Pot tient au mode autocuiseur, qui change entièrement la catégorie. Si vous ne faites que mijoter, le Crock-Pot remplit l'essentiel avec compétence dans le bas de gamme.",
  "note_pana": "Mijoteuse programmable de 6 quarts pilotée par sonde — une sonde de température enfichable bascule en maintien au chaud lorsque l'aliment atteint une température à cœur réglée, plus une cuisson minutée classique en High ou Low.",
  "note_twin": "Mijoteuse manuelle compacte de 2 quarts — High, Low et Warm sur un simple cadran avec cuve en grès amovible. Sans minuteur ni sonde ; idéale pour les sauces à tremper, les accompagnements et les petites quantités.",
  "pin": "Cinq mijoteuses comparées en 2026 — Crock-Pot 6 quarts, Instant Pot Duo 7-en-1, Cuisinart CSC-800, Hamilton Beach Set & Forget 33967 et le Crock-Pot 2 quarts Mini. Laquelle gère les ragoûts de nuit, les gros rôtis et les petits accompagnements sans surveillance ?",
  "p3_badge": "Idéal pour les cuissons longues précises",
  "p3_review": "Le Hamilton Beach Set & Forget 33967 est conçu autour d'une sonde de température enfichable qui bascule l'appareil en maintien au chaud dès que l'aliment atteint une température à cœur cible. Pour les rôtis et les grosses pièces où la cuisson compte plus que le temps écoulé, cela supprime la principale source d'erreur de la mijoteuse. Il propose aussi des durées de cuisson programmables classiques en High ou Low.",
  "p3_pros": ["La sonde de température maintient l'aliment à une température à cœur réglée", "Le minuteur programmable passe automatiquement en maintien au chaud", "Cuve de 6 quarts avec couvercle à clip pour le transport"],
  "p3_cons": ["La sonde et les programmes ajoutent des étapes par rapport à une simple mijoteuse à trois positions"],
  "p3_specs": {"Capacité": "6 quarts", "Sonde": "Oui (température)", "Minuteur": "Oui (programmable)", "Cuve": "Grès", "Couvercle": "À clip", "Maintien au chaud": "Automatique"},
  "p4_badge": "Meilleur choix compact économique",
  "p4_review": "Le Crock-Pot 2 quarts Mini (SCCPMC225) occupe une niche étroite : une mijoteuse petites quantités pour les sauces à tremper, les accompagnements et les repas pour une à deux personnes, à un prix bien inférieur à un appareil pleine taille. La cuve en grès amovible se retire pour servir et nettoyer, et un simple cadran High/Low/Warm le rend infaillible. L'absence de minuteur ou de sonde est la raison pour laquelle la plupart des acheteurs qui ont besoin de précision choisissent plutôt le Hamilton Beach 33967.",
  "p4_pros": ["Encombrement compact de 2 quarts pour les petites cuisines", "Cuve en grès amovible pour servir et nettoyer facilement", "Simple cadran High, Low et Warm"],
  "p4_cons": ["Ni minuteur ni sonde de température — marche/arrêt manuel uniquement"],
  "p4_specs": {"Capacité": "2 quarts", "Positions": "High / Low / Warm", "Minuteur": "Aucun", "Cuve": "Grès", "Couvercle": "Verre", "Commande": "Cadran manuel"},
  "rf3_label": "Pour les rôtis précis et les grosses pièces",
  "rf3_reason": "La sonde de température maintient l'aliment à une température à cœur réglée et bascule seule en maintien au chaud, si bien que la cuisson ne dépend plus de l'horloge.",
  "rf4_label": "Pour les petites quantités et les accompagnements",
  "rf4_reason": "La cuve de 2 quarts est la façon la moins chère et la moins contraignante d'aborder la mijoteuse pour les sauces à tremper, les sauces et les repas pour une à deux personnes.",
}

T["es"] = {
  "description": "Cinco ollas de cocción lenta comparadas en 2026: Crock-Pot de 6 cuartos, Instant Pot Duo, Cuisinart CSC-800, Hamilton Beach Set & Forget 33967 y la Crock-Pot Mini de 2 cuartos. Capacidad, programabilidad y cuál se adapta a tu forma de cocinar.",
  "lede": "Cinco ollas de cocción lenta, desde modelos básicos de tres posiciones hasta una unidad programable controlada por sonda y una mini compacta de 2 cuartos. Es la frecuencia de uso semanal, no la variedad de recetas, lo que determina qué característica importa de verdad.",
  "s0p1": "También hay una segunda vertiente en la historia de la olla de cocción lenta. Algunos modelos añaden una sonda para eliminar las conjeturas en cocciones largas: un asado que necesita una temperatura interna objetivo en lugar de un reloj, un estofado que quieres pasar a mantener caliente en cuanto alcance la temperatura, una olla de alubias que prefieres no pasarte de cocción. Otros reducen todo el formato a una mini de 2 cuartos para guarniciones, salsas para mojar y pequeñas cantidades que una olla de 6 cuartos vuelve incómodas.",
  "s3p2": "La fricción honesta: los 3,5 cuartos de capacidad de la Cuisinart CSC-800 se quedan cortos para una familia de cuatro que cocina un asado entero. Para quien quiere una olla más grande más una sonda de temperatura que pase sola a mantener caliente, la Hamilton Beach Set & Forget 33967 es la alternativa.",
  "s4h": "Hamilton Beach Set & Forget 33967 — programable y controlada por sonda",
  "s4p0": "La Hamilton Beach Set & Forget 33967 se construye en torno a una función: una sonda de temperatura desmontable. En lugar de cocinar un número fijo de horas esperando que el resultado sea correcto, fijas una temperatura interna objetivo y la olla pasa a mantener caliente en el instante en que el alimento la alcanza. Para un asado o una pieza grande donde el punto importa más que el tiempo transcurrido, esto elimina la principal fuente de error de la cocción lenta.",
  "s4p1": "También ofrece cocción programable convencional: fija un tiempo en High o Low, y descuenta y pasa automáticamente a mantener caliente. La cazuela de gres de 6 cuartos es lo bastante grande para un asado familiar con verduras, y la tapa se cierra a presión, lo que la hace práctica para llevar a una comida compartida sin que el contenido se derrame.",
  "s4p2": "La contrapartida es que la sonda y la lógica programable añaden un paso frente a una olla sencilla de tres posiciones, y la unidad ocupa más espacio en la encimera. Para quien solo ajusta y se aleja con un simple dial, esa complejidad es innecesaria, pero para quien quiere precisión de temperatura en cocciones largas, es la razón para elegir este modelo.",
  "s5h": "Crock-Pot Mini de 2 cuartos — compacta y sencilla",
  "s5p0": "La Crock-Pot Mini de 2 cuartos (SCCPMC225) es la opción de pequeñas cantidades para hogares que quieren salsas para mojar, guarniciones, salsas o una comida para una o dos personas sin dedicar encimera a una olla de 6 cuartos. Usa las mismas tres posiciones que sus hermanas mayores —High, Low y Warm— en un simple dial manual, y la cazuela de gres extraíble se saca para servir y limpiar.",
  "s5p1": "La limitación frente a la Hamilton Beach 33967 es la ausencia de temporizador o sonda de temperatura: es solo manual encendido/apagado, así que controlas el punto fijando High o Low y vigilando el reloj tú mismo. Para un asado grande que necesita precisión, la Hamilton Beach es la mejor opción. El caso de la Mini es más estrecho y claro: la forma más pequeña y económica de empezar en la cocción lenta para quien sobre todo prepara pequeñas cantidades y no necesita control programable.",
  "s6p3": "Cocina y consumo: las cinco se enchufan a una toma estándar y consumen poco frente a los electrodomésticos de alta potencia, así que la carga del circuito no es problema. Ninguna tiene base compatible con inducción. El espacio en la encimera es la limitación relevante en cocinas pequeñas: la Crock-Pot de 6 cuartos y la Hamilton Beach 33967 ocupan algo similar a un hervidor eléctrico grande. La Cuisinart CSC-800 y la Crock-Pot Mini de 2 cuartos son lo bastante compactas para convivir con otros electrodomésticos en una encimera estándar.",
  "faq2": "5-6 cuartos (aproximadamente 4,7-5,7 litros) para una familia de cuatro con porciones estándar. La Crock-Pot de 6 cuartos es la correcta aquí: admite una paleta de cerdo de 2 kg con verduras dejando sitio para que circule el líquido, y llena a 4 cuartos basta para una comida familiar sin dejar tanto hueco como para que la cocción sea desigual. Los modelos más pequeños (Cuisinart de 3,5 L, la Crock-Pot Mini de 2 cuartos) son aparatos para 1-2 personas o para guarniciones. La Hamilton Beach 33967 de 6 cuartos iguala a la Crock-Pot en capacidad y añade una sonda de temperatura para piezas grandes en las que quieres una temperatura interna precisa.",
  "faq5": "Para la cocción lenta básica (guisos, estofados, sopas), la diferencia entre una olla económica y una de gama alta es menor de lo que sugiere el marketing. El mecanismo de cocción fundamental es el mismo: cazuela de cerámica o acero inoxidable, tapa, resistencia de baja potencia. Pagas más por: un temporizador programable y transición a mantener caliente (vale la pena si tu horario es irregular), una sonda de temperatura como la de la Hamilton Beach 33967 (vale la pena si cocinas asados donde el punto importa más que el tiempo), cerámica más gruesa para un reparto del calor más uniforme en cocciones largas, y una calidad de fabricación que afecta a la durabilidad. El sobreprecio de la Instant Pot es por el modo olla a presión, que cambia la categoría por completo. Si solo vas a cocinar a fuego lento, la Crock-Pot hace lo esencial con solvencia en la gama baja.",
  "note_pana": "Olla de cocción lenta programable de 6 cuartos controlada por sonda: una sonda de temperatura desmontable pasa a mantener caliente cuando el alimento alcanza una temperatura interna fijada, además de cocción programada convencional en High o Low.",
  "note_twin": "Olla de cocción lenta manual compacta de 2 cuartos: High, Low y Warm en un dial sencillo con cazuela de gres extraíble. Sin temporizador ni sonda; ideal para salsas, guarniciones y pequeñas cantidades.",
  "pin": "Cinco ollas de cocción lenta comparadas en 2026: Crock-Pot de 6 cuartos, Instant Pot Duo 7 en 1, Cuisinart CSC-800, Hamilton Beach Set & Forget 33967 y la Crock-Pot Mini de 2 cuartos. ¿Cuál maneja guisos nocturnos, asados grandes y guarniciones pequeñas sin vigilancia?",
  "p3_badge": "Mejor para cocciones largas precisas",
  "p3_review": "La Hamilton Beach Set & Forget 33967 se construye en torno a una sonda de temperatura desmontable que pasa la olla a mantener caliente en cuanto el alimento alcanza una temperatura interna objetivo. Para asados y piezas grandes donde el punto importa más que el tiempo transcurrido, esto elimina la principal fuente de error de la cocción lenta. También admite tiempos de cocción programables convencionales en High o Low.",
  "p3_pros": ["La sonda de temperatura mantiene el alimento a una temperatura interna fijada", "El temporizador programable pasa automáticamente a mantener caliente", "Cazuela de 6 cuartos con tapa a presión para el transporte"],
  "p3_cons": ["La sonda y los programas añaden pasos frente a una olla sencilla de tres posiciones"],
  "p3_specs": {"Capacidad": "6 cuartos", "Sonda": "Sí (temperatura)", "Temporizador": "Sí (programable)", "Cazuela": "Gres", "Tapa": "A presión", "Mantener caliente": "Automático"},
  "p4_badge": "Mejor opción compacta económica",
  "p4_review": "La Crock-Pot Mini de 2 cuartos (SCCPMC225) ocupa un nicho estrecho: una olla de pequeñas cantidades para salsas para mojar, guarniciones y comidas para una o dos personas a un precio muy inferior al de una unidad de tamaño completo. La cazuela de gres extraíble se saca para servir y limpiar, y un sencillo dial High/Low/Warm la hace infalible. La ausencia de temporizador o sonda es la razón por la que la mayoría de quienes necesitan precisión eligen la Hamilton Beach 33967.",
  "p4_pros": ["Tamaño compacto de 2 cuartos para cocinas pequeñas", "Cazuela de gres extraíble para servir y limpiar con facilidad", "Sencillo dial con High, Low y Warm"],
  "p4_cons": ["Sin temporizador ni sonda de temperatura: solo encendido/apagado manual"],
  "p4_specs": {"Capacidad": "2 cuartos", "Posiciones": "High / Low / Warm", "Temporizador": "Ninguno", "Cazuela": "Gres", "Tapa": "Cristal", "Control": "Dial manual"},
  "rf3_label": "Para asados precisos y piezas grandes",
  "rf3_reason": "La sonda de temperatura mantiene el alimento a una temperatura interna fijada y pasa sola a mantener caliente, de modo que el punto deja de depender del reloj.",
  "rf4_label": "Para pequeñas cantidades y guarniciones",
  "rf4_reason": "La cazuela de 2 cuartos es la forma más económica y sencilla de empezar en la cocción lenta para salsas, guarniciones y comidas para una o dos personas.",
}

T["it"] = {
  "description": "Cinque slow cooker a confronto nel 2026: Crock-Pot da 6 quarti, Instant Pot Duo, Cuisinart CSC-800, Hamilton Beach Set & Forget 33967 e la Crock-Pot Mini da 2 quarti. Capacità, programmabilità e quale si adatta al tuo modo di cucinare.",
  "lede": "Cinque slow cooker, dai modelli base a tre posizioni a un'unità programmabile controllata da sonda fino alla mini compatta da 2 quarti. È la frequenza d'uso settimanale, non la varietà delle ricette, a determinare quale caratteristica conti davvero.",
  "s0p1": "C'è anche un secondo filone nella storia dello slow cooker. Alcuni modelli aggiungono una sonda per togliere ogni dubbio nelle cotture lunghe: un arrosto che richiede una temperatura interna obiettivo anziché un orologio, un brasato che vuoi far passare al mantenimento in caldo nel momento in cui raggiunge la temperatura, una pentola di legumi che preferisci non scuocere. Altri riducono l'intero formato a una mini da 2 quarti per contorni, salse e piccole quantità che una pentola da 6 quarti rende scomode.",
  "s3p2": "L'attrito onesto: la capacità da 3,5 quarti della Cuisinart CSC-800 è ridotta per una famiglia di quattro che cucina un arrosto intero. Per chi vuole una pentola più grande e una sonda di temperatura che passi da sola al mantenimento in caldo, la Hamilton Beach Set & Forget 33967 è l'alternativa.",
  "s4h": "Hamilton Beach Set & Forget 33967 — programmabile e controllata da sonda",
  "s4p0": "La Hamilton Beach Set & Forget 33967 è costruita attorno a una funzione: una sonda di temperatura a innesto. Invece di cuocere per un numero fisso di ore sperando nel risultato giusto, imposti una temperatura interna obiettivo e l'apparecchio passa al mantenimento in caldo nell'istante in cui l'alimento la raggiunge. Per un arrosto o un taglio grande in cui la cottura conta più del tempo trascorso, questo elimina la principale fonte di errore dello slow cooking.",
  "s4p1": "Offre anche la cottura programmabile classica: imposta un tempo su High o Low e l'apparecchio fa il conto alla rovescia e passa automaticamente al mantenimento in caldo. La pentola in gres da 6 quarti è abbastanza capiente per un arrosto di famiglia con verdure, e il coperchio si aggancia saldamente, il che la rende pratica da portare a una cena condivisa senza che il contenuto trabocchi.",
  "s4p2": "Il compromesso è che la sonda e la logica programmabile aggiungono un passaggio rispetto a uno slow cooker semplice a tre posizioni, e l'unità occupa più spazio sul piano. Per chi imposta e se ne va con una semplice manopola, quella complessità è superflua, ma per chi vuole precisione di temperatura nelle cotture lunghe è la ragione per scegliere questo modello.",
  "s5h": "Crock-Pot Mini da 2 quarti — compatta e semplice",
  "s5p0": "La Crock-Pot Mini da 2 quarti (SCCPMC225) è l'opzione per piccole quantità per le famiglie che vogliono salse, contorni, sughi o un pasto per una o due persone senza dedicare il piano a una pentola da 6 quarti. Usa le stesse tre posizioni delle sorelle maggiori — High, Low e Warm — su una semplice manopola manuale, e la pentola in gres estraibile si toglie per servire e pulire.",
  "s5p1": "Il limite rispetto alla Hamilton Beach 33967 è l'assenza di timer o sonda di temperatura: è solo manuale acceso/spento, quindi controlli la cottura impostando High o Low e tenendo d'occhio tu stesso l'orologio. Per un arrosto grande che richiede precisione, la Hamilton Beach è la scelta migliore. Il caso della Mini è più ristretto e chiaro: il modo più piccolo ed economico per avvicinarsi allo slow cooking per chi prepara soprattutto piccole quantità e non ha bisogno di controllo programmabile.",
  "s6p3": "Cucina e alimentazione: tutte e cinque si collegano a una presa standard e assorbono poco rispetto agli elettrodomestici ad alta potenza, quindi il carico del circuito non è un problema. Nessuna ha una base compatibile con l'induzione. Lo spazio sul piano è il vincolo rilevante nelle cucine piccole: la Crock-Pot da 6 quarti e la Hamilton Beach 33967 hanno un ingombro simile a un grande bollitore elettrico. La Cuisinart CSC-800 e la Crock-Pot Mini da 2 quarti sono abbastanza compatte da convivere con altri elettrodomestici su un piano standard.",
  "faq2": "5-6 quarti (circa 4,7-5,7 litri) per una famiglia di quattro con porzioni standard. La Crock-Pot da 6 quarti è quella giusta qui: accoglie una spalla di maiale da 2 kg con verdure lasciando spazio alla circolazione del liquido, e riempita a 4 quarti basta per un pasto di famiglia senza lasciare tanto vuoto da rendere la cottura disomogenea. I modelli più piccoli (Cuisinart da 3,5 L, la Crock-Pot Mini da 2 quarti) sono apparecchi per 1-2 persone o per contorni. La Hamilton Beach 33967 da 6 quarti eguaglia la Crock-Pot in capacità e aggiunge una sonda di temperatura per i tagli grandi in cui vuoi una temperatura interna precisa.",
  "faq5": "Per lo slow cooking di base (spezzatini, brasati, zuppe), la differenza tra uno slow cooker economico e uno premium è minore di quanto il marketing lasci intendere. Il meccanismo di cottura fondamentale è lo stesso: pentola in ceramica o acciaio, coperchio, resistenza a bassa potenza. Si paga di più per: un timer programmabile e il passaggio al mantenimento in caldo (utile se gli orari sono irregolari), una sonda di temperatura come quella della Hamilton Beach 33967 (utile se cucini arrosti in cui la cottura conta più del tempo), una ceramica più spessa per una distribuzione del calore più uniforme nelle cotture lunghe, e una qualità costruttiva che incide sulla durata. Il sovrapprezzo dell'Instant Pot è per la modalità pentola a pressione, che cambia del tutto la categoria. Se cucini solo a fuoco lento, la Crock-Pot svolge il compito essenziale con competenza nella fascia bassa.",
  "note_pana": "Slow cooker programmabile da 6 quarti controllato da sonda: una sonda di temperatura a innesto passa al mantenimento in caldo quando l'alimento raggiunge una temperatura interna impostata, oltre alla cottura a tempo classica su High o Low.",
  "note_twin": "Slow cooker manuale compatto da 2 quarti: High, Low e Warm su una semplice manopola con pentola in gres estraibile. Senza timer né sonda; ideale per salse, contorni e piccole quantità.",
  "pin": "Cinque slow cooker a confronto nel 2026: Crock-Pot da 6 quarti, Instant Pot Duo 7 in 1, Cuisinart CSC-800, Hamilton Beach Set & Forget 33967 e la Crock-Pot Mini da 2 quarti. Quale gestisce stufati notturni, arrosti grandi e piccoli contorni senza doverla sorvegliare?",
  "p3_badge": "Migliore per cotture lunghe precise",
  "p3_review": "La Hamilton Beach Set & Forget 33967 è costruita attorno a una sonda di temperatura a innesto che fa passare l'apparecchio al mantenimento in caldo nel momento in cui l'alimento raggiunge una temperatura interna obiettivo. Per arrosti e tagli grandi in cui la cottura conta più del tempo trascorso, questo elimina la principale fonte di errore dello slow cooking. Offre anche tempi di cottura programmabili classici su High o Low.",
  "p3_pros": ["La sonda di temperatura mantiene l'alimento a una temperatura interna impostata", "Il timer programmabile passa automaticamente al mantenimento in caldo", "Pentola da 6 quarti con coperchio a innesto per il trasporto"],
  "p3_cons": ["Sonda e programmi aggiungono passaggi rispetto a uno slow cooker semplice a tre posizioni"],
  "p3_specs": {"Capacità": "6 quarti", "Sonda": "Sì (temperatura)", "Timer": "Sì (programmabile)", "Pentola": "Gres", "Coperchio": "A innesto", "Mantenimento in caldo": "Automatico"},
  "p4_badge": "Migliore scelta compatta economica",
  "p4_review": "La Crock-Pot Mini da 2 quarti (SCCPMC225) occupa una nicchia ristretta: uno slow cooker per piccole quantità per salse, contorni e pasti per una o due persone a un prezzo molto inferiore a un'unità di dimensioni piene. La pentola in gres estraibile si toglie per servire e pulire, e una semplice manopola High/Low/Warm la rende a prova di errore. L'assenza di timer o sonda è il motivo per cui la maggior parte di chi ha bisogno di precisione sceglie invece la Hamilton Beach 33967.",
  "p4_pros": ["Ingombro compatto da 2 quarti per cucine piccole", "Pentola in gres estraibile per servire e pulire con facilità", "Semplice manopola con High, Low e Warm"],
  "p4_cons": ["Nessun timer né sonda di temperatura: solo acceso/spento manuale"],
  "p4_specs": {"Capacità": "2 quarti", "Posizioni": "High / Low / Warm", "Timer": "Nessuno", "Pentola": "Gres", "Coperchio": "Vetro", "Controllo": "Manopola manuale"},
  "rf3_label": "Per arrosti precisi e tagli grandi",
  "rf3_reason": "La sonda di temperatura mantiene l'alimento a una temperatura interna impostata e passa da sola al mantenimento in caldo, così la cottura non dipende più dall'orologio.",
  "rf4_label": "Per piccole quantità e contorni",
  "rf4_reason": "La pentola da 2 quarti è il modo più economico e semplice per avvicinarsi allo slow cooking per salse, sughi e pasti per una o due persone.",
}

T["pt-BR"] = {
  "description": "Cinco panelas de cozimento lento comparadas em 2026: Crock-Pot de 6 quartos, Instant Pot Duo, Cuisinart CSC-800, Hamilton Beach Set & Forget 33967 e a Crock-Pot Mini de 2 quartos. Capacidade, programação e qual combina com seu jeito de cozinhar.",
  "lede": "Cinco panelas de cozimento lento, do modelo básico de três posições a uma unidade programável controlada por sonda e a mini compacta de 2 quartos. É a frequência de uso semanal, não a variedade de receitas, que define qual especificação realmente importa.",
  "s0p1": "Há também uma segunda vertente na história da panela de cozimento lento. Alguns modelos acrescentam uma sonda para tirar a adivinhação dos cozimentos longos: um assado que precisa de uma temperatura interna alvo em vez de um relógio, um cozido que você quer passar para manter aquecido no instante em que atinge a temperatura, uma panela de feijão que prefere não passar do ponto. Outros reduzem o formato inteiro a uma mini de 2 quartos para acompanhamentos, molhos e pequenas quantidades que uma panela de 6 quartos torna desajeitadas.",
  "s3p2": "O atrito honesto: a capacidade de 3,5 quartos da Cuisinart CSC-800 é pequena para uma família de quatro que cozinha um assado inteiro. Para quem quer uma panela maior mais uma sonda de temperatura que passa sozinha para manter aquecido, a Hamilton Beach Set & Forget 33967 é a alternativa.",
  "s4h": "Hamilton Beach Set & Forget 33967 — programável e controlada por sonda",
  "s4p0": "A Hamilton Beach Set & Forget 33967 é construída em torno de um recurso: uma sonda de temperatura encaixável. Em vez de cozinhar por um número fixo de horas torcendo pelo resultado certo, você define uma temperatura interna alvo, e o aparelho passa para manter aquecido no instante em que o alimento a atinge. Para um assado ou uma peça grande em que o ponto importa mais que o tempo decorrido, isso elimina a principal fonte de erro do cozimento lento.",
  "s4p1": "Ele também oferece cozimento programável convencional: defina um tempo em High ou Low, e ele faz a contagem regressiva e passa automaticamente para manter aquecido. A cuba de grés de 6 quartos é grande o suficiente para um assado de família com legumes, e a tampa trava firme, o que a torna prática para levar a um almoço coletivo sem o conteúdo derramar.",
  "s4p2": "O custo é que a sonda e a lógica programável acrescentam um passo em relação a uma panela simples de três posições, e a unidade ocupa mais espaço na bancada. Para quem só ajusta e se afasta com um simples botão, essa complexidade é desnecessária, mas para quem quer precisão de temperatura em cozimentos longos é o motivo para escolher este modelo.",
  "s5h": "Crock-Pot Mini de 2 quartos — compacta e simples",
  "s5p0": "A Crock-Pot Mini de 2 quartos (SCCPMC225) é a opção de pequenas quantidades para lares que querem molhos, acompanhamentos, caldas ou uma refeição para uma ou duas pessoas sem dedicar bancada a uma panela de 6 quartos. Usa as mesmas três posições das irmãs maiores — High, Low e Warm — em um simples botão manual, e a cuba de grés removível sai para servir e limpar.",
  "s5p1": "A limitação em relação à Hamilton Beach 33967 é a ausência de timer ou sonda de temperatura: é apenas manual liga/desliga, então você controla o ponto definindo High ou Low e olhando o relógio você mesmo. Para um assado grande que precisa de precisão, a Hamilton Beach é a melhor escolha. O caso da Mini é mais estreito e claro: a forma menor e mais barata de entrar no cozimento lento para quem prepara sobretudo pequenas quantidades e não precisa de controle programável.",
  "s6p3": "Cozinha e energia: todas as cinco são ligadas a uma tomada padrão e consomem pouco em comparação com eletrodomésticos de alta potência, então a carga do circuito não é preocupação. Nenhuma tem base compatível com indução. O espaço de bancada é a restrição relevante em cozinhas pequenas: a Crock-Pot de 6 quartos e a Hamilton Beach 33967 têm dimensão parecida com uma chaleira elétrica grande. A Cuisinart CSC-800 e a Crock-Pot Mini de 2 quartos são compactas o bastante para conviver com outros aparelhos numa bancada padrão.",
  "faq2": "5-6 quartos (aproximadamente 4,7-5,7 litros) para uma família de quatro com porções padrão. A Crock-Pot de 6 quartos é a certa aqui: comporta uma paleta de porco de 2 kg com legumes deixando espaço para o líquido circular, e cheia até 4 quartos basta para uma refeição de família sem deixar tanto vazio a ponto de cozinhar de forma desigual. Os modelos menores (Cuisinart de 3,5 L, a Crock-Pot Mini de 2 quartos) são aparelhos para 1-2 pessoas ou para acompanhamentos. A Hamilton Beach 33967 de 6 quartos iguala a Crock-Pot em capacidade e acrescenta uma sonda de temperatura para peças grandes em que você quer uma temperatura interna precisa.",
  "faq5": "Para o cozimento lento básico (ensopados, refogados, sopas), a diferença entre uma panela econômica e uma premium é menor do que o marketing sugere. O mecanismo de cozimento fundamental é o mesmo: cuba de cerâmica ou inox, tampa, resistência de baixa potência. Você paga mais por: um timer programável e transição para manter aquecido (vale a pena se sua agenda é irregular), uma sonda de temperatura como a da Hamilton Beach 33967 (vale a pena se você faz assados em que o ponto importa mais que o tempo), cerâmica mais grossa para distribuição de calor mais uniforme em cozimentos longos, e qualidade de fabricação que afeta a durabilidade. O acréscimo da Instant Pot é pelo modo de pressão, que muda a categoria por completo. Se você só cozinha em fogo lento, a Crock-Pot faz o essencial com competência na faixa baixa.",
  "note_pana": "Panela de cozimento lento programável de 6 quartos controlada por sonda: uma sonda de temperatura encaixável passa para manter aquecido quando o alimento atinge uma temperatura interna definida, além de cozimento por tempo convencional em High ou Low.",
  "note_twin": "Panela de cozimento lento manual compacta de 2 quartos: High, Low e Warm em um botão simples com cuba de grés removível. Sem timer nem sonda; ideal para molhos, acompanhamentos e pequenas quantidades.",
  "pin": "Cinco panelas de cozimento lento comparadas em 2026: Crock-Pot de 6 quartos, Instant Pot Duo 7 em 1, Cuisinart CSC-800, Hamilton Beach Set & Forget 33967 e a Crock-Pot Mini de 2 quartos. Qual dá conta de ensopados noturnos, assados grandes e pequenos acompanhamentos sem ficar vigiando?",
  "p3_badge": "Melhor para cozimentos longos precisos",
  "p3_review": "A Hamilton Beach Set & Forget 33967 é construída em torno de uma sonda de temperatura encaixável que faz o aparelho passar para manter aquecido no instante em que o alimento atinge uma temperatura interna alvo. Para assados e peças grandes em que o ponto importa mais que o tempo decorrido, isso elimina a principal fonte de erro do cozimento lento. Ela também oferece tempos de cozimento programáveis convencionais em High ou Low.",
  "p3_pros": ["A sonda de temperatura mantém o alimento em uma temperatura interna definida", "O timer programável passa automaticamente para manter aquecido", "Cuba de 6 quartos com tampa de encaixe para transporte"],
  "p3_cons": ["A sonda e os programas acrescentam passos em relação a uma panela simples de três posições"],
  "p3_specs": {"Capacidade": "6 quartos", "Sonda": "Sim (temperatura)", "Timer": "Sim (programável)", "Cuba": "Grés", "Tampa": "De encaixe", "Manter aquecido": "Automático"},
  "p4_badge": "Melhor opção compacta econômica",
  "p4_review": "A Crock-Pot Mini de 2 quartos (SCCPMC225) ocupa um nicho estreito: uma panela de pequenas quantidades para molhos, acompanhamentos e refeições para uma ou duas pessoas a um preço bem abaixo de uma unidade de tamanho cheio. A cuba de grés removível sai para servir e limpar, e um simples botão High/Low/Warm a torna à prova de erro. A ausência de timer ou sonda é o motivo pelo qual a maioria de quem precisa de precisão escolhe a Hamilton Beach 33967.",
  "p4_pros": ["Dimensão compacta de 2 quartos para cozinhas pequenas", "Cuba de grés removível para servir e limpar com facilidade", "Botão simples com High, Low e Warm"],
  "p4_cons": ["Sem timer nem sonda de temperatura: apenas liga/desliga manual"],
  "p4_specs": {"Capacidade": "2 quartos", "Posições": "High / Low / Warm", "Timer": "Nenhum", "Cuba": "Grés", "Tampa": "Vidro", "Controle": "Botão manual"},
  "rf3_label": "Para assados precisos e peças grandes",
  "rf3_reason": "A sonda de temperatura mantém o alimento em uma temperatura interna definida e passa sozinha para manter aquecido, de modo que o ponto deixa de depender do relógio.",
  "rf4_label": "Para pequenas quantidades e acompanhamentos",
  "rf4_reason": "A cuba de 2 quartos é a forma mais barata e simples de entrar no cozimento lento para molhos, caldas e refeições para uma ou duas pessoas.",
}

# Save
def apply(loc, t):
    p = os.path.join(DIR, loc + ".json")
    d = json.load(open(p, encoding="utf-8"))
    d["description"] = t["description"]
    d["lede"] = t["lede"]
    d["sections"][0]["paragraphs"][1] = t["s0p1"]
    d["sections"][3]["paragraphs"][2] = t["s3p2"]
    d["sections"][4]["heading"] = t["s4h"]
    d["sections"][4]["paragraphs"][0] = t["s4p0"]
    d["sections"][4]["paragraphs"][1] = t["s4p1"]
    d["sections"][4]["paragraphs"][2] = t["s4p2"]
    d["sections"][5]["heading"] = t["s5h"]
    d["sections"][5]["paragraphs"][0] = t["s5p0"]
    d["sections"][5]["paragraphs"][1] = t["s5p1"]
    d["sections"][6]["paragraphs"][3] = t["s6p3"]
    d["faqs"][2]["a"] = t["faq2"]
    d["faqs"][5]["a"] = t["faq5"]
    d["offerNotes"]["panasonic-sr-mp300"] = t["note_pana"]
    d["offerNotes"]["twinbird-ep-4694"] = t["note_twin"]
    d["pinDescription"] = t["pin"]
    pr3 = d["products"][3]
    pr3["badge"] = t["p3_badge"]; pr3["review"] = t["p3_review"]
    pr3["pros"] = t["p3_pros"]; pr3["cons"] = t["p3_cons"]; pr3["specs"] = t["p3_specs"]
    pr4 = d["products"][4]
    pr4["badge"] = t["p4_badge"]; pr4["review"] = t["p4_review"]
    pr4["pros"] = t["p4_pros"]; pr4["cons"] = t["p4_cons"]; pr4["specs"] = t["p4_specs"]
    d["recommendedFor"][3]["label"] = t["rf3_label"]; d["recommendedFor"][3]["reason"] = t["rf3_reason"]
    d["recommendedFor"][4]["label"] = t["rf4_label"]; d["recommendedFor"][4]["reason"] = t["rf4_reason"]
    json.dump(d, open(p, "w", encoding="utf-8"), ensure_ascii=False, indent=2)
    print("wrote", loc)

for loc, t in T.items():
    apply(loc, t)
print("DONE batch 1")
