/**
 * Fetch current prices from Amazon.co.jp for all catalog offers that have
 * a real amazon-jp ASIN (not a search-URL fallback).
 * Also preserves existing USD prices from the catalog price field.
 *
 * Usage:  cd site && npx tsx scripts/fetch-prices.ts
 * Output: src/lib/affiliates/prices-override.ts  (auto-generated)
 *
 * Schedule via GitHub Actions to run daily.
 */
import fs from "node:fs";
import path from "node:path";
import https from "node:https";
import { CATALOG } from "../src/lib/affiliates/catalog";

const OUT_PATH = path.resolve(__dirname, "../src/lib/affiliates/prices-override.ts");
const DELAY_MS = 1500; // polite delay between requests
const TIMEOUT_MS = 10000;

// ── helpers ──────────────────────────────────────────────────────────────────

function sleep(ms: number) {
  return new Promise<void>((r) => setTimeout(r, ms));
}

function fetchPage(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const req = https.get(
      url,
      {
        headers: {
          "User-Agent":
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
          "Accept-Language": "ja-JP,ja;q=0.9",
          Accept: "text/html,application/xhtml+xml",
        },
        timeout: TIMEOUT_MS,
      },
      (res) => {
        const chunks: Buffer[] = [];
        res.on("data", (c: Buffer) => chunks.push(c));
        res.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
      }
    );
    req.on("error", reject);
    req.on("timeout", () => { req.destroy(); reject(new Error("timeout")); });
  });
}

function extractJpPrice(html: string): string | null {
  // Pattern 1: JSON embedded in page — "priceAmount":1288.00
  const m1 = html.match(/"priceAmount":([\d.]+)/);
  if (m1) {
    const yen = Math.round(parseFloat(m1[1]));
    return `¥${yen.toLocaleString("ja-JP")}`;
  }
  // Pattern 2: a-offscreen span — >¥1,288<
  const m2 = html.match(/class="a-offscreen">(¥[\d,]+)</);
  if (m2) return m2[1];
  // Pattern 3: a-price-whole — >1,288<
  const m3 = html.match(/class="a-price-whole">([\d,]+)</);
  if (m3) return `¥${m3[1]}`;
  return null;
}

function formatUsd(raw: string | undefined): string | null {
  if (!raw) return null;
  const m = raw.match(/\$[\d.,]+/);
  return m ? m[0] : null;
}

// ── main ─────────────────────────────────────────────────────────────────────

async function main() {
  // Build list of offers to fetch: real amazon-jp ASIN (no search-URL rawUrl)
  const toFetch = CATALOG.flatMap((offer) => {
    const jpLink = offer.links.find(
      (l) =>
        l.network === "amazon-jp" &&
        !(l.rawUrl && l.rawUrl.includes("/s?k="))
    );
    if (!jpLink) return [];
    return [{ offer, asin: jpLink.productId }];
  });

  console.log(`Fetching JP prices for ${toFetch.length} offers…`);

  const prices: Record<string, Record<string, string>> = {};

  // Seed with existing USD prices from catalog
  for (const o of CATALOG) {
    const usd = formatUsd(o.price);
    if (usd) {
      prices[o.id] = { ...prices[o.id], US: usd };
    }
  }

  let ok = 0, failed = 0;

  for (let i = 0; i < toFetch.length; i++) {
    const { offer, asin } = toFetch[i];
    const url = `https://www.amazon.co.jp/dp/${asin}`;

    try {
      const html = await fetchPage(url);
      const price = extractJpPrice(html);
      if (price) {
        prices[offer.id] = { ...prices[offer.id], JP: price };
        ok++;
        if (ok % 50 === 0) process.stdout.write(`  [${i + 1}/${toFetch.length}] ${ok} ok, ${failed} failed\n`);
      } else {
        failed++;
      }
    } catch {
      failed++;
    }

    if (i < toFetch.length - 1) await sleep(DELAY_MS);
  }

  console.log(`\nDone: ${ok} prices fetched, ${failed} failed.`);

  // ── write output ────────────────────────────────────────────────────────────
  const entries = Object.entries(prices)
    .filter(([, v]) => Object.keys(v).length > 0)
    .sort(([a], [b]) => a.localeCompare(b));

  const lines: string[] = [
    "/**",
    " * Market-specific price overrides for catalog offers.",
    " * Auto-generated by scripts/fetch-prices.ts — do not edit manually.",
    ` * Last updated: ${new Date().toISOString().slice(0, 10)}`,
    " */",
    "export const PRICES: Record<string, Partial<Record<string, string>>> = {",
  ];

  for (const [id, markets] of entries) {
    const inner = Object.entries(markets)
      .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
      .join(", ");
    lines.push(`  ${JSON.stringify(id)}: { ${inner} },`);
  }

  lines.push("};", "");
  fs.writeFileSync(OUT_PATH, lines.join("\n"), "utf8");
  console.log(`Written → ${OUT_PATH}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
