import type { NewOffer } from "./batch-articles-types";

export const OFFERS: NewOffer[] = [
  // ===== FASHION =====
  // best-leather-tote-bag-2026
  { id: "madewell-transport-tote", nameEn: "Madewell Transport Tote", nameJa: "Madewell トランスポート トート", descEn: "Vegetable-tanned leather, 13-inch laptop fits, holds 16 lb daily haul. Open-top, single compartment, develops a deep patina in 6 months.", descJa: "ベジタブルタンレザー、13インチPC対応、約7kgまでのデイリー使い。オープントップ・1気室・6ヶ月で深い艶が出る。", priceMin: "$168", priceMax: "$198", category: "fashion", badge: "👜", url: "https://www.madewell.com/" },
  { id: "coach-willow-tote", nameEn: "Coach Willow Tote 24", nameJa: "Coach ウィロー トート 24", descEn: "Refined pebble leather, gusseted sides, magnetic snap closure. Mid-size structured silhouette, fits 13-inch MacBook on the diagonal.", descJa: "リファインド ペブルレザー、マチ付き、マグネットスナップ。中型構造、13インチMacBookを斜め収納可。", priceMin: "$395", priceMax: "$495", category: "fashion", badge: "👜", url: "https://www.coach.com/" },
  { id: "tory-burch-ella-tote", nameEn: "Tory Burch Ella Tote", nameJa: "Tory Burch エラ トート", descEn: "Recycled nylon body with leather trim, double-T logo. Lightweight (1.2 lb empty), packable, holds 14-inch laptop plus daily essentials.", descJa: "リサイクルナイロン本体＋レザートリム、ダブルTロゴ。空時0.5kgと軽量、折りたためる、14インチPC＋日常品を収納。", priceMin: "$228", priceMax: "$248", category: "fashion", badge: "👜", url: "https://www.toryburch.com/" },
  { id: "longchamp-le-pliage", nameEn: "Longchamp Le Pliage Original", nameJa: "Longchamp ル・プリアージュ オリジナル", descEn: "Foldable nylon tote with leather flap, French heritage classic since 1993. Sizes XS-XL, six colorways. Folds flat for travel.", descJa: "折り畳みナイロントート＋レザーフラップ、1993年から続く仏ヘリテージ。XS〜XLの4サイズ、6カラー。旅行用にフラットに畳める。", priceMin: "$135", priceMax: "$210", category: "fashion", badge: "👜", url: "https://www.longchamp.com/" },
  { id: "cuyana-classic-leather-tote", nameEn: "Cuyana Classic Leather Tote", nameJa: "Cuyana クラシック レザー トート", descEn: "Pebbled leather, monogram available, structured base, no exterior hardware. Italian tannery, 16-inch laptop fits, ages to a soft drape.", descJa: "ペブルドレザー、モノグラム可、構造的なボトム、外側金具なし。イタリアタンナリー、16インチPC対応、使い込むとソフトに馴染む。", priceMin: "$278", priceMax: "$378", category: "fashion", badge: "👜", url: "https://www.cuyana.com/" },

  // best-everyday-sneakers-2026
  { id: "allbirds-tree-runner", nameEn: "Allbirds Tree Runner", nameJa: "Allbirds ツリーランナー", descEn: "Eucalyptus tree fiber upper, sugarcane-based SweetFoam midsole. Machine washable, breathable for warm climates, 8.4 oz per shoe.", descJa: "ユーカリ繊維アッパー、サトウキビ由来SweetFoamミッドソール。洗濯機OK、暖かい気候向けの通気性、片足約238g。", priceMin: "$98", priceMax: "$110", category: "fashion", badge: "👟", url: "https://www.allbirds.com/" },
  { id: "veja-v10-leather", nameEn: "Veja V-10 Leather", nameJa: "Veja V-10 レザー", descEn: "Chrome-free leather upper, wild rubber sole from Amazon. Vegan glue. Made in Brazil, transparent supply chain, low-stack silhouette.", descJa: "クロムフリーレザーアッパー、アマゾン産ワイルドラバーソール、ヴィーガングルー。ブラジル製、透明なサプライチェーン、ロースタックシルエット。", priceMin: "$155", priceMax: "$170", category: "fashion", badge: "👟", url: "https://www.veja-store.com/" },
  { id: "cariuma-oca-low", nameEn: "Cariuma Oca Low", nameJa: "Cariuma Oca Low", descEn: "Organic canvas upper, natural rubber sole, cork insoles, mamona oil-based latex. Plants two trees per pair via Pacto trees program.", descJa: "オーガニックキャンバスアッパー、天然ラバーソール、コルクインソール、ヒマシ油由来ラテックス。1足購入で2本植樹。", priceMin: "$79", priceMax: "$98", category: "fashion", badge: "👟", url: "https://cariuma.com/" },
  { id: "common-projects-achilles-low", nameEn: "Common Projects Achilles Low", nameJa: "Common Projects アキレス ロー", descEn: "Italian Nappa leather, gold-foil serial number on heel. Minimalist tennis silhouette. Hand-finished in Marche, Italy.", descJa: "イタリア製ナッパレザー、ヒールに金箔シリアルナンバー。ミニマリストテニスシルエット。イタリア・マルケ州で手作業仕上げ。", priceMin: "$435", priceMax: "$520", category: "fashion", badge: "👟", url: "https://www.commonprojects.com/" },
  { id: "koio-capri-triple-white", nameEn: "Koio Capri Triple White", nameJa: "Koio カプリ トリプル ホワイト", descEn: "Italian full-grain leather, hand-stitched in Marche. Tonal stitching, lined with vegetable-tanned leather. Lighter than Common Projects.", descJa: "イタリア製フルグレインレザー、マルケ州で手縫い。トーンステッチ、ベジタブルタンレザー裏地。Common Projectsより軽量。", priceMin: "$248", priceMax: "$298", category: "fashion", badge: "👟", url: "https://www.koio.co/" },

  // best-mens-leather-wallet-2026
  { id: "bellroy-hide-and-seek", nameEn: "Bellroy Hide & Seek", nameJa: "Bellroy Hide & Seek", descEn: "Environmentally certified leather, RFID variant available, 5-12 cards plus hidden pocket. Slim bifold profile (0.5-inch thick).", descJa: "環境認証レザー、RFID版あり、カード5〜12枚＋隠しポケット。スリム二つ折り（厚さ約13mm）。", priceMin: "$99", priceMax: "$119", category: "fashion", badge: "👛", url: "https://bellroy.com/" },
  { id: "saddleback-medium-bifold", nameEn: "Saddleback Medium Bifold", nameJa: "Saddleback ミディアム 二つ折り", descEn: "Full-grain bridle leather, 100-year warranty, holds 8 cards plus cash. Hand-stitched, develops dramatic patina, virtually indestructible.", descJa: "フルグレインブライドルレザー、100年保証、カード8枚＋現金収納。手縫い、深い艶が出る、ほぼ破壊不可能。", priceMin: "$179", priceMax: "$199", category: "fashion", badge: "👛", url: "https://saddlebackleather.com/" },
  { id: "fossil-derrick-rfid-bifold", nameEn: "Fossil Derrick RFID Bifold", nameJa: "Fossil デリック RFID 二つ折り", descEn: "Pebbled leather with RFID-blocking lining, 8 card slots, 2 bill compartments. Most affordable RFID option from a major brand.", descJa: "ペブルレザー＋RFIDブロッキング裏地、カードスロット8枚、紙幣収納2気室。主要ブランドで最も安価なRFID対応。", priceMin: "$45", priceMax: "$60", category: "fashion", badge: "👛", url: "https://www.fossil.com/" },
  { id: "ridge-aluminum-wallet", nameEn: "Ridge Aluminum Wallet", nameJa: "Ridge アルミニウム ウォレット", descEn: "Anodized aluminum plates with elastic band, holds 1-12 cards. RFID blocking. Optional money clip or cash strap. Lifetime warranty.", descJa: "アノダイズドアルミプレート＋エラスティックバンド、カード1〜12枚。RFIDブロック。マネークリップ/キャッシュストラップ選択可。生涯保証。", priceMin: "$75", priceMax: "$115", category: "fashion", badge: "👛", url: "https://ridge.com/" },
  { id: "ekster-parliament-leather", nameEn: "Ekster Parliament Leather", nameJa: "Ekster パーラメント レザー", descEn: "Premium leather exterior with aluminum cardholder mechanism. Trackable via solar-powered card. Holds 12 cards, slim profile.", descJa: "プレミアムレザー外装＋アルミ製カードホルダー機構。ソーラー充電トラッカーカード対応。カード12枚、スリム設計。", priceMin: "$89", priceMax: "$119", category: "fashion", badge: "👛", url: "https://ekster.com/" },

  // best-cashmere-sweater-2026
  { id: "naadam-essential-cashmere-crew", nameEn: "Naadam Essential Cashmere Crew", nameJa: "Naadam エッセンシャル カシミア クルー", descEn: "Mongolian Grade-A cashmere, 2-ply, mid-weight. Direct trade from herders (50% premium). 30+ colors. Pills less than $50 imitators.", descJa: "モンゴル産グレードAカシミア、2プライ、中厚。牧夫から直接買付（50%プレミアム）。30色以上。$50台の類似品より毛玉が出にくい。", priceMin: "$98", priceMax: "$135", category: "fashion", badge: "🧶", url: "https://naadam.co/" },
  { id: "quince-mongolian-cashmere-crew", nameEn: "Quince Mongolian Cashmere Crew", nameJa: "Quince モンゴリアン カシミア クルー", descEn: "Grade-A inner Mongolian cashmere, 2-ply, factory-direct pricing. Same supplier as some $300+ brands. 14 colors.", descJa: "グレードA内モンゴル産カシミア、2プライ、工場直販。$300+ブランドと同じサプライヤー。14色展開。", priceMin: "$50", priceMax: "$70", category: "fashion", badge: "🧶", url: "https://www.onequince.com/" },
  { id: "jcrew-classic-cashmere-crew", nameEn: "J.Crew Classic Cashmere Crew", nameJa: "J.Crew クラシック カシミア クルー", descEn: "Italian-spun yarn, classic fit, true-to-size. Reliable for office wear under blazers. 12 colors, often discounted to $90.", descJa: "イタリア紡績糸、クラシックフィット、サイズ通り。ブレザーの下に着るオフィス用途で堅実。12色、頻繁に$90に値引き。", priceMin: "$148", priceMax: "$198", category: "fashion", badge: "🧶", url: "https://www.jcrew.com/" },
  { id: "everlane-cashmere-crew", nameEn: "Everlane The Cashmere Crew", nameJa: "Everlane ザ カシミア クルー", descEn: "Grade-A cashmere, 2-ply, slim modern fit. Transparent pricing breakdown shown on product page. 8 colors.", descJa: "グレードAカシミア、2プライ、スリムモダンフィット。商品ページに透明な価格内訳掲載。8色。", priceMin: "$130", priceMax: "$160", category: "fashion", badge: "🧶", url: "https://www.everlane.com/" },
  { id: "white-warren-cashmere-vneck", nameEn: "White + Warren Cashmere V-Neck", nameJa: "White + Warren カシミア Vネック", descEn: "Italian cashmere, longer body length, softer than mass-market brands. Made in China with Italian supervision.", descJa: "イタリア産カシミア、丈長め、量産ブランドより柔らか。中国製、イタリアの監修下生産。", priceMin: "$245", priceMax: "$295", category: "fashion", badge: "🧶", url: "https://whiteandwarren.com/" },

  // best-merino-wool-tshirt-2026
  { id: "smartwool-merino-150-base", nameEn: "Smartwool Merino 150 Base Tee", nameJa: "Smartwool メリノ 150 ベース", descEn: "150 g/m² merino, ZQ-certified, slim fit. Best for active layering, dries fast. Made in Vietnam.", descJa: "150 g/m²メリノ、ZQ認証、スリムフィット。アクティブレイヤリング向き、速乾。ベトナム製。", priceMin: "$70", priceMax: "$85", category: "fashion", badge: "🐑", url: "https://www.smartwool.com/" },
  { id: "icebreaker-tech-lite-ii-tee", nameEn: "Icebreaker Tech Lite II Tee", nameJa: "Icebreaker テックライト II Tシャツ", descEn: "150 g/m² merino, raglan sleeves, regular fit. Most popular merino tee for casual + light hiking. ZQ-certified New Zealand wool.", descJa: "150 g/m²メリノ、ラグランスリーブ、レギュラーフィット。カジュアル＋ライトハイキング用途で最人気。ZQ認証ニュージーランド産。", priceMin: "$80", priceMax: "$95", category: "fashion", badge: "🐑", url: "https://www.icebreaker.com/" },
  { id: "woolprince-100-merino-crew", nameEn: "Wool&Prince 100% Merino Crew", nameJa: "Wool&Prince 100%メリノ クルー", descEn: "190 g/m² merino, designed for 100-day wear tests. Boxy modern fit. Direct-to-consumer, Made in Portugal.", descJa: "190 g/m²メリノ、100日連続着用テスト前提設計。ボクシーモダンフィット。ポルトガル製、D2C。", priceMin: "$98", priceMax: "$118", category: "fashion", badge: "🐑", url: "https://woolandprince.com/" },
  { id: "unbound-merino-tshirt", nameEn: "Unbound Merino Crew Tee", nameJa: "Unbound Merino クルー Tシャツ", descEn: "190 g/m² merino, slim modern fit. Marketed as 'wear for weeks without washing.' Made in China, Canadian brand.", descJa: "190 g/m²メリノ、スリムモダンフィット。「数週間洗わず着られる」を訴求。中国製、カナダブランド。", priceMin: "$85", priceMax: "$100", category: "fashion", badge: "🐑", url: "https://unboundmerino.com/" },
  { id: "ridge-merino-journey-crew", nameEn: "Ridge Merino Journey Crew", nameJa: "Ridge Merino ジャーニー クルー", descEn: "150 g/m² merino, athletic fit, more affordable than Smartwool. US-designed, ethically made in China.", descJa: "150 g/m²メリノ、アスレチックフィット、Smartwoolより安価。米国設計、中国エシカル生産。", priceMin: "$45", priceMax: "$60", category: "fashion", badge: "🐑", url: "https://ridgemerinowool.com/" },

  // best-polarized-sunglasses-2026
  { id: "rayban-aviator-classic-polarized", nameEn: "Ray-Ban Aviator Classic Polarized", nameJa: "Ray-Ban アビエーター クラシック 偏光", descEn: "Iconic teardrop, G-15 polarized green or B-15 brown lenses. Crystal lenses, metal frame. Made in Italy by Luxottica.", descJa: "象徴的なティアドロップ、G-15偏光グリーンまたはB-15ブラウンレンズ。クリスタルレンズ、メタルフレーム。ルックスオティカ製イタリア。", priceMin: "$203", priceMax: "$236", category: "fashion", badge: "🕶️", url: "https://www.ray-ban.com/" },
  { id: "oakley-holbrook-prizm-polarized", nameEn: "Oakley Holbrook Prizm Polarized", nameJa: "Oakley ホルブルック プリズム 偏光", descEn: "O-Matter frame, Prizm polarized lens optimizes color contrast for specific activities. Most-recommended sport-casual polarized.", descJa: "O-Matterフレーム、Prizm偏光レンズが用途別カラーコントラスト最適化。スポーツカジュアルで最も推奨される偏光モデル。", priceMin: "$203", priceMax: "$236", category: "fashion", badge: "🕶️", url: "https://www.oakley.com/" },
  { id: "maui-jim-peahi-polarized", nameEn: "Maui Jim Peahi Polarized", nameJa: "Maui Jim ペアヒ 偏光", descEn: "PolarizedPlus2 lens technology, four color modes, magnesium frame. Best-in-class glare reduction near water.", descJa: "PolarizedPlus2レンズ技術、4カラーモード、マグネシウムフレーム。水辺でのグレア抑制でクラス最高。", priceMin: "$229", priceMax: "$329", category: "fashion", badge: "🕶️", url: "https://www.mauijim.com/" },
  { id: "persol-714-folding-polarized", nameEn: "Persol 714 Folding Polarized", nameJa: "Persol 714 折りたたみ 偏光", descEn: "Steve McQueen's folding frame, handmade Italian acetate, Meflecto flex hinge. Iconic 1960s design with crystal polarized lens.", descJa: "スティーブ・マックイーンの折りたたみフレーム、手作りイタリアアセテート、Meflectoフレックスヒンジ。1960年代の象徴デザイン＋クリスタル偏光レンズ。", priceMin: "$420", priceMax: "$520", category: "fashion", badge: "🕶️", url: "https://www.persol.com/" },
  { id: "warby-parker-haskell-polarized", nameEn: "Warby Parker Haskell Polarized", nameJa: "Warby Parker ハスケル 偏光", descEn: "Custom cellulose acetate, polycarbonate polarized lens, anti-reflective coating. Most affordable retail polarized at $145.", descJa: "カスタムセルロースアセテート、ポリカーボネート偏光レンズ、反射防止コーティング。リテール偏光で最も安価な$145。", priceMin: "$145", priceMax: "$175", category: "fashion", badge: "🕶️", url: "https://www.warbyparker.com/" },

  // ===== FINANCE =====
  // best-cashback-credit-card-2026
  { id: "chase-freedom-unlimited", nameEn: "Chase Freedom Unlimited", nameJa: "Chase Freedom Unlimited", descEn: "1.5% cash back on all purchases, 5% travel via Chase Travel, 3% dining and drugstores. $0 annual fee, $200 welcome bonus.", descJa: "全購入1.5%キャッシュバック、Chase Travel経由旅行5%、外食・薬局3%。年会費$0、ウェルカム$200。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "💳", url: "https://creditcards.chase.com/" },
  { id: "citi-double-cash", nameEn: "Citi Double Cash Card", nameJa: "Citi Double Cash カード", descEn: "1% when you buy, 1% when you pay (= 2% flat). No bonus categories, no caps, $0 annual fee. Best flat-rate cashback in 2026.", descJa: "購入時1%＋支払時1%＝合計2%フラット。ボーナスカテゴリ・上限なし、年会費$0。2026年フラット式最強。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "💳", url: "https://www.citi.com/" },
  { id: "wells-fargo-active-cash", nameEn: "Wells Fargo Active Cash", nameJa: "Wells Fargo Active Cash", descEn: "2% flat cash back, $200 welcome bonus, $0 annual fee. 0% intro APR for 12 months. Best signup bonus among 2% cards.", descJa: "2%フラットキャッシュバック、$200ボーナス、年会費$0。12ヶ月0%導入APR。2%カードで最大級のサインアップボーナス。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "💳", url: "https://www.wellsfargo.com/" },
  { id: "capital-one-quicksilver", nameEn: "Capital One Quicksilver", nameJa: "Capital One Quicksilver", descEn: "1.5% flat cash back, $200 welcome bonus, $0 annual fee, $0 foreign transaction fee. Best for travelers among cashback cards.", descJa: "1.5%フラット、$200ボーナス、年会費$0、外貨手数料$0。キャッシュバック系で旅行者向け最適。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "💳", url: "https://www.capitalone.com/" },
  { id: "discover-it-cashback", nameEn: "Discover it Cash Back", nameJa: "Discover it Cash Back", descEn: "5% rotating categories (quarterly), 1% everything else. Doubles all cashback in your first year. $0 annual fee.", descJa: "5%四半期ローテーションカテゴリ＋1%それ以外。初年度全キャッシュバック2倍。年会費$0。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "💳", url: "https://www.discover.com/" },

  // best-travel-credit-card-2026
  { id: "chase-sapphire-preferred", nameEn: "Chase Sapphire Preferred", nameJa: "Chase Sapphire Preferred", descEn: "$95 annual fee, 5x travel via Chase, 3x dining, 60K bonus = ~$750 in travel. Best mid-tier travel card in 2026.", descJa: "年会費$95、Chase Travel経由5倍、外食3倍、60Kボーナス=旅行価値約$750。2026年ミッドティア旅行カードの最有力。", priceMin: "$95", priceMax: "$95", category: "finance", badge: "✈️", url: "https://creditcards.chase.com/" },
  { id: "amex-gold-card", nameEn: "American Express Gold Card", nameJa: "American Express ゴールド", descEn: "$325 annual fee, 4x at restaurants and US supermarkets (capped), $120 dining credit + $120 Uber credit. Best for restaurant spenders.", descJa: "年会費$325、レストラン＋米国スーパー4倍（上限あり）、$120レストラン＋$120 Uberクレジット。レストラン利用多めの人向け。", priceMin: "$325", priceMax: "$325", category: "finance", badge: "✈️", url: "https://www.americanexpress.com/" },
  { id: "capital-one-venture-x", nameEn: "Capital One Venture X", nameJa: "Capital One Venture X", descEn: "$395 fee, $300 Capital One Travel credit, 10K anniversary miles, Priority Pass + Capital One lounges. Effective fee: $0 if you use credits.", descJa: "年会費$395、$300 Capital One Travelクレジット、毎年10Kマイル、Priority Pass＋自社ラウンジ。実質$0。", priceMin: "$395", priceMax: "$395", category: "finance", badge: "✈️", url: "https://www.capitalone.com/" },
  { id: "citi-premier-card", nameEn: "Citi Strata Premier", nameJa: "Citi Strata プレミア", descEn: "$95 fee, 3x on air, hotels, restaurants, supermarkets, gas. Transfer partners include Singapore Airlines, Avianca, Turkish.", descJa: "年会費$95、航空・ホテル・外食・スーパー・ガソリン3倍。トランスファーパートナーにシンガポール、アビアンカ、ターキッシュ。", priceMin: "$95", priceMax: "$95", category: "finance", badge: "✈️", url: "https://www.citi.com/" },
  { id: "chase-sapphire-reserve", nameEn: "Chase Sapphire Reserve", nameJa: "Chase Sapphire Reserve", descEn: "$795 annual fee, $300 travel credit, Priority Pass, 8x via Chase Travel, $120 Lyft credit. Best premium card if you maximize benefits.", descJa: "年会費$795、$300旅行クレジット、Priority Pass、Chase Travel経由8倍、$120 Lyftクレジット。特典を活用すれば最強プレミアム。", priceMin: "$795", priceMax: "$795", category: "finance", badge: "✈️", url: "https://creditcards.chase.com/" },

  // best-high-yield-savings-account-2026
  { id: "marcus-online-savings", nameEn: "Marcus by Goldman Sachs Savings", nameJa: "Marcus by Goldman Sachs 普通預金", descEn: "4.40% APY (May 2026), no minimum balance, no fees. FDIC-insured up to $250K. Owned by Goldman Sachs, US-only.", descJa: "APY 4.40%（2026年5月）、最低残高なし、手数料なし。FDIC保険$250K。ゴールドマン・サックス傘下、米国限定。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "🏦", url: "https://www.marcus.com/" },
  { id: "ally-online-savings", nameEn: "Ally Online Savings", nameJa: "Ally オンライン普通預金", descEn: "4.20% APY, no minimum, no monthly fees. Buckets feature for goal-based saving. Best UX in HYSA space.", descJa: "APY 4.20%、最低残高なし、月額手数料なし。目標別バケット機能。HYSA分野でUX最強。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "🏦", url: "https://www.ally.com/" },
  { id: "sofi-checking-savings", nameEn: "SoFi Checking + Savings", nameJa: "SoFi 当座＋普通預金", descEn: "4.60% APY on savings with direct deposit, 0.50% on checking, no fees. Combo account, $300 sign-up bonus.", descJa: "直接入金で普通預金APY 4.60%、当座0.50%、手数料なし。コンボ口座、サインアップ$300。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "🏦", url: "https://www.sofi.com/" },
  { id: "discover-online-savings", nameEn: "Discover Online Savings", nameJa: "Discover オンライン普通預金", descEn: "4.10% APY, no minimum, no fees, 24/7 US-based support. Pairs well with Discover it Cashback card.", descJa: "APY 4.10%、最低残高なし、手数料なし、米国24時間サポート。Discover it Cashbackカードと相性良し。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "🏦", url: "https://www.discover.com/" },
  { id: "capital-one-360-performance", nameEn: "Capital One 360 Performance Savings", nameJa: "Capital One 360 パフォーマンス", descEn: "4.10% APY, no minimum, no fees, physical Capital One branches available. Best if you also use Capital One credit cards.", descJa: "APY 4.10%、最低残高なし、手数料なし、Capital One実店舗あり。Capital Oneクレカと併用に最適。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "🏦", url: "https://www.capitalone.com/" },

  // best-robo-advisor-2026
  { id: "betterment-robo", nameEn: "Betterment", nameJa: "Betterment", descEn: "0.25% management fee, low-cost ETFs, tax-loss harvesting, automatic rebalancing. Goal-based investing. $0 minimum.", descJa: "運用報酬0.25%、低コストETF、タックスロスハーベスティング、自動リバランス。ゴールベース投資。最低額$0。", priceMin: "0.25%", priceMax: "0.40%", category: "finance", badge: "🤖", url: "https://www.betterment.com/" },
  { id: "wealthfront-robo", nameEn: "Wealthfront", nameJa: "Wealthfront", descEn: "0.25% management fee, tax-loss harvesting on accounts $100K+, 529 college plans, customizable portfolios. $500 minimum.", descJa: "運用報酬0.25%、$100K+でタックスロスハーベスティング、529大学資金プラン、カスタム可能。最低$500。", priceMin: "0.25%", priceMax: "0.25%", category: "finance", badge: "🤖", url: "https://www.wealthfront.com/" },
  { id: "schwab-intelligent-portfolios", nameEn: "Schwab Intelligent Portfolios", nameJa: "Schwab Intelligent Portfolios", descEn: "Zero management fee (uses Schwab ETFs that have expense ratios). $5K minimum. Best if you want no advisory fee.", descJa: "運用報酬0%（経費率のあるSchwab ETF使用）。最低$5K。アドバイザリー手数料を払いたくない人向け。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "🤖", url: "https://www.schwab.com/" },
  { id: "fidelity-go", nameEn: "Fidelity Go", nameJa: "Fidelity Go", descEn: "$0 fee under $25K, 0.35% above. Uses Fidelity Flex funds with 0% expense ratio. Best for small portfolios.", descJa: "$25K未満は手数料$0、超過分0.35%。経費率0%のFidelity Flexファンド使用。少額ポートフォリオ最適。", priceMin: "$0", priceMax: "0.35%", category: "finance", badge: "🤖", url: "https://www.fidelity.com/" },
  { id: "vanguard-digital-advisor", nameEn: "Vanguard Digital Advisor", nameJa: "Vanguard Digital Advisor", descEn: "0.20% all-in fee (including ETF expenses). $100 minimum. Uses Vanguard's low-cost index ETFs. Pure passive approach.", descJa: "ETF経費込み総合0.20%。最低$100。Vanguard低コストインデックスETF使用。純パッシブ運用。", priceMin: "0.20%", priceMax: "0.20%", category: "finance", badge: "🤖", url: "https://investor.vanguard.com/" },

  // best-budgeting-app-2026
  { id: "ynab-app", nameEn: "YNAB (You Need A Budget)", nameJa: "YNAB（家計簿アプリ）", descEn: "$15/mo or $109/yr. Zero-based budgeting philosophy, hands-on category assignment. Best for serious debt payoff and habit change.", descJa: "月$15または年$109。ゼロベース予算、能動的カテゴリ割り当て。本気の負債返済・習慣変革向け。", priceMin: "$15/mo", priceMax: "$109/yr", category: "finance", badge: "💰", url: "https://www.ynab.com/" },
  { id: "monarch-money", nameEn: "Monarch Money", nameJa: "Monarch Money", descEn: "$15/mo or $99/yr. Flexible budgeting + investment tracking, household sharing, custom categories. Best Mint replacement in 2026.", descJa: "月$15または年$99。柔軟な予算＋投資追跡、家族共有、カスタムカテゴリ。2026年Mintの後継として最有力。", priceMin: "$15/mo", priceMax: "$99/yr", category: "finance", badge: "💰", url: "https://www.monarchmoney.com/" },
  { id: "copilot-budgeting", nameEn: "Copilot Money", nameJa: "Copilot Money", descEn: "$13/mo or $95/yr. iOS-first design, AI-powered categorization, beautiful charts. Best for design-conscious Apple users.", descJa: "月$13または年$95。iOSファースト設計、AI自動カテゴリ分け、美しいチャート。デザイン重視のApple派向け。", priceMin: "$13/mo", priceMax: "$95/yr", category: "finance", badge: "💰", url: "https://copilot.money/" },
  { id: "every-dollar-app", nameEn: "EveryDollar (by Ramsey Solutions)", nameJa: "EveryDollar（Ramsey Solutions）", descEn: "$0 free tier, $80/yr Premium. Zero-based budgeting Ramsey-style, debt snowball tools. Best free tier in 2026.", descJa: "無料版＋年$80プレミアム。Ramseyスタイルのゼロベース予算、デットスノーボール。2026年無料版で最有力。", priceMin: "$0", priceMax: "$80/yr", category: "finance", badge: "💰", url: "https://www.ramseysolutions.com/" },
  { id: "rocket-money", nameEn: "Rocket Money", nameJa: "Rocket Money", descEn: "$3-12/mo. Auto-detects subscriptions and negotiates bills on your behalf. Less budgeting, more spending optimization.", descJa: "月$3〜12。サブスクを自動検出、請求書交渉を代行。予算管理というより支出最適化ツール。", priceMin: "$3/mo", priceMax: "$12/mo", category: "finance", badge: "💰", url: "https://www.rocketmoney.com/" },

  // best-stock-trading-app-2026
  { id: "fidelity-mobile", nameEn: "Fidelity Mobile", nameJa: "Fidelity モバイル", descEn: "$0 commission, fractional shares, no payment-for-order-flow (PFOF). Best brokerage for serious long-term investors.", descJa: "手数料$0、端数株対応、注文フローの売却（PFOF）なし。本気の長期投資家向け最有力ブローカー。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "📈", url: "https://www.fidelity.com/" },
  { id: "charles-schwab-mobile", nameEn: "Charles Schwab Mobile", nameJa: "Charles Schwab モバイル", descEn: "$0 commission, fractional shares (Schwab Stock Slices), 24/7 phone support, integrated with Schwab banking.", descJa: "手数料$0、端数株（Schwab Stock Slices）、24時間電話サポート、Schwab銀行と連動。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "📈", url: "https://www.schwab.com/" },
  { id: "robinhood-app", nameEn: "Robinhood", nameJa: "Robinhood", descEn: "$0 commission, simplest UX, Robinhood Gold offers margin and IRA matching. Crypto trading 24/7. Best for first-time investors.", descJa: "手数料$0、最もシンプルなUX、Robinhood Goldでマージン・IRAマッチング。仮想通貨24時間取引。初心者向け最有力。", priceMin: "$0", priceMax: "$5/mo", category: "finance", badge: "📈", url: "https://robinhood.com/" },
  { id: "webull-app", nameEn: "Webull", nameJa: "Webull", descEn: "$0 commission, advanced charting, paper trading mode, free Level 2 data. Best for active traders who want pro tools.", descJa: "手数料$0、高度なチャート、ペーパートレード、レベル2データ無料。プロツールが欲しいアクティブトレーダー向け。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "📈", url: "https://www.webull.com/" },
  { id: "etrade-mobile", nameEn: "E*TRADE Mobile (Morgan Stanley)", nameJa: "E*TRADE モバイル（Morgan Stanley）", descEn: "$0 commission for stocks/ETFs, Power E*TRADE app for options, integrated with Morgan Stanley research. Best balance of pro and casual.", descJa: "株/ETF手数料$0、Power E*TRADEでオプション、Morgan Stanleyリサーチ統合。プロ・カジュアルのバランス最適。", priceMin: "$0", priceMax: "$0", category: "finance", badge: "📈", url: "https://us.etrade.com/" },

  // ===== PARENTING =====
  // best-baby-stroller-2026
  { id: "uppababy-vista-v3", nameEn: "UPPAbaby Vista V3", nameJa: "UPPAbaby ヴィスタ V3", descEn: "Modular convertible stroller, accommodates up to 3 children with adapters. Bassinet included, 27-lb frame, 50-lb capacity per seat.", descJa: "モジュラー変換ストローラー、アダプタで最大3人乗り。バシネット付属、フレーム12kg、各シート22.7kg対応。", priceMin: "$1099", priceMax: "$1199", category: "parenting", badge: "👶", url: "https://www.uppababy.com/" },
  { id: "bugaboo-fox-5", nameEn: "Bugaboo Fox 5", nameJa: "Bugaboo フォックス 5", descEn: "Premium all-terrain stroller, large foam-filled wheels, magnesium chassis. Reversible seat, one-piece folded for storage.", descJa: "プレミアム全地形ストローラー、大型発泡充填ホイール、マグネシウムシャーシ。リバーシブルシート、ワンピース折り畳み。", priceMin: "$1399", priceMax: "$1499", category: "parenting", badge: "👶", url: "https://www.bugaboo.com/" },
  { id: "nuna-mixx-next", nameEn: "Nuna Mixx Next", nameJa: "Nuna Mixx Next", descEn: "Magnetic 5-point harness, large all-terrain wheels, one-hand fold. Compatible with Pipa car seat for travel system.", descJa: "マグネット式5点ハーネス、大型全地形ホイール、片手折り畳み。Pipaチャイルドシートと連動でトラベルシステム化。", priceMin: "$799", priceMax: "$899", category: "parenting", badge: "👶", url: "https://nunababy.com/" },
  { id: "mockingbird-single-to-double", nameEn: "Mockingbird Single-to-Double", nameJa: "Mockingbird シングル to ダブル", descEn: "Direct-to-consumer pricing, converts from single to double with second seat kit ($150). 45-lb seat capacity, all-terrain wheels.", descJa: "D2C価格、第二シートキット（$150）でシングル→ダブル変換。シート耐荷重20.4kg、全地形ホイール。", priceMin: "$450", priceMax: "$600", category: "parenting", badge: "👶", url: "https://www.hellomockingbird.com/" },
  { id: "doona-x-infant-car-seat", nameEn: "Doona X Infant Car Seat-Stroller", nameJa: "Doona X 乳児用シート＋ストローラー", descEn: "2-in-1 infant car seat that converts to stroller in 1 second. New 2025 model lighter than original. Best for travel/Uber.", descJa: "2-in-1乳児用シート、1秒でストローラー変換。2025新モデルで軽量化。旅行・Uber利用に最適。", priceMin: "$550", priceMax: "$650", category: "parenting", badge: "👶", url: "https://www.doona.com/" },

  // best-baby-car-seat-2026
  { id: "nuna-pipa-rx", nameEn: "Nuna Pipa RX", nameJa: "Nuna Pipa RX", descEn: "Lie-flat car seat (NHTSA-approved), 4-32 lb capacity, lightweight 7.4 lb. Compatible with Nuna strollers + airline travel.", descJa: "フラットリクライニング（NHTSA認可）、対応1.8〜14.5kg、軽量3.4kg。Nunaストローラー連動＋機内対応。", priceMin: "$549", priceMax: "$599", category: "parenting", badge: "🚗", url: "https://nunababy.com/" },
  { id: "britax-willow-s", nameEn: "Britax Willow S Infant Car Seat", nameJa: "Britax Willow S 乳児用シート", descEn: "SafeWash fabrics machine-washable, ClickTight installation, SafeCenter LATCH. 4-35 lb, includes anti-rebound base.", descJa: "SafeWash素材で洗濯機可、ClickTight取り付け、SafeCenter LATCH。1.8〜15.9kg対応、リバウンド防止ベース付属。", priceMin: "$329", priceMax: "$399", category: "parenting", badge: "🚗", url: "https://www.britax.com/" },
  { id: "chicco-keyfit-35", nameEn: "Chicco KeyFit 35", nameJa: "Chicco キーフィット 35", descEn: "Top-rated by Consumer Reports for 8 years running. 4-35 lb, ReclineSure system, single-hand level. $250 is hard to beat.", descJa: "Consumer Reports最高評価8年連続。1.8〜15.9kg、ReclineSureシステム、片手レベル調整。$250でこのコスパは無双。", priceMin: "$249", priceMax: "$299", category: "parenting", badge: "🚗", url: "https://www.chiccousa.com/" },
  { id: "clek-liing", nameEn: "Clek Liing", nameJa: "Clek Liing", descEn: "Aluminum honeycomb crumple zone, GREENGUARD Gold certified, no flame retardants. 4-35 lb, anti-rebound bar standard.", descJa: "アルミハニカム圧潰ゾーン、GREENGUARDゴールド認証、難燃剤不使用。1.8〜15.9kg、リバウンドバー標準装備。", priceMin: "$429", priceMax: "$499", category: "parenting", badge: "🚗", url: "https://clekinc.com/" },
  { id: "evenflo-revolve360", nameEn: "Evenflo Revolve360 Slim", nameJa: "Evenflo Revolve360 Slim", descEn: "Rotating all-in-one (rear-facing, forward, booster) for up to 120 lb. Most affordable rotating seat. Slim base for 3-across.", descJa: "回転式オールインワン（後ろ向き・前向き・ブースター）最大54kg対応。回転式で最安。スリムベースで3席並列可。", priceMin: "$349", priceMax: "$429", category: "parenting", badge: "🚗", url: "https://www.evenflo.com/" },

  // best-baby-bottle-2026
  { id: "dr-browns-options-plus", nameEn: "Dr. Brown's Options+ Anti-Colic", nameJa: "Dr. Brown's Options+ 抗コリック", descEn: "Internal vent system reduces air ingestion, removable for older babies. Most pediatrician-recommended in 2026.", descJa: "内部ベントシステムで空気摂取を低減、大きくなったら取り外し可能。2026年小児科医推奨No.1。", priceMin: "$25", priceMax: "$35", category: "parenting", badge: "🍼", url: "https://www.drbrownsbaby.com/" },
  { id: "comotomo-natural-feel", nameEn: "Comotomo Natural Feel", nameJa: "Comotomo ナチュラルフィール", descEn: "100% silicone body and nipple, wide neck mimics breast. Best for breastfed babies transitioning to bottles.", descJa: "100%シリコンボトル＋乳首、ワイド口で胸を模倣。母乳育児からの移行に最適。", priceMin: "$22", priceMax: "$28", category: "parenting", badge: "🍼", url: "https://comotomo.com/" },
  { id: "philips-avent-natural-response", nameEn: "Philips Avent Natural Response", nameJa: "Philips Avent ナチュラルレスポンス", descEn: "Petal-textured wide nipple, AirFree vent reduces colic. Flow control responds to baby's sucking pattern.", descJa: "花弁テクスチャの広乳首、AirFreeベントでコリック低減。赤ちゃんの吸引パターンに反応する流量制御。", priceMin: "$24", priceMax: "$32", category: "parenting", badge: "🍼", url: "https://www.philips.com/" },
  { id: "tommee-tippee-closer", nameEn: "Tommee Tippee Closer to Nature", nameJa: "Tommee Tippee クローザートゥネイチャー", descEn: "Breast-like silicone nipple, anti-colic valve, dishwasher and sterilizer safe. UK's most-recommended bottle brand.", descJa: "胸を模した形状のシリコン乳首、抗コリックバルブ、食洗機・滅菌器対応。英国推奨No.1ブランド。", priceMin: "$18", priceMax: "$28", category: "parenting", badge: "🍼", url: "https://www.tommeetippee.com/" },
  { id: "mam-easy-start-anti-colic", nameEn: "MAM Easy Start Anti-Colic", nameJa: "MAM イージースタート 抗コリック", descEn: "Self-sterilizing in microwave in 3 minutes. SkinSoft nipple texture has 80% acceptance rate.", descJa: "電子レンジで3分自己殺菌。SkinSoft乳首素材の受け入れ率80%。", priceMin: "$15", priceMax: "$22", category: "parenting", badge: "🍼", url: "https://www.mambaby.com/" },

  // best-baby-carrier-2026
  { id: "ergobaby-omni-breeze", nameEn: "Ergobaby Omni Breeze", nameJa: "Ergobaby Omni Breeze", descEn: "SoftFlex Mesh, 4 carry positions (front-inward, front-outward, hip, back), 7-45 lb capacity. Best for hot climates.", descJa: "SoftFlex Mesh、4抱っこポジション（対面・前向き・ヒップ・おんぶ）、3.2〜20.4kg対応。暑い気候に最適。", priceMin: "$199", priceMax: "$220", category: "parenting", badge: "🤱", url: "https://www.ergobaby.com/" },
  { id: "baby-tula-explore", nameEn: "Baby Tula Explore", nameJa: "Baby Tula Explore", descEn: "Hundreds of printed patterns, machine washable, ergonomic seat. 7-45 lb, lumbar support. Best style options on market.", descJa: "数百種類のプリント柄、洗濯機可、人間工学シート。3.2〜20.4kg、腰サポート付き。最大級の柄バリエ。", priceMin: "$179", priceMax: "$199", category: "parenting", badge: "🤱", url: "https://babytula.com/" },
  { id: "babybjorn-mini", nameEn: "BabyBjörn Mini", nameJa: "BabyBjörn Mini", descEn: "Newborn-only carrier (8-25 lb), no waist belt, easy on/off solo. Front-inward and front-outward. Best for newborn ease.", descJa: "新生児専用キャリア（3.6〜11.3kg）、ウエストベルトなし、一人で簡単着脱。対面・前向き。新生児に最適。", priceMin: "$109", priceMax: "$139", category: "parenting", badge: "🤱", url: "https://www.babybjorn.com/" },
  { id: "lillebaby-complete", nameEn: "LÍLLÉbaby Complete All Seasons", nameJa: "LÍLLÉbaby コンプリート オールシーズン", descEn: "6 carry positions including front-outward newborn, zip-down panel for ventilation. 7-45 lb, lumbar support.", descJa: "6抱っこポジション（新生児の前向きを含む）、ジップダウンパネルで通気調節。3.2〜20.4kg、腰サポート。", priceMin: "$149", priceMax: "$179", category: "parenting", badge: "🤱", url: "https://www.lillebaby.com/" },
  { id: "artipoppe-zeitgeist", nameEn: "Artipoppe Zeitgeist", nameJa: "Artipoppe Zeitgeist", descEn: "Luxury Dutch brand, cashmere/wool blends, Instagram-favorite. 7-45 lb, ergonomic. Best for those who want investment-piece aesthetics.", descJa: "オランダのラグジュアリーブランド、カシミア／ウール混紡、Instagram人気。3.2〜20.4kg、人間工学。投資的なエステティックを求める人向け。", priceMin: "$390", priceMax: "$600", category: "parenting", badge: "🤱", url: "https://www.artipoppe.com/" },

  // best-baby-formula-2026
  { id: "bobbie-organic", nameEn: "Bobbie Organic Infant Formula", nameJa: "Bobbie オーガニック乳児用ミルク", descEn: "USDA Organic, modeled after European recipes (more lactose, organic A2 milk). FDA-regulated US production. $26/can.", descJa: "USDAオーガニック、欧州レシピ準拠（ラクトース多め、オーガニックA2乳）。FDA管轄の米国生産。$26/缶。", priceMin: "$26", priceMax: "$32", category: "parenting", badge: "🍼", url: "https://www.hibobbie.com/" },
  { id: "holle-stage-1-organic", nameEn: "Holle Stage 1 Organic", nameJa: "Holle ステージ1 オーガニック", descEn: "European (German) organic formula, Demeter biodynamic certified, no maltodextrin. Now imported legally to US via Organic Start.", descJa: "欧州（ドイツ）オーガニック粉ミルク、Demeterバイオダイナミック認証、マルトデキストリン不使用。Organic Start経由で米国に正規輸入。", priceMin: "$30", priceMax: "$40", category: "parenting", badge: "🍼", url: "https://www.holle.ch/" },
  { id: "kendamil-organic", nameEn: "Kendamil Organic Whole Milk", nameJa: "Kendamil オーガニック ホールミルク", descEn: "UK-made, FDA-cleared, uses whole milk (not skim+vegetable oils). Plant-based DHA from algae. Best EU-style formula in US.", descJa: "英国製、FDA認可、全乳使用（スキム＋植物油ではない）。藻類由来植物性DHA。米国で買えるEUスタイル最強。", priceMin: "$28", priceMax: "$38", category: "parenting", badge: "🍼", url: "https://www.kendamil.com/" },
  { id: "similac-pure-bliss", nameEn: "Similac Pure Bliss", nameJa: "Similac Pure Bliss", descEn: "Non-GMO, milk-based, lactose only carb (no corn syrup), no artificial growth hormones. Abbott's premium tier.", descJa: "非GMO、乳ベース、糖質はラクトースのみ（コーンシロップ不使用）、人工成長ホルモン不使用。Abbottのプレミアム層。", priceMin: "$30", priceMax: "$38", category: "parenting", badge: "🍼", url: "https://www.similac.com/" },
  { id: "earths-best-organic-dairy", nameEn: "Earth's Best Organic Dairy", nameJa: "Earth's Best オーガニック乳", descEn: "USDA Organic, no growth hormones or pesticides, has DHA and ARA. Most affordable organic formula widely available.", descJa: "USDAオーガニック、成長ホルモン・農薬不使用、DHA・ARA含有。広く出回るオーガニックで最安。", priceMin: "$22", priceMax: "$28", category: "parenting", badge: "🍼", url: "https://www.earthsbest.com/" },

  // best-diaper-bag-2026
  { id: "freshly-picked-classic-diaper", nameEn: "Freshly Picked Classic Diaper Bag", nameJa: "Freshly Picked クラシック ダイパーバッグ", descEn: "Vegan leather, 10 pockets, fits stroller handle, MagSafe iPhone holder. Lightweight 2.6 lb. Best style option.", descJa: "ヴィーガンレザー、ポケット10個、ストローラーハンドル取り付け可、MagSafe iPhoneホルダー。軽量1.2kg。スタイル最強。", priceMin: "$165", priceMax: "$185", category: "parenting", badge: "🎒", url: "https://www.freshlypicked.com/" },
  { id: "skip-hop-mainframe", nameEn: "Skip Hop Mainframe Diaper Backpack", nameJa: "Skip Hop メインフレーム ダイパーバックパック", descEn: "Tech-friendly design, USB port, padded laptop sleeve, 17 pockets. Most affordable feature-rich diaper bag at $100.", descJa: "テック親和設計、USBポート、パッド入りPCスリーブ、ポケット17個。$100で多機能ダイパーバッグの最安。", priceMin: "$80", priceMax: "$110", category: "parenting", badge: "🎒", url: "https://www.skiphop.com/" },
  { id: "petunia-pickle-bottom-axis", nameEn: "Petunia Pickle Bottom Axis", nameJa: "Petunia Pickle Bottom アクシス", descEn: "Convertible backpack/messenger, magnetic flap, removable changing pad. Sustainably made, 15+ colors.", descJa: "バックパック⇔メッセンジャー変換、マグネティックフラップ、取り外し可能おむつ替えパッド。サステイナブル生産、15色以上。", priceMin: "$179", priceMax: "$229", category: "parenting", badge: "🎒", url: "https://www.petunia.com/" },
  { id: "ju-ju-be-be-right-back", nameEn: "Ju-Ju-Be Be Right Back", nameJa: "Ju-Ju-Be ビーライトバック", descEn: "Antimicrobial lining, machine washable, 14+ pockets, stroller straps. Disney and Star Wars themed prints available.", descJa: "抗菌ライニング、洗濯機可、ポケット14個以上、ストローラーストラップ。ディズニー・スターウォーズ柄あり。", priceMin: "$170", priceMax: "$200", category: "parenting", badge: "🎒", url: "https://ju-ju-be.com/" },
  { id: "fawn-design-original", nameEn: "Fawn Design Original", nameJa: "Fawn Design オリジナル", descEn: "Vegan leather, simple silhouette, 9 pockets, hidden stroller straps. Looks like a regular backpack, not a diaper bag.", descJa: "ヴィーガンレザー、シンプルシルエット、ポケット9個、隠しストローラーストラップ。普通のバックパックに見えるデザイン。", priceMin: "$160", priceMax: "$185", category: "parenting", badge: "🎒", url: "https://fawndesign.com/" },

  // ===== PETS =====
  // best-cat-tree-2026
  { id: "frisco-72-cat-tree", nameEn: "Frisco 72-in Faux Fur Cat Tree", nameJa: "Frisco 72インチ フェイクファー キャットツリー", descEn: "183 cm tall, 7 platforms + 2 condos + sisal posts. Most affordable big cat tree on Chewy at $130.", descJa: "183cm、プラットフォーム7段＋小屋2＋サイザル柱。Chewyで$130と大型では最安。", priceMin: "$120", priceMax: "$150", category: "pets", badge: "🐈", url: "https://www.chewy.com/" },
  { id: "midwest-curious-cat-cube", nameEn: "MidWest Curious Cat Cube", nameJa: "MidWest キュリオス キャットキューブ", descEn: "Modular collapsible cube system. Stack multiple cubes for vertical play. Quiet velcro construction.", descJa: "モジュール式折り畳みキューブシステム。積み重ねて縦の遊び場に。静音ベルクロ。", priceMin: "$50", priceMax: "$75", category: "pets", badge: "🐈", url: "https://www.midwesthomes4pets.com/" },
  { id: "on2pets-large-cat-tree", nameEn: "On2 Pets Large Cat Tree", nameJa: "On2 Pets ラージ キャットツリー", descEn: "Realistic faux leaves on multi-tier perches, looks like indoor tree. 198 cm tall, US-handmade. Premium aesthetic.", descJa: "リアルなフェイクリーフ多段パーチ、室内ツリーのような外観。198cm、米国手作り。プレミアム審美。", priceMin: "$330", priceMax: "$420", category: "pets", badge: "🐈", url: "https://on2pets.com/" },
  { id: "vesper-v-high-base", nameEn: "Vesper V-High Base", nameJa: "Vesper V-High Base", descEn: "Modern walnut-finish MDF, two memory foam platforms, removable cushions. Looks like furniture, not a cat tree.", descJa: "モダンなウォルナット仕上げMDF、メモリーフォーム2段、クッション取り外し可能。家具のような外観。", priceMin: "$280", priceMax: "$320", category: "pets", badge: "🐈", url: "https://www.vesperhome.com/" },
  { id: "refined-feline-lotus-tower", nameEn: "The Refined Feline Lotus Tower", nameJa: "The Refined Feline ロータスタワー", descEn: "Real wood (mahogany/walnut), curved perches, ultra-modern. 213 cm tall. Premium price for showroom-grade design.", descJa: "本木材（マホガニー／ウォルナット）、曲線パーチ、超モダン。213cm。ショールーム級デザインのプレミア価格。", priceMin: "$420", priceMax: "$520", category: "pets", badge: "🐈", url: "https://therefinedfeline.com/" },

  // best-automatic-litter-box-2026
  { id: "litter-robot-4", nameEn: "Litter-Robot 4", nameJa: "Litter-Robot 4", descEn: "Self-cleaning globe design, app monitoring (waste level, cat weight), 90-day warranty. $700+ but #1 in 2026.", descJa: "セルフクリーニング球体設計、アプリ監視（廃棄物レベル、猫の体重）、90日保証。$700+だが2026年No.1。", priceMin: "$649", priceMax: "$749", category: "pets", badge: "📦", url: "https://www.litter-robot.com/" },
  { id: "petkit-pura-x", nameEn: "PETKIT Pura X", nameJa: "PETKIT Pura X", descEn: "Compact rotating drum design, smell-removal filter, app control. Best alternative to Litter-Robot at $450.", descJa: "コンパクト回転ドラム設計、消臭フィルター、アプリ制御。$450でLitter-Robotの代替最有力。", priceMin: "$450", priceMax: "$550", category: "pets", badge: "📦", url: "https://www.petkit.com/" },
  { id: "petsafe-scoopfree-crystal-pro", nameEn: "PetSafe ScoopFree Crystal Pro", nameJa: "PetSafe ScoopFree クリスタル プロ", descEn: "Crystal litter tray slides out, sensor-triggered rake. Most affordable auto litter box at $200.", descJa: "クリスタル砂トレイがスライド、センサー作動レーキ。$200で自動猫トイレで最安。", priceMin: "$180", priceMax: "$230", category: "pets", badge: "📦", url: "https://www.petsafe.net/" },
  { id: "litter-robot-3-connect", nameEn: "Litter-Robot 3 Connect", nameJa: "Litter-Robot 3 Connect", descEn: "Older Litter-Robot model, app-connected, still excellent. Often $200 cheaper than LR4. Lifetime brand reputation.", descJa: "旧型Litter-Robot、アプリ連動、依然優秀。LR4より$200安いことが多い。ブランドの生涯評価。", priceMin: "$549", priceMax: "$649", category: "pets", badge: "📦", url: "https://www.litter-robot.com/" },
  { id: "casa-leo-loo-too", nameEn: "Casa Leo Loo Too", nameJa: "Casa Leo Loo Too", descEn: "Wifi-connected, multi-cat distinction by weight, large 11-inch entry, UV light sanitization. Newer 2024 entrant.", descJa: "Wi-Fi接続、体重で多頭飼い識別、大型11インチ入口、UV殺菌。2024新参。", priceMin: "$649", priceMax: "$749", category: "pets", badge: "📦", url: "https://leospaw.com/" },

  // best-dog-crate-2026
  { id: "midwest-icrate-double-door", nameEn: "MidWest iCrate Double Door", nameJa: "MidWest iCrate ダブルドア", descEn: "Folding wire crate, 7 sizes (XS-XXL), divider panel for puppies. Industry standard, $50-90 for most sizes.", descJa: "折り畳みワイヤークレート、7サイズ（XS〜XXL）、子犬用ディバイダーパネル。業界標準、ほとんどのサイズで$50〜90。", priceMin: "$45", priceMax: "$120", category: "pets", badge: "🐕", url: "https://www.midwesthomes4pets.com/" },
  { id: "frisco-heavy-duty-crate", nameEn: "Frisco Heavy Duty Crate", nameJa: "Frisco ヘビーデューティー クレート", descEn: "Steel-reinforced corners, two latches per door, removable wheels. Best for moderately destructive dogs.", descJa: "スチール補強コーナー、ドアごとに2つのラッチ、取り外し可能ホイール。中度に破壊的な犬向け最有力。", priceMin: "$200", priceMax: "$350", category: "pets", badge: "🐕", url: "https://www.chewy.com/" },
  { id: "diggs-revol-collapsible", nameEn: "Diggs Revol Collapsible Crate", nameJa: "Diggs Revol 折り畳みクレート", descEn: "Designer crate with diamond-pattern aluminum, ceiling hatch, garage-style door. Folds in one move. Beautiful for living rooms.", descJa: "ダイヤモンドパターンアルミのデザイナークレート、天井ハッチ、ガレージスタイルドア。ワンモーション折り畳み。リビング映え。", priceMin: "$280", priceMax: "$395", category: "pets", badge: "🐕", url: "https://www.diggs.pet/" },
  { id: "impact-collapsible-crate", nameEn: "Impact Collapsible Dog Crate", nameJa: "Impact 折り畳みドッグクレート", descEn: "Aluminum, USA-made, FAA-approved for cargo travel. Most durable for escape artists. Lifetime warranty.", descJa: "アルミ、米国製、貨物機内持ち込み対応（FAA認可）。脱走犬向けで最も頑丈。生涯保証。", priceMin: "$650", priceMax: "$950", category: "pets", badge: "🐕", url: "https://www.impactdogcrates.com/" },
  { id: "gunner-g1-intermediate", nameEn: "Gunner G1 Intermediate Kennel", nameJa: "Gunner G1 中型ケンネル", descEn: "Double-walled rotomolded plastic, CPS Level-IV crash-tested, lifetime warranty. Survives car crashes intact.", descJa: "二重壁ロトモールドプラスチック、CPSレベルIV衝突試験、生涯保証。事故で無傷で残る。", priceMin: "$700", priceMax: "$899", category: "pets", badge: "🐕", url: "https://gunner.com/" },

  // best-dog-leash-2026
  { id: "ruffwear-front-range-leash", nameEn: "Ruffwear Front Range Leash", nameJa: "Ruffwear フロントレンジ リード", descEn: "Padded handle, traffic loop near collar, reflective trim. 5-ft, accessory loop. Best balance of features at $40.", descJa: "パッド入りハンドル、首輪近くのトラフィックループ、反射トリム。5フィート、アクセサリーループ。$40で機能バランス最強。", priceMin: "$35", priceMax: "$45", category: "pets", badge: "🐕", url: "https://ruffwear.com/" },
  { id: "kurgo-quantum-6-in-1", nameEn: "Kurgo Quantum 6-in-1 Leash", nameJa: "Kurgo Quantum 6-in-1 リード", descEn: "Six configurations: standard, hands-free, double-dog, tether, etc. Reflective stitching, lifetime warranty.", descJa: "6パターン構成：標準、ハンズフリー、ダブル犬、テザー他。反射ステッチ、生涯保証。", priceMin: "$30", priceMax: "$40", category: "pets", badge: "🐕", url: "https://www.kurgo.com/" },
  { id: "max-neo-double-handle", nameEn: "Max and Neo Double Handle Leash", nameJa: "Max and Neo ダブルハンドル リード", descEn: "Heavy-duty nylon, second handle near collar for traffic, donates a leash to a rescue per purchase. Best value at $20.", descJa: "ヘビーデューティーナイロン、首輪近くの第二ハンドル、購入ごとに保護団体にリード寄付。$20で最高コスパ。", priceMin: "$18", priceMax: "$25", category: "pets", badge: "🐕", url: "https://maxandneo.com/" },
  { id: "blueberry-pet-multi-color", nameEn: "Blueberry Pet Multi-Color Leash", nameJa: "Blueberry Pet マルチカラー リード", descEn: "Affordable styled leashes, dozens of designs, soft padded handle. Best style options at sub-$20 price.", descJa: "手頃なスタイリッシュリード、デザイン数十種、ソフトパッドハンドル。$20以下でスタイル最強。", priceMin: "$13", priceMax: "$20", category: "pets", badge: "🐕", url: "https://www.bluedogcollars.com/" },
  { id: "flexi-new-classic-retractable", nameEn: "Flexi New Classic Retractable", nameJa: "Flexi ニュークラシック 伸縮リード", descEn: "16-ft (5 m) retractable tape leash, one-button brake. German-made, multiple sizes (XS-L). Industry standard retractable.", descJa: "5mテープ伸縮リード、ワンボタンブレーキ。ドイツ製、複数サイズ（XS〜L）。伸縮リードの業界標準。", priceMin: "$25", priceMax: "$50", category: "pets", badge: "🐕", url: "https://flexilive.com/" },

  // best-aquarium-kit-2026
  { id: "fluval-flex-15-gallon", nameEn: "Fluval Flex 15-Gallon", nameJa: "Fluval Flex 15ガロン", descEn: "Curved-front aquarium, 3-stage filtration hidden in rear, app-controlled LED lighting. All-in-one kit. Best mid-size starter.", descJa: "フロントカーブ、3段濾過を背面に隠す、アプリ制御LED。オールインワンキット。中型スターターで最有力。", priceMin: "$200", priceMax: "$280", category: "pets", badge: "🐟", url: "https://www.fluvalaquatics.com/" },
  { id: "aqueon-led-mini-bow-5", nameEn: "Aqueon LED MiniBow 5", nameJa: "Aqueon LED ミニボウ 5", descEn: "5-gallon curved-front kit with QuietFlow filter, LED light, dechlorinator sample. Best beginner kit under $80.", descJa: "5ガロンフロントカーブキット、QuietFlowフィルター、LED照明、塩素中和剤サンプル。$80以下で初心者最強。", priceMin: "$60", priceMax: "$90", category: "pets", badge: "🐟", url: "https://www.aqueon.com/" },
  { id: "marineland-portrait-5-gallon", nameEn: "Marineland Portrait 5-Gallon Glass", nameJa: "Marineland ポートレート 5ガロン ガラス", descEn: "Vertical glass aquarium, hidden 3-stage filtration, sliding glass canopy, adjustable LED. Modern desk-friendly design.", descJa: "縦型ガラス水槽、3段濾過を隠蔽、スライドガラスカバー、調整可能LED。デスク親和モダンデザイン。", priceMin: "$100", priceMax: "$140", category: "pets", badge: "🐟", url: "https://www.marineland.com/" },
  { id: "tetra-aquarium-20-gallon", nameEn: "Tetra Aquarium 20-Gallon Kit", nameJa: "Tetra Aquarium 20ガロン キット", descEn: "20-gallon glass tank with heater, filter (Whisper 20), LED light, water conditioner. Best entry into community aquariums.", descJa: "20ガロンガラス水槽＋ヒーター、フィルター（Whisper 20）、LED、水質調整剤。コミュニティ水槽のエントリー最強。", priceMin: "$140", priceMax: "$190", category: "pets", badge: "🐟", url: "https://www.tetra-fish.com/" },
  { id: "fluval-spec-v-5-gallon", nameEn: "Fluval Spec V 5-Gallon", nameJa: "Fluval Spec V 5ガロン", descEn: "5-gallon nano with 3-stage filter and 7000K LED, etched glass, perfect for shrimp or single betta. Premium nano choice.", descJa: "5ガロンナノ、3段フィルター＋7000K LED、エッチングガラス、エビや単独ベタに最適。プレミアムナノ。", priceMin: "$130", priceMax: "$170", category: "pets", badge: "🐟", url: "https://www.fluvalaquatics.com/" },

  // best-pet-grooming-clipper-2026
  { id: "wahl-bravura-lithium", nameEn: "Wahl Bravura Lithium", nameJa: "Wahl Bravura リチウム", descEn: "Cordless lithium-ion (90 min runtime), 5-in-1 adjustable blade, quiet for nervous pets. Best home-grooming choice.", descJa: "コードレスリチウムイオン（90分稼働）、5-in-1可変ブレード、神経質なペットに静音。家庭用グルーミング最強。", priceMin: "$150", priceMax: "$200", category: "pets", badge: "✂️", url: "https://wahlpro.com/" },
  { id: "andis-proclip-agc2", nameEn: "Andis ProClip AGC2", nameJa: "Andis ProClip AGC2", descEn: "Two-speed corded clipper, used by professional groomers. UltraEdge or CeramicEdge blades. Industry workhorse.", descJa: "2スピードコード式クリッパー、プロのグルーマー使用。UltraEdgeまたはCeramicEdgeブレード。業界の働き馬。", priceMin: "$170", priceMax: "$220", category: "pets", badge: "✂️", url: "https://www.andis.com/" },
  { id: "oster-a5-two-speed", nameEn: "Oster A5 Two-Speed", nameJa: "Oster A5 2スピード", descEn: "Corded, 90+ year design, replacement parts widely available. Heavy-duty for thick coats. Iconic golden body.", descJa: "コード式、90年以上続く設計、交換パーツ広く流通。厚い被毛に対応するヘビーデューティー。象徴の金色ボディ。", priceMin: "$140", priceMax: "$200", category: "pets", badge: "✂️", url: "https://www.osterpro.com/" },
  { id: "wahl-show-pro-plus", nameEn: "Wahl Show Pro Plus", nameJa: "Wahl ショープロプラス", descEn: "Corded, single-speed, lightweight 12 oz, suitable for ear/face detailing. Best for finishing work.", descJa: "コード式、シングルスピード、340gの軽量、耳・顔の細部仕上げ向き。フィニッシュ作業に最有力。", priceMin: "$70", priceMax: "$100", category: "pets", badge: "✂️", url: "https://wahlpro.com/" },
  { id: "andis-pulse-zr-ii", nameEn: "Andis Pulse ZR II Cordless", nameJa: "Andis Pulse ZR II コードレス", descEn: "Cordless 5-speed, removable lithium battery, super heavy-duty motor. Professional groomers' favorite cordless.", descJa: "コードレス5スピード、リチウムバッテリー取り外し可、超ヘビーデューティーモーター。プロのグルーマー人気No.1コードレス。", priceMin: "$350", priceMax: "$450", category: "pets", badge: "✂️", url: "https://www.andis.com/" },

  // ===== TRAVEL =====
  // best-toiletry-bag-2026
  { id: "peak-design-wash-pouch", nameEn: "Peak Design Wash Pouch", nameJa: "Peak Design ウォッシュポーチ", descEn: "Recycled nylon, hanging hook, multiple compartments, water-resistant. Available in V or M sizes. Best modern design.", descJa: "リサイクルナイロン、吊り下げフック、複数仕切り、撥水。VまたはMサイズ。モダンデザイン最強。", priceMin: "$60", priceMax: "$85", category: "travel", badge: "🧴", url: "https://www.peakdesign.com/" },
  { id: "away-large-toiletry-bag", nameEn: "Away The Large Toiletry Bag", nameJa: "Away ザ・ラージ トイレタリーバッグ", descEn: "Coated nylon exterior, leather trim, removable wet/dry pouch, mirror. Pairs with Away luggage line. Lifetime warranty.", descJa: "コーティングナイロン外装、レザートリム、取り外し可能な濡れ／乾燥用ポーチ、ミラー付き。Awayスーツケースラインと統一。生涯保証。", priceMin: "$65", priceMax: "$95", category: "travel", badge: "🧴", url: "https://www.awaytravel.com/" },
  { id: "dagne-dover-hunter-toiletry", nameEn: "Dagne Dover Hunter Toiletry", nameJa: "Dagne Dover ハンター トイレタリー", descEn: "Recycled neoprene body, oversized opening, contoured base. Available in S/M/L. Best for those with many bottles.", descJa: "リサイクルネオプレン本体、大開口、底面成形。S/M/Lサイズ。多くのボトル収納向け最有力。", priceMin: "$65", priceMax: "$95", category: "travel", badge: "🧴", url: "https://www.dagnedover.com/" },
  { id: "bagsmart-hanging-toiletry", nameEn: "BAGSMART Hanging Toiletry Bag", nameJa: "BAGSMART ハンギング トイレタリーバッグ", descEn: "Hanging swivel hook, 4 compartments, water-resistant fabric. Most affordable feature-rich option at $25.", descJa: "回転吊り下げフック、4仕切り、撥水生地。$25で多機能トイレタリーバッグ最安。", priceMin: "$22", priceMax: "$30", category: "travel", badge: "🧴", url: "https://www.bag-smart.com/" },
  { id: "tortuga-toiletry-pouch", nameEn: "Tortuga Toiletry Pouch", nameJa: "Tortuga トイレタリーポーチ", descEn: "Waterproof TPU lining, hanging hook, organized mesh pockets. Designed for one-bag travelers. Compact 1.5 L volume.", descJa: "防水TPUライニング、吊り下げフック、整理メッシュポケット。ワンバッグトラベラー向け設計。コンパクトな1.5L容量。", priceMin: "$40", priceMax: "$55", category: "travel", badge: "🧴", url: "https://www.tortugabackpacks.com/" },

  // best-money-belt-2026
  { id: "eagle-creek-undercover-belt", nameEn: "Eagle Creek Undercover Money Belt", nameJa: "Eagle Creek アンダーカバー マネーベルト", descEn: "Moisture-wicking back, adjustable elastic, fits passport + cards + cash. Industry-standard travel money belt.", descJa: "吸湿背面、調節可エラスティック、パスポート＋カード＋現金収納。トラベルマネーベルトの業界標準。", priceMin: "$25", priceMax: "$32", category: "travel", badge: "💼", url: "https://www.eaglecreek.com/" },
  { id: "lewis-n-clark-rfid-belt", nameEn: "Lewis N. Clark RFID Money Belt", nameJa: "Lewis N. Clark RFID マネーベルト", descEn: "RFID-blocking fabric, breathable nylon mesh, fits passport. Anti-theft strap design. Best with RFID protection.", descJa: "RFIDブロック生地、通気性ナイロンメッシュ、パスポート収納。盗難防止ストラップ設計。RFID付き最有力。", priceMin: "$18", priceMax: "$25", category: "travel", badge: "💼", url: "https://www.lewisnclark.com/" },
  { id: "alpine-rivers-leg-wallet", nameEn: "Alpine Rivers Leg Wallet", nameJa: "Alpine Rivers レッグウォレット", descEn: "Worn on calf or thigh under pants, breathable mesh back, two compartments. Best for invisible carry.", descJa: "ふくらはぎ／太ももにズボン下装着、通気メッシュ背面、2仕切り。不可視キャリーで最有力。", priceMin: "$20", priceMax: "$28", category: "travel", badge: "💼", url: "https://www.alpinerivers.com/" },
  { id: "peak-gear-rfid-belt", nameEn: "Peak Gear RFID Money Belt", nameJa: "Peak Gear RFID マネーベルト", descEn: "RFID-blocking, moisture-wicking, expandable. Lifetime warranty, included passport scanner card.", descJa: "RFIDブロック、吸湿、伸縮可。生涯保証、パスポートスキャナーカード付属。", priceMin: "$20", priceMax: "$28", category: "travel", badge: "💼", url: "https://www.peakgearstore.com/" },
  { id: "zero-grid-money-belt", nameEn: "Zero Grid Money Belt", nameJa: "Zero Grid マネーベルト", descEn: "Slim profile fits under thin shirts, RFID-blocking, ripstop nylon. Best for hot climates due to mesh back.", descJa: "薄シャツの下に収まるスリムプロファイル、RFIDブロック、リップストップナイロン。メッシュ背面で暑い気候に最有力。", priceMin: "$22", priceMax: "$30", category: "travel", badge: "💼", url: "https://www.zerogrid.com/" },

  // best-travel-day-pack-2026
  { id: "osprey-daylite-plus", nameEn: "Osprey Daylite Plus", nameJa: "Osprey デイライトプラス", descEn: "20 L, padded laptop sleeve (16-inch), hipbelt, multiple pockets. Attaches to larger Osprey packs. Lifetime warranty.", descJa: "20L、パッド入りPCスリーブ（16インチ）、ヒップベルト、複数ポケット。大型Ospreyパックに連結可。生涯保証。", priceMin: "$75", priceMax: "$85", category: "travel", badge: "🎒", url: "https://www.osprey.com/" },
  { id: "peak-design-everyday-15l", nameEn: "Peak Design Everyday Backpack 15L", nameJa: "Peak Design エブリデイ バックパック 15L", descEn: "Recycled weatherproof shell, FlexFold dividers for cameras + tech, 13-inch laptop pouch. Best photographer's day pack.", descJa: "リサイクル耐候性シェル、カメラ＋テック用FlexFoldディバイダー、13インチPCポーチ。フォトグラファーのデイパック最有力。", priceMin: "$210", priceMax: "$250", category: "travel", badge: "🎒", url: "https://www.peakdesign.com/" },
  { id: "patagonia-altvia-pack-14l", nameEn: "Patagonia Altvia Pack 14L", nameJa: "Patagonia Altvia Pack 14L", descEn: "14 L, recycled nylon, lightweight 1 lb, fits hydration reservoir. Best for active days mixing town and trail.", descJa: "14L、リサイクルナイロン、軽量450g、ハイドレーションリザーバー対応。街と山を行き来する日に最有力。", priceMin: "$99", priceMax: "$129", category: "travel", badge: "🎒", url: "https://www.patagonia.com/" },
  { id: "fjallraven-kanken-classic", nameEn: "Fjällräven Kånken Classic", nameJa: "Fjällräven カンケン クラシック", descEn: "16 L, iconic Swedish boxy shape, Vinylon F fabric, removable seat pad. Style classic, not technical. 50+ colors.", descJa: "16L、象徴的なスウェディッシュ ボクシー形状、Vinylon F生地、取り外し可能シートパッド。スタイル系（技術系ではない）。50色以上。", priceMin: "$95", priceMax: "$115", category: "travel", badge: "🎒", url: "https://www.fjallraven.com/" },
  { id: "deuter-speed-lite-13", nameEn: "Deuter Speed Lite 13", nameJa: "Deuter スピードライト 13", descEn: "13 L, ultralight (400 g), pole carry, hipbelt. Best for fast-and-light day-hike crossover.", descJa: "13L、ウルトラライト（400g）、ポールキャリー、ヒップベルト。ファスト＆ライトのデイハイクに最有力。", priceMin: "$80", priceMax: "$100", category: "travel", badge: "🎒", url: "https://www.deuter.com/" },

  // best-camera-backpack-2026
  { id: "peak-design-everyday-30l", nameEn: "Peak Design Everyday Backpack 30L", nameJa: "Peak Design エブリデイ バックパック 30L", descEn: "30 L, FlexFold dividers, 15-inch laptop sleeve, MagLatch closure, weatherproof. Most-recommended hybrid travel/camera pack.", descJa: "30L、FlexFoldディバイダー、15インチPCスリーブ、MagLatch開閉、耐候。トラベル＋カメラハイブリッドで最も推奨。", priceMin: "$290", priceMax: "$320", category: "travel", badge: "📷", url: "https://www.peakdesign.com/" },
  { id: "wandrd-prvke-31l", nameEn: "WANDRD PRVKE 31L", nameJa: "WANDRD PRVKE 31L", descEn: "Roll-top, fits DSLR + 4-5 lenses, side and top camera access, expandable to 35 L. Best for video kit travel.", descJa: "ロールトップ、DSLR＋レンズ4〜5本、サイド＋トップカメラアクセス、35L拡張。ビデオキット旅行で最有力。", priceMin: "$269", priceMax: "$319", category: "travel", badge: "📷", url: "https://www.wandrd.com/" },
  { id: "lowepro-flipside-400-aw-iii", nameEn: "Lowepro Flipside 400 AW III", nameJa: "Lowepro フリップサイド 400 AW III", descEn: "Body-side access door (anti-theft), fits two pro-size DSLRs + lenses, all-weather cover. Industry workhorse.", descJa: "背面アクセスドア（盗難防止）、プロサイズDSLR2台＋レンズ収納、全天候カバー。業界の働き馬。", priceMin: "$170", priceMax: "$220", category: "travel", badge: "📷", url: "https://www.lowepro.com/" },
  { id: "manfrotto-advanced-iii-active", nameEn: "Manfrotto Advanced III Active Backpack", nameJa: "Manfrotto Advanced III アクティブ バックパック", descEn: "23 L, padded camera compartment + 15-inch laptop area + tripod attachment. Best entry-tier camera backpack.", descJa: "23L、パッド入りカメラ室＋15インチPCエリア＋三脚取り付け。エントリー層のカメラバックパックで最有力。", priceMin: "$130", priceMax: "$160", category: "travel", badge: "📷", url: "https://www.manfrotto.com/" },
  { id: "thinktank-airport-essentials", nameEn: "Think Tank Airport Essentials", nameJa: "Think Tank エアポート エッセンシャル", descEn: "22 L, carry-on compliant for all major airlines, fits 2 DSLRs + 5 lenses + 15-inch laptop. Best for air travel.", descJa: "22L、主要航空会社の機内持ち込み対応、DSLR2台＋レンズ5本＋15インチPC。航空機旅行で最有力。", priceMin: "$200", priceMax: "$250", category: "travel", badge: "📷", url: "https://www.thinktankphoto.com/" },

  // best-travel-laundry-bag-2026
  { id: "scrubba-wash-bag", nameEn: "Scrubba Wash Bag", nameJa: "Scrubba ウォッシュバッグ", descEn: "Internal washboard, roll-top seal, washes 1-2 garments in 3 minutes. Award-winning Australian design. Best for ultralight travel.", descJa: "内蔵洗濯板、ロールトップ密閉、3分で1〜2着洗える。受賞歴あるオーストラリア発デザイン。ウルトラライト旅行で最有力。", priceMin: "$55", priceMax: "$75", category: "travel", badge: "👕", url: "https://thescrubba.com/" },
  { id: "sea-to-summit-laundry-bag", nameEn: "Sea to Summit Lightweight Laundry Bag", nameJa: "Sea to Summit ライトウェイト ランドリーバッグ", descEn: "Mesh nylon, drawstring closure, 22 L volume, weighs 1.4 oz. Excellent for separating dirty from clean.", descJa: "メッシュナイロン、ドローストリング閉鎖、22L容量、40g。汚れ物と清潔な物の分離に最適。", priceMin: "$15", priceMax: "$22", category: "travel", badge: "👕", url: "https://www.seatosummit.com/" },
  { id: "ebags-medium-laundry-bag", nameEn: "eBags Medium Laundry Bag", nameJa: "eBags ミディアム ランドリーバッグ", descEn: "Lightweight nylon with drawstring, machine washable. Plain practical design, fits 1-week of clothes.", descJa: "ドローストリング付きライトウェイトナイロン、洗濯機可。シンプル実用設計、1週間分の衣類が入る。", priceMin: "$12", priceMax: "$18", category: "travel", badge: "👕", url: "https://www.ebags.com/" },
  { id: "boundless-voyage-mesh-bag", nameEn: "Boundless Voyage Mesh Laundry Bag", nameJa: "Boundless Voyage メッシュランドリーバッグ", descEn: "Mesh polyester for ventilation, dual compartment (dirty/clean), drawstring closure. Best dual-compartment under $15.", descJa: "通気メッシュポリエステル、デュアル仕切り（汚れ／清潔）、ドローストリング閉鎖。$15以下でデュアル仕切り最有力。", priceMin: "$13", priceMax: "$18", category: "travel", badge: "👕", url: "https://www.boundless-voyage.com/" },
  { id: "hibag-foldable-laundry", nameEn: "HiBag Foldable Laundry Bag", nameJa: "HiBag 折り畳みランドリーバッグ", descEn: "Oxford nylon, holds 60+ shirts, foldable into pouch, included shoulder strap. Doubles as a day-of-departure carrier.", descJa: "オックスフォードナイロン、シャツ60着以上収納、ポーチに折り畳み可、ショルダーストラップ付属。出発日のキャリアにも転用可能。", priceMin: "$14", priceMax: "$22", category: "travel", badge: "👕", url: "https://www.hibagstore.com/" },

  // best-compression-socks-2026
  { id: "sockwell-circulator-compression", nameEn: "Sockwell Circulator Compression Socks", nameJa: "Sockwell サーキュレーター 着圧ソックス", descEn: "Merino wool blend, graduated compression (15-20 mmHg), targeted cushion. Best for office work + travel.", descJa: "メリノウール混紡、グラデュエーテッド圧（15-20mmHg）、ターゲットクッション。オフィスワーク＋旅行に最有力。", priceMin: "$25", priceMax: "$35", category: "travel", badge: "🧦", url: "https://sockwellusa.com/" },
  { id: "comrad-knee-high-compression", nameEn: "Comrad Knee-High Compression Socks", nameJa: "Comrad ニーハイ 着圧ソックス", descEn: "Recycled nylon, 15-20 mmHg, soft fabric, hundreds of colors. Direct-to-consumer pricing. Best style options.", descJa: "リサイクルナイロン、15-20mmHg、ソフト生地、数百色。D2C価格。スタイル最強。", priceMin: "$25", priceMax: "$30", category: "travel", badge: "🧦", url: "https://comradsocks.com/" },
  { id: "physix-gear-sport-compression", nameEn: "Physix Gear Sport Compression Socks", nameJa: "Physix Gear スポーツ着圧ソックス", descEn: "20-30 mmHg (medical grade), athletic fit, anti-bacterial. Best Amazon-direct option for runners.", descJa: "20-30mmHg（医療グレード）、アスレチックフィット、抗菌。ランナー向けAmazon直販最有力。", priceMin: "$20", priceMax: "$28", category: "travel", badge: "🧦", url: "https://physixgear.com/" },
  { id: "copper-fit-energy-compression", nameEn: "Copper Fit Energy Compression Socks", nameJa: "Copper Fit エナジー 着圧ソックス", descEn: "Copper-infused fibers, 15-20 mmHg, moisture-wicking. Most widely available at US drugstores.", descJa: "銅繊維、15-20mmHg、吸湿。米国ドラッグストアで最も入手しやすい。", priceMin: "$15", priceMax: "$25", category: "travel", badge: "🧦", url: "https://copperfit.com/" },
  { id: "vim-and-vigr-cotton-compression", nameEn: "VIM & VIGR Cotton Compression Socks", nameJa: "VIM & VIGR コットン 着圧ソックス", descEn: "15-20 mmHg, wide calf available, cotton-rich blend, modern patterns. Best for those who want compression that doesn't look medical.", descJa: "15-20mmHg、ワイドカーフあり、コットンリッチ混紡、モダンパターン。医療っぽくない着圧を求める人に最有力。", priceMin: "$30", priceMax: "$40", category: "travel", badge: "🧦", url: "https://www.vimandvigr.com/" },
];
