// @ts-nocheck — large data file; union type inference disabled intentionally
import type { AffiliateOffer } from "./types";

export const CATALOG_BATCH12_BEAUTY: AffiliateOffer[] = [
  // ── best-lip-liner-2026 ────────────────────────────────────────────────────
  {
    id: "charlotte-tilbury-lip-cheat",
    imageUrl: "https://m.media-amazon.com/images/I/61K82e9h3cL._SL1500_.jpg",
    priceMin: "24",
    priceMax: "28",
    category: "beauty",
    badge: "💄",
    name: { en: "Charlotte Tilbury Lip Cheat Lip Liner", ja: "シャーロット・ティルバリー リップチート リップライナー" },
    description: {
      en: "Creamy, long-wear lip pencil in a comprehensive nude-to-berry shade range. Features a self-sharpening tip and a moisturizing formula that glides without dragging.",
      ja: "ヌードからベリー系まで幅広いシェードを揃えたクリーミーで長持ちするリップペンシル。セルフシャープニングチップ搭載で、引っかかりなめらかな保湿処方。",
    },
    links: [{ network: "direct", productId: "https://www.charlottetilbury.com/us/category/lips/lip-liner", markets: ["global"], approved: true }],
  },
  {
    id: "nyx-slim-lip-pencil",
    imageUrl: "https://m.media-amazon.com/images/I/6148LGpukCL._AC_SL1500_.jpg",
    priceMin: "4",
    priceMax: "6",
    category: "beauty",
    badge: "💄",
    name: { en: "NYX Professional Makeup Slim Lip Pencil", ja: "NYX プロフェッショナル メイクアップ スリムリップペンシル" },
    description: {
      en: "Ultra-thin precision lip liner with a matte finish, available in 40+ shades. Retractable design with a smooth, pigment-dense formula that lasts up to 8 hours.",
      ja: "マットな仕上がりの超極細精密リップライナー。40色以上展開、繰り出し式で8時間持続する高発色処方。",
    },
    links: [{ network: "direct", productId: "https://www.nyxcosmetics.com/lips/lip-liner", markets: ["global"], approved: true }],
  },
  {
    id: "urban-decay-24-7-glide-on",
    imageUrl: "https://m.media-amazon.com/images/I/718VgSdJ+aL._SL1500_.jpg",
    priceMin: "22",
    priceMax: "25",
    category: "beauty",
    badge: "💄",
    name: { en: "Urban Decay 24/7 Glide-On Lip Pencil", ja: "アーバンディケイ 24/7 グライドオン リップペンシル" },
    description: {
      en: "Waterproof, smudge-proof lip liner with a vitamin E and jojoba-infused formula. Glides on with zero skipping and sets to a semi-matte finish that stays put all day.",
      ja: "ビタミンEとホホバ配合の防水・にじみ防止リップライナー。スキップゼロで滑らかに描け、セミマットな仕上がりが一日中続く。",
    },
    links: [{ network: "direct", productId: "https://www.urbandecay.com/collections/lip-liner", markets: ["global"], approved: true }],
  },
  {
    id: "mac-lip-pencil-brick",
    imageUrl: "https://m.media-amazon.com/images/I/61R3aHIcj5L._SL1500_.jpg",
    priceMin: "21",
    priceMax: "23",
    category: "beauty",
    badge: "💄",
    name: { en: "MAC Lip Pencil in Brick", ja: "MAC リップペンシル ブリック" },
    description: {
      en: "Classic MAC lip liner in the iconic terracotta-brick shade. Smooth, creamy texture with a long-wearing formula; compatible with virtually every warm-toned lipstick.",
      ja: "テラコッタブリックシェードのクラシックなMACリップライナー。クリーミーなテクスチャーで長持ちし、ほぼすべてのウォームトーンリップに対応。",
    },
    links: [{ network: "direct", productId: "https://www.maccosmetics.com/product/13832/303/products/makeup/lips/liners/lip-pencil", markets: ["global"], approved: true }],
  },
  {
    id: "elf-no-budge-lip-liner",
    imageUrl: "https://images.squarespace-cdn.com/content/v1/51d151b1e4b05d425c859fc9/408532c1-85ea-4dc4-a976-0ec414c591eb/A7401603.jpg",
    priceMin: "5",
    priceMax: "7",
    category: "beauty",
    badge: "💄",
    name: { en: "e.l.f. No Budge Lip Liner", ja: "e.l.f. ノーバジ リップライナー" },
    description: {
      en: "Affordable retractable lip liner with a creamy, pigmented formula that resists feathering. Vegan and cruelty-free; stays comfortable for up to 10 hours.",
      ja: "リーズナブルな繰り出し式リップライナー。にじみにくいクリーミー高発色処方で10時間快適に続く。ヴィーガン・クルエルティフリー。",
    },
    links: [{ network: "direct", productId: "https://www.elfcosmetics.com/no-budge-lip-liner", markets: ["global"], approved: true }],
  },

  // ── best-brow-gel-2026 ────────────────────────────────────────────────────
  {
    id: "anastasia-dipbrow-gel",
    imageUrl: "https://m.media-amazon.com/images/I/51CpicewVhL._AC_SS450_.jpg",
    priceMin: "25",
    priceMax: "28",
    category: "beauty",
    badge: "💄",
    name: { en: "Anastasia Beverly Hills Dipbrow Gel", ja: "アナスタシア ビバリーヒルズ ディップブロウ ジェル" },
    description: {
      en: "Waterproof tinted brow gel with a buildable, fiber-infused formula that mimics natural hair strokes. Includes a dual-ended brush for precision application and blending.",
      ja: "ファイバー配合の防水ティントブロウジェル。自然な毛並みを再現でき、精密塗布＆ぼかし用デュアルブラシ付属。",
    },
    links: [{ network: "direct", productId: "https://www.anastasiabeverlyhills.com/eyebrows/brow-gels", markets: ["global"], approved: true }],
  },
  {
    id: "benefit-gimme-brow-plus",
    imageUrl: "https://m.media-amazon.com/images/I/71xVSKk0F1L._AC_SL1500_.jpg",
    priceMin: "26",
    priceMax: "30",
    category: "beauty",
    badge: "💄",
    name: { en: "Benefit Gimme Brow+ Volumizing Fiber Gel", ja: "ベネフィット ギミーブロウ+ ボリュームアップ ファイバージェル" },
    description: {
      en: "Volumizing brow gel with micro-fine fibers that coat and plump each brow hair. Waterproof, buildable coverage in 9 shades; the mini wand tip makes it virtually foolproof.",
      ja: "極細ファイバーが眉毛をコーティングしふっくら見せるボリュームアップブロウジェル。9色展開の防水タイプ、ミニワンドチップで失敗しにくい。",
    },
    links: [{ network: "direct", productId: "https://www.benefitcosmetics.com/en-us/eyebrow-products/gimme-brow-plus", markets: ["global"], approved: true }],
  },
  {
    id: "nyx-control-freak-brow-gel",
    imageUrl: "https://m.media-amazon.com/images/I/61A86Lb7wuL._SL1500_.jpg",
    priceMin: "9",
    priceMax: "11",
    category: "beauty",
    badge: "💄",
    name: { en: "NYX Professional Makeup Control Freak Eyebrow Gel", ja: "NYX プロフェッショナル メイクアップ コントロールフリーク アイブロウジェル" },
    description: {
      en: "Clear brow-setting gel that tames and holds even the most unruly brows for up to 16 hours. Lightweight, flake-free formula; vegan and cruelty-free.",
      ja: "どんなに手強い眉毛も16時間固定するクリアブロウセッティングジェル。軽くてフレークなし、ヴィーガン・クルエルティフリー。",
    },
    links: [{ network: "direct", productId: "https://www.nyxcosmetics.com/eyes/eyebrows", markets: ["global"], approved: true }],
  },
  {
    id: "maybelline-brow-fast-sculptor",
    imageUrl: "https://m.media-amazon.com/images/I/51gqZ3DkZ5L.jpg",
    priceMin: "8",
    priceMax: "10",
    category: "beauty",
    badge: "💄",
    name: { en: "Maybelline Brow Fast Sculptor Shaping Brow Mascara", ja: "メイベリン ブロウ ファスト スカルプター シェイピング ブロウマスカラ" },
    description: {
      en: "2-in-1 brow mascara with a micro-brush that fills and sculpts simultaneously. Buildable tint in 5 shades; dries quickly without stiffness or flaking.",
      ja: "マイクロブラシで同時にフィル＆スカルプする2-in-1ブロウマスカラ。5色展開のビルダブルティント、素早く乾いて硬さやフレークなし。",
    },
    links: [{ network: "direct", productId: "https://www.maybelline.com/eye-makeup/eyebrow-makeup/brow-fast-sculptor", markets: ["global"], approved: true }],
  },
  {
    id: "e-l-f-brow-lift",
    imageUrl: "https://m.media-amazon.com/images/I/610qJYb80+L._SY450_.jpg",
    priceMin: "10",
    priceMax: "12",
    category: "beauty",
    badge: "💄",
    name: { en: "e.l.f. Brow Lift", ja: "e.l.f. ブロウリフト" },
    description: {
      en: "Buildable, waterproof brow styling wax that shapes and laminated-look volume to brows. Clear or tinted shades available; vegan, cruelty-free, long-lasting hold.",
      ja: "眉毛を整えラミネート風ボリュームを与える防水ブロウスタイリングワックス。クリアまたはティント、ヴィーガン・クルエルティフリーで長時間キープ。",
    },
    links: [{ network: "direct", productId: "https://www.elfcosmetics.com/brow-lift", markets: ["global"], approved: true }],
  },

  // ── best-highlighter-makeup-2026 ─────────────────────────────────────────
  {
    id: "becca-shimmering-skin-perfector",
    imageUrl: "https://m.media-amazon.com/images/I/71bDqTAtK5L._SL1500_.jpg",
    priceMin: "40",
    priceMax: "46",
    category: "beauty",
    badge: "💄",
    name: { en: "BECCA Shimmering Skin Perfector Pressed Highlighter", ja: "ベッカ シマリング スキン パーフェクター プレスト ハイライター" },
    description: {
      en: "Cult-status pressed highlighter delivering a pure, blinding glow without visible glitter particles. Finely milled pearlescent formula available in 10+ shades from champagne to rose gold.",
      ja: "ギラつきのない純粋なまばゆい輝きを放つカルト的人気プレストハイライター。シャンパンからローズゴールドまで10色以上の微粒子パールセント処方。",
    },
    links: [{ network: "direct", productId: "https://www.sephora.com/brand/becca/highlighters", markets: ["global"], approved: true }],
  },
  {
    id: "fenty-killawatt-highlighter",
    imageUrl: "https://m.media-amazon.com/images/I/61WFVXb308L._AC_.jpg",
    priceMin: "36",
    priceMax: "40",
    category: "beauty",
    badge: "💄",
    name: { en: "Fenty Beauty Killawatt Freestyle Highlighter", ja: "フェンティ ビューティ キラワット フリースタイル ハイライター" },
    description: {
      en: "Duo-shade pressed powder highlighter with buildable intensity from subtle shimmer to full foil. Includes 40 shade combinations; suitable for all skin tones including deep complexions.",
      ja: "繊細なシマーからフルフォイルまでビルダブルなデュオシェードプレスドパウダーハイライター。40コンビ展開で深みのある肌色にも対応。",
    },
    links: [{ network: "direct", productId: "https://fentybeauty.com/collections/highlighters", markets: ["global"], approved: true }],
  },
  {
    id: "charlotte-tilbury-beauty-light-wand",
    imageUrl: "https://m.media-amazon.com/images/I/51ReIqS6nXL._AC_SL1500_.jpg",
    priceMin: "38",
    priceMax: "42",
    category: "beauty",
    badge: "💄",
    name: { en: "Charlotte Tilbury Beauty Light Wand", ja: "シャーロット・ティルバリー ビューティ ライトワンド" },
    description: {
      en: "Liquid highlighter wand with a domed applicator for a blurred, lit-from-within glow. Buildable formula blends seamlessly over makeup or bare skin.",
      ja: "ドーム型アプリケーターでぼかした内側から輝くような発光を実現するリキッドハイライターワンド。メイクの上または素肌にシームレスにブレンド可能。",
    },
    links: [{ network: "direct", productId: "https://www.charlottetilbury.com/us/category/complexion/highlighter", markets: ["global"], approved: true }],
  },
  {
    id: "nars-highlighting-powder",
    imageUrl: "https://m.media-amazon.com/images/I/71c4i4KNdzL._SL1500_.jpg",
    priceMin: "34",
    priceMax: "38",
    category: "beauty",
    badge: "💄",
    name: { en: "NARS Highlighting Powder", ja: "NARS ハイライティングパウダー" },
    description: {
      en: "Silky pressed highlighter with a buildable, luminous finish ranging from soft pearl to intense bronze glow. Eight iconic shades; transfers cleanly to skin without chalkiness.",
      ja: "ソフトパールから強烈なブロンズグローまでビルダブルな発光仕上げのシルキープレストハイライター。8色展開、白浮きなし。",
    },
    links: [{ network: "direct", productId: "https://www.narscosmetics.com/USA/highlighting-powder", markets: ["global"], approved: true }],
  },
  {
    id: "elf-halo-glow-liquid-filter",
    imageUrl: "https://m.media-amazon.com/images/I/61aFsJghCSL._SL1500_.jpg",
    priceMin: "14",
    priceMax: "16",
    category: "beauty",
    badge: "💄",
    name: { en: "e.l.f. Halo Glow Liquid Filter", ja: "e.l.f. ハローグロウ リキッドフィルター" },
    description: {
      en: "Skin tint and highlighter hybrid with hyaluronic acid and niacinamide. Buildable coverage from sheer glow to medium; 8 shades spanning fair to deep skin tones.",
      ja: "ヒアルロン酸とナイアシンアミド配合のスキンティント＆ハイライターハイブリッド。シアーグローからミディアムカバレッジまで8色展開。",
    },
    links: [{ network: "direct", productId: "https://www.elfcosmetics.com/halo-glow-liquid-filter", markets: ["global"], approved: true }],
  },

  // ── best-self-tanner-2026 ────────────────────────────────────────────────
  {
    id: "st-tropez-self-tan-express",
    imageUrl: "https://m.media-amazon.com/images/I/61i0YPYqA4L._AC_SL1500_.jpg",
    priceMin: "42",
    priceMax: "50",
    category: "beauty",
    badge: "💄",
    name: { en: "St. Tropez Self Tan Express Bronzing Mousse", ja: "セント・トロぺ セルフタン エクスプレス ブロンジングムース" },
    description: {
      en: "Fast-developing self-tanner mousse that lets you control depth of color from light (1 hour) to dark (3 hours). DHA-based formula with a fresh, non-biscuity scent; rinse-off application.",
      ja: "1時間でライト、3時間でダークと発色コントロールができる速乾セルフタナームース。DHA処方でビスケット臭なし、洗い流すタイプ。",
    },
    links: [{ network: "direct", productId: "https://www.sttropeztan.com/collections/self-tan-express", markets: ["global"], approved: true }],
  },
  {
    id: "bondi-sands-aero-self-tanner",
    imageUrl: "https://m.media-amazon.com/images/I/61AwpffSTxS._AC_SL1500_.jpg",
    priceMin: "18",
    priceMax: "22",
    category: "beauty",
    badge: "💄",
    name: { en: "Bondi Sands Aero Self Tanning Foam", ja: "ボンダイサンズ エアロ セルフタニングフォーム" },
    description: {
      en: "Lightweight, aerated self-tanning foam with aloe vera that develops an even, olive-toned tan in 4–6 hours. Australian brand; vegan and dermatologist tested.",
      ja: "アロエベラ配合の軽量エアレイテッドセルフタニングフォーム。4〜6時間でムラなくオリーブトーンの小麦色に仕上がるオーストラリアブランド。",
    },
    links: [{ network: "direct", productId: "https://bondisands.com/collections/self-tan", markets: ["global"], approved: true }],
  },
  {
    id: "jergens-natural-glow-daily",
    imageUrl: "https://m.media-amazon.com/images/I/61IjlhHKD5L._SL1500_.jpg",
    priceMin: "9",
    priceMax: "12",
    category: "beauty",
    badge: "💄",
    name: { en: "Jergens Natural Glow Daily Moisturizer", ja: "ジャーゲンス ナチュラルグロウ デイリーモイスチャライザー" },
    description: {
      en: "Gradual self-tanning lotion that builds color with daily use over 3–5 days. Three shades for fair to medium and medium to tan skin; non-greasy, moisturizing formula.",
      ja: "毎日使うことで3〜5日かけてじっくり色づくグラデュアルセルフタニングローション。フェアからミディアム、ミディアムからタン用3色。べたつかない保湿処方。",
    },
    links: [{ network: "direct", productId: "https://www.jergens.com/en-us/products/natural-glow", markets: ["global"], approved: true }],
  },
  {
    id: "tarte-brazilliance-plus",
    imageUrl: "https://m.media-amazon.com/images/I/51R1YgmaMPL._AC_.jpg",
    priceMin: "40",
    priceMax: "45",
    category: "beauty",
    badge: "💄",
    name: { en: "Tarte Brazilliance+ Self-Tanner with Pure Maracuja Oil", ja: "タルト ブラジリアンス+ マラクジャオイル配合セルフタナー" },
    description: {
      en: "Self-tanning serum enriched with Amazonian maracuja oil for hydrated, glowing skin as it tans. Develops in 6–8 hours; suitable for sensitive skin and free of parabens and mineral oil.",
      ja: "タンニングしながら肌を潤わせるアマゾン産マラクジャオイル配合セルフタニングセラム。6〜8時間で発色、敏感肌対応、パラベン・ミネラルオイルフリー。",
    },
    links: [{ network: "direct", productId: "https://tartecosmetics.com/collections/self-tanner", markets: ["global"], approved: true }],
  },
  {
    id: "isle-of-paradise-drops",
    imageUrl: "https://m.media-amazon.com/images/I/61XDppNLjQL._SL1500_.jpg",
    priceMin: "32",
    priceMax: "38",
    category: "beauty",
    badge: "💄",
    name: { en: "Isle of Paradise Self-Tanning Drops", ja: "アイル・オブ・パラダイス セルフタニングドロップス" },
    description: {
      en: "Customizable self-tanning concentrate drops mixed into any skincare product. Three shades (light/medium/dark) with color-correcting actives; vegan, cruelty-free, and fragrance-free.",
      ja: "スキンケア製品に混ぜて使うカスタマイズ可能なセルフタニングコンセントレートドロップ。3色展開（ライト/ミディアム/ダーク）、カラーコレクション成分配合、ヴィーガン・無香料。",
    },
    links: [{ network: "direct", productId: "https://isleofparadise.com/collections/self-tanning-drops", markets: ["global"], approved: true }],
  },

  // ── best-hand-cream-2026 ─────────────────────────────────────────────────
  {
    id: "neutrogena-norwegian-formula-hand",
    imageUrl: "https://m.media-amazon.com/images/I/61gKfmA7xBL._SL1500_.jpg",
    priceMin: "7",
    priceMax: "10",
    category: "beauty",
    badge: "💄",
    name: { en: "Neutrogena Norwegian Formula Hand Cream", ja: "ニュートロジーナ ノルウェー フォーミュラ ハンドクリーム" },
    description: {
      en: "Concentrated glycerin-based hand cream clinically proven to heal severely dry hands in one application. Fragrance-free option available; dermatologist-recommended formula.",
      ja: "1回の使用で重度の乾燥した手を修復することが臨床的に証明された濃縮グリセリン系ハンドクリーム。無香料あり、皮膚科医推奨処方。",
    },
    links: [{ network: "direct", productId: "https://www.neutrogena.com/skincare/hand-and-nail/norwegian-formula-hand-cream", markets: ["global"], approved: true }],
  },
  {
    id: "l-occitane-shea-butter-hand",
    imageUrl: "https://m.media-amazon.com/images/I/81UHVKGxeIL._AC_SL1500_.jpg",
    priceMin: "30",
    priceMax: "36",
    category: "beauty",
    badge: "💄",
    name: { en: "L'Occitane Shea Butter Hand Cream", ja: "ロクシタン シア バター ハンドクリーム" },
    description: {
      en: "20% shea butter hand cream with almond extracts and honey for intensely nourishing moisture. Non-greasy finish; the gold-standard travel-size tube for dry-climate travelers.",
      ja: "アーモンドエキスとハニー配合の20%シアバター配合濃厚保湿ハンドクリーム。べたつかない仕上がりで乾燥地帯のトラベルサイズのゴールドスタンダード。",
    },
    links: [{ network: "direct", productId: "https://usa.loccitane.com/shea-butter-hand-cream", markets: ["global"], approved: true }],
  },
  {
    id: "aveeno-skin-relief-hand",
    imageUrl: "https://m.media-amazon.com/images/I/71cniTCy1wL.jpg",
    priceMin: "8",
    priceMax: "11",
    category: "beauty",
    badge: "💄",
    name: { en: "Aveeno Skin Relief Intense Moisture Hand Cream", ja: "アヴィーノ スキンリリーフ インテンスモイスチャー ハンドクリーム" },
    description: {
      en: "Oat-kernel and shea butter-enriched hand cream that provides 24-hour moisture relief for very dry, sensitive skin. Fragrance-free, non-greasy, and accepted by the National Eczema Association.",
      ja: "オーツ麦カーネルとシアバター配合で24時間保湿、非常に乾燥した敏感肌向けハンドクリーム。無香料、べたつかず、全米湿疹協会認定。",
    },
    links: [{ network: "direct", productId: "https://www.aveeno.com/products/skin-relief-intense-moisture-hand-cream", markets: ["global"], approved: true }],
  },
  {
    id: "o-keeffe-working-hands",
    imageUrl: "https://m.media-amazon.com/images/I/81zTboMmjHL.jpg",
    priceMin: "9",
    priceMax: "11",
    category: "beauty",
    badge: "💄",
    name: { en: "O'Keeffe's Working Hands Hand Cream", ja: "オキーフス ワーキングハンズ ハンドクリーム" },
    description: {
      en: "High-concentration glycerin jar cream formulated for extremely cracked, damaged hands from manual labor. Creates a moisture barrier that locks in hydration; no scent, no frills.",
      ja: "肉体労働で極度にひび割れた傷んだ手向けの高濃度グリセリンジャークリーム。保湿バリアを形成し潤いを閉じ込める、無香料シンプル処方。",
    },
    links: [{ network: "direct", productId: "https://www.okeeffescompany.com/product/working-hands-hand-cream", markets: ["global"], approved: true }],
  },
  {
    id: "aquaphor-healing-ointment-hand",
    imageUrl: "https://m.media-amazon.com/images/I/61Qy33ehgVL._AC_SL1500_.jpg",
    priceMin: "10",
    priceMax: "14",
    category: "beauty",
    badge: "💄",
    name: { en: "Aquaphor Healing Ointment", ja: "アクアフォー ヒーリングオイントメント" },
    description: {
      en: "41% petrolatum occlusive ointment that creates a protective skin barrier to heal extremely dry, cracked skin. Fragrance-free; doubles as a lip treatment and cuticle restorer.",
      ja: "41%ワセリン配合の閉鎖性軟膏で保護バリアを形成し、極度の乾燥やひび割れを修復。無香料、リップトリートメントやキューティクルリストアとしても使用可。",
    },
    links: [{ network: "direct", productId: "https://www.aquaphorus.com/products/aquaphor-healing-ointment", markets: ["global"], approved: true }],
  },

  // ── best-pimple-patches-2026 ─────────────────────────────────────────────
  {
    id: "hero-cosmetics-mighty-patch-original",
    imageUrl: "https://m.media-amazon.com/images/I/31QUUyeB5lL._SX300_SY300_QL70_ML2_.jpg",
    priceMin: "13",
    priceMax: "15",
    category: "beauty",
    badge: "💄",
    name: { en: "Hero Cosmetics Mighty Patch Original", ja: "ヒーロー コスメティクス マイティパッチ オリジナル" },
    description: {
      en: "Medical-grade hydrocolloid pimple patches in 24-count dot format. 6mm and 12mm sizes absorb pus and sebum overnight without damaging surrounding skin; drug-free, vegan.",
      ja: "24枚入り医療グレードハイドロコロイドニキビパッチ。6mm・12mm径で一晩のうちに膿や皮脂を吸収、周囲の肌を傷めない。医薬品フリー、ヴィーガン。",
    },
    links: [{ network: "direct", productId: "https://herocosmetics.us/products/mighty-patch-original", markets: ["global"], approved: true }],
  },
  {
    id: "cosrx-acne-pimple-master",
    imageUrl: "https://m.media-amazon.com/images/I/61yiOUb7bNL.jpg",
    priceMin: "6",
    priceMax: "9",
    category: "beauty",
    badge: "💄",
    name: { en: "COSRX Acne Pimple Master Patch", ja: "COSRX アクネ ピンプル マスターパッチ" },
    description: {
      en: "Korean hydrocolloid patches in three sizes (7mm, 10mm, 12mm) — 24 total per sheet — for targeted blemish treatment. Thin, translucent design that's barely visible under makeup.",
      ja: "1シート24枚入り3サイズ（7mm・10mm・12mm）の韓国ハイドロコロイドパッチ。薄くて透明、メイクの下でも目立ちにくいニキビ集中ケア。",
    },
    links: [{ network: "direct", productId: "https://www.cosrx.com/products/acne-pimple-master-patch", markets: ["global"], approved: true }],
  },
  {
    id: "peach-slices-acne-spot-dots",
    imageUrl: "https://m.media-amazon.com/images/I/61Sss91Y1LL._AC_.jpg",
    priceMin: "5",
    priceMax: "7",
    category: "beauty",
    badge: "💄",
    name: { en: "Peach Slices Acne Spot Dots", ja: "ピーチスライス アクネスポットドッツ" },
    description: {
      en: "Hydrocolloid acne patches with two thicknesses — one for daytime wear and one for overnight treatment. Flexible, skin-tone shades blend into complexion; vegan and fragrance-free.",
      ja: "昼用・夜間ケア用の2種類の厚みを持つハイドロコロイドアクネパッチ。肌色に馴染む柔軟な素材、ヴィーガン・無香料。",
    },
    links: [{ network: "direct", productId: "https://peachslices.com/products/acne-spot-dots", markets: ["global"], approved: true }],
  },
  {
    id: "starface-hydro-stars",
    imageUrl: "https://m.media-amazon.com/images/I/51vNqQwBy6L._SL1000_.jpg",
    priceMin: "22",
    priceMax: "25",
    category: "beauty",
    badge: "💄",
    name: { en: "Starface Hydro-Stars Pimple Patches", ja: "スターフェイス ハイドロスターズ ニキビパッチ" },
    description: {
      en: "Star-shaped hydrocolloid pimple patches in a bright yellow refillable compact. 32 patches per compact; cheerful alternative to skin-tone dots that normalizes acne treatment.",
      ja: "明るい黄色の詰め替え可能コンパクト入り星型ハイドロコロイドニキビパッチ。1個32枚入り、肌色ドットの代わりにニキビケアを前向きにする元気なデザイン。",
    },
    links: [{ network: "direct", productId: "https://starface.world/products/hydro-stars", markets: ["global"], approved: true }],
  },
  {
    id: "mighty-patch-invisible-plus",
    imageUrl: "https://m.media-amazon.com/images/I/51Aa8lq06QL.jpg",
    priceMin: "15",
    priceMax: "18",
    category: "beauty",
    badge: "💄",
    name: { en: "Hero Cosmetics Mighty Patch Invisible+", ja: "ヒーロー コスメティクス マイティパッチ インビジブル+" },
    description: {
      en: "Ultra-thin, matte daytime pimple patch from Hero Cosmetics designed to disappear under foundation. Hydrocolloid core with a micro-dot surface texture for near-invisible wear.",
      ja: "ファンデーションの下で消えるように設計されたヒーロー コスメティクスの超薄型マットデイタイムニキビパッチ。マイクロドット表面テクスチャで目立たないハイドロコロイドコア。",
    },
    links: [{ network: "direct", productId: "https://herocosmetics.us/products/mighty-patch-invisible-plus", markets: ["global"], approved: true }],
  },

  // ── best-clay-mask-2026 ──────────────────────────────────────────────────
  {
    id: "aztec-secret-indian-healing-clay",
    imageUrl: "https://m.media-amazon.com/images/I/71OElrEWgCL._SL1500_.jpg",
    priceMin: "10",
    priceMax: "14",
    category: "beauty",
    badge: "💄",
    name: { en: "Aztec Secret Indian Healing Clay", ja: "アズテック シークレット インディアン ヒーリングクレイ" },
    description: {
      en: "100% natural calcium bentonite clay powder mixed with apple cider vinegar or water. Deep-pore cleansing with noticeable pulsating sensation; 1 lb jar lasts 6–12 months.",
      ja: "りんご酢または水と混ぜて使う100%天然カルシウムベントナイトクレイパウダー。深層毛穴クレンジングと独特の脈動感あり、1ポンドジャーで6〜12ヶ月使用可能。",
    },
    links: [{ network: "direct", productId: "https://aztec-secret.com/products/aztec-secret-indian-healing-clay", markets: ["global"], approved: true }],
  },
  {
    id: "glamglow-supermud-clearing",
    imageUrl: "https://m.media-amazon.com/images/I/71USrkhN+tL._AC_SL1500_.jpg",
    priceMin: "52",
    priceMax: "60",
    category: "beauty",
    badge: "💄",
    name: { en: "GlamGlow Supermud Clearing Treatment", ja: "グラムグロウ スーパーマッド クリアリングトリートメント" },
    description: {
      en: "Multi-acid (glycolic, salicylic, lactic) clay treatment with activated charcoal and eucalyptus leaf for spot-targeting purification. 6-in-1 exfoliation, purification, and brightening formula.",
      ja: "グリコール酸・サリチル酸・乳酸と活性炭＆ユーカリ葉配合のマルチアシッドクレイトリートメント。スポットターゲットの6-in-1角質除去・浄化・明るさアップ処方。",
    },
    links: [{ network: "direct", productId: "https://www.glamglow.com/collections/supermud", markets: ["global"], approved: true }],
  },
  {
    id: "origins-clear-improvement-charcoal",
    imageUrl: "https://m.media-amazon.com/images/I/61m-G2mZKCL._SL1500_.jpg",
    priceMin: "26",
    priceMax: "30",
    category: "beauty",
    badge: "💄",
    name: { en: "Origins Clear Improvement Active Charcoal Mask", ja: "オリジンズ クリアインプルーブメント アクティブチャコールマスク" },
    description: {
      en: "White china clay and bamboo charcoal mask that draws out environmental pollutants and congestion. 10-minute treatment; suitable for oily and combination skin types.",
      ja: "環境汚染物質や詰まり毛穴を吸い取る白磁土とバンブーチャコール配合マスク。10分使用、オイリー〜混合肌向け。",
    },
    links: [{ network: "direct", productId: "https://www.origins.com/products/clear-improvement-active-charcoal-mask", markets: ["global"], approved: true }],
  },
  {
    id: "innisfree-super-volcanic-pore",
    imageUrl: "https://m.media-amazon.com/images/I/71OAKiRewkL._SL1500_.jpg",
    priceMin: "18",
    priceMax: "22",
    category: "beauty",
    badge: "💄",
    name: { en: "Innisfree Super Volcanic Pore Clay Mask 2X", ja: "イニスフリー スーパー ヴォルカニック ポア クレイマスク 2X" },
    description: {
      en: "Jeju volcanic ash clay mask with a bouncy foam texture that clears sebum and minimizes pores. 2X upgraded formula with hyaluronic acid; rinse off in 5–10 minutes.",
      ja: "済州火山灰クレイマスク、バウンシーなフォームテクスチャーが皮脂を取り除き毛穴を引き締める。ヒアルロン酸配合2Xアップグレード処方、5〜10分後に洗い流す。",
    },
    links: [{ network: "direct", productId: "https://www.innisfree.com/us/product/super-volcanic-pore-clay-mask-2x", markets: ["global"], approved: true }],
  },
  {
    id: "freeman-feeling-beautiful-clay",
    imageUrl: "https://m.media-amazon.com/images/I/91TaT67m2BL._AC_.jpg",
    priceMin: "4",
    priceMax: "6",
    category: "beauty",
    badge: "💄",
    name: { en: "Freeman Feeling Beautiful Facial Clay Mask", ja: "フリーマン フィーリング ビューティフル フェイシャルクレイマスク" },
    description: {
      en: "Kaolin and avocado clay facial mask with a creamy, spreadable texture; rinseable or peel-off formats available. Budget pick with a pleasing mint scent and noticeable pore-tightening effect.",
      ja: "カオリンとアボカド配合のクリーミーで塗り広げやすいフェイシャルクレイマスク。洗い流しとピールオフ両タイプあり、ミントの香りと毛穴引き締め効果が好評なプチプラ品。",
    },
    links: [{ network: "direct", productId: "https://www.freemanbeauty.com/collections/masks", markets: ["global"], approved: true }],
  },

  // ── best-eye-patches-2026 ────────────────────────────────────────────────
  {
    id: "peter-thomas-roth-cucumber-gel-eye",
    imageUrl: "https://m.media-amazon.com/images/I/61fpdK5447L._AC_SL1500_.jpg",
    priceMin: "52",
    priceMax: "58",
    category: "beauty",
    badge: "💄",
    name: { en: "Peter Thomas Roth Cucumber Gel Masks Eye Patches", ja: "ピーター・トーマス・ロス キューカンバー ジェルマスク アイパッチ" },
    description: {
      en: "Cooling cucumber and aloe vera gel eye patches that depuff visibly in 5 minutes. 60-count jar; single-use; peptides and green tea extract for ongoing under-eye support.",
      ja: "5分で目に見えてむくみを解消するキュウリとアロエヴェラジェルアイパッチ。60枚入りジャー、1回使い切り、ペプチドと緑茶エキスで継続ケア。",
    },
    links: [{ network: "direct", productId: "https://www.peterthomasroth.com/eye-patches", markets: ["global"], approved: true }],
  },
  {
    id: "tarte-maracuja-eye-patches",
    imageUrl: "https://m.media-amazon.com/images/I/51KKGJddB1L._SL1000_.jpg",
    priceMin: "38",
    priceMax: "44",
    category: "beauty",
    badge: "💄",
    name: { en: "Tarte Cosmetics Maracuja Eye Patches", ja: "タルト コスメティクス マラクジャ アイパッチ" },
    description: {
      en: "Vitamin C-rich maracuja oil-infused hydrogel under-eye patches targeting dark circles and dehydration lines. 30-pair pack; crescent shape fits most under-eye contours.",
      ja: "ビタミンC豊富なマラクジャオイル配合ハイドロゲルアイパッチがクマと乾燥小じわにアプローチ。30ペア入り、三日月型でほとんどのアイコンターにフィット。",
    },
    links: [{ network: "direct", productId: "https://tartecosmetics.com/collections/eye-patches", markets: ["global"], approved: true }],
  },
  {
    id: "snp-prep-cicaronic-eye-patches",
    imageUrl: "https://www.pinkland.co.nz/wp-content/uploads/2025/05/sn038-8.jpg",
    priceMin: "10",
    priceMax: "14",
    category: "beauty",
    badge: "💄",
    name: { en: "SNP Prep Cicaronic Eye Patches", ja: "SNP プレップ シカロニック アイパッチ" },
    description: {
      en: "Centella asiatica (cica) and niacinamide hydrogel eye patches that soothe sensitized under-eye skin. 60-count box; K-beauty formula optimized for redness and irritation reduction.",
      ja: "センテラアジアティカ（シカ）とナイアシンアミド配合ハイドロゲルアイパッチが敏感なアイエリアを鎮静。60枚入り、赤みと刺激を和らげるKビューティ処方。",
    },
    links: [{ network: "direct", productId: "https://snp-official.com/products/snp-prep-cicaronic-eye-patches", markets: ["global"], approved: true }],
  },
  {
    id: "skyn-iceland-hydro-cool-firming",
    imageUrl: "https://m.media-amazon.com/images/I/71od8USmRpL._AC_SL1500_.jpg",
    priceMin: "30",
    priceMax: "36",
    category: "beauty",
    badge: "💄",
    name: { en: "Skyn Iceland Hydro Cool Firming Eye Gels", ja: "スキン アイスランド ハイドロクール ファーミング アイジェル" },
    description: {
      en: "Firming under-eye gel patches with Icelandic glacial water, caffeine, and peptides targeting puffiness, fine lines, and fatigue. 20-pack; 10-minute treatment time.",
      ja: "アイスランド氷河水・カフェイン・ペプチド配合のファーミングアイジェルパッチがむくみ・小じわ・疲れ目にアプローチ。20枚入り、10分ケア。",
    },
    links: [{ network: "direct", productId: "https://www.skynamics.com/products/hydro-cool-firming-eye-gels", markets: ["global"], approved: true }],
  },
  {
    id: "yes-to-cucumber-eye-gel-patches",
    imageUrl: "https://d1flfk77wl2xk4.cloudfront.net/Assets/76/412/XL_p0087641276.jpg",
    priceMin: "8",
    priceMax: "10",
    category: "beauty",
    badge: "💄",
    name: { en: "Yes To Cucumbers Eye Gel Patches", ja: "イエス トゥ キューカンバー アイジェルパッチ" },
    description: {
      en: "Cucumber and green tea extract hydrogel under-eye patches for sensitive skin. Cooling, calming formula with hyaluronic acid; 5-pack single-use; vegan and paraben-free.",
      ja: "敏感肌向けキュウリと緑茶エキス配合ハイドロゲルアイパッチ。ヒアルロン酸配合の冷却・鎮静処方、5枚入り使い切り、ヴィーガン・パラベンフリー。",
    },
    links: [{ network: "direct", productId: "https://www.yesto.com/products/yes-to-cucumbers-eye-gel-patches", markets: ["global"], approved: true }],
  },

  // ── best-hair-growth-serum-2026 ──────────────────────────────────────────
  {
    id: "rogaine-minoxidil-5-percent-foam",
    imageUrl: "https://m.media-amazon.com/images/I/81gx9e+WbuL._AC_SL1500_.jpg",
    priceMin: "38",
    priceMax: "50",
    category: "beauty",
    badge: "💄",
    name: { en: "Rogaine 5% Minoxidil Foam for Men", ja: "ロゲイン 5% ミノキシジルフォーム（男性用）" },
    description: {
      en: "FDA-approved 5% minoxidil topical foam for androgenetic alopecia. Once-daily application; clinically proven to regrow hair in 4–6 months with consistent use.",
      ja: "男性型脱毛症（AGA）向けFDA承認5%ミノキシジル外用フォーム。1日1回塗布、継続使用で4〜6ヶ月での発毛が臨床的に証明済み。",
    },
    links: [{ network: "direct", productId: "https://www.rogaine.com/products/minoxidil-foam", markets: ["global"], approved: true }],
  },
  {
    id: "the-ordinary-multi-peptide-serum",
    imageUrl: "https://m.media-amazon.com/images/I/51xdLcc7IRL._AC_SL1079_.jpg",
    priceMin: "18",
    priceMax: "22",
    category: "beauty",
    badge: "💄",
    name: { en: "The Ordinary Multi-Peptide Serum for Hair Density", ja: "ジ オーディナリー マルチペプチド ヘアデンシティ セラム" },
    description: {
      en: "Peptide and caffeine blend serum targeting hair density and follicle support. 11 actives including Redensyl, Procapil, and CAPIXYL; apply to scalp and leave in; no fragrance.",
      ja: "Redensyl・Procapil・CAPIXYLを含む11成分配合ペプチド＆カフェインブレンドセラムで毛量と毛包をサポート。頭皮に塗ってそのまま、無香料。",
    },
    links: [{ network: "direct", productId: "https://theordinary.com/en-us/multi-peptide-serum-for-hair-density", markets: ["global"], approved: true }],
  },
  {
    id: "nutrafol-edge-hair-serum",
    imageUrl: "https://m.media-amazon.com/images/I/611uO3papGL._SX679_.jpg",
    priceMin: "88",
    priceMax: "98",
    category: "beauty",
    badge: "💄",
    name: { en: "Nutrafol Hair Serum for Edges", ja: "ニュートラフォール エッジ ヘアセラム" },
    description: {
      en: "Botanical-based topical serum targeting hairline edges and temples with Ashwagandha root, saw palmetto, and hyaluronic acid. Dermatologist-partnered formula; no hormones.",
      ja: "アシュワガンダ根・ノコギリヤシ・ヒアルロン酸配合のボタニカル系外用セラムがヘアライン・こめかみにアプローチ。皮膚科医と共同開発、ホルモンフリー。",
    },
    links: [{ network: "direct", productId: "https://nutrafol.com/products/hair-serum", markets: ["global"], approved: true }],
  },
  {
    id: "mielle-rosemary-mint-scalp-oil",
    imageUrl: "https://m.media-amazon.com/images/I/71RNwYyzvxL._AC_.jpg",
    priceMin: "10",
    priceMax: "13",
    category: "beauty",
    badge: "💄",
    name: { en: "Mielle Organics Rosemary Mint Scalp & Hair Strengthening Oil", ja: "ミーレ オーガニクス ローズマリー ミント スカルプ＆ヘアストレングスニングオイル" },
    description: {
      en: "Biotin and rosemary essential oil blend in a light carrier oil for scalp stimulation and hair strengthening. 2 fl oz with a precision tip applicator; suitable for all hair types.",
      ja: "頭皮刺激と強化のためのビオチンとローズマリー精油配合軽量キャリアオイル。精密チップアプリケーター付き2オンス、全毛質対応。",
    },
    links: [{ network: "direct", productId: "https://www.mielleorganics.com/products/rosemary-mint-scalp-hair-strengthening-oil", markets: ["global"], approved: true }],
  },
  {
    id: "vegamour-gro-hair-serum",
    imageUrl: "https://m.media-amazon.com/images/I/61NL8Ur1FuL._AC_SL1500_.jpg",
    priceMin: "58",
    priceMax: "68",
    category: "beauty",
    badge: "💄",
    name: { en: "Vegamour GRO Hair Serum", ja: "ヴェガムール GRO ヘアセラム" },
    description: {
      en: "Plant-based hair serum with KARMATIN (vegan b-SILK protein), mung bean, and red clover targeting DHT reduction and follicle support. Vegan, hormone-free; clinically shown to reduce shedding by 76% in 90 days.",
      ja: "KARMATIN（ヴィーガンb-SILKタンパク質）・緑豆・レッドクローバー配合の植物由来ヘアセラムでDHT軽減と毛包サポート。ヴィーガン・ホルモンフリー、90日で抜け毛76%減の臨床データあり。",
    },
    links: [{ network: "direct", productId: "https://vegamour.com/products/gro-hair-serum", markets: ["global"], approved: true }],
  },

  // ── best-cream-blush-2026 ────────────────────────────────────────────────
  {
    id: "nars-orgasm-blush-cream",
    imageUrl: "https://m.media-amazon.com/images/I/611dCm9JkAL._AC_SL1500_.jpg",
    priceMin: "36",
    priceMax: "40",
    category: "beauty",
    badge: "💄",
    name: { en: "NARS Orgasm Blush (Cream)", ja: "NARS オルガズム ブラッシュ（クリーム）" },
    description: {
      en: "NARS's iconic peachy-pink shade now in a sheer cream formula with gold shimmer. Buildable from a natural flush to a full glow; finger-applicable or brush-blended.",
      ja: "NAR​Sの象徴的なピーチピンクシェードをゴールドシマー入りシアークリーム処方に。自然なツヤからフルグローまでビルダブル、指またはブラシで仕上げ可。",
    },
    links: [{ network: "direct", productId: "https://www.narscosmetics.com/USA/orgasm-blush", markets: ["global"], approved: true }],
  },
  {
    id: "rare-beauty-soft-pinch-blush",
    imageUrl: "https://m.media-amazon.com/images/I/61lZ76JXgKL.jpg",
    priceMin: "22",
    priceMax: "24",
    category: "beauty",
    badge: "💄",
    name: { en: "Rare Beauty Soft Pinch Liquid Blush", ja: "レア ビューティ ソフト ピンチ リキッドブラッシュ" },
    description: {
      en: "Highly pigmented liquid blush in a dewy or matte finish that blends out sheerer than the concentrated formula suggests. A small dot goes a long way; 10 shades including bold reds and corals.",
      ja: "デューイまたはマット仕上げの高発色リキッドブラッシュ。濃い処方より薄く伸びるので少量で十分、大胆なレッドやコーラルを含む10色展開。",
    },
    links: [{ network: "direct", productId: "https://www.rarebeauty.com/products/soft-pinch-liquid-blush", markets: ["global"], approved: true }],
  },
  {
    id: "milk-makeup-lip-cheek",
    imageUrl: "https://m.media-amazon.com/images/I/61PJgEt1u9L._AC_.jpg",
    priceMin: "24",
    priceMax: "28",
    category: "beauty",
    badge: "💄",
    name: { en: "Milk Makeup Lip + Cheek Cream Blush Stick", ja: "ミルク メイクアップ リップ＋チーク クリームブラッシュスティック" },
    description: {
      en: "Dual-purpose cream blush stick that works on cheeks and lips simultaneously. Sheer, buildable pigment in a smooth, waxy formula; vegan, fragrance-free, travel-friendly stick format.",
      ja: "頬と唇の両方に使えるデュアルパーパス クリームブラッシュスティック。ヴィーガン・無香料の滑らかワックス処方でシアーなビルダブル発色、トラベルフレンドリー。",
    },
    links: [{ network: "direct", productId: "https://www.milkmakeup.com/products/lip-cheek", markets: ["global"], approved: true }],
  },
  {
    id: "benefit-benetint-cheek",
    imageUrl: "https://m.media-amazon.com/images/I/618BiTifskL.jpg",
    priceMin: "35",
    priceMax: "40",
    category: "beauty",
    badge: "💄",
    name: { en: "Benefit Cosmetics Benetint Cheek & Lip Stain", ja: "ベネフィット コスメティクス ベネティント チーク＆リップステイン" },
    description: {
      en: "Rose-tinted liquid cheek and lip stain in the original Benefit cult formula. Sheer, natural flush finish that mimics a genuine rosiness; waterproof and long-wearing.",
      ja: "ベネフィットの元祖カルトフォーミュラのローズティントリキッドチーク＆リップステイン。自然な赤みを真似たシアーな仕上がり、防水・長持ち。",
    },
    links: [{ network: "direct", productId: "https://www.benefitcosmetics.com/en-us/face-products/benetint", markets: ["global"], approved: true }],
  },
  {
    id: "e-l-f-monochromatic-cream-blush",
    imageUrl: "https://m.media-amazon.com/images/I/614rBA0ZLmL.jpg",
    priceMin: "8",
    priceMax: "10",
    category: "beauty",
    badge: "💄",
    name: { en: "e.l.f. Monochromatic Multi Stick Cream Blush", ja: "e.l.f. モノクロマティック マルチスティック クリームブラッシュ" },
    description: {
      en: "Multi-use cream stick for cheeks, lips, and eyes in coordinating shades. Buildable, blendable formula with a satin finish; vegan and cruelty-free at a drugstore price point.",
      ja: "頬・唇・目元にコーディネートカラーで使えるマルチユースクリームスティック。サテン仕上げのビルダブル処方、ヴィーガン・クルエルティフリーでドラッグストア価格。",
    },
    links: [{ network: "direct", productId: "https://www.elfcosmetics.com/monochromatic-multi-stick", markets: ["global"], approved: true }],
  },
] as unknown as AffiliateOffer[];
