// @ts-nocheck — travel batch 12 offers (2026-06-13). 50 offers across 10 travel articles.
import type { AffiliateOffer } from "./types";

export const CATALOG_BATCH12_TRAVEL: AffiliateOffer[] = [
  // ── best-travel-fanny-pack-2026 ──────────────────────────────────────────
  {
    id: "osprey-daylite-waist",
    imageUrl: "https://m.media-amazon.com/images/I/71HcDo-SRDL._AC_SL1500_.jpg",
    priceMin: 55,
    priceMax: 70,
    category: "travel",
    badge: "✈️",
    name: { en: "Osprey Daylite Waist Pack", ja: "オスプレー デイライト ウエストパック" },
    description: {
      en: "Lightweight 1L hip pack with LidLock attachment point for Osprey packs, fleece-lined sunglass pocket, and dedicated passport slot.",
      ja: "オスプレーパックへのLidLock接続対応、フリース素材のサングラスポケット、パスポート専用スロット付きの1L軽量ヒップパック。",
    },
    links: [{ network: "direct", productId: "https://www.osprey.com/us/en/product/daylite-waist-DAYLITEWST.html", markets: ["global"], approved: true }],
  },
  {
    id: "patagonia-atom-sling-8l",
    imageUrl: "https://m.media-amazon.com/images/I/61QFZpJ-+1L._AC_SX679_.jpg",
    priceMin: 79,
    priceMax: 89,
    category: "travel",
    badge: "✈️",
    name: { en: "Patagonia Atom Sling 8L", ja: "パタゴニア アトム スリング 8L" },
    description: {
      en: "8-liter sling bag made from recycled nylon with DWR finish, full-perimeter main zip for easy access, and Fair Trade Certified sewing.",
      ja: "DWR加工リサイクルナイロン製、フルペリメタージップとフェアトレード認定縫製の8Lスリングバッグ。",
    },
    links: [{ network: "direct", productId: "https://www.patagonia.com/product/atom-sling-bag-8-liters/48261.html", markets: ["global"], approved: true }],
  },
  {
    id: "lululemon-everywhere-belt-bag",
    imageUrl: "https://m.media-amazon.com/images/I/51B2Bq18AGL._AC_SL1500_.jpg",
    priceMin: 38,
    priceMax: 48,
    category: "travel",
    badge: "✈️",
    name: { en: "Lululemon Everywhere Belt Bag 1L", ja: "ルルレモン エブリウェア ベルトバッグ 1L" },
    description: {
      en: "1L water-resistant belt bag with front zip pocket, main compartment for phone and slim wallet, and adjustable crossbody strap.",
      ja: "前面ジップポケット・スマホと薄型財布が入るメインコンパートメント・調整可能なクロスボディストラップ付き1L撥水バッグ。",
    },
    links: [{ network: "direct", productId: "https://shop.lululemon.com/p/bags/Everywhere-Belt-Bag/_/prod10060447", markets: ["global"], approved: true }],
  },
  {
    id: "rei-co-op-trailgate-hip",
    imageUrl: "https://s3.amazonaws.com/images.gearjunkie.com/uploads/2023/07/IMG_3205.jpeg",
    priceMin: 45,
    priceMax: 55,
    category: "travel",
    badge: "✈️",
    name: { en: "REI Co-op Trailgate Hip Pack", ja: "REI Co-op トレイルゲート ヒップパック" },
    description: {
      en: "Trail-optimized hip pack with ventilated back panel, top-loading water bottle sleeve, and padded hipbelt for full-day wear.",
      ja: "通気バックパネル、上部ウォーターボトルスリーブ、終日装着向けパッド入りヒップベルト付きのトレイル特化ヒップパック。",
    },
    links: [{ network: "direct", productId: "https://www.rei.com/product/207469/rei-co-op-trailgate-hip-pack", markets: ["global"], approved: true }],
  },
  {
    id: "running-room-flipbelt-classic",
    imageUrl: "https://m.media-amazon.com/images/I/61LlFwC6CtL._AC_UL1500_.jpg",
    priceMin: 25,
    priceMax: 35,
    category: "travel",
    badge: "✈️",
    name: { en: "FlipBelt Classic", ja: "フリップベルト クラシック" },
    description: {
      en: "Tubular stretch belt with zipperless open-top pockets around the circumference, machine washable, nearly invisible under clothing.",
      ja: "ジッパーレスのオープントップポケットが周囲に配置された伸縮チューブベルト。洗濯機対応、衣服の下でほぼ見えない。",
    },
    links: [{ network: "direct", productId: "https://flipbelt.com/products/flipbelt-classic", markets: ["global"], approved: true }],
  },

  // ── best-travel-garment-bag-2026 ─────────────────────────────────────────
  {
    id: "briggs-riley-baseline-garment",
    imageUrl: "https://m.media-amazon.com/images/I/91QdrHPgcVL._AC_SL1500_.jpg",
    priceMin: 299,
    priceMax: 349,
    category: "travel",
    badge: "✈️",
    name: { en: "Briggs & Riley Baseline Garment Bag", ja: "ブリッグス＆ライリー ベースライン ガーメントバッグ" },
    description: {
      en: "1680-denier ballistic nylon garment bag with CX compression expansion, organized dress shirt panel, and lifetime unconditional warranty.",
      ja: "1680Dバリスティックナイロン、CXコンプレッションエクスパンション、ドレスシャツパネル付き。生涯無条件保証。",
    },
    links: [{ network: "direct", productId: "https://www.briggs-riley.com/products/baseline-garment-bag", markets: ["global"], approved: true }],
  },
  {
    id: "travelpro-maxlite-5-garment",
    imageUrl: "https://m.media-amazon.com/images/I/A1eSTu0H7SL._AC_SX679_.jpg",
    priceMin: 99,
    priceMax: 139,
    category: "travel",
    badge: "✈️",
    name: { en: "Travelpro Maxlite 5 Garment Bag", ja: "トラベルプロ マックスライト5 ガーメントバッグ" },
    description: {
      en: "Lightweight polyester garment bag at 1.45 kg with luggage pass-through sleeve, hook, and zippered accessory pouch.",
      ja: "1.45kgの軽量ポリエステルガーメントバッグ。スーツケース用パススルースリーブ・フック・アクセサリーポーチ付き。",
    },
    links: [{ network: "direct", productId: "https://www.travelpro.com/products/maxlite-5-carry-on-garment-bag", markets: ["global"], approved: true }],
  },
  {
    id: "samsonite-classic-business-garment",
    imageUrl: "https://m.media-amazon.com/images/I/91W+k1e1BaL._AC_SL1500_.jpg",
    priceMin: 149,
    priceMax: 189,
    category: "travel",
    badge: "✈️",
    name: { en: "Samsonite Classic Business Garment Bag", ja: "サムソナイト クラシック ビジネス ガーメントバッグ" },
    description: {
      en: "Two-section garment bag with individual hooks, wipeable nylon shoe compartment lining, and extensive accessory panel organization.",
      ja: "独立フック付き2セクション、拭き取り可能なシューズコンパートメント、充実したアクセサリーパネル収納のガーメントバッグ。",
    },
    links: [{ network: "direct", productId: "https://www.samsonite.com/classic-business-2-gusseted-garment-bag/", markets: ["global"], approved: true }],
  },
  {
    id: "garment-packing-cube-packsmith",
    imageUrl: "https://m.media-amazon.com/images/I/91JbGNj0XPL._AC_.jpg",
    priceMin: 79,
    priceMax: 99,
    category: "travel",
    badge: "✈️",
    name: { en: "Packsmith Garment Packing Cube System", ja: "パックスミス ガーメント パッキングキューブシステム" },
    description: {
      en: "Modular garment bag that converts to packing cubes when not carrying a suit, lightweight travel nylon with YKK zippers.",
      ja: "スーツ不使用時にパッキングキューブに変換できるモジュラーガーメントバッグ。軽量トラベルナイロン、YKKジッパー使用。",
    },
    links: [{ network: "direct", productId: "https://packsmith.com/products/garment-packing-cube", markets: ["global"], approved: true }],
  },
  {
    id: "pb-travel-tri-fold-garment",
    imageUrl: "https://m.media-amazon.com/images/I/81Uf4mlCw9L._AC_SL1500_.jpg",
    priceMin: 49,
    priceMax: 69,
    category: "travel",
    badge: "✈️",
    name: { en: "Pottery Barn Travel Tri-Fold Garment Bag", ja: "ポタリーバーン トラベル トリフォールド ガーメントバッグ" },
    description: {
      en: "Tri-fold garment bag packing to approximately 38 cm height for regional jet overhead bin compatibility, under 1 kg.",
      ja: "三つ折りで約38cmに収まりリージョナルジェットの頭上収納にも対応、1kg以下の軽量ガーメントバッグ。",
    },
    links: [{ network: "direct", productId: "https://www.potterybarn.com/products/tri-fold-garment-bag/", markets: ["global"], approved: true }],
  },

  // ── best-hiking-daypack-2026 ──────────────────────────────────────────────
  {
    id: "osprey-talon-22",
    imageUrl: "https://m.media-amazon.com/images/I/61Y9hYVdJvL._AC_SL1001_.jpg",
    priceMin: 130,
    priceMax: 160,
    category: "travel",
    badge: "✈️",
    name: { en: "Osprey Talon 22", ja: "オスプレー タロン 22" },
    description: {
      en: "22L hiking daypack with AirSpeed ventilated mesh suspension, integrated rain cover, and FlapJacket top cover. Weighs 0.62 kg.",
      ja: "AirSpeed通気メッシュサスペンション・統合レインカバー・FlapJacket天蓋付きの22Lデイパック。重量0.62kg。",
    },
    links: [{ network: "direct", productId: "https://www.osprey.com/us/en/product/talon-22-pack-TALON22S24.html", markets: ["global"], approved: true }],
  },
  {
    id: "gregory-zulu-30",
    imageUrl: "https://m.media-amazon.com/images/I/81wPK+IWFfL._AC_SL1500_.jpg",
    priceMin: 160,
    priceMax: 200,
    category: "travel",
    badge: "✈️",
    name: { en: "Gregory Zulu 30", ja: "グレゴリー ズール 30" },
    description: {
      en: "30L hiking daypack with FreeFloat dynamic suspension, Auto Fit harness, and class-leading hipbelt pockets. Weighs 0.95 kg.",
      ja: "FreeFloat動的サスペンション・Auto Fitハーネス・クラス最大のヒップベルトポケット付き30Lデイパック。重量0.95kg。",
    },
    links: [{ network: "direct", productId: "https://www.gregorypacks.com/packs-bags/day-packs/zulu-30-pack/111480.html", markets: ["global"], approved: true }],
  },
  {
    id: "deuter-speed-lite-24",
    imageUrl: "https://m.media-amazon.com/images/I/71TGOYqDoUL._AC_SL1500_.jpg",
    priceMin: 110,
    priceMax: 140,
    category: "travel",
    badge: "✈️",
    name: { en: "Deuter Speed Lite 24", ja: "ドイター スピードライト 24" },
    description: {
      en: "24L ultralight daypack with Aircomfort FlexLite back system and front bungee for wet layers. Weighs 0.65 kg.",
      ja: "Aircomfort FlexLiteバックシステムとウェットレイヤー用フロントバンジー付き24L超軽量デイパック。重量0.65kg。",
    },
    links: [{ network: "direct", productId: "https://www.deuter.com/us-en/bags/hiking/420421-speed-lite-24.html", markets: ["global"], approved: true }],
  },
  {
    id: "rei-co-op-flash-22",
    imageUrl: "https://bikehikesafari.com/wp-content/uploads/2023/02/REI-Co-op-Flash-22.jpg",
    priceMin: 79,
    priceMax: 99,
    category: "travel",
    badge: "✈️",
    name: { en: "REI Co-op Flash 22 Pack", ja: "REI Co-op フラッシュ 22 パック" },
    description: {
      en: "22L budget hiking daypack with 3L hydration sleeve, compression straps, and deep water bottle pockets. Value entry point.",
      ja: "3Lハイドレーションスリーブ・コンプレッションストラップ・深いウォーターボトルポケット付き22Lデイパック。コスパ重視。",
    },
    links: [{ network: "direct", productId: "https://www.rei.com/product/177577/rei-co-op-flash-22-pack", markets: ["global"], approved: true }],
  },
  {
    id: "black-diamond-pursuit-30",
    imageUrl: "https://m.media-amazon.com/images/I/81OYQp4YM8L._AC_SL1500_.jpg",
    priceMin: 149,
    priceMax: 179,
    category: "travel",
    badge: "✈️",
    name: { en: "Black Diamond Pursuit 30 Backpack", ja: "ブラックダイヤモンド パースート 30 バックパック" },
    description: {
      en: "30L technical terrain daypack with BioLink suspension for close-to-body load control on scrambling routes, ice axe loop included.",
      ja: "スクランブルルート向けBioLinkサスペンション・アイスアックスループ付き30L技術的地形向けデイパック。",
    },
    links: [{ network: "direct", productId: "https://www.blackdiamondequipment.com/en_US/product/pursuit-30-backpack/", markets: ["global"], approved: true }],
  },

  // ── best-travel-sleep-mask-2026 ───────────────────────────────────────────
  {
    id: "manta-sleep-mask-pro",
    imageUrl: "https://m.media-amazon.com/images/I/914LjwsgplL._AC_SL1500_.jpg",
    priceMin: 79,
    priceMax: 89,
    category: "travel",
    badge: "✈️",
    name: { en: "Manta Sleep Mask PRO", ja: "マンタ スリープマスク プロ" },
    description: {
      en: "Contoured sleep mask with individually adjustable eye cups for zero eye pressure, removable nose foam bridge for 100% blackout.",
      ja: "個別調整可能なアイカップで眼球圧力ゼロ、着脱可能なノーズフォームブリッジで完全遮光を実現する立体アイマスク。",
    },
    links: [{ network: "direct", productId: "https://mantasleep.com/products/manta-sleep-mask-pro", markets: ["global"], approved: true }],
  },
  {
    id: "alaska-bear-silk-sleep-mask",
    imageUrl: "https://m.media-amazon.com/images/S/aplus-seller-content-images-us-east-1/ATVPDKIKX0DER/A6CQF6TQU15UK/10bb65c5-7e51-4832-bab1-c78388bdf7d4._CR0,0,970,600_PT0_SX970__.jpg",
    priceMin: 12,
    priceMax: 18,
    category: "travel",
    badge: "✈️",
    name: { en: "Alaska Bear Natural Silk Sleep Mask", ja: "アラスカベア ナチュラルシルク スリープマスク" },
    description: {
      en: "19-momme mulberry silk flat sleep mask with adjustable strap, lightweight and temperature regulating. Best flat-foam experience.",
      ja: "19匁桑シルク製フラットアイマスク。調整可能ストラップ付き、軽量で体温調節素材。フラット系最高の肌触り。",
    },
    links: [{ network: "direct", productId: "https://www.amazon.com/s?k=Alaska+Bear+Natural+Silk+Sleep+Mask", markets: ["global"], approved: true }],
  },
  {
    id: "tempur-pedic-sleep-mask",
    imageUrl: "https://m.media-amazon.com/images/I/517-mCaKRyL._AC_SX425_.jpg",
    priceMin: 25,
    priceMax: 35,
    category: "travel",
    badge: "✈️",
    name: { en: "Tempur-Pedic Sleep Mask", ja: "テンピュール スリープマスク" },
    description: {
      en: "Flat sleep mask using Tempur pressure-relief material that conforms to facial contours, reducing pressure points vs. standard foam.",
      ja: "顔の輪郭に合わせてフィットするTempur素材採用フラットアイマスク。標準フォームより圧力ポイントを軽減。",
    },
    links: [{ network: "direct", productId: "https://www.tempurpedic.com/shop-sleep-masks/", markets: ["global"], approved: true }],
  },
  {
    id: "bucky-40-blinks-mask",
    imageUrl: "https://m.media-amazon.com/images/I/71tMiyyMtqL._AC_SL1500_.jpg",
    priceMin: 9,
    priceMax: 14,
    category: "travel",
    badge: "✈️",
    name: { en: "Bucky 40 Blinks Sleep Mask", ja: "バッキー 40ブリンクス スリープマスク" },
    description: {
      en: "Molded rigid-shell contoured sleep mask with deep nose cutout for near-total blackout and zero eye contact. Adjustable strap.",
      ja: "深いノーズカットアウトで準完全遮光、眼球に接触しない成形硬質シェル立体アイマスク。調整可能ストラップ付き。",
    },
    links: [{ network: "direct", productId: "https://www.bucky.com/products/40-blinks-sleep-mask", markets: ["global"], approved: true }],
  },
  {
    id: "drift-to-sleep-contour-mask",
    imageUrl: "https://m.media-amazon.com/images/I/71XeNnWKV0L._AC_.jpg",
    priceMin: 8,
    priceMax: 13,
    category: "travel",
    badge: "✈️",
    name: { en: "Drift to Sleep Contour Sleep Mask", ja: "ドリフト・トゥ・スリープ コンターマスク" },
    description: {
      en: "Soft fabric contoured sleep mask with included nose bridge foam insert for improved light blocking. Ultralight and packable.",
      ja: "ノーズブリッジフォームインサート同梱の柔らかい布立体アイマスク。超軽量で収納性高い。",
    },
    links: [{ network: "direct", productId: "https://www.amazon.com/s?k=Drift+to+Sleep+Contour+Sleep+Mask", markets: ["global"], approved: true }],
  },

  // ── best-travel-hair-dryer-2026 ───────────────────────────────────────────
  {
    id: "conair-1600w-dual-voltage",
    imageUrl: "https://m.media-amazon.com/images/I/61VhgNJTNxL._AC_SL1500_.jpg",
    priceMin: 18,
    priceMax: 28,
    category: "travel",
    badge: "✈️",
    name: { en: "Conair 1600W Dual Voltage Travel Dryer", ja: "コンエア 1600W デュアルボルテージ トラベルドライヤー" },
    description: {
      en: "1600W dual-voltage (110/220V) travel hair dryer with fold-down handle, clearly placed voltage switch, and ceramic filter coating.",
      ja: "折りたたみハンドル・見やすい電圧スイッチ・セラミックフィルターコーティング付きの1600W デュアルボルテージトラベルドライヤー。",
    },
    links: [{ network: "direct", productId: "https://www.conair.com/en_US/products/hair-care/hair-dryers/travel-hair-dryers/", markets: ["global"], approved: true }],
  },
  {
    id: "dyson-supersonic-travel",
    imageUrl: "https://m.media-amazon.com/images/I/61iexiRP24L._SL1500_.jpg",
    priceMin: 429,
    priceMax: 499,
    category: "travel",
    badge: "✈️",
    name: { en: "Dyson Supersonic Hair Dryer Travel Edition", ja: "ダイソン スーパーソニック トラベルエディション" },
    description: {
      en: "Dual-voltage Dyson Supersonic with digital V9 motor (110,000 rpm), intelligent heat control measuring temperature 40x/second, and magnetic attachments.",
      ja: "デジタルモーターV9（11万rpm）・毎秒40回の温度計測・マグネットアタッチメント採用のデュアルボルテージダイソン スーパーソニック。",
    },
    links: [{ network: "direct", productId: "https://www.dyson.com/hair-care/hair-dryers/supersonic", markets: ["global"], approved: true }],
  },
  {
    id: "remington-d3190-damage-protection",
    imageUrl: "https://m.media-amazon.com/images/I/71ZyHPCc7wS._AC_SX679_.jpg",
    priceMin: 45,
    priceMax: 65,
    category: "travel",
    badge: "✈️",
    name: { en: "Remington D3190 Damage Protection Travel Dryer", ja: "レミントン D3190 ダメージプロテクション トラベルドライヤー" },
    description: {
      en: "Dual-voltage travel dryer with ionic and ceramic technology plus Micro Conditioner coating that releases conditioning agents into airflow.",
      ja: "イオン・セラミック技術とMicro Conditionerコーティング（気流にコンディショニング成分を放出）採用デュアルボルテージトラベルドライヤー。",
    },
    links: [{ network: "direct", productId: "https://www.remington.com/products/hair-care/hair-dryers/", markets: ["global"], approved: true }],
  },
  {
    id: "babyliss-pro-nano-titanium-travel",
    imageUrl: "https://m.media-amazon.com/images/I/718T8B7PmLL._SL1500_.jpg",
    priceMin: 89,
    priceMax: 119,
    category: "travel",
    badge: "✈️",
    name: { en: "BaByliss Pro Nano Titanium Travel Dryer", ja: "バビリス プロ ナノチタニウム トラベルドライヤー" },
    description: {
      en: "Professional dual-voltage travel dryer with titanium heating element for consistent heat across back-to-back styling sessions.",
      ja: "連続スタイリングでも安定したプロ熱を実現するチタン加熱素子採用のデュアルボルテージプロ仕様トラベルドライヤー。",
    },
    links: [{ network: "direct", productId: "https://www.babylisspro.com/shop/hair-dryers/", markets: ["global"], approved: true }],
  },
  {
    id: "revlon-one-step-travel",
    imageUrl: "https://m.media-amazon.com/images/I/71mVFOZHVfL._AC_SL1500_.jpg",
    priceMin: 25,
    priceMax: 40,
    category: "travel",
    badge: "✈️",
    name: { en: "Revlon One-Step Volumizer Travel", ja: "レブロン ワンステップ ボリューマイザー トラベル" },
    description: {
      en: "Compact dual-voltage blow-dry brush that dries and volumizes simultaneously, cutting total styling time to under 5 minutes.",
      ja: "乾燥とボリューミングを同時にこなし総スタイリング時間を5分以下に短縮するコンパクトデュアルボルテージブローブラシ。",
    },
    links: [{ network: "direct", productId: "https://www.revlon.com/all-products/hair-tools/blow-dry-brushes/", markets: ["global"], approved: true }],
  },

  // ── best-rolling-duffel-bag-2026 ─────────────────────────────────────────
  {
    id: "eagle-creek-cargo-hauler-wheel-duffel-130l",
    imageUrl: "https://media.s-bol.com/Rgz9Px7QBrYK/1200x876.jpg",
    priceMin: 299,
    priceMax: 349,
    category: "travel",
    badge: "✈️",
    name: { en: "Eagle Creek Cargo Hauler Wheel Duffel 130L", ja: "イーグルクリーク カーゴホーラー ウィールダッフル 130L" },
    description: {
      en: "130L rolling duffel with 900D HTPE puncture-resistant fabric, metal-axle in-line wheels, and No-Leash lifetime warranty.",
      ja: "900D HTPE耐貫通素材・金属アクスルインラインホイール・No-Leash生涯保証付き130Lローリングダッフル。",
    },
    links: [{ network: "direct", productId: "https://www.eaglecreek.com/products/cargo-hauler-wheeled-duffel-bag-130l", markets: ["global"], approved: true }],
  },
  {
    id: "north-face-rolling-thunder-30",
    imageUrl: "https://m.media-amazon.com/images/I/61pQTMKZQQL._AC_UX385_.jpg",
    priceMin: 149,
    priceMax: 179,
    category: "travel",
    badge: "✈️",
    name: { en: "The North Face Rolling Thunder 30 Duffel", ja: "ザ・ノース・フェイス ローリングサンダー 30 ダッフル" },
    description: {
      en: "30L carry-on size rolling duffel with U-shape main compartment opening and dedicated shoe compartment at base.",
      ja: "U字開口メインコンパートメントと底部専用シューズコンパートメント付きの機内持ち込み対応30Lローリングダッフル。",
    },
    links: [{ network: "direct", productId: "https://www.thenorthface.com/en-us/bags-and-gear/luggage/rolling-thunder-30-duffel-NF0A3C91", markets: ["global"], approved: true }],
  },
  {
    id: "patagonia-black-hole-wheeled-duffel-100l",
    imageUrl: "https://wornwear.patagonia.com/cdn/shop/files/qwbx4ucjcwfh9xac4orm.jpg?v=1724164434",
    priceMin: 299,
    priceMax: 349,
    category: "travel",
    badge: "✈️",
    name: { en: "Patagonia Black Hole Wheeled Duffel 100L", ja: "パタゴニア ブラックホール ウィールド ダッフル 100L" },
    description: {
      en: "100L wheeled duffel with TPU-laminated recycled ripstop nylon for rain resistance and tucking backpack straps in a rear panel pocket.",
      ja: "雨に強いTPUラミネートリサイクルリップストップナイロン製、リアパネルポケット収納バックパックストラップ付き100Lウィールドダッフル。",
    },
    links: [{ network: "direct", productId: "https://www.patagonia.com/product/black-hole-wheeled-duffel-bag-100-liters/49348.html", markets: ["global"], approved: true }],
  },
  {
    id: "samsonite-wheeled-duffel-28",
    imageUrl: "https://m.media-amazon.com/images/I/81GMWncDL7L._AC_SX679_.jpg",
    priceMin: 119,
    priceMax: 149,
    category: "travel",
    badge: "✈️",
    name: { en: "Samsonite Wheeled Duffel 28\"", ja: "サムソナイト ウィールドダッフル 28インチ" },
    description: {
      en: "Suitcase-style rolling duffel with spinner wheels, zippered interior divider, laundry pouch, and side mesh pockets.",
      ja: "スーツケースライクな整理、スピナーホイール、ジッパー仕切り、ランドリーポーチ付きローリングダッフル。",
    },
    links: [{ network: "direct", productId: "https://www.samsonite.com/wheeled-duffel-bags/", markets: ["global"], approved: true }],
  },
  {
    id: "travelpro-crew-versapack-rolling-duffel",
    imageUrl: "https://m.media-amazon.com/images/I/71Fs3-aBB-L._AC_SX569_.jpg",
    priceMin: 129,
    priceMax: 169,
    category: "travel",
    badge: "✈️",
    name: { en: "Travelpro Crew VersaPack Rolling Duffel", ja: "トラベルプロ クルー バーサパック ローリングダッフル" },
    description: {
      en: "Crew-grade rolling duffel with Duraguard coated fabric, near wobble-free telescoping handle, and airline professional build quality.",
      ja: "Duraguardコーティング素材・ぐらつきのないテレスコープハンドルを持つ航空会社クルー品質ローリングダッフル。",
    },
    links: [{ network: "direct", productId: "https://www.travelpro.com/products/crew-versapack-rolling-duffel", markets: ["global"], approved: true }],
  },

  // ── best-weekender-bag-2026 ───────────────────────────────────────────────
  {
    id: "away-the-weekender-bag",
    imageUrl: "https://s.yimg.com/ny/api/res/1.2/zXD6AR_.pB26kH1l3IhPEA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyNDI7aD0xMDM1/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2019-06/36144340-9903-11e9-be7c-bc487beb65a3",
    priceMin: 195,
    priceMax: 225,
    category: "travel",
    badge: "✈️",
    name: { en: "Away The Weekender Bag", ja: "アウェイ ザ・ウィークエンダーバッグ" },
    description: {
      en: "Weekender bag with Outsider aluminum frame to maintain shape, removable snap-in laundry bag, and isolated shoe compartment.",
      ja: "形状を保つOutsiderアルミニウムフレーム・スナップ式着脱ランドリーバッグ・隔離シューズコンパートメント付きウィークエンダー。",
    },
    links: [{ network: "direct", productId: "https://www.awaytravel.com/travel-bags/the-weekender", markets: ["global"], approved: true }],
  },
  {
    id: "herschel-novel-duffel-42l",
    imageUrl: "https://m.media-amazon.com/images/I/61WJY450cWL._AC_SY879_.jpg",
    priceMin: 69,
    priceMax: 89,
    category: "travel",
    badge: "✈️",
    name: { en: "Herschel Novel Duffel Bag 42L", ja: "ハーシェル ノーベル ダッフルバッグ 42L" },
    description: {
      en: "42L recycled polyester duffel with signature stripe lining, adjustable padded shoulder strap, and distinctive heritage-brand aesthetic.",
      ja: "シグネチャーストライプ内装・調整可能パッドショルダーストラップ付きの42Lリサイクルポリエステルダッフル。",
    },
    links: [{ network: "direct", productId: "https://herschel.com/shop/duffel-bags/novel-duffel-bag", markets: ["global"], approved: true }],
  },
  {
    id: "filson-duffle-medium",
    imageUrl: "https://m.media-amazon.com/images/I/61U-p+m1kVL._AC_SL1500_.jpg",
    priceMin: 395,
    priceMax: 445,
    category: "travel",
    badge: "✈️",
    name: { en: "Filson Medium Duffle Bag", ja: "フィルソン ミディアム ダッフルバッグ" },
    description: {
      en: "Tin Cloth waxed canvas duffle bag with bridle leather handles that improves with age. Lifetime workmanship guarantee from Filson.",
      ja: "年月とともに貫禄が増すTin Clothワックスドキャンバスとブライドルレザーハンドル。フィルソンの生涯縫製保証付き。",
    },
    links: [{ network: "direct", productId: "https://www.filson.com/products/duffle-bag-medium.html", markets: ["global"], approved: true }],
  },
  {
    id: "tumi-alpha-bravo-weekender",
    imageUrl: "https://m.media-amazon.com/images/I/71PBAlZhB3L._AC_SL1500_.jpg",
    priceMin: 395,
    priceMax: 445,
    category: "travel",
    badge: "✈️",
    name: { en: "Tumi Alpha Bravo Weekender", ja: "トゥミ アルファブラボー ウィークエンダー" },
    description: {
      en: "1680D ballistic nylon weekender bag with exterior 15-inch laptop sleeve, front Alpha Bravo organization panel, and Add-A-Bag sleeve.",
      ja: "外付け15インチラップトップスリーブ・フロントAlpha Bravoパネル・Add-A-Bagスリーブ付き1680Dバリスティックナイロンウィークエンダー。",
    },
    links: [{ network: "direct", productId: "https://www.tumi.com/c/alpha-bravo-bags", markets: ["global"], approved: true }],
  },
  {
    id: "everlane-weekend-bag",
    imageUrl: "https://s.yimg.com/ny/api/res/1.2/ezXG_X5Yl5dHccsrjlNnnA--/YXBwaWQ9aGlnaGxhbmRlcjt3PTk2MA--/https://media.zenfs.com/en/travel.travelleisure.com/9e55e91b1a872bc9eec3739ec23f26d5",
    priceMin: 75,
    priceMax: 95,
    category: "travel",
    badge: "✈️",
    name: { en: "Everlane The Weekend Bag", ja: "エバーレーン ザ・ウィークエンドバッグ" },
    description: {
      en: "Minimalist recycled nylon weekend bag with clean construction, padded shoulder strap, and deliberately understated design.",
      ja: "丁寧な縫製・パッドショルダーストラップ・意図的にシンプルなデザインのリサイクルナイロン製ミニマリストウィークエンドバッグ。",
    },
    links: [{ network: "direct", productId: "https://www.everlane.com/products/weekender-bag", markets: ["global"], approved: true }],
  },

  // ── best-travel-jewelry-case-2026 ─────────────────────────────────────────
  {
    id: "wolf-cub-single-watch-roll",
    imageUrl: "https://cdn.shopify.com/s/files/1/0721/9897/9877/files/461106_1_dc3d7106-c10c-47f0-88df-6d8053910da5_1200x.jpg?v=1697556794",
    priceMin: 89,
    priceMax: 119,
    category: "travel",
    badge: "✈️",
    name: { en: "Wolf Cub Single Watch Roll", ja: "ウルフ カブ シングルウォッチロール" },
    description: {
      en: "Single-watch travel roll with cream leather interior cylinder, soft calf leather exterior, and secure snap closure.",
      ja: "クリームレザーインテリアシリンダー・ソフトカーフレザー外装・スナップ留めの1本収納時計ロール。",
    },
    links: [{ network: "direct", productId: "https://wolfdesigns.com/products/cub-single-watch-roll", markets: ["global"], approved: true }],
  },
  {
    id: "stackers-travel-jewelry-case",
    imageUrl: "https://m.media-amazon.com/images/I/81Is0DRw-SL._AC_SL1500_.jpg",
    priceMin: 55,
    priceMax: 75,
    category: "travel",
    badge: "✈️",
    name: { en: "Stackers Travel Jewelry Case", ja: "スタッカーズ トラベルジュエリーケース" },
    description: {
      en: "Full-organization jewelry case with individual necklace snap hooks, foam-lined earring panel with post holes, ring slots, and velvet lining.",
      ja: "個別スナップフックのネックレス収納・ポスト穴付きフォームピアスパネル・指輪スロット・ベルベットライニング付きジュエリーケース。",
    },
    links: [{ network: "direct", productId: "https://stackers.com/collections/travel-jewelry-cases", markets: ["global"], approved: true }],
  },
  {
    id: "mele-co-giana-travel-jewelry-roll",
    imageUrl: "https://m.media-amazon.com/images/I/815hg1iDUBL._AC_SL1500_.jpg",
    priceMin: 22,
    priceMax: 32,
    category: "travel",
    badge: "✈️",
    name: { en: "Mele & Co. Giana Travel Jewelry Roll", ja: "メレ＆コー ジアナ トラベルジュエリーロール" },
    description: {
      en: "Three-level jewelry roll with zipper pouch, ring roll, and necklace snap-cover bar. Printed fabric exterior passes as a cosmetics bag.",
      ja: "ジッパーポーチ・指輪ロール・ネックレスバー付き3レベルジュエリーロール。化粧品バッグに見えるプリント布外装。",
    },
    links: [{ network: "direct", productId: "https://www.mele.com/collections/travel-jewelry-organizers", markets: ["global"], approved: true }],
  },
  {
    id: "bagsmart-jewelry-organizer",
    imageUrl: "https://m.media-amazon.com/images/I/71uIL82PiZL._AC_SL1500_.jpg",
    priceMin: 18,
    priceMax: 28,
    category: "travel",
    badge: "✈️",
    name: { en: "BAGSMART Travel Jewelry Organizer", ja: "バッグスマート トラベルジュエリーオーガナイザー" },
    description: {
      en: "High-compartment-count jewelry organizer with multiple foam earring panels, ring rolls, and individual necklace ties. Best value-per-slot.",
      ja: "複数フォームピアスパネル・指輪ロール・個別ネックレスタイ付き高コンパートメント数ジュエリーオーガナイザー。",
    },
    links: [{ network: "direct", productId: "https://www.bagsmart.com/collections/jewelry-organizer", markets: ["global"], approved: true }],
  },
  {
    id: "draka-travel-jewelry-pouch",
    imageUrl: "https://m.media-amazon.com/images/I/71mFqUk5M6L._AC_SL1500_.jpg",
    priceMin: 9,
    priceMax: 15,
    category: "travel",
    badge: "✈️",
    name: { en: "Draka Travel Jewelry Pouch", ja: "ドラカ トラベルジュエリーポーチ" },
    description: {
      en: "Minimalist fabric jewelry pouch that packs nearly flat, suitable for light jewelry travelers carrying 1-3 pieces.",
      ja: "ほぼフラットに収納できるミニマリスト布ジュエリーポーチ。1〜3点程度の軽いジュエリー旅行者に適切。",
    },
    links: [{ network: "direct", productId: "https://www.amazon.com/s?k=draka+travel+jewelry+pouch", markets: ["global"], approved: true }],
  },

  // ── best-underwater-camera-2026 ───────────────────────────────────────────
  {
    id: "olympus-tough-tg-7",
    imageUrl: "https://m.media-amazon.com/images/I/71mwBVnGBsL._AC_SL1500_.jpg",
    priceMin: 379,
    priceMax: 429,
    category: "travel",
    badge: "✈️",
    name: { en: "Olympus Tough TG-7 Waterproof Camera", ja: "オリンパス タフ TG-7 防水カメラ" },
    description: {
      en: "15-meter waterproof compact camera with f/2.0 lens (fastest in category), Microscope mode, and dedicated underwater scene modes.",
      ja: "f/2.0レンズ（カテゴリー最速）・マイクロスコープモード・専用水中シーンモード付きの15m防水コンパクトカメラ。",
    },
    links: [{ network: "direct", productId: "https://www.olympus.com/en/cameras/compact-cameras/tough-cameras/tg-7/", markets: ["global"], approved: true }],
  },
  {
    id: "gopro-hero13-black",
    imageUrl: "https://m.media-amazon.com/images/I/615eTO83jLL.jpg",
    priceMin: 349,
    priceMax: 399,
    category: "travel",
    badge: "✈️",
    name: { en: "GoPro HERO13 Black", ja: "GoPro HERO13 ブラック" },
    description: {
      en: "30-meter waterproof action camera with HyperSmooth 6.0 stabilization, 5.3K video, and Max Lens Mod 2.0 compatibility.",
      ja: "HyperSmooth 6.0手ぶれ補正・5.3K動画・Max Lens Mod 2.0対応の30m防水アクションカメラ。",
    },
    links: [{ network: "direct", productId: "https://gopro.com/en/us/cameras/hero13black/CHDHX-131-master.html", markets: ["global"], approved: true }],
  },
  {
    id: "nikon-coolpix-w300",
    imageUrl: "https://m.media-amazon.com/images/I/71uJOg99oIL._AC_SL1500_.jpg",
    priceMin: 299,
    priceMax: 349,
    category: "travel",
    badge: "✈️",
    name: { en: "Nikon Coolpix W300 Waterproof Camera", ja: "ニコン クールピクス W300 防水カメラ" },
    description: {
      en: "30-meter waterproof compact with 16MP sensor, f/2.8 aperture, dedicated underwater blue/green water color correction modes.",
      ja: "16MPセンサー・f/2.8・専用青・緑水色補正モード付きの30m防水コンパクトカメラ。",
    },
    links: [{ network: "direct", productId: "https://www.nikon.com/en/products/compact-digital-cameras/coolpix-w300/", markets: ["global"], approved: true }],
  },
  {
    id: "akaso-brave-7-le",
    imageUrl: "https://m.media-amazon.com/images/I/71JnAbIOeeL._AC_SL1500_.jpg",
    priceMin: 129,
    priceMax: 159,
    category: "travel",
    badge: "✈️",
    name: { en: "AKASO Brave 7 LE Action Camera", ja: "アカソ ブレイブ 7 LE アクションカメラ" },
    description: {
      en: "4K/30fps action camera with included waterproof housing to 40 meters (131ft), EIS stabilization, and half the price of GoPro.",
      ja: "付属防水ハウジングで40m対応・EIS手ぶれ補正・GoProの半額の4K/30fpsアクションカメラ。",
    },
    links: [{ network: "direct", productId: "https://www.akasotech.com/brave-7-le-action-camera", markets: ["global"], approved: true }],
  },
  {
    id: "fujifilm-instax-mini-evo-waterproof-case",
    imageUrl: "https://m.media-amazon.com/images/I/71oY29wCzJL._AC_SL1500_.jpg",
    priceMin: 149,
    priceMax: 179,
    category: "travel",
    badge: "✈️",
    name: { en: "Fujifilm Instax Mini Evo + Waterproof Case", ja: "富士フイルム インスタックス ミニ EVO + 防水ケース" },
    description: {
      en: "Instax Mini Evo instant print camera paired with dedicated waterproof case rated to 10 meters, for unique travel memory-making.",
      ja: "10m防水ケース対応のインスタックスミニEVOインスタントプリントカメラ。水辺での特別な旅の思い出作りに。",
    },
    links: [{ network: "direct", productId: "https://instax.com/mini_evo/en/", markets: ["global"], approved: true }],
  },

  // ── best-travel-clothesline-2026 ─────────────────────────────────────────
  {
    id: "sea-to-summit-clothesline",
    imageUrl: "https://m.media-amazon.com/images/I/71Rcz5zKgzL._AC_SL1500_.jpg",
    priceMin: 18,
    priceMax: 25,
    category: "travel",
    badge: "✈️",
    name: { en: "Sea to Summit Clothesline", ja: "シートゥサミット クロースライン" },
    description: {
      en: "3.8-meter double-bungee clothesline that holds items without clips via elastic tension, stainless hooks, packs to ChapStick size.",
      ja: "伸縮張力でクリップなしにアイテムを保持するステンレスフック付き3.8mダブルバンジー物干しロープ。リップバームサイズに収納。",
    },
    links: [{ network: "direct", productId: "https://www.seatosummit.com/products/camping-accessories/clothesline-acolthln/", markets: ["global"], approved: true }],
  },
  {
    id: "lewis-n-clark-portable-travel-clothesline",
    imageUrl: "https://m.media-amazon.com/images/S/aplus-media/vc/f19e6703-e2cf-4fa2-ac87-ea95793b681b.__CR0,0,970,600_PT0_SX970_V1___.jpg",
    priceMin: 8,
    priceMax: 14,
    category: "travel",
    badge: "✈️",
    name: { en: "Lewis N Clark Portable Travel Clothesline", ja: "ルイスNクラーク ポータブル トラベル クロースライン" },
    description: {
      en: "3-meter travel clothesline with large beginner-friendly plastic hooks, includes separate clothespins for heavier items.",
      ja: "初心者でも操作しやすい大型プラスチックフック・重いアイテム用洗濯バサミ同梱の3mトラベルクロースライン。",
    },
    links: [{ network: "direct", productId: "https://www.amazon.com/s?k=Lewis+N+Clark+Travel+Clothesline", markets: ["global"], approved: true }],
  },
  {
    id: "cocoon-travel-clothesline",
    imageUrl: "https://www.outdoortrends.de/media/9f/ff/fa/1771525881/cocoon-travel-clothesline-waescheleine-coc-tcl1-_1_1771525881455.jpg?ts=1771525881",
    priceMin: 15,
    priceMax: 22,
    category: "travel",
    badge: "✈️",
    name: { en: "Cocoon Travel Clothesline", ja: "コクーン トラベル クロースライン" },
    description: {
      en: "Solid-cord clothesline with 8 integrated non-removable clips and adjustable end hooks for variable bathroom span widths.",
      ja: "8個の固定統合クリップ・スパン幅に合わせられる調整可能エンドフック付きのソリッドコードクロースライン。",
    },
    links: [{ network: "direct", productId: "https://www.cocoon.com/product/travel-clothesline/", markets: ["global"], approved: true }],
  },
  {
    id: "nite-ize-gear-tie-clothesline",
    imageUrl: "https://m.media-amazon.com/images/I/71NGV+wtfzL.jpg",
    priceMin: 10,
    priceMax: 16,
    category: "travel",
    badge: "✈️",
    name: { en: "Nite Ize Gear Tie Clothesline Kit", ja: "ナイトアイズ ギアタイ クロースラインキット" },
    description: {
      en: "Dual-purpose stretchable gear tie that functions as a clothesline when wrapped around bathroom fixtures and as a general gear organizer.",
      ja: "バスルームの備品に巻き付けて物干しロープとしても、ギア整理にも使えるデュアルユース伸縮ギアタイ。",
    },
    links: [{ network: "direct", productId: "https://www.niteize.com/collection/gear-tie-clothesline", markets: ["global"], approved: true }],
  },
  {
    id: "travelon-elastic-travel-clothesline",
    imageUrl: "https://m.media-amazon.com/images/S/aplus-media-library-service-media/0fb0e7a4-a4be-48b4-b180-3bf9521eae29.__CR0,0,970,600_PT0_SX970_V1___.png",
    priceMin: 6,
    priceMax: 10,
    category: "travel",
    badge: "✈️",
    name: { en: "Travelon Elastic Travel Clothesline", ja: "トラベロン エラスティック トラベル クロースライン" },
    description: {
      en: "Budget elastic clothesline with suction cup hooks for smooth bathroom surfaces, packs flat. Entry point for clothesline travel.",
      ja: "滑らかな表面用吸盤フック・フラット収納の予算向けエラスティッククロースライン。物干しロープ旅行のお試しに。",
    },
    links: [{ network: "direct", productId: "https://www.travelon.com/product/elastic-clothesline/", markets: ["global"], approved: true }],
  },
] as unknown as AffiliateOffer[];
