// @ts-nocheck — parenting batch 12 (2026-06-13). 50 offers across 10 articles.
import type { AffiliateOffer } from "./types";

export const CATALOG_BATCH12_PARENTING: AffiliateOffer[] = [
  // === best-convertible-car-seat-2026 ===
  {
    id: "graco-4ever-dlx",
    imageUrl: "https://m.media-amazon.com/images/I/814LByNL7KL.jpg",
    priceMin: "199",
    priceMax: "280",
    category: "parenting",
    badge: "👶",
    name: { en: "Graco 4Ever DLX 4-in-1 Car Seat", ja: "グレコ 4Ever DLX 4-in-1チャイルドシート" },
    description: { en: "All-in-one convertible car seat covering rear-facing to 50 lbs, forward-facing to 65 lbs, and booster to 120 lbs. Features rethread-free Simply Safe Adjust harness and InRight LATCH.", ja: "後ろ向き約23kgから前向き約30kg、ブースター約54kgまでカバーするオールインワンコンバーチブルシート。スレッドフリーのSimply Safe Adjustハーネスと InRight LATCHを搭載。" },
    links: [{ network: "amazon-us", productId: "graco-4ever-dlx", rawUrl: "https://www.amazon.com/s?k=Graco+4Ever+DLX+4-in-1+Car+Seat", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "britax-boulevard-clicktight",
    imageUrl: "https://m.media-amazon.com/images/I/81B6zKMvf6L._SX679_.jpg",
    priceMin: "279",
    priceMax: "340",
    category: "parenting",
    badge: "👶",
    name: { en: "Britax Boulevard ClickTight Convertible Car Seat", ja: "ブリタックス ブールバード ClickTight コンバーチブルシート" },
    description: { en: "Premium convertible car seat with ClickTight installation system threading the seat belt through the shell for a foolproof install. Includes SafeCell impact-absorbing base and dual side-impact protection.", ja: "シートベルトをシェルに通すClickTight取り付けシステムを採用したプレミアムコンバーチブルシート。SafeCell衝撃吸収ベースとデュアルサイドインパクトプロテクションを搭載。" },
    links: [{ network: "amazon-us", productId: "britax-boulevard-clicktight", rawUrl: "https://www.amazon.com/s?k=Britax+Boulevard+ClickTight+Convertible+Car+Seat", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "chicco-nextfit-zip",
    imageUrl: "https://m.media-amazon.com/images/I/81A4c1SYY9L._AC_.jpg",
    priceMin: "219",
    priceMax: "260",
    category: "parenting",
    badge: "👶",
    name: { en: "Chicco NextFit Zip Convertible Car Seat", ja: "チッコ NextFit Zip コンバーチブルシート" },
    description: { en: "Convertible car seat with 9-position recline for easy installation in vehicles with steep seat angles. Zip-off machine-washable cover removes in 30 seconds.", ja: "急な座席角度の車でも取り付けやすい9段階リクライニング付きコンバーチブルシート。30秒で取り外せる洗濯機対応ジップ式カバー付き。" },
    links: [{ network: "amazon-us", productId: "chicco-nextfit-zip", rawUrl: "https://www.amazon.com/s?k=Chicco+NextFit+Zip+Convertible+Car+Seat", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "evenflo-gold-revolve360",
    imageUrl: "https://m.media-amazon.com/images/I/91htsp064HL._SL1500_.jpg",
    priceMin: "349",
    priceMax: "420",
    category: "parenting",
    badge: "👶",
    name: { en: "Evenflo Gold Revolve360 Rotating Convertible Car Seat", ja: "エベンフロ ゴールド Revolve360 回転式コンバーチブルシート" },
    description: { en: "360-degree rotating convertible car seat with one-hand rotation lock. Rated NHTSA 5-star with dual side-impact protection. Simplifies loading sleeping toddlers.", ja: "片手ロック機能付き360度回転式コンバーチブルシート。NHTSA 5つ星認定でデュアルサイドインパクトプロテクション搭載。眠ったままの幼児の乗せ降ろしを簡単に。" },
    links: [{ network: "amazon-us", productId: "evenflo-gold-revolve360", rawUrl: "https://www.amazon.com/s?k=Evenflo+Gold+Revolve360+Rotating+Convertible+Car+Seat", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "cosco-scenera-next",
    imageUrl: "https://m.media-amazon.com/images/I/91QAlNPPliL._AC_SL1500_.jpg",
    priceMin: "40",
    priceMax: "55",
    category: "parenting",
    badge: "👶",
    name: { en: "Cosco Scenera NEXT Convertible Car Seat", ja: "コスコ Scenera NEXT コンバーチブルシート" },
    description: { en: "Narrowest convertible car seat at 16.5 inches wide — fits 3-across in standard back seats. Lightweight at 10 lbs. Meets all federal FMVSS 213 safety standards.", ja: "幅約42cmで最もスリムなコンバーチブルシート——標準的な後部座席に3台並べられる。約4.5kgと軽量。連邦FMVSS 213安全基準に適合。" },
    links: [{ network: "amazon-us", productId: "cosco-scenera-next", rawUrl: "https://www.amazon.com/s?k=Cosco+Scenera+NEXT+Convertible+Car+Seat", markets: ["US", "EU", "UK", "global"], approved: true }],
  },

  // === best-booster-seat-2026 ===
  {
    id: "graco-tranzitions-3in1",
    imageUrl: "https://m.media-amazon.com/images/I/71gAXzvKyWL._SX569_.jpg",
    priceMin: "79",
    priceMax: "110",
    category: "parenting",
    badge: "👶",
    name: { en: "Graco Tranzitions 3-in-1 Harness Booster Car Seat", ja: "グレコ Tranzitions 3-in-1ハーネスジュニアシート" },
    description: { en: "IIHS Best Bet rated 3-in-1 booster transitioning from harness (to 65 lbs) through high-back to backless booster. Adjustable belt guide fits children 38-57 inches tall.", ja: "IIHSベストベット認定の3-in-1ジュニアシート。ハーネス（約30kgまで）からハイバック、バックレスジュニアへと変換。身長約96〜145cmの子どもに対応する調整可能なベルトガイド付き。" },
    links: [{ network: "amazon-us", productId: "graco-tranzitions-3in1", rawUrl: "https://www.amazon.com/s?k=Graco+Tranzitions+3-in-1+Harness+Booster+Car+Seat", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "britax-highpoint-belt",
    imageUrl: "https://m.media-amazon.com/images/I/41zJbVBNVxL._AC_.jpg",
    priceMin: "159",
    priceMax: "200",
    category: "parenting",
    badge: "👶",
    name: { en: "Britax Highpoint Belt-Positioning Booster Car Seat", ja: "ブリタックス Highpoint ベルトポジショニングジュニアシート" },
    description: { en: "IIHS Best Bet rated high-back booster with ClickSafe belt guides that lock the belt in correct position. QuickConvert to backless. Excellent side-impact wing protection.", ja: "ClickSafeベルトガイドで正しい位置にベルトをロックするIIHSベストベット認定ハイバックジュニアシート。QuickConvertでバックレスに変換可能。優れたサイドインパクトウィングプロテクション。" },
    links: [{ network: "amazon-us", productId: "britax-highpoint-belt", rawUrl: "https://www.amazon.com/s?k=Britax+Highpoint+Belt-Positioning+Booster+Car+Seat", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "cybex-solution-s2",
    imageUrl: "https://m.media-amazon.com/images/I/513vAqrsb9L._AC_SL1500_.jpg",
    priceMin: "229",
    priceMax: "280",
    category: "parenting",
    badge: "👶",
    name: { en: "Cybex Solution S2 i-Fix High-Back Booster Seat", ja: "サイベックス Solution S2 i-Fix ハイバックジュニアシート" },
    description: { en: "European-style high-back booster with deeply reclined seatback for comfort on long drives. L.S.P. headrest system absorbs side-impact energy through a dedicated channel.", ja: "長距離ドライブで快適な深くリクライニングするシートバック付きヨーロッパスタイルのハイバックジュニアシート。専用チャンネルを通じてサイドインパクトエネルギーを吸収するL.S.P.ヘッドレストシステム搭載。" },
    links: [{ network: "amazon-us", productId: "cybex-solution-s2", rawUrl: "https://www.amazon.com/s?k=Cybex+Solution+S2+High-Back+Booster+Seat", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "chicco-myfit-zip",
    imageUrl: "https://m.media-amazon.com/images/I/8166D-dBeBL.jpg",
    priceMin: "149",
    priceMax: "185",
    category: "parenting",
    badge: "👶",
    name: { en: "Chicco MyFit Zip Air Harness and Booster Car Seat", ja: "チッコ MyFit Zip Air ハーネス&ジュニアシート" },
    description: { en: "2-in-1 harness and booster with zip-off machine-washable cover that removes in under a minute. Energy-absorbing steel frame. Converts from high-back to backless booster.", ja: "1分以内に取り外せる洗濯機対応ジップ式カバー付き2-in-1ハーネス&ジュニアシート。エネルギー吸収スチールフレーム。ハイバックからバックレスジュニアに変換可能。" },
    links: [{ network: "amazon-us", productId: "chicco-myfit-zip", rawUrl: "https://www.amazon.com/s?k=Chicco+MyFit+Zip+Harness+Booster+Car+Seat", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "bubblebum-inflatable",
    imageUrl: "https://m.media-amazon.com/images/I/81c16Yv9ErL._SL1500_.jpg",
    priceMin: "39",
    priceMax: "55",
    category: "parenting",
    badge: "👶",
    name: { en: "BubbleBum Inflatable Travel Booster Car Seat", ja: "バブルバム 膨張式トラベルジュニアシート" },
    description: { en: "FAA-approved inflatable booster car seat — the only booster approved for airline use. Deflates to fit under airplane seats, weighs under 1 lb. Fits children 40-100 lbs.", ja: "FAA承認の膨張式ジュニアシート——航空機での使用が承認された唯一のジュニアシート。空気を抜いて飛行機の座席下に収納可能、重量450g未満。18〜45kgの子どもに対応。" },
    links: [{ network: "amazon-us", productId: "bubblebum-inflatable", rawUrl: "https://www.amazon.com/s?k=BubbleBum+Inflatable+Travel+Booster+Car+Seat", markets: ["US", "EU", "UK", "global"], approved: true }],
  },

  // === best-double-stroller-2026 ===
  {
    id: "uppababy-vista-v3",
    imageUrl: "https://m.media-amazon.com/images/I/61uxuZSK2sL.jpg",
    priceMin: "999",
    priceMax: "1299",
    category: "parenting",
    badge: "👶",
    name: { en: "UPPAbaby Vista V3 Stroller", ja: "アップリカ Vista V3ベビーカー" },
    description: { en: "Premium modular stroller system that expands from single to double via RumbleSeat II attachment without compromising main seat. One-step fold with both seats attached.", ja: "RumbleSeat IIアタッチメントでメインシートを妥協せずにシングルからダブルに拡張できるプレミアムモジュラーベビーカーシステム。両シートを付けたまま1ステップで折りたたみ可能。" },
    links: [{ network: "amazon-us", productId: "uppababy-vista-v3", rawUrl: "https://www.amazon.com/s?k=UPPAbaby+Vista+V3+Stroller", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "baby-jogger-city-mini-gt2-double",
    imageUrl: "https://m.media-amazon.com/images/I/81qNQ7MhUQL._AC_.jpg",
    priceMin: "599",
    priceMax: "699",
    category: "parenting",
    badge: "👶",
    name: { en: "Baby Jogger City Mini GT2 Double Stroller", ja: "ベビージョガー シティミニ GT2ダブルベビーカー" },
    description: { en: "Side-by-side double stroller, 29 inches wide with one-hand fold and both seats attached. All-terrain wheels and hand-actuated parking brake. Both seats recline independently to near-flat.", ja: "並列ダブルベビーカー、両シートを付けたまま片手折りたたみ可能な幅74cm。オールテレーンホイールと手動式パーキングブレーキ付き。両シートが独立してフルフラット近くにリクライニング。" },
    links: [{ network: "amazon-us", productId: "baby-jogger-city-mini-gt2-double", rawUrl: "https://www.amazon.com/s?k=Baby+Jogger+City+Mini+GT2+Double+Stroller", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "joovy-caboose-too",
    imageUrl: "https://m.media-amazon.com/images/I/51k00EeHhAL._AC_SL1000_.jpg",
    priceMin: "299",
    priceMax: "349",
    category: "parenting",
    badge: "👶",
    name: { en: "Joovy Caboose Too Ultralight Sit and Stand Stroller", ja: "ジュービー カブース Too 超軽量シット＆スタンドベビーカー" },
    description: { en: "Tandem stroller with rear bench seat that converts to a standing platform — ideal for toddler-plus-infant families. Front seat accepts most major infant car seat brands.", ja: "後ろのベンチシートがスタンディングプラットフォームに変換できるタンデムベビーカー——幼児プラス乳児の家族に最適。前のシートがほとんどの主要インファントカーシートブランドに対応。" },
    links: [{ network: "amazon-us", productId: "joovy-caboose-too", rawUrl: "https://www.amazon.com/s?k=Joovy+Caboose+Too+Ultralight+Sit+and+Stand+Stroller", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "graco-ready2grow-lx",
    imageUrl: "https://m.media-amazon.com/images/I/91TgbG2SAmL._SL1500_.jpg",
    priceMin: "179",
    priceMax: "229",
    category: "parenting",
    badge: "👶",
    name: { en: "Graco Ready2Grow LX 2.0 Double Stroller", ja: "グレコ Ready2Grow LX 2.0ダブルベビーカー" },
    description: { en: "Budget tandem double stroller with three rear riding configurations: standing platform, bench seat, and rear bucket seat. Accepts Graco SnugRide infant car seats in both positions.", ja: "スタンディングプラットフォーム・ベンチシート・後ろバケットシートの3つの後部乗車設定があるバジェットタンデムダブルベビーカー。両ポジションでGraco SnugRideインファントカーシートに対応。" },
    links: [{ network: "amazon-us", productId: "graco-ready2grow-lx", rawUrl: "https://www.amazon.com/s?k=Graco+Ready2Grow+LX+Double+Stroller", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "zoe-xl2-best",
    imageUrl: "https://www.just-twins.com/wp-content/uploads/2019/05/51zS6MG2BK7L.jpg",
    priceMin: "349",
    priceMax: "419",
    category: "parenting",
    badge: "👶",
    name: { en: "ZOE XL2 BEST v2 Double Stroller", ja: "ZOE XL2 BEST v2ダブルベビーカー" },
    description: { en: "Lightest double stroller at 20 lbs. Folds to carry-on dimensions for air travel — includes gate-check bag. Both seats fully recline independently with UPF50+ canopies.", ja: "重量約9kgで最軽量のダブルベビーカー。航空トラベル向けキャリーオンサイズに折りたためる——ゲートチェックバッグ付属。両シートがUPF50+キャノピー付きで独立してフルフラットにリクライニング。" },
    links: [{ network: "amazon-us", productId: "zoe-xl2-best", rawUrl: "https://www.amazon.com/s?k=ZOE+XL2+BEST+Double+Stroller", markets: ["US", "EU", "UK", "global"], approved: true }],
  },

  // === best-jogging-stroller-2026 ===
  {
    id: "bob-revolution-flex-30",
    imageUrl: "https://m.media-amazon.com/images/I/81tIT-FoM8L._AC_.jpg",
    priceMin: "399",
    priceMax: "479",
    category: "parenting",
    badge: "👶",
    name: { en: "BOB Revolution Flex 3.0 Jogging Stroller", ja: "BOB Revolution Flex 3.0ジョギングベビーカー" },
    description: { en: "Premium jogging stroller with independent front suspension, air-filled 16-inch tires, and lockable swivel front wheel. Hand brake for downhill control. Adjustable handlebar.", ja: "独立フロントサスペンション・空気入り40cmタイヤ・ロック可能スウィベルフロントホイール付きプレミアムジョギングベビーカー。下り坂制御用ハンドブレーキ。調整可能なハンドルバー。" },
    links: [{ network: "amazon-us", productId: "bob-revolution-flex-30", rawUrl: "https://www.amazon.com/s?k=BOB+Revolution+Flex+3.0+Jogging+Stroller", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "thule-urban-glide-3",
    imageUrl: "https://www.thule.com/-/p/d1s8Kk8U_kmOKUJY1Gii3xTWKf8Fj_6jun_yjEVvVMQ/rs:fit/h:991/cb:1.4/w:991/plain/approved/std.lang.all/81/35/1568135.png",
    priceMin: "549",
    priceMax: "649",
    category: "parenting",
    badge: "👶",
    name: { en: "Thule Urban Glide 3 Jogging Stroller", ja: "スーリー Urban Glide 3ジョギングベビーカー" },
    description: { en: "Swedish-engineered premium jogging stroller with refined suspension for smooth trail and pavement performance. Magnetic harness buckle closure and comprehensive reflective coverage for low-light running.", ja: "なめらかなトレイルと舗装路での洗練されたサスペンション付きスウェーデン製プレミアムジョギングベビーカー。マグネットハーネスバックルと低光量ランニング用包括的な反射カバレッジ。" },
    links: [{ network: "amazon-us", productId: "thule-urban-glide-3", rawUrl: "https://www.amazon.com/s?k=Thule+Urban+Glide+3+Jogging+Stroller", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "schwinn-interval-jogging",
    imageUrl: "https://m.media-amazon.com/images/I/81oTNtrlfZL._SX679_.jpg",
    priceMin: "199",
    priceMax: "249",
    category: "parenting",
    badge: "👶",
    name: { en: "Schwinn Interval Jogging Stroller", ja: "シュウィン Intervalジョギングベビーカー" },
    description: { en: "Mid-range jogging stroller with never-flat foam-filled tires and parent console included. Adjustable handlebar accommodates heights from 5'0\" to 6'4\".", ja: "絶対にパンクしないフォーム入りタイヤとペアレントコンソール付きのミドルレンジジョギングベビーカー。身長152〜193cmに対応する調整可能なハンドルバー。" },
    links: [{ network: "amazon-us", productId: "schwinn-interval-jogging", rawUrl: "https://www.amazon.com/s?k=Schwinn+Interval+Jogging+Stroller", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "baby-trend-expedition-jogger",
    imageUrl: "https://m.media-amazon.com/images/I/81vXyfe8AwL._SL1500_.jpg",
    priceMin: "89",
    priceMax: "119",
    category: "parenting",
    badge: "👶",
    name: { en: "Baby Trend Expedition Jogger Travel System", ja: "ベビートレンド Expedition Joggerトラベルシステム" },
    description: { en: "Budget jogging stroller with pneumatic tires and lockable front swivel. Reclining seat accepts infants from 6 months. Fits smooth pavement jogging at moderate speeds.", ja: "空気入りタイヤとロック可能フロントスウィベル付きバジェットジョギングベビーカー。生後6ヶ月からの乳児に対応するリクライニングシート。なめらかな舗装路での中程度の速度でのジョギングに対応。" },
    links: [{ network: "amazon-us", productId: "baby-trend-expedition-jogger", rawUrl: "https://www.amazon.com/s?k=Baby+Trend+Expedition+Jogger", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "contours-ridge-jogging",
    imageUrl: "https://m.media-amazon.com/images/I/712KeUZXnQL._SL1500_.jpg",
    priceMin: "279",
    priceMax: "329",
    category: "parenting",
    badge: "👶",
    name: { en: "Contours Ridge Jogging Stroller", ja: "コントアーズ Ridgeジョギングベビーカー" },
    description: { en: "All-terrain jogging stroller with adjustable rear suspension designed for real trail running. 16-inch air-filled rear wheels and lockable swivel for off-road capability.", ja: "本格的なトレイルランニング用に設計された調整可能なリアサスペンション付きオールテレーンジョギングベビーカー。40cm空気入りリアホイールとオフロード能力のためのロック可能スウィベル。" },
    links: [{ network: "amazon-us", productId: "contours-ridge-jogging", rawUrl: "https://www.amazon.com/s?k=Contours+Ridge+Jogging+Stroller", markets: ["US", "EU", "UK", "global"], approved: true }],
  },

  // === best-baby-food-storage-containers-2026 ===
  {
    id: "oxo-tot-glass-baby-blocks",
    imageUrl: "https://m.media-amazon.com/images/I/810thncX5cL._SL1500_.jpg",
    priceMin: "16",
    priceMax: "28",
    category: "parenting",
    badge: "👶",
    name: { en: "OXO Tot Glass Baby Blocks Food Storage Containers", ja: "OXO Tot ガラス製ベビーブロック食品保存容器" },
    description: { en: "Glass baby food storage with press-lock lids creating an airtight seal. Available in 2oz and 4oz sizes, stackable in freezer and fridge. Dishwasher-safe on top rack.", ja: "気密シールを作るプレスロック蓋付きガラス製離乳食保存容器。60mlと120mlサイズで冷凍庫と冷蔵庫で積み重ね可能。上段食洗機対応。" },
    links: [{ network: "amazon-us", productId: "oxo-tot-glass-baby-blocks", rawUrl: "https://www.amazon.com/s?k=OXO+Tot+Glass+Baby+Blocks+Food+Storage", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "bbox-freezer-tray",
    imageUrl: "https://m.media-amazon.com/images/I/71LGyzdVZQL._AC_SL1500_.jpg",
    priceMin: "18",
    priceMax: "25",
    category: "parenting",
    badge: "👶",
    name: { en: "b.box Silicone Baby Food Freezer Tray", ja: "b.box シリコン製離乳食冷凍トレー" },
    description: { en: "Silicone freezer tray producing 15 individual 1oz cubes per batch. Thick silicone construction ensures clean cube pop-out even when fully frozen. Snap-on lid for freezer storage.", ja: "1バッチで15個の30mlキューブを作るシリコン製冷凍トレー。厚いシリコン構造で完全に凍った状態でもきれいなキューブポップアウトを実現。冷凍庫保存用スナップ式蓋付き。" },
    links: [{ network: "amazon-us", productId: "bbox-freezer-tray", rawUrl: "https://www.amazon.com/s?k=b.box+Baby+Food+Freezer+Tray+Silicone", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "wean-green-glass-cubes",
    imageUrl: "https://m.media-amazon.com/images/I/61cph9UA1yL._AC_SY300_SX300_QL70_ML2_.jpg",
    priceMin: "19",
    priceMax: "28",
    category: "parenting",
    badge: "👶",
    name: { en: "Wean Green Glass Baby Food Cubes Storage", ja: "ウィーングリーン ガラス製離乳食キューブ保存容器" },
    description: { en: "Tempered glass baby food storage cubes with snap-lock lids — zero plastic in food contact. Available in 4oz and 8oz sizes. Even microwave heat distribution reduces hot spots.", ja: "食品接触部にプラスチックなしのスナップロック蓋付き強化ガラス製離乳食保存キューブ。120mlと240mlサイズ。均等なレンジ加熱配分でホットスポットを軽減。" },
    links: [{ network: "amazon-us", productId: "wean-green-glass-cubes", rawUrl: "https://www.amazon.com/s?k=Wean+Green+Glass+Baby+Food+Cubes", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "mumi-bubi-silicone-pods",
    imageUrl: "https://www.naturalbabygoods.com/wp-content/uploads/2025/09/mumi_bubi_solids_starter_kit.jpg",
    priceMin: "29",
    priceMax: "39",
    category: "parenting",
    badge: "👶",
    name: { en: "Mumi & Bubi Solids Starter Kit Silicone Pods", ja: "ムミ＆ブビ ソリッドスターターキット シリコンポッド" },
    description: { en: "3oz flexible silicone pods in a zippered carry case with individual pod slots — ideal for daycare and travel. Freezer, dishwasher, and microwave safe.", ja: "個別ポッドスロット付きジッパーキャリーケースの90ml柔軟シリコンポッド——保育所と旅行に最適。冷凍・食洗機・電子レンジ対応。" },
    links: [{ network: "amazon-us", productId: "mumi-bubi-silicone-pods", rawUrl: "https://www.amazon.com/s?k=Mumi+Bubi+Solids+Starter+Kit+Silicone+Baby+Food", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "kiddo-feeder-silicone-tray",
    imageUrl: "https://m.media-amazon.com/images/I/81TZ5l+b+rL._AC_SS450_.jpg",
    priceMin: "12",
    priceMax: "18",
    category: "parenting",
    badge: "👶",
    name: { en: "WeeSprout Silicone Baby Food Freezer Tray with Lid", ja: "ウィースプラウト シリコン製離乳食冷凍トレー（蓋付き）" },
    description: { en: "Budget silicone baby food tray with 12 compartments at 2oz each. Stackable with lid design to maximize freezer space. BPA-free silicone construction.", ja: "12コンパートメントに各60mlのバジェットシリコン製離乳食トレー。冷凍庫のスペースを最大化するための蓋付きスタッカブルデザイン。BPAフリーシリコン製。" },
    links: [{ network: "amazon-us", productId: "kiddo-feeder-silicone-tray", rawUrl: "https://www.amazon.com/s?k=WeeSprout+Silicone+Baby+Food+Tray+With+Lid", markets: ["US", "EU", "UK", "global"], approved: true }],
  },

  // === best-kids-water-bottle-2026 ===
  {
    id: "hydro-flask-kids-wide-mouth",
    imageUrl: "https://m.media-amazon.com/images/I/51KVWTdmIZL._AC_SL1500_.jpg",
    priceMin: "29",
    priceMax: "35",
    category: "parenting",
    badge: "👶",
    name: { en: "Hydro Flask Kids Wide Mouth Water Bottle 12oz", ja: "ハイドロフラスク キッズ ワイドマウス水筒 350ml" },
    description: { en: "12oz kids stainless steel insulated water bottle with TempShield double-wall insulation keeping water cold for 22+ hours. DuraCoat powder finish resists chips after concrete drop tests.", ja: "22時間以上の保冷を実現するTempShieldダブルウォール断熱付き350mlステンレス鋼製子ども用水筒。コンクリート落下テスト後もペイント欠けに耐えるDuraCoat粉体仕上げ。" },
    links: [{ network: "amazon-us", productId: "hydro-flask-kids-wide-mouth", rawUrl: "https://www.amazon.com/s?k=Hydro+Flask+Kids+Wide+Mouth+12oz+Water+Bottle", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "klean-kanteen-kid-kanteen",
    imageUrl: "https://m.media-amazon.com/images/I/61VJTa8enFL._AC_SL1494_.jpg",
    priceMin: "23",
    priceMax: "30",
    category: "parenting",
    badge: "👶",
    name: { en: "Klean Kanteen Kid Kanteen Insulated Water Bottle 12oz", ja: "クリーンカンティーン キッドカンティーン断熱水筒 350ml" },
    description: { en: "12oz insulated stainless steel kids bottle with Sport Cap pull-straw for independent drinking from age 2.5. Chip-resistant ColorLast coating. Sport Cap fully dishwasher-safe.", ja: "2.5歳以上が独立して飲めるSport Capプル式ストロー付き350ml断熱ステンレス鋼製子ども用水筒。耐チップColorLastコーティング。Sport Capが食洗機対応。" },
    links: [{ network: "amazon-us", productId: "klean-kanteen-kid-kanteen", rawUrl: "https://www.amazon.com/s?k=Klean+Kanteen+Kid+Kanteen+Insulated+12oz", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "nalgene-kids-on-the-fly",
    imageUrl: "https://m.media-amazon.com/images/I/512kb6ksa1L._AC_SY741_.jpg",
    priceMin: "13",
    priceMax: "18",
    category: "parenting",
    badge: "👶",
    name: { en: "Nalgene Kids On the Fly Water Bottle 14oz", ja: "ナルゲン キッズ オン・ザ・フライ 水筒 400ml" },
    description: { en: "14oz BPA-free Tritan plastic kids bottle with wide opening for ice and flip-straw lid. Lightest bottle tested at 3.8oz. Fully dishwasher-safe including all lid components.", ja: "氷が入れやすいワイドオープニングとフリップストロー蓋付きBPAフリーTritan素材の400ml子ども用水筒。テスト中最軽量の約110g。蓋コンポーネント含め全て食洗機対応。" },
    links: [{ network: "amazon-us", productId: "nalgene-kids-on-the-fly", rawUrl: "https://www.amazon.com/s?k=Nalgene+Kids+On+the+Fly+Water+Bottle", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "camelbak-eddy-kids",
    imageUrl: "https://m.media-amazon.com/images/I/81H4tmk9uML._AC_SL1500_.jpg",
    priceMin: "14",
    priceMax: "20",
    category: "parenting",
    badge: "👶",
    name: { en: "CamelBak Eddy+ Kids Water Bottle 12oz", ja: "キャメルバック エディ+ キッズ水筒 350ml" },
    description: { en: "12oz BPA-free Tritan plastic kids bottle with bite-and-sip straw valve. Fully dishwasher-safe lid assembly on top rack. Lightweight and spill-resistant for school use.", ja: "バイト＆シップストローバルブ付きBPAフリーTritan素材の350ml子ども用水筒。蓋アセンブリが上段食洗機対応。学校用に軽量でこぼれにくい。" },
    links: [{ network: "amazon-us", productId: "camelbak-eddy-kids", rawUrl: "https://www.amazon.com/s?k=CamelBak+Eddy+Kids+Water+Bottle+12oz", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "thermoflask-kids-14oz",
    imageUrl: "https://m.media-amazon.com/images/I/61wFTSNrJIL._AC_SL1500_.jpg",
    priceMin: "16",
    priceMax: "22",
    category: "parenting",
    badge: "👶",
    name: { en: "Thermoflask Kids Insulated Water Bottle 14oz", ja: "サーモフラスク キッズ断熱水筒 400ml" },
    description: { en: "14oz double-wall vacuum insulated stainless steel kids bottle achieving 24-hour cold performance. Includes both straw lid and chug lid. BPA-free at roughly half the price of Hydro Flask.", ja: "24時間保冷を実現するダブルウォール真空断熱ステンレス鋼製400ml子ども用水筒。ストロー蓋と直飲み蓋が両方付属。Hydro Flaskの約半額でBPAフリー。" },
    links: [{ network: "amazon-us", productId: "thermoflask-kids-14oz", rawUrl: "https://www.amazon.com/s?k=Thermoflask+Kids+Insulated+Water+Bottle+14oz", markets: ["US", "EU", "UK", "global"], approved: true }],
  },

  // === best-kids-scooter-2026 ===
  {
    id: "micro-mini-deluxe-classic",
    imageUrl: "https://scooterdojo.com/wp-content/uploads/2023/09/micro-mini-deluxe-scooter-review-1155x770.png",
    priceMin: "89",
    priceMax: "109",
    category: "parenting",
    badge: "👶",
    name: { en: "Micro Mini Deluxe Classic Scooter (Ages 2-5)", ja: "マイクロ ミニデラックスクラシック スクーター（2〜5歳）" },
    description: { en: "Premium Swiss-engineered 3-wheel lean-to-steer scooter for ages 2-5. Wide deck with raised rails for secure footing. Tool-free adjustable T-bar grows from age 2 to 5.", ja: "2〜5歳向けプレミムスイス製3輪リーン式スクーター。安全な足元のための隆起したレール付きワイドデッキ。ツールなしで2〜5歳まで調整可能なTバー。" },
    links: [{ network: "amazon-us", productId: "micro-mini-deluxe-classic", rawUrl: "https://www.amazon.com/s?k=Micro+Mini+Deluxe+Classic+Scooter", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "radio-flyer-lean-n-glide",
    imageUrl: "https://m.media-amazon.com/images/I/61wVcJreZAL._AC_SX569_.jpg",
    priceMin: "49",
    priceMax: "69",
    category: "parenting",
    badge: "👶",
    name: { en: "Radio Flyer Lean N Glide Scooter", ja: "レディオフライヤー リーン＆グライド スクーター" },
    description: { en: "3-wheel lean-to-steer scooter for beginners with wide deck, foam grip handles, and rear foot brake. Stable platform suitable for ages 2-5 learning to ride.", ja: "ワイドデッキ・フォームグリップハンドル・リアフットブレーキ付きの初心者向け3輪リーン式スクーター。2〜5歳の乗り始めに適した安定したプラットフォーム。" },
    links: [{ network: "amazon-us", productId: "radio-flyer-lean-n-glide", rawUrl: "https://www.amazon.com/s?k=Radio+Flyer+Lean+N+Glide+Scooter", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "globber-primo-foldable",
    imageUrl: "https://m.media-amazon.com/images/I/61tM7GIW3oL._AC_SL1500_.jpg",
    priceMin: "69",
    priceMax: "89",
    category: "parenting",
    badge: "👶",
    name: { en: "Globber Primo Foldable Plus Lights 3-Wheel Scooter", ja: "グロバー プリモ フォールダブル プラスライト 3輪スクーター" },
    description: { en: "3-wheel foldable lean-to-steer scooter with one-button fold mechanism. Adjustable T-bar covers ages 2-6. Compact fold fits car trunks and transit luggage areas.", ja: "ワンボタン折りたたみメカニズム付き3輪折りたたみリーン式スクーター。2〜6歳をカバーする調整可能なTバー。コンパクトな折りたたみが車のトランクと公共交通の荷物エリアに適合。" },
    links: [{ network: "amazon-us", productId: "globber-primo-foldable", rawUrl: "https://www.amazon.com/s?k=Globber+Primo+Foldable+3+Wheel+Scooter", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "razor-a5-lux",
    imageUrl: "https://m.media-amazon.com/images/S/aplus-media/vc/2a5f4abb-c1a8-425b-b6b1-6fbb5d584b71.__CR0,0,970,300_PT0_SX970_V1___.jpg",
    priceMin: "59",
    priceMax: "79",
    category: "parenting",
    badge: "👶",
    name: { en: "Razor A5 Lux Kick Scooter", ja: "レイザー A5 Luxキックスクーター" },
    description: { en: "Commuter-grade 2-wheel scooter for ages 8+ with 200mm urethane wheels that handle sidewalk cracks and pebbles. Aircraft-grade aluminum frame supports up to 220 lbs. ABEC-5 bearings.", ja: "歩道のひび割れや小石に対応する200mmウレタンホイール付き8歳以上向けコミューターグレードの2輪スクーター。航空グレードアルミフレームは100kgまで対応。ABEC-5ベアリング。" },
    links: [{ network: "amazon-us", productId: "razor-a5-lux", rawUrl: "https://www.amazon.com/s?k=Razor+A5+Lux+Kick+Scooter", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "yvolution-y-glider-kiwi",
    imageUrl: "https://m.media-amazon.com/images/I/51AYsq6uLYL._AC_SL1200_.jpg",
    priceMin: "39",
    priceMax: "55",
    category: "parenting",
    badge: "👶",
    name: { en: "Yvolution Y Glider Kiwi 3-Wheel Scooter", ja: "イボルーション Y グライダー キウイ 3輪スクーター" },
    description: { en: "Budget 3-wheel lean-to-steer scooter for ages 3-5 with wide footboard and adjustable handlebar. Rear brake included. Entry-level price for first-time scooter buyers.", ja: "ワイドフットボードと調整可能なハンドルバー付き3〜5歳向けバジェット3輪リーン式スクーター。リアブレーキ付き。初めてスクーターを購入する方向けの入門価格。" },
    links: [{ network: "amazon-us", productId: "yvolution-y-glider-kiwi", rawUrl: "https://www.amazon.com/s?k=Yvolution+Y+Glider+Kiwi+3+Wheel+Scooter", markets: ["US", "EU", "UK", "global"], approved: true }],
  },

  // === best-baby-teething-toys-2026 ===
  {
    id: "nuby-icybite-hard-soft-teether",
    imageUrl: "https://m.media-amazon.com/images/I/91XZRv28ZnL._SL1500_.jpg",
    priceMin: "4",
    priceMax: "8",
    category: "parenting",
    badge: "👶",
    name: { en: "Nuby IcyBite Hard Soft Teether Ring", ja: "ニュービー アイスバイト ハードソフト歯固めリング" },
    description: { en: "Dual hard/soft zone teether addressing multiple teething stages in one toy. Food-grade silicone, CPSC-compliant, BPA and phthalate-free. Refrigerate for cold gum relief.", ja: "1つのおもちゃで複数の歯が生える段階に対応するデュアルハード/ソフトゾーン歯固め。食品グレードシリコン製、CPSC準拠、BPA・フタル酸フリー。冷蔵庫で冷やして歯ぐみを和らげる。" },
    links: [{ network: "amazon-us", productId: "nuby-icybite-hard-soft-teether", rawUrl: "https://www.amazon.com/s?k=Nuby+IcyBite+Hard+Soft+Teether", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "sophie-giraffe-teether",
    imageUrl: "https://m.media-amazon.com/images/I/71kNKlMxENL._AC_SL1500_.jpg",
    priceMin: "22",
    priceMax: "28",
    category: "parenting",
    badge: "👶",
    name: { en: "Sophie la Girafe Natural Rubber Teether", ja: "ソフィー ラ ジラーフ 天然ゴム製歯固め" },
    description: { en: "Classic 100% natural rubber teether made in France since 1961. Multiple surface textures on legs, neck, head, and body cover different tooth positions as teething progresses.", ja: "1961年からフランスで製造されている100%天然ゴム製クラシック歯固め。脚・首・頭・体の複数の表面テクスチャーが歯の萌出進行に伴い異なる歯の位置をカバー。" },
    links: [{ network: "amazon-us", productId: "sophie-giraffe-teether", rawUrl: "https://www.amazon.com/s?k=Sophie+la+Girafe+Natural+Rubber+Teether", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "manhattan-toy-winkel",
    imageUrl: "https://m.media-amazon.com/images/S/aplus-media/vc/6f5abe9c-94bf-4e08-9edd-0c967328961e.jpg",
    priceMin: "14",
    priceMax: "19",
    category: "parenting",
    badge: "👶",
    name: { en: "Manhattan Toy Winkel Rattle and Sensory Teether", ja: "マンハッタントイ ウィンクル ラトル＆センサリー歯固め" },
    description: { en: "Interconnected soft tube loop teether for ages 3-5 months when grip is still developing. BPA-free polyethylene tubes with textured rings. Rattle mechanism inside for auditory feedback.", ja: "握力がまだ発達中の3〜5ヶ月向けの相互接続されたやわらかなチューブループ歯固め。テクスチャーリング付きBPAフリーポリエチレンチューブ。聴覚フィードバックのための内部ガラガラ機能。" },
    links: [{ network: "amazon-us", productId: "manhattan-toy-winkel", rawUrl: "https://www.amazon.com/s?k=Manhattan+Toy+Winkel+Rattle+Sensory+Teether", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "bam-bam-natural-rubber",
    imageUrl: "https://m.media-amazon.com/images/I/81xxNpO3KML.jpg",
    priceMin: "12",
    priceMax: "18",
    category: "parenting",
    badge: "👶",
    name: { en: "Bam & Boo Natural Rubber Baby Teether Toy", ja: "バム＆ブー 天然ゴム赤ちゃん用歯固めおもちゃ" },
    description: { en: "Verified 100% natural latex rubber teether with three-ring design providing distinct grip points and texture zones. Solid construction allows full water rinsing without mold risk.", ja: "確認済み100%天然ラテックスゴム製の異なる握り点とテクスチャーゾーンを提供する3リングデザインの歯固め。中実構造でカビのリスクなしに完全に流水すすぎ可能。" },
    links: [{ network: "amazon-us", productId: "bam-bam-natural-rubber", rawUrl: "https://www.amazon.com/s?k=Bam+Boo+Natural+Rubber+Baby+Teether", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "munchkin-twisty-figure8",
    imageUrl: "https://m.media-amazon.com/images/I/81XpnHEsxxL.jpg",
    priceMin: "6",
    priceMax: "10",
    category: "parenting",
    badge: "👶",
    name: { en: "Munchkin Twisty Figure 8 Teether", ja: "マンチキン ツイスティ フィギュア8歯固め" },
    description: { en: "Budget silicone teether in figure-8 shape with multiple texture zones — smooth sides, bumpy ridges, and raised nubs. Self-orienting shape makes it easy to grab from any angle.", ja: "なめらかな側面・でこぼこしたリッジ・隆起したナブの複数のテクスチャーゾーン付きバジェットシリコン製8の字型歯固め。自己方向付けの形状でどの角度からも掴みやすい。" },
    links: [{ network: "amazon-us", productId: "munchkin-twisty-figure8", rawUrl: "https://www.amazon.com/s?k=Munchkin+Twisty+Figure+8+Teether", markets: ["US", "EU", "UK", "global"], approved: true }],
  },

  // === best-nursery-glider-2026 ===
  {
    id: "pottery-barn-performance-glider",
    imageUrl: "https://assets.pkimgs.com/pkimgs/ab/images/dp/wcm/202414/0030/open-box-merritt-slipcovered-swivel-glider-performance-hea-o.jpg",
    priceMin: "699",
    priceMax: "899",
    category: "parenting",
    badge: "👶",
    name: { en: "Pottery Barn Performance Twill Glider & Ottoman", ja: "ポタリーバーン パフォーマンスツイル グライダー＆オットマン" },
    description: { en: "Premium nursery glider with Performance Twill fabric that beads liquid on contact and wipes clean. Hardwood frame with synchronized glide ottoman. Deep seat with solid lumbar support.", ja: "接触時に液体を弾いて拭き取れるPerformance Twillファブリック付きプレミアムナーサリーグライダー。同期するオットマン付き無垢材フレーム。しっかりした腰部サポート付き深い座面。" },
    links: [{ network: "direct", productId: "https://www.potterybarn.com/products/glider/", markets: ["global"], approved: true }],
  },
  {
    id: "babyletto-kiwi-glider",
    imageUrl: "https://m.media-amazon.com/images/I/81vJHl7A4dL._AC_SL1500_.jpg",
    priceMin: "599",
    priceMax: "799",
    category: "parenting",
    badge: "👶",
    name: { en: "babyletto Kiwi Power Recliner and Swivel Glider", ja: "babyletto キウイ パワーリクライナー＆スウィベルグライダー" },
    description: { en: "GREENGUARD Gold certified nursery glider with low VOC emissions — ideal for newborn rooms. Optional power recline saves floor space vs separate ottoman. Modern low-profile design.", ja: "新生児の部屋の空気の質に配慮した低VOC排出GREENGUARD Gold認証ナーサリーグライダー。オプションのパワーリクライニングで別のオットマンなしにフロアスペースを節約。現代的な低プロファイルデザイン。" },
    links: [{ network: "amazon-us", productId: "babyletto-kiwi-glider", rawUrl: "https://www.amazon.com/s?k=babyletto+Kiwi+Power+Recliner+Glider+Nursery", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "dutailier-ultramotion-glider",
    imageUrl: "https://m.media-amazon.com/images/I/817g7GEh6ZS._SL1500_.jpg",
    priceMin: "499",
    priceMax: "649",
    category: "parenting",
    badge: "👶",
    name: { en: "Dutailier Ultramotion Upholstered Glider with USB", ja: "デュテイリエ ウルトラモーション USB付き布張りグライダー" },
    description: { en: "Nursery glider with multi-position glide lock that stops the chair at any point in the arc — ideal for sleeping-baby transfers. Built-in USB-A and USB-C charger on armrest.", ja: "眠っている赤ちゃんの移動に最適なグライドアークの任意のポイントでチェアを止めるマルチポジションロック付きナーサリーグライダー。アームレストに内蔵USB-AとUSB-Cチャージャー。" },
    links: [{ network: "amazon-us", productId: "dutailier-ultramotion-glider", rawUrl: "https://www.amazon.com/s?k=Dutailier+Ultramotion+Glider+Nursery+USB", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "homcom-nursery-rocker-glider",
    imageUrl: "https://m.media-amazon.com/images/I/71mu3H-PTOL._AC_SL1500_.jpg",
    priceMin: "179",
    priceMax: "229",
    category: "parenting",
    badge: "👶",
    name: { en: "HOMCOM Nursery Glider Rocking Chair with Ottoman", ja: "HOMCOM ナーサリーグライダーロッキングチェア オットマン付き" },
    description: { en: "Mid-range nursery glider with padded armrests and smooth glide mechanism. Single-person assembly in approximately 45 minutes. Suitable for most adults with adequate back support.", ja: "パッド付きアームレストとなめらかなグライドメカニズム付きのミドルレンジナーサリーグライダー。約45分の1人での組み立て。十分な背部サポートで多くの大人に適している。" },
    links: [{ network: "amazon-us", productId: "homcom-nursery-rocker-glider", rawUrl: "https://www.amazon.com/s?k=HOMCOM+Nursery+Glider+Rocking+Chair+with+Ottoman", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "dorel-living-nursery-glider",
    imageUrl: "https://m.media-amazon.com/images/I/71TKfO+4mDL._SL1500_.jpg",
    priceMin: "129",
    priceMax: "169",
    category: "parenting",
    badge: "👶",
    name: { en: "Dorel Living Nursery Glider with Ottoman", ja: "ドレル リビング ナーサリーグライダー オットマン付き" },
    description: { en: "Budget nursery glider including matching synchronized ottoman. Assembles in under 30 minutes with two bolts. Quiet glide mechanism suitable for light-sleeping infants.", ja: "マッチングする同期オットマン付きバジェットナーサリーグライダー。2本のボルトで30分以内に組み立て可能。軽い眠りの乳児に適した静かなグライドメカニズム。" },
    links: [{ network: "amazon-us", productId: "dorel-living-nursery-glider", rawUrl: "https://www.amazon.com/s?k=Dorel+Living+Nursery+Glider+with+Ottoman", markets: ["US", "EU", "UK", "global"], approved: true }],
  },

  // === best-toddler-table-and-chairs-2026 ===
  {
    id: "ikea-latt-table-chairs",
    imageUrl: "https://m.media-amazon.com/images/I/51QWsr0lzcL._AC_.jpg",
    priceMin: "29",
    priceMax: "40",
    category: "parenting",
    badge: "👶",
    name: { en: "IKEA LÄTT Children's Table with 2 Chairs", ja: "イケア LÄTT 子ども用テーブルと椅子2脚セット" },
    description: { en: "Solid pine toddler table and 2 chairs set. Wide chair leg stance provides tip-over stability. Tool-free assembly in 20 minutes with included Allen key. Handles washable markers easily.", ja: "堅固なパイン製幼児用テーブルと椅子2脚セット。転倒防止安定性のための広い椅子脚スタンス。付属の六角レンチで20分のツールフリー組み立て。水性マーカーを簡単に処理。" },
    links: [{ network: "direct", productId: "https://www.ikea.com/us/en/p/latt-childrens-table-and-2-chairs-white-pine-s29259787/", markets: ["global"], approved: true }],
  },
  {
    id: "melissa-doug-wooden-table",
    imageUrl: "https://m.media-amazon.com/images/I/81hxs6iRQCL._AC_SL1500_.jpg",
    priceMin: "89",
    priceMax: "119",
    category: "parenting",
    badge: "👶",
    name: { en: "Melissa & Doug Wooden Table & 2 Chairs Set", ja: "メリッサ＆ダグ 木製テーブル＆椅子2脚セット" },
    description: { en: "Hardwood toddler table set with chairs arriving pre-assembled. Smooth lacquer surface is the easiest to clean on any wood set. Denser construction than pine alternatives.", ja: "椅子が組み立て済みで届くハードウッド製幼児用テーブルセット。このリストのどの木製セットより洗いやすいなめらかなラッカーサーフェス。パイン代替品より密度の高い構造。" },
    links: [{ network: "amazon-us", productId: "melissa-doug-wooden-table", rawUrl: "https://www.amazon.com/s?k=Melissa+Doug+Wooden+Table+2+Chairs+Set+Toddler", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "step2-lifestyle-custom-table",
    imageUrl: "https://m.media-amazon.com/images/I/81lsRHCL-AL._AC_SL1500_.jpg",
    priceMin: "79",
    priceMax: "109",
    category: "parenting",
    badge: "👶",
    name: { en: "Step2 Lifestyle Custom Kitchen Table Set", ja: "ステップ2 ライフスタイル カスタムキッチンテーブルセット" },
    description: { en: "Activity table set with built-in storage compartments and kitchen-themed design. Molded plastic surface is easiest to clean on this list. Extends pretend play patterns beyond eating and drawing.", ja: "内蔵収納コンパートメントとキッチンをテーマにしたデザインのアクティビティテーブルセット。このリストで最も洗いやすい成形プラスチックサーフェス。食事と絵を超えたままごと遊びのパターンを延長。" },
    links: [{ network: "amazon-us", productId: "step2-lifestyle-custom-table", rawUrl: "https://www.amazon.com/s?k=Step2+Lifestyle+Custom+Kitchen+Table+Set+Toddler", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "tot-tutors-kids-table-set",
    imageUrl: "https://m.media-amazon.com/images/I/71QQp1BguoL._AC_SL1500_.jpg",
    priceMin: "49",
    priceMax: "65",
    category: "parenting",
    badge: "👶",
    name: { en: "Tot Tutors Kids Table and 2 Chairs Set", ja: "トットチューターズ 子ども用テーブルと椅子2脚セット" },
    description: { en: "Plastic toddler table set with stackable chairs that nest on the table when not in use — minimizing floor footprint. Tool-free snap-together assembly under 15 minutes.", ja: "不使用時にテーブルにネストできるスタッカブルチェア付きプラスチック製幼児用テーブルセット——フロアフットプリントを最小化。15分以内の道具なしスナップ式組み立て。" },
    links: [{ network: "amazon-us", productId: "tot-tutors-kids-table-set", rawUrl: "https://www.amazon.com/s?k=Tot+Tutors+Kids+Table+and+Chairs+Set", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
  {
    id: "keter-kids-table-outdoor",
    imageUrl: "https://webimg.praktiker.hu/_upload/images/praktiker_catalog/299246/299246_01_asztal-gyerekmonoblock-kids-table.png?version=9f7877db",
    priceMin: "69",
    priceMax: "89",
    category: "parenting",
    badge: "👶",
    name: { en: "Keter Kids Outdoor Table and Chairs Set", ja: "ケター キッズ屋外テーブルと椅子セット" },
    description: { en: "Weather-resistant UV-stable resin kids table and chairs designed for outdoor use. Fully waterproof — can be hosed down after outdoor art and snack sessions. No assembly required.", ja: "屋外使用向けに設計された耐候性UV安定樹脂製子ども用テーブルと椅子。完全防水——屋外のアートとおやつセッション後にホースで洗い流せる。組み立て不要。" },
    links: [{ network: "amazon-us", productId: "keter-kids-table-outdoor", rawUrl: "https://www.amazon.com/s?k=Keter+Kids+Outdoor+Table+and+Chairs+Set", markets: ["US", "EU", "UK", "global"], approved: true }],
  },
] as unknown as AffiliateOffer[];
