// @ts-nocheck — fashion batch 12 offers (2026-06-13). 50 entries across 10 articles.
import type { AffiliateOffer } from "./types";

export const CATALOG_BATCH12_FASHION: AffiliateOffer[] = [
  // --- best-mens-sneakers-2026 ---
  {
    id: "new-balance-990v6",
    imageUrl: "https://m.media-amazon.com/images/I/51i-emZa0rL._AC_SL1000_.jpg",
    priceMin: "185",
    priceMax: "200",
    category: "fashion",
    badge: "👗",
    name: { en: "New Balance 990v6", ja: "ニューバランス 990v6" },
    description: {
      en: "MADE IN USA running-heritage sneaker with ENCAP midsole technology and pigskin/mesh upper. Available in multiple colorways including the iconic grey.",
      ja: "ENCAMミッドソール技術とピッグスキン・メッシュアッパーを採用したMADE IN USA ランニングヘリテージスニーカー。アイコニックなグレーを含む複数のカラーウェイで展開。",
    },
    links: [{ network: "direct", productId: "https://www.newbalance.com/pd/made-in-usa-990v6/M990V6-26722.html", markets: ["global"], approved: true }],
  },
  {
    id: "adidas-samba-og",
    imageUrl: "https://m.media-amazon.com/images/I/61wYbVMG+-L._AC_SL1500_.jpg",
    priceMin: "100",
    priceMax: "110",
    category: "fashion",
    badge: "👗",
    name: { en: "Adidas Samba OG", ja: "アディダス サンバ OG" },
    description: {
      en: "Classic 1950s football training shoe revived as a lifestyle icon. Leather upper with gum sole, low-profile silhouette suitable for almost any outfit.",
      ja: "1950年代のフットボールトレーニングシューズがライフスタイルアイコンとして復活。レザーアッパーとガムソール、ほぼどんなコーデにも合うロープロファイルシルエット。",
    },
    links: [{ network: "direct", productId: "https://www.adidas.com/us/samba-og-shoes/B75806.html", markets: ["global"], approved: true }],
  },
  {
    id: "nike-air-max-90",
    imageUrl: "https://m.media-amazon.com/images/I/61jns0L2RUL._AC_UY625_.jpg",
    priceMin: "110",
    priceMax: "130",
    category: "fashion",
    badge: "👗",
    name: { en: "Nike Air Max 90", ja: "ナイキ エアマックス 90" },
    description: {
      en: "Iconic 1990 running-inspired sneaker with visible heel Air unit. Mesh and leather upper in classic colorblocked design, waffle rubber outsole.",
      ja: "ビジブルヒールエアユニットを備えた1990年のアイコニックなランニングインスパイアードスニーカー。クラシックなカラーブロックデザインのメッシュ・レザーアッパーとワッフルラバーアウトソール。",
    },
    links: [{ network: "direct", productId: "https://www.nike.com/t/air-max-90-mens-shoes-6n3vKB", markets: ["global"], approved: true }],
  },
  {
    id: "asics-gel-1130",
    imageUrl: "https://m.media-amazon.com/images/I/61FaMBWaTwL._AC_SL1425_.jpg",
    priceMin: "80",
    priceMax: "95",
    category: "fashion",
    badge: "👗",
    name: { en: "Asics Gel-1130", ja: "アシックス ゲル-1130" },
    description: {
      en: "Retro running-inspired sneaker with GEL cushioning in heel and forefoot. Breathable mesh upper with leather overlays in bold chunky silhouette.",
      ja: "ヒールとフォアフットにGELクッションを備えたレトロランニングインスパイアードスニーカー。大胆なチャンキーシルエットに通気性メッシュアッパーとレザーオーバーレイ。",
    },
    links: [{ network: "direct", productId: "https://www.asics.com/us/en-us/gel-1130/p/1201A255-100.html", markets: ["global"], approved: true }],
  },
  {
    id: "vans-old-skool-36-dx",
    imageUrl: "https://media.sivasdescalzo.com/media/catalog/product/V/N/VN0A54F3103_sivasdescalzo-Vans-UA_OLD_SKOOL_36_DX-1633358504-2.jpg?quality=70&auto=webp&fit=bounds&width=950",
    priceMin: "75",
    priceMax: "90",
    category: "fashion",
    badge: "👗",
    name: { en: "Vans Old Skool 36 DX (Anaheim Factory)", ja: "バンズ オールドスクール 36 DX（アナハイムファクトリー）" },
    description: {
      en: "Premium recreation of the original 1976 Old Skool specs. OG waffle sole pattern, narrow toe box, canvas/suede upper with iconic sidestripe.",
      ja: "1976年のオリジナルオールドスクール仕様のプレミアム復刻版。OGワッフルソールパターン、狭いトゥボックス、アイコニックなサイドストライプ付きキャンバス・スエードアッパー。",
    },
    links: [{ network: "direct", productId: "https://www.vans.com/en-us/shoes-c00081/old-skool-36-dx-anaheim-factory-pvn0a38g2upj", markets: ["global"], approved: true }],
  },

  // --- best-womens-sneakers-2026 ---
  {
    id: "new-balance-574-womens",
    imageUrl: "https://m.media-amazon.com/images/I/81BrWsS1eTL._AC_UL1500_.jpg",
    priceMin: "80",
    priceMax: "90",
    category: "fashion",
    badge: "👗",
    name: { en: "New Balance 574 (Women's)", ja: "ニューバランス 574（レディース）" },
    description: {
      en: "Women's-specific last with ENCAP midsole and leather/mesh upper. 40-year heritage design in dozens of colorways from understated grey to vibrant pastels.",
      ja: "レディース専用ラストにENCAPミッドソールとレザー・メッシュアッパー。40年のヘリテージデザインを落ち着いたグレーから鮮やかなパステルまで数十のカラーウェイで展開。",
    },
    links: [{ network: "direct", productId: "https://www.newbalance.com/pd/574/WL574-25201.html", markets: ["global"], approved: true }],
  },
  {
    id: "adidas-gazelle-bold-womens",
    imageUrl: "https://m.media-amazon.com/images/I/714atv1LI2L._AC_SL1500_.jpg",
    priceMin: "100",
    priceMax: "110",
    category: "fashion",
    badge: "👗",
    name: { en: "Adidas Gazelle Bold (Women's)", ja: "アディダス ガゼル ボールド（レディース）" },
    description: {
      en: "Platform-sole evolution of the classic Gazelle. Suede upper with gum sole, elevated height adds modern proportion to the iconic silhouette.",
      ja: "クラシックなガゼルのプラットフォームソール進化版。ガムソール付きスエードアッパー、上げられた高さがアイコニックなシルエットに現代的なプロポーションを加える。",
    },
    links: [{ network: "direct", productId: "https://www.adidas.com/us/gazelle-bold-shoes/HQ6893.html", markets: ["global"], approved: true }],
  },
  {
    id: "nike-cortez-womens",
    imageUrl: "https://m.media-amazon.com/images/I/51Kq5VVpRoL._AC_SL1100_.jpg",
    priceMin: "75",
    priceMax: "85",
    category: "fashion",
    badge: "👗",
    name: { en: "Nike Cortez (Women's)", ja: "ナイキ コルテス（レディース）" },
    description: {
      en: "Nike's oldest silhouette from 1972. Leather upper in classic colorblock design with flared outsole for stability. Lightweight and highly versatile.",
      ja: "1972年からのナイキ最古のシルエット。安定性のあるフレアアウトソール付きクラシックカラーブロックデザインのレザーアッパー。軽量で高い汎用性。",
    },
    links: [{ network: "direct", productId: "https://www.nike.com/t/cortez-womens-shoes-4lXRmn", markets: ["global"], approved: true }],
  },
  {
    id: "onitsuka-tiger-mexico-66-womens",
    imageUrl: "https://images.asics.com/is/image/asics/1183B566_201_SR_RT_GLB?qlt=80&wid=350&hei=300&bgc=255,255,255&resMode=bisharp",
    priceMin: "120",
    priceMax: "135",
    category: "fashion",
    badge: "👗",
    name: { en: "Onitsuka Tiger Mexico 66 (Women's)", ja: "オニツカタイガー メキシコ66（レディース）" },
    description: {
      en: "Japanese-crafted slim low-profile sneaker with precise leather upper and iconic stripe detailing. Narrow fit for slim to medium-width feet.",
      ja: "精密なレザーアッパーとアイコニックなストライプディテールの日本製スリムロープロファイルスニーカー。細から中程度の幅の足向けナロウフィット。",
    },
    links: [{ network: "direct", productId: "https://www.onitsukatiger.com/us/en-us/mexico-66/p/D4J2L-0101.html", markets: ["global"], approved: true }],
  },
  {
    id: "converse-chuck-70-womens",
    imageUrl: "https://m.media-amazon.com/images/I/81hUHCY-i1L._AC_SL1500_.jpg",
    priceMin: "85",
    priceMax: "95",
    category: "fashion",
    badge: "👗",
    name: { en: "Converse Chuck 70 (Women's)", ja: "コンバース チャック 70（レディース）" },
    description: {
      en: "Upgraded recreation of the 1970s original with heavier canvas, better insole cushioning, and improved rubber quality throughout.",
      ja: "より重いキャンバス、優れたインソールクッション性、全体的に向上したゴム品質を備えた1970年代オリジナルのアップグレード復刻版。",
    },
    links: [{ network: "direct", productId: "https://www.converse.com/c/chuck-70", markets: ["global"], approved: true }],
  },

  // --- best-ballet-flats-2026 ---
  {
    id: "repetto-cendrillon-ballet-flat",
    imageUrl: "https://thefrench.com/wp-content/uploads/2023/08/Repetto-cendrillon-flats-IMG_1896.jpg",
    priceMin: "245",
    priceMax: "265",
    category: "fashion",
    badge: "👗",
    name: { en: "Repetto Cendrillon Ballet Flat", ja: "レペット サンドリヨン バレエフラット" },
    description: {
      en: "Handmade in France using the 'stitch and return' ballet slipper construction. Lamb leather upper with elastic gore at instep for secure fit.",
      ja: "バレエスリッパの「ステッチアンドリターン」工法でフランスで手作り。インステップのゴアエラスティック付きラムレザーアッパーで安定したフィット。",
    },
    links: [{ network: "direct", productId: "https://www.repetto.com/en-us/ballet-flats/cendrillon", markets: ["global"], approved: true }],
  },
  {
    id: "sam-edelman-felicia-flat",
    imageUrl: "https://m.media-amazon.com/images/I/51inOIxT1rL._AC_SL1500_.jpg",
    priceMin: "60",
    priceMax: "75",
    category: "fashion",
    badge: "👗",
    name: { en: "Sam Edelman Felicia Ballet Flat", ja: "サムエデルマン フェリシア バレエフラット" },
    description: {
      en: "Bestselling everyday ballet flat available in suede, leather, and fabric options across many colors. Wide-fit toe box accommodates most foot shapes.",
      ja: "多数のカラーでスエード・レザー・ファブリックオプション展開のベストセラー日常使いバレエフラット。ワイドフィットのトゥボックスがほとんどの足型に対応。",
    },
    links: [{ network: "direct", productId: "https://www.samedelman.com/collections/flats/products/felicia", markets: ["global"], approved: true }],
  },
  {
    id: "tieks-by-gavrieli-ballet-flat",
    imageUrl: "https://tieks.com/media/poppy2019_hp_slide.jpg",
    priceMin: "195",
    priceMax: "225",
    category: "fashion",
    badge: "👗",
    name: { en: "Tieks by Gavrieli Ballet Flat", ja: "ティークス by ガブリエリ バレエフラット" },
    description: {
      en: "Italian leather ballet flat with split sole and padded footbed for superior comfort. Folds completely flat for travel. Minimal break-in required.",
      ja: "優れた快適性のためのスプリットソールとパッドフットベッド付きイタリアンレザーバレエフラット。旅行のために完全にフラットに折りたたみ可能。ほぼブレイクイン不要。",
    },
    links: [{ network: "direct", productId: "https://www.tieks.com/collections/all-tieks", markets: ["global"], approved: true }],
  },
  {
    id: "madewell-the-bowed-ballet-flat",
    imageUrl: "https://www.madewell.com/images/NN901_BK5229_d4?wid=1400&hei=1779&fmt=jpeg&fit=crop&qlt=75",
    priceMin: "128",
    priceMax: "138",
    category: "fashion",
    badge: "👗",
    name: { en: "Madewell The Bowed Ballet Flat", ja: "メイドウェル ザ バウドバレエフラット" },
    description: {
      en: "Leather-lined mid-range ballet flat with flexible rubber outsole and lightly padded insole. Bow detail, slightly pointed toe, true-to-size fit.",
      ja: "フレキシブルラバーアウトソールとわずかにパッドが入ったインソール付きレザーライニングのミッドレンジバレエフラット。リボンディテール、わずかに尖ったトゥ、真サイズフィット。",
    },
    links: [{ network: "direct", productId: "https://www.madewell.com/the-bowed-ballet-flat", markets: ["global"], approved: true }],
  },
  {
    id: "amazon-essentials-ballet-flat",
    imageUrl: "https://m.media-amazon.com/images/I/71EI4a3IYsL._AC_SL1500_.jpg",
    priceMin: "25",
    priceMax: "38",
    category: "fashion",
    badge: "👗",
    name: { en: "Amazon Essentials Ballet Flat", ja: "アマゾンエッセンシャルズ バレエフラット" },
    description: {
      en: "Affordable faux-leather ballet flat in a clean silhouette. Available in wide size range including wide widths. Suitable for office and casual wear.",
      ja: "クリーンなシルエットの手頃な価格のフェイクレザーバレエフラット。ワイドサイズを含む幅広いサイズ展開。オフィスとカジュアル着用に対応。",
    },
    links: [{ network: "direct", productId: "https://www.amazon.com/s?k=amazon+essentials+women+ballet+flat", markets: ["global"], approved: true }],
  },

  // --- best-wide-leg-pants-2026 ---
  {
    id: "agolde-low-slung-baggy-jeans",
    imageUrl: "https://is4.revolveassets.com/images/p4/n/z/AGOL-WJ488_V1.jpg",
    priceMin: "198",
    priceMax: "228",
    category: "fashion",
    badge: "👗",
    name: { en: "Agolde Low-Slung Baggy Jeans", ja: "アゴルデ ロースラング バギージーンズ" },
    description: {
      en: "100% organic cotton MADE IN USA denim with low rise and wide leg. Stiff from factory and softens beautifully with wear. Distinctive low-rise proportion.",
      ja: "ローライズとワイドレッグの100%オーガニックコットンMADE IN USAデニム。工場出荷時は硬く、着用とともに美しく柔らかくなる。独特のローライズプロポーション。",
    },
    links: [{ network: "direct", productId: "https://www.agolde.com/products/low-slung-baggy", markets: ["global"], approved: true }],
  },
  {
    id: "reformation-veda-wide-leg-pant",
    imageUrl: "https://m.media-amazon.com/images/G/01/Shopbop/p/prod/products/refor/refor411681071b/refor411681071b_1701204431008_2-0._QL90_UX1128_.jpg",
    priceMin: "148",
    priceMax: "178",
    category: "fashion",
    badge: "👗",
    name: { en: "Reformation Veda Wide-Leg Pant", ja: "リフォーメーション ベダ ワイドレッグパンツ" },
    description: {
      en: "Linen and linen-blend wide-leg pant with high-rise waistband. Available in petite, regular, and tall inseams. Third-party sustainability certified.",
      ja: "ハイライズウエストバンドのリネン・リネンブレンドワイドレッグパンツ。ペティート・レギュラー・トールインシームで展開。サードパーティサステナビリティ認証。",
    },
    links: [{ network: "direct", productId: "https://www.thereformation.com/products/veda-pant", markets: ["global"], approved: true }],
  },
  {
    id: "citizens-of-humanity-paloma-wide",
    imageUrl: "https://www.mytheresa.com/media/1094/1238/100/29/P01115534_d1.jpg",
    priceMin: "238",
    priceMax: "258",
    category: "fashion",
    badge: "👗",
    name: { en: "Citizens of Humanity Paloma Wide-Leg Jeans", ja: "シチズンズオブヒューマニティ パロマ ワイドレッグジーンズ" },
    description: {
      en: "Premium structured denim wide-leg pant with high waist. Heavy denim holds shape wash after wash. Classic straight-leg quality that photographs like tailored trousers.",
      ja: "ハイウエストのプレミアム構造的デニムワイドレッグパンツ。重いデニムが何度洗っても形を保つ。テーラードトラウザーズのように写真映えするクラシックなストレートレッグ品質。",
    },
    links: [{ network: "direct", productId: "https://www.citizensofhumanity.com/products/paloma-baggy-jeans", markets: ["global"], approved: true }],
  },
  {
    id: "free-people-good-luck-wide-leg",
    imageUrl: "https://u-mercari-images.mercdn.net/photos/m64331474910_1.jpg",
    priceMin: "78",
    priceMax: "98",
    category: "fashion",
    badge: "👗",
    name: { en: "Free People Good Luck Wide-Leg Pant", ja: "フリーピープル グッドラック ワイドレッグパンツ" },
    description: {
      en: "Lightweight stretch blend wide-leg pant with hidden elastic waistband behind faux-fly front. Comfortable all-day wear, lightweight and packable for travel.",
      ja: "フォールスフライフロントの後ろに隠された伸縮性ウエストバンド付き軽量ストレッチブレンドワイドレッグパンツ。終日快適な着用感、旅行に軽量パッカブル。",
    },
    links: [{ network: "direct", productId: "https://www.freepeople.com/shop/good-luck-wide-leg-pant", markets: ["global"], approved: true }],
  },
  {
    id: "target-universal-thread-wide-leg",
    imageUrl: "https://parade.com/.image/t_share/MjA5NzI3MjQxNDc3Njk1MTQ1/target-universal-thread-high-rise-tailored-wide-leg-jeans-medium-wash.jpg",
    priceMin: "35",
    priceMax: "45",
    category: "fashion",
    badge: "👗",
    name: { en: "Target Universal Thread Wide-Leg Jeans", ja: "ターゲット ユニバーサルスレッド ワイドレッグジーンズ" },
    description: {
      en: "Budget-friendly high-rise wide-leg denim in multiple washes. Flat waistband sits well on most body types. Remarkable quality-to-price ratio.",
      ja: "複数のウォッシュ展開のバジェット向けハイライズワイドレッグデニム。フラットウエストバンドがほとんどの体型にうまく座る。驚くほどの価格対品質比。",
    },
    links: [{ network: "direct", productId: "https://www.target.com/s?searchTerm=universal+thread+wide+leg+jeans", markets: ["global"], approved: true }],
  },

  // --- best-linen-shirt-2026 ---
  {
    id: "officine-generale-linen-shirt",
    imageUrl: "https://cdn.clothbase.com/uploads/535f07e8-864d-4034-bebe-71ed232c12f0/image.jpg",
    priceMin: "200",
    priceMax: "280",
    category: "fashion",
    badge: "👗",
    name: { en: "Officine Generale Linen Shirt", ja: "オフィシーヌジェネラル リネンシャツ" },
    description: {
      en: "Heavy French Norman linen shirt with relaxed fit, dropped shoulders, corozo buttons, French seams, and side vents. Made in France.",
      ja: "リラックスフィット、ドロップショルダー、コロゾボタン、フレンチシーム、サイドベント付きの重いフランスノルマンディーリネンシャツ。フランス製。",
    },
    links: [{ network: "direct", productId: "https://www.officine-generale.com/en-us/shirts", markets: ["global"], approved: true }],
  },
  {
    id: "uniqlo-premium-linen-shirt",
    imageUrl: "https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/404406/item/goods_66_404406.jpg?width=2000",
    priceMin: "49",
    priceMax: "59",
    category: "fashion",
    badge: "👗",
    name: { en: "Uniqlo Premium Linen Shirt", ja: "ユニクロ プレミアムリネンシャツ" },
    description: {
      en: "Japanese-mill medium-weight linen shirt in relaxed regular fit. Excellent color retention through multiple washes. Best value in this category.",
      ja: "リラックスしたレギュラーフィットの日本製中重量リネンシャツ。複数回の洗濯後も優れた発色保持。このカテゴリーで最高のコスパ。",
    },
    links: [{ network: "direct", productId: "https://www.uniqlo.com/us/en/men/shirts/linen", markets: ["global"], approved: true }],
  },
  {
    id: "everlane-relaxed-linen-shirt",
    imageUrl: "https://media.everlane.com/image/upload/c_fill,w_3840,ar_4:5,q_auto,dpr_1.0,f_auto,fl_progressive:steep/i/f0a262be_eb9d",
    priceMin: "88",
    priceMax: "108",
    category: "fashion",
    badge: "👗",
    name: { en: "Everlane Relaxed Linen Shirt", ja: "エバーレーン リラックスリネンシャツ" },
    description: {
      en: "Deliberately boxy-cut linen shirt with dropped shoulders and earthtone colorway range. Designed for the oversized aesthetic with clean hem for untucked wear.",
      ja: "ドロップショルダーとアーシートーンカラーレンジの意図的にボクシーカットのリネンシャツ。アンタック着用向けクリーンヘム付きオーバーサイズ美学のために設計。",
    },
    links: [{ network: "direct", productId: "https://www.everlane.com/products/mens-relaxed-linen-shirt", markets: ["global"], approved: true }],
  },
  {
    id: "buck-mason-washed-linen-shirt",
    imageUrl: "https://cdn.shopify.com/s/files/1/0123/5065/2473/files/BW13323.663FSD_CROSSHATCH_LINEN_ARTIST_SHIRT_FLAXSEED.jpg?v=1714585610",
    priceMin: "138",
    priceMax: "148",
    category: "fashion",
    badge: "👗",
    name: { en: "Buck Mason Washed Linen Shirt", ja: "バックメイソン ウォッシュドリネンシャツ" },
    description: {
      en: "Pre-washed linen shirt that feels broken-in from first wear. Available in Cuban collar and button-down. Slightly slimmer cut than most linen shirts.",
      ja: "初回着用から着込んだような感触の事前ウォッシュリネンシャツ。キューバンカラーとボタンダウンで展開。ほとんどのリネンシャツよりわずかにスリムなカット。",
    },
    links: [{ network: "direct", productId: "https://www.buckmason.com/products/washed-linen-shirt", markets: ["global"], approved: true }],
  },
  {
    id: "h-and-m-linen-shirt",
    imageUrl: "https://image.hm.com/assets/hm/ed/77/ed7769953b45eae9248ed180990de4e8ce495097.jpg?imwidth=2160",
    priceMin: "25",
    priceMax: "35",
    category: "fashion",
    badge: "👗",
    name: { en: "H&M Linen Shirt", ja: "H&M リネンシャツ" },
    description: {
      en: "Budget-friendly lightweight linen shirt in basic cut. Clean collar and hem construction. Available in stores globally for easy in-person fit-testing.",
      ja: "ベーシックカットの手頃な価格の軽量リネンシャツ。きれいな襟と裾の構造。グローバルに実店舗で販売され試着が容易。",
    },
    links: [{ network: "direct", productId: "https://www2.hm.com/en_us/men/shop-by-product/shirts/linen.html", markets: ["global"], approved: true }],
  },

  // --- best-bomber-jacket-2026 ---
  {
    id: "alpha-industries-ma-1-bomber",
    imageUrl: "https://m.media-amazon.com/images/I/612KWDDIdaL._AC_SL1500_.jpg",
    priceMin: "150",
    priceMax: "185",
    category: "fashion",
    badge: "👗",
    name: { en: "Alpha Industries MA-1 Bomber Jacket", ja: "アルファインダストリーズ MA-1 ボンバージャケット" },
    description: {
      en: "Original military-spec nylon bomber with reversible orange lining. Tight rib-knit trim that holds shape for years. Available in sage green, black, and many other colorways.",
      ja: "リバーシブルオレンジ裏地付きオリジナルミリタリースペックナイロンボンバー。何年もシェイプを保つきつめのリブニットトリム。セージグリーン、ブラック、その他多数のカラーウェイで展開。",
    },
    links: [{ network: "direct", productId: "https://www.alphaindustries.com/products/ma-1-flight-jacket", markets: ["global"], approved: true }],
  },
  {
    id: "acne-studios-mihara-bomber",
    imageUrl: "https://www.acnestudios.com/dw/image/v2/AAXV_PRD/on/demandware.static/-/Sites-acne-product-catalog/default/dw7b9e1be5/images/B9/B90864-/2000x/B90864-900_C.jpg?sw=560&sh=840",
    priceMin: "700",
    priceMax: "900",
    category: "fashion",
    badge: "👗",
    name: { en: "Acne Studios Mihara Bomber Jacket", ja: "アクネスタジオ ミハラ ボンバージャケット" },
    description: {
      en: "Fashion-forward satin bomber with exaggerated proportions in collaboration with Japanese designer. Subtle sheen, premium construction that maintains form across seasons.",
      ja: "日本人デザイナーとのコラボによる誇張されたプロポーションのファッション前衛的サテンボンバー。微妙な光沢、シーズンを超えてフォームを維持するプレミアム構造。",
    },
    links: [{ network: "direct", productId: "https://www.acnestudios.com/us/en/bomber-jackets", markets: ["global"], approved: true }],
  },
  {
    id: "topman-satin-bomber-jacket",
    imageUrl: "https://di2ponv0v5otw.cloudfront.net/posts/2024/02/05/65c1d29f97b5d089f085bbc8/m_65c1d2bd1645f7075779eef3.jpg",
    priceMin: "80",
    priceMax: "105",
    category: "fashion",
    badge: "👗",
    name: { en: "Topman Satin Bomber Jacket", ja: "トップマン サテンボンバージャケット" },
    description: {
      en: "Fashion-forward satin bomber at a mid-range price. Available in black, burgundy, and seasonal colors. Decent rib-knit quality for the price point.",
      ja: "中価格帯のファッション前衛的サテンボンバー。ブラック、バーガンディー、シーズナルカラーで展開。この価格帯では良好なリブニット品質。",
    },
    links: [{ network: "direct", productId: "https://www.topman.com/en/tmuk/category/jackets-coats-3428165/bomber-jackets", markets: ["global"], approved: true }],
  },
  {
    id: "levi-bomber-jacket-cotton",
    imageUrl: "https://images-na.ssl-images-amazon.com/images/I/917DNl8%2B45L._AC_UX425_.jpg",
    priceMin: "110",
    priceMax: "130",
    category: "fashion",
    badge: "👗",
    name: { en: "Levi's Cotton Twill Bomber Jacket", ja: "リーバイス コットンツイル ボンバージャケット" },
    description: {
      en: "Versatile cotton twill bomber that works across casual and smart-casual contexts. Subtle Levi's branding, relaxed non-oversized cut.",
      ja: "カジュアルとスマートカジュアル両方に対応する汎用性の高いコットンツイルボンバー。控えめなリーバイスブランディング、オーバーサイズでないリラックスカット。",
    },
    links: [{ network: "direct", productId: "https://www.levi.com/US/en_US/clothing/men/outerwear/bomber-jackets", markets: ["global"], approved: true }],
  },
  {
    id: "zara-bomber-jacket-basic",
    imageUrl: "http://garmisland.com/cdn/shop/products/image_5606602a-0fb6-4315-a84d-8c5a95110388.jpg?v=1668271428",
    priceMin: "50",
    priceMax: "70",
    category: "fashion",
    badge: "👗",
    name: { en: "Zara Basic Bomber Jacket", ja: "ザラ ベーシックボンバージャケット" },
    description: {
      en: "Budget fast-fashion bomber in current-season proportions. Polyester shell with minimal water resistance. Best for casual seasonal wear without longevity expectations.",
      ja: "現行シーズンのプロポーションの手頃なファストファッションボンバー。最小限の耐水性のポリエステルシェル。耐久性を期待しないカジュアルなシーズナル着用に最適。",
    },
    links: [{ network: "direct", productId: "https://www.zara.com/us/en/man-jackets-bomber-l855.html", markets: ["global"], approved: true }],
  },

  // --- best-maxi-dress-2026 ---
  {
    id: "reformation-linen-maxi-dress",
    imageUrl: "https://cdn.saksfifthavenue.com/is/image/saks/0400022860985_SERENITY_A2?wid=600&hei=800&qlt=90&resMode=sharp2&op_usm=0.9%2C1.0%2C8%2C0",
    priceMin: "198",
    priceMax: "278",
    category: "fashion",
    badge: "👗",
    name: { en: "Reformation Linen Maxi Dress", ja: "リフォーメーション リネンマキシドレス" },
    description: {
      en: "Medium-weight linen maxi dress with adjustable straps and true-to-size fit. Opaque, drapes without clinging. Third-party certified sustainable production.",
      ja: "調整可能なストラップと真サイズフィットの中重量リネンマキシドレス。不透明で密着せずドレープ。サードパーティ認証の持続可能な生産。",
    },
    links: [{ network: "direct", productId: "https://www.thereformation.com/categories/dresses/maxi-dresses", markets: ["global"], approved: true }],
  },
  {
    id: "free-people-fp-one-maxi",
    imageUrl: "https://images.urbndata.com/is/image/FreePeople/97252704_040_a/?$a15-pdp-detail-shot$&fit=constrain&qlt=80&wid=640",
    priceMin: "128",
    priceMax: "158",
    category: "fashion",
    badge: "👗",
    name: { en: "Free People FP One Maxi Dress", ja: "フリーピープル FP One マキシドレス" },
    description: {
      en: "Romantic lightweight maxi with considered prints. Smocked or elasticated top options stay in place all day. Beautiful drape and movement in photos.",
      ja: "考えられたプリントのロマンティックな軽量マキシ。スモックドまたはエラスティケイテッドトップオプションが一日中位置を保つ。写真での美しいドレープと動き。",
    },
    links: [{ network: "direct", productId: "https://www.freepeople.com/shop/fp-one-maxi-dress", markets: ["global"], approved: true }],
  },
  {
    id: "anthropologie-lenora-maxi",
    imageUrl: "https://images.urbndata.com/is/image/Anthropologie/4130211620047_031_b?$a15-pdp-detail-shot$&fit=constrain&qlt=80&wid=640",
    priceMin: "148",
    priceMax: "188",
    category: "fashion",
    badge: "👗",
    name: { en: "Anthropologie Lenora Maxi Dress", ja: "アンソロポロジー レノラ マキシドレス" },
    description: {
      en: "Consistently top-reviewed Anthropologie maxi with best-in-class print selection. V-neck, woven cotton or linen-blend fabric, seasonally updated colorways.",
      ja: "最高のプリント選択肢を持つアンソロポロジーで継続的に高評価のマキシ。Vネック、ウーブンコットンまたはリネンブレンド生地、シーズナルに更新されるカラーウェイ。",
    },
    links: [{ network: "direct", productId: "https://www.anthropologie.com/search?q=lenora+maxi+dress", markets: ["global"], approved: true }],
  },
  {
    id: "madewell-lucie-maxi-dress",
    imageUrl: "https://di2ponv0v5otw.cloudfront.net/posts/2023/01/18/63c8605fbd66cdc7dcafc9d3/m_63c8605fbd66cdc7dcafc9d4.jpg",
    priceMin: "128",
    priceMax: "148",
    category: "fashion",
    badge: "👗",
    name: { en: "Madewell Lucie Maxi Dress", ja: "メイドウェル ルーシー マキシドレス" },
    description: {
      en: "Jersey knit maxi dress with clean lines and forgiving stretch. Machine washable with good color retention. Works for casual to slightly dressed-up contexts.",
      ja: "クリーンなラインとフォルギビングなストレッチのジャージーニットマキシドレス。機械洗い可能で優れた発色保持。カジュアルからやや上品なシーンまで対応。",
    },
    links: [{ network: "direct", productId: "https://www.madewell.com/lucie-maxi-dress", markets: ["global"], approved: true }],
  },
  {
    id: "amazon-daily-ritual-maxi-dress",
    imageUrl: "https://m.media-amazon.com/images/I/71WQ4B6s49L._AC_UL1500_.jpg",
    priceMin: "30",
    priceMax: "42",
    category: "fashion",
    badge: "👗",
    name: { en: "Amazon Daily Ritual Maxi Dress", ja: "アマゾン デイリーリチュアル マキシドレス" },
    description: {
      en: "Affordable soft jersey maxi in clean cut. Washes well without losing shape. Available in wide size range including plus sizes for casual and beach wear.",
      ja: "クリーンなカットの手頃な価格の柔らかいジャージーマキシ。洗濯後も形を保つ。カジュアルとビーチ着用向けにプラスサイズを含む幅広いサイズ展開。",
    },
    links: [{ network: "direct", productId: "https://www.amazon.com/s?k=daily+ritual+maxi+dress", markets: ["global"], approved: true }],
  },

  // --- best-wrap-dress-2026 ---
  {
    id: "diane-von-furstenberg-julian-wrap",
    imageUrl: "https://m.media-amazon.com/images/I/81ociEfRPuL._AC_SL1500_.jpg",
    priceMin: "350",
    priceMax: "498",
    category: "fashion",
    badge: "👗",
    name: { en: "Diane von Furstenberg Julian Wrap Dress", ja: "ダイアン・フォン・ファステンバーグ ジュリアン ラップドレス" },
    description: {
      en: "The original wrap dress design, refined over 50 years. Matte jersey fabric, secure sash closure, prints designed specifically for the wrap silhouette.",
      ja: "50年かけて洗練されたオリジナルのラップドレスデザイン。マットジャージー生地、安全なサッシュクロージャー、ラップシルエット専用に設計されたプリント。",
    },
    links: [{ network: "direct", productId: "https://www.dvf.com/collections/wrap-dresses", markets: ["global"], approved: true }],
  },
  {
    id: "faithfull-the-brand-wrap-dress",
    imageUrl: "https://is4.revolveassets.com/images/p4/n/z/FAIB-WD179_V1.jpg",
    priceMin: "165",
    priceMax: "220",
    category: "fashion",
    badge: "👗",
    name: { en: "Faithfull the Brand Wrap Dress", ja: "フェイスフルザブランド ラップドレス" },
    description: {
      en: "Lightweight woven wrap dress with resort-forward prints in Mediterranean aesthetic. Machine washable, generous waist sizing for the wrap's adjustability.",
      ja: "地中海的美学のリゾート前衛的プリントの軽量ウーブンラップドレス。機械洗い可能、ラップの調整可能性に対応するジェネラスなウエストサイジング。",
    },
    links: [{ network: "direct", productId: "https://www.faithfullthebrand.com/collections/dresses/wrap", markets: ["global"], approved: true }],
  },
  {
    id: "revolve-astr-wrap-dress",
    imageUrl: "https://is4.revolveassets.com/images/p4/n/uv/ASTR-WD722_V1.jpg",
    priceMin: "98",
    priceMax: "148",
    category: "fashion",
    badge: "👗",
    name: { en: "ASTR the Label Wrap Dress (via Revolve)", ja: "ASTRザレーベル ラップドレス（レボルブ経由）" },
    description: {
      en: "Fashion-forward matte crepe wrap dress with inner waist snap for security. Current prints at mid-range price. Available via Revolve and direct.",
      ja: "安定性のための内側ウエストスナップ付きファッション前衛的マットクレープラップドレス。中価格帯で現代的なプリント。レボルブと直販で入手可能。",
    },
    links: [{ network: "direct", productId: "https://www.revolveclothing.com/astr-the-label/br/2a7d4a/", markets: ["global"], approved: true }],
  },
  {
    id: "banana-republic-wrap-midi-dress",
    imageUrl: "https://bananarepublicfactory.gapfactory.com/webcontent/0027/816/421/cn27816421.jpg",
    priceMin: "130",
    priceMax: "180",
    category: "fashion",
    badge: "👗",
    name: { en: "Banana Republic Wrap Midi Dress", ja: "バナナリパブリック ラップミディドレス" },
    description: {
      en: "Office-appropriate wrap midi in stretch crepe or ponte. Shallow V-neck, below-knee length, professional neutral colorways. Machine washable in most SKUs.",
      ja: "ストレッチクレープまたはポンテのオフィス向けラップミディ。浅いVネック、膝下丈、プロフェッショナルなニュートラルカラーウェイ。ほとんどのSKUで機械洗い可能。",
    },
    links: [{ network: "direct", productId: "https://bananarepublic.gap.com/browse/category.do?cid=5049", markets: ["global"], approved: true }],
  },
  {
    id: "asos-design-wrap-midi-dress",
    imageUrl: "https://images.asos-media.com/products/asos-design-wrap-tux-midi-dress-with-shoulder-pads-in-black/204176533-1-black?$n_640w$&wid=513&fit=constrain",
    priceMin: "40",
    priceMax: "60",
    category: "fashion",
    badge: "👗",
    name: { en: "ASOS Design Wrap Midi Dress", ja: "ASOSデザイン ラップミディドレス" },
    description: {
      en: "Budget wrap midi with extensive size options including tall, petite, and plus. Regular new print releases. Add a waist snap for improved closure security.",
      ja: "トール・ペティート・プラスを含む広範なサイズオプションのバジェットラップミディ。定期的な新プリントリリース。クロージャー安定性向上のためにウエストスナップを追加することを推奨。",
    },
    links: [{ network: "direct", productId: "https://www.asos.com/women/dresses/wrap-dresses/", markets: ["global"], approved: true }],
  },

  // --- best-baseball-cap-2026 ---
  {
    id: "new-era-9forty-adjustable-cap",
    imageUrl: "https://m.media-amazon.com/images/I/71qnRojld6L._AC_SL1500_.jpg",
    priceMin: "28",
    priceMax: "38",
    category: "fashion",
    badge: "👗",
    name: { en: "New Era 9FORTY Adjustable Cap", ja: "ニューエラ 9FORTY アジャスタブルキャップ" },
    description: {
      en: "Low-profile structured crown with adjustable snap closure. Terry cotton sweatband, tight rib-knit, available in virtually any colorway or team logo.",
      ja: "調整可能なスナップクロージャー付きロープロファイル構造化クラウン。テリーコットンスウェットバンド、引き締まったリブニット、ほぼすべてのカラーウェイやチームロゴで入手可能。",
    },
    links: [{ network: "direct", productId: "https://www.neweracap.com/collections/9forty", markets: ["global"], approved: true }],
  },
  {
    id: "carhartt-wip-backley-cap",
    imageUrl: "https://m.media-amazon.com/images/I/61ZA6f7D-iL._AC_SL1200_.jpg",
    priceMin: "35",
    priceMax: "45",
    category: "fashion",
    badge: "👗",
    name: { en: "Carhartt WIP Backley Cap", ja: "カーハートWIP バックレーキャップ" },
    description: {
      en: "Unstructured cotton canvas cap with metal strap closure and minimal Carhartt C logo. Seasonal colorways that consistently make sense for fashion-forward wardrobes.",
      ja: "金属ストラップクロージャーと最小限のカーハートCロゴ付きアンストラクチャードコットンキャンバスキャップ。ファッション前衛的なワードローブに一貫して合うシーズナルカラーウェイ。",
    },
    links: [{ network: "direct", productId: "https://www.carhartt-wip.com/en/accessories/headwear", markets: ["global"], approved: true }],
  },
  {
    id: "nike-dri-fit-swoosh-cap",
    imageUrl: "https://m.media-amazon.com/images/I/71ztbxtLMgL._AC_SL1500_.jpg",
    priceMin: "25",
    priceMax: "32",
    category: "fashion",
    badge: "👗",
    name: { en: "Nike Dri-FIT Swoosh Cap", ja: "ナイキ ドライフィット スウッシュキャップ" },
    description: {
      en: "Performance-focused cap with Dri-FIT moisture-wicking fabric and ventilated structured crown. Curved brim for sun protection. Best for athletic use.",
      ja: "ドライフィット吸汗素材と通気性のある構造化クラウンのパフォーマンス重視キャップ。日焼け防止用カーブブリム。アスレチック使用に最適。",
    },
    links: [{ network: "direct", productId: "https://www.nike.com/t/dri-fit-swoosh-cap", markets: ["global"], approved: true }],
  },
  {
    id: "polo-ralph-lauren-classic-cap",
    imageUrl: "https://m.media-amazon.com/images/I/615YA7V5CeL._AC_UL1500_.jpg",
    priceMin: "40",
    priceMax: "60",
    category: "fashion",
    badge: "👗",
    name: { en: "Polo Ralph Lauren Classic Cap", ja: "ポロラルフローレン クラシックキャップ" },
    description: {
      en: "Wool-blend or chino twill structured cap with strapback closure and Polo Pony logo. Works across casual and smart-casual contexts.",
      ja: "ストラップバッククロージャーとポロポニーロゴ付きウールブレンドまたはチノツイル構造化キャップ。カジュアルとスマートカジュアル両方に対応。",
    },
    links: [{ network: "direct", productId: "https://www.ralphlauren.com/accessories/hats/", markets: ["global"], approved: true }],
  },
  {
    id: "flexfit-110-pro-formance-cap",
    imageUrl: "https://m.media-amazon.com/images/I/71y5FplxEtL._AC_SL1500_.jpg",
    priceMin: "18",
    priceMax: "28",
    category: "fashion",
    badge: "👗",
    name: { en: "Flexfit 110 Pro-Formance Cap", ja: "フレックスフィット 110 プロフォーマンスキャップ" },
    description: {
      en: "Structured crown with snapback closure and athletic mesh panels for ventilation. Available blank for custom embroidery. Very low price for the construction quality.",
      ja: "通気性のためのアスレチックメッシュパネルとスナップバッククロージャー付き構造化クラウン。カスタム刺繍用のブランクで入手可能。構造品質に対して非常に低い価格。",
    },
    links: [{ network: "direct", productId: "https://www.flexfit.com/products/110-cool-and-dry-pro-formance-cap", markets: ["global"], approved: true }],
  },

  // --- best-hoop-earrings-2026 ---
  {
    id: "mejuri-bold-hoops-14k",
    imageUrl: "https://cdn.shopify.com/s/files/1/0631/8568/2616/files/0-NEWYEARESSENTIALSREFRESH-PaveDiamondBoldSmallHoops15mm-14K-Angled_053.jpg?v=1722952099",
    priceMin: "148",
    priceMax: "248",
    category: "fashion",
    badge: "👗",
    name: { en: "Mejuri Bold Hoops 14k Gold", ja: "メジュリ ボールドフープス 14kゴールド" },
    description: {
      en: "Solid 14k gold hoop earrings with hinged clicker closure and smooth interior finish. Available in 20mm and 30mm diameter. No plating — indefinite lifespan with care.",
      ja: "ヒンジドクリッカークロージャーと滑らかな内側仕上げのソリッド14kゴールドフープイヤリング。20mmと30mm径で展開。メッキなし——手入れ次第で無限の寿命。",
    },
    links: [{ network: "direct", productId: "https://mejuri.com/shop/products/bold-hoops-14k-yellow-gold", markets: ["global"], approved: true }],
  },
  {
    id: "gorjana-power-gemstone-hoops",
    imageUrl: "https://images.bloomingdalesassets.com/is/image/BLM/products/7/optimized/10822857_fpx.tif?op_sharpen=1&wid=700&fit=fit,1&$filtersm$",
    priceMin: "58",
    priceMax: "88",
    category: "fashion",
    badge: "👗",
    name: { en: "Gorjana Power Gemstone Hoop Earrings", ja: "ゴルジャーナ パワージェムストーン フープイヤリング" },
    description: {
      en: "18k gold-plated brass hoops with genuine semi-precious stone settings (amethyst, labradorite, turquoise). Thicker plating than standard fashion jewelry.",
      ja: "本物の半貴石（アメジスト、ラブラドライト、ターコイズ）セッティング付き18kゴールドメッキブラスフープ。標準的なファッションジュエリーより厚いメッキ。",
    },
    links: [{ network: "direct", productId: "https://gorjana.com/collections/hoops", markets: ["global"], approved: true }],
  },
  {
    id: "pandora-sterling-hoop-earrings",
    imageUrl: "https://images-na.ssl-images-amazon.com/images/I/71cJQkHF1FL._AC_UL1500_.jpg",
    priceMin: "55",
    priceMax: "85",
    category: "fashion",
    badge: "👗",
    name: { en: "Pandora Sterling Hoop Earrings", ja: "パンドラ スターリング フープイヤリング" },
    description: {
      en: "Recycled sterling silver hoops with hollow-tube construction for lightweight comfort. Globally available with clear returns policy. Hypoallergenic base metal.",
      ja: "軽量な快適さのための中空チューブ構造のリサイクルスターリングシルバーフープ。明確な返品ポリシーでグローバルに入手可能。低アレルギー性ベースメタル。",
    },
    links: [{ network: "direct", productId: "https://us.pandora.net/en/jewelry/earrings/hoop-earrings/", markets: ["global"], approved: true }],
  },
  {
    id: "missoma-gold-vermeil-hoops",
    imageUrl: "https://us.missoma.com/cdn/shop/products/mini-tidal-hoop-earrings-18ct-gold-plated-vermeil-earrings-missoma-631971.jpg?v=1697465984",
    priceMin: "78",
    priceMax: "128",
    category: "fashion",
    badge: "👗",
    name: { en: "Missoma Gold Vermeil Hoop Earrings", ja: "ミソマ ゴールドヴェルメイル フープイヤリング" },
    description: {
      en: "18k gold vermeil over sterling silver hoops with editorial design details (hammered texture, chain detailing). Hinged clicker closure on key styles.",
      ja: "エディトリアルなデザインディテール（ハンマードテクスチャー、チェーンディテール）付きスターリングシルバー上の18kゴールドヴェルメイルフープ。主要スタイルにヒンジドクリッカークロージャー。",
    },
    links: [{ network: "direct", productId: "https://www.missoma.com/collections/hoops", markets: ["global"], approved: true }],
  },
  {
    id: "baublebar-pisa-hoop-earrings",
    imageUrl: "https://product-images.thecoolhour.com/images/unscaled/baublebar_baublebar_pisa_layered_hoop_earrings.jpg",
    priceMin: "28",
    priceMax: "48",
    category: "fashion",
    badge: "👗",
    name: { en: "BaubleBar Pisa Hoop Earrings", ja: "バウブルバー ピサ フープイヤリング" },
    description: {
      en: "14k gold-plated hoop earrings in 20mm, 30mm, and 40mm options. Clicker closure mechanism at an accessible price point. Best for occasional and trend-specific wear.",
      ja: "20mm、30mm、40mmオプションの14kゴールドメッキフープイヤリング。アクセシブルな価格帯でクリッカークロージャーメカニズム。偶発的なトレンド特有の着用に最適。",
    },
    links: [{ network: "direct", productId: "https://www.baublebar.com/collections/hoop-earrings", markets: ["global"], approved: true }],
  },
] as unknown as AffiliateOffer[];
