/**
 * Market-specific price overrides for catalog offers.
 * Auto-generated by scripts/fetch-prices.ts — do not edit manually.
 * Keys are offer IDs; values are market → display price strings.
 */
export const PRICES: Record<string, Partial<Record<string, string>>> = {};
