// AUTO-GENERATED (2026-06-29) — 製品スペック表の表示ラベル(多言語)。
// 値は specs-cache.json に出典付きで保持し、表示時にこのラベルでローカライズする。
// 量産AI生成の未検証specを、Web一次情報で検証した実データへ置換する厳選施策の一部。
// 翻訳ロケール: en(源) + ja/zh-CN/ko/de/es/fr/it/ru/pt-BR。未収録ロケールは en にフォールバック。
// 再生成: scratchpad/build-labels.mjs（keys-en.tsv + labels-*.tsv より）。

// 一部キーは値側に単位が無い旧データ用に単位を補う（値に既に単位があれば二重付与しない）。
export const SPEC_UNITS: Record<string, string> = {
  calories: " kcal",
  protein_g: " g",
  totalFat_g: " g",
  sugars_g: " g",
  fiber_g: " g",
  sodium_mg: " mg",
};

export const SPEC_LABELS: Record<string, Record<string, string>> = {
  "ac_adapter_included": {"en":"AC adapter included","ja":"ACアダプター付属","zh-CN":"含AC适配器","ko":"AC 어댑터 포함","de":"Netzteil enthalten","es":"Adaptador de CA incluido","fr":"Adaptateur secteur inclus","it":"Alimentatore incluso","ru":"Адаптер питания в комплекте","pt-BR":"Adaptador CA incluído"},
  "accessories": {"en":"Accessories","ja":"付属品","zh-CN":"配件","ko":"액세서리","de":"Zubehör","es":"Accesorios","fr":"Accessoires","it":"Accessori","ru":"Аксессуары","pt-BR":"Acessórios"},
  "acidity": {"en":"Acidity","ja":"酸味","zh-CN":"酸度","ko":"산도","de":"Säuregehalt","es":"Acidez","fr":"Acidité","it":"Acidità","ru":"Кислотность","pt-BR":"Acidez"},
  "acv_per_serving": {"en":"ACV per serving","ja":"1食あたりのリンゴ酢","zh-CN":"每份苹果醋","ko":"1회분당 ACV","de":"ACV pro Portion","es":"Vinagre por porción","fr":"Vinaigre par portion","it":"ACV per porzione","ru":"Яблочный уксус на порцию","pt-BR":"ACV por porção"},
  "adjustable": {"en":"Adjustable","ja":"調整可能","zh-CN":"可调节","ko":"조절 가능","de":"Verstellbar","es":"Ajustable","fr":"Réglable","it":"Regolabile","ru":"Регулируемый","pt-BR":"Ajustável"},
  "adjustable_length": {"en":"Adjustable length","ja":"長さ調整","zh-CN":"可调长度","ko":"길이 조절","de":"Verstellbare Länge","es":"Longitud ajustable","fr":"Longueur réglable","it":"Lunghezza regolabile","ru":"Регулируемая длина","pt-BR":"Comprimento ajustável"},
  "adjustable_range": {"en":"Adjustable range","ja":"調整範囲","zh-CN":"可调范围","ko":"조절 범위","de":"Verstellbereich","es":"Rango de ajuste","fr":"Plage de réglage","it":"Intervallo regolabile","ru":"Диапазон регулировки","pt-BR":"Faixa de ajuste"},
  "age_range": {"en":"Age range","ja":"対象年齢","zh-CN":"适用年龄","ko":"연령대","de":"Altersbereich","es":"Rango de edad","fr":"Tranche d'âge","it":"Fascia d'età","ru":"Возрастной диапазон","pt-BR":"Faixa etária"},
  "aged": {"en":"Aged","ja":"熟成","zh-CN":"陈酿","ko":"숙성","de":"Gereift","es":"Añejado","fr":"Vieilli","it":"Invecchiato","ru":"Выдержка","pt-BR":"Envelhecido"},
  "alcohol_free": {"en":"Alcohol free","ja":"アルコールフリー","zh-CN":"无酒精","ko":"무알코올","de":"Alkoholfrei","es":"Sin alcohol","fr":"Sans alcool","it":"Senza alcol","ru":"Без спирта","pt-BR":"Sem álcool"},
  "anc": {"en":"Active noise cancelling","ja":"アクティブノイズキャンセリング","zh-CN":"主动降噪","ko":"액티브 노이즈 캔슬링","de":"Aktive Geräuschunterdrückung","es":"Cancelación activa de ruido","fr":"Réduction active de bruit","it":"Cancellazione attiva del rumore","ru":"Активное шумоподавление","pt-BR":"Cancelamento ativo de ruído"},
  "app": {"en":"App","ja":"アプリ","zh-CN":"应用","ko":"앱","de":"App","es":"App","fr":"Application","it":"App","ru":"Приложение","pt-BR":"App"},
  "app_connected": {"en":"App connected","ja":"アプリ連携","zh-CN":"应用连接","ko":"앱 연결","de":"App-Anbindung","es":"Conexión con app","fr":"Connecté à l'app","it":"Connesso all'app","ru":"Подключение к приложению","pt-BR":"Conexão com app"},
  "app_control": {"en":"App control","ja":"アプリ操作","zh-CN":"应用控制","ko":"앱 제어","de":"App-Steuerung","es":"Control por app","fr":"Contrôle par app","it":"Controllo da app","ru":"Управление через приложение","pt-BR":"Controle por app"},
  "apy": {"en":"APY","ja":"APY","zh-CN":"年化收益率","ko":"APY","de":"APY","es":"APY","fr":"APY","it":"APY","ru":"APY","pt-BR":"APY"},
  "atm_access": {"en":"ATM access","ja":"ATM利用","zh-CN":"ATM 取款","ko":"ATM 이용","de":"Geldautomatenzugang","es":"Acceso a cajeros","fr":"Accès aux DAB","it":"Accesso ai bancomat","ru":"Доступ к банкоматам","pt-BR":"Acesso a caixas eletrônicos"},
  "attachments_compatible": {"en":"Attachments compatible","ja":"アタッチメント対応","zh-CN":"兼容配件","ko":"부착물 호환","de":"Aufsätze kompatibel","es":"Accesorios compatibles","fr":"Accessoires compatibles","it":"Accessori compatibili","ru":"Совместимые насадки","pt-BR":"Acessórios compatíveis"},
  "auto_empty": {"en":"Auto empty","ja":"自動ゴミ収集","zh-CN":"自动集尘","ko":"자동 비움","de":"Automatische Entleerung","es":"Vaciado automático","fr":"Vidage automatique","it":"Svuotamento automatico","ru":"Автоопустошение","pt-BR":"Esvaziamento automático"},
  "back_pad_positions": {"en":"Back pad positions","ja":"バックパッド位置","zh-CN":"背垫位置","ko":"등받이 위치","de":"Rückenpolster-Positionen","es":"Posiciones del respaldo","fr":"Positions du dossier","it":"Posizioni schienale","ru":"Положения спинки","pt-BR":"Posições do encosto"},
  "band_type": {"en":"Band type","ja":"バンドタイプ","zh-CN":"表带类型","ko":"밴드 유형","de":"Armbandtyp","es":"Tipo de correa","fr":"Type de bracelet","it":"Tipo di cinturino","ru":"Тип ремешка","pt-BR":"Tipo de pulseira"},
  "bands": {"en":"Bands","ja":"バンド","zh-CN":"表带","ko":"밴드","de":"Bänder","es":"Correas","fr":"Bracelets","it":"Cinturini","ru":"Ремешки","pt-BR":"Pulseiras"},
  "bar_spacing": {"en":"Bar spacing","ja":"バー間隔","zh-CN":"栏杆间距","ko":"창살 간격","de":"Stababstand","es":"Espaciado de barras","fr":"Espacement des barreaux","it":"Distanza tra le barre","ru":"Расстояние между прутьями","pt-BR":"Espaçamento das barras"},
  "base_oil": {"en":"Base oil","ja":"ベースオイル","zh-CN":"基础油","ko":"베이스 오일","de":"Basisöl","es":"Aceite base","fr":"Huile de base","it":"Olio base","ru":"Базовое масло","pt-BR":"Óleo base"},
  "battery": {"en":"Battery","ja":"バッテリー","zh-CN":"电池","ko":"배터리","de":"Akku","es":"Batería","fr":"Batterie","it":"Batteria","ru":"Аккумулятор","pt-BR":"Bateria"},
  "battery_life": {"en":"Battery life","ja":"バッテリー持続時間","zh-CN":"电池续航","ko":"배터리 수명","de":"Akkulaufzeit","es":"Duración de batería","fr":"Autonomie","it":"Durata batteria","ru":"Время работы от батареи","pt-BR":"Duração da bateria"},
  "battery_runtime": {"en":"Battery runtime","ja":"バッテリー稼働時間","zh-CN":"电池工作时间","ko":"배터리 작동 시간","de":"Akku-Betriebszeit","es":"Tiempo de funcionamiento","fr":"Autonomie de la batterie","it":"Autonomia batteria","ru":"Время работы батареи","pt-BR":"Tempo de funcionamento da bateria"},
  "bean_type": {"en":"Bean type","ja":"豆の種類","zh-CN":"豆类型","ko":"원두 종류","de":"Bohnensorte","es":"Tipo de grano","fr":"Type de grain","it":"Tipo di chicco","ru":"Тип зёрен","pt-BR":"Tipo de grão"},
  "bearing_type": {"en":"Bearing type","ja":"ベアリングタイプ","zh-CN":"轴承类型","ko":"베어링 유형","de":"Lagertyp","es":"Tipo de rodamiento","fr":"Type de roulement","it":"Tipo di cuscinetto","ru":"Тип подшипника","pt-BR":"Tipo de rolamento"},
  "blade_type": {"en":"Blade type","ja":"刃の種類","zh-CN":"刀片类型","ko":"블레이드 유형","de":"Klingentyp","es":"Tipo de cuchilla","fr":"Type de lame","it":"Tipo di lama","ru":"Тип лезвия","pt-BR":"Tipo de lâmina"},
  "bluetooth_codecs": {"en":"Bluetooth codecs","ja":"Bluetoothコーデック","zh-CN":"蓝牙编解码器","ko":"블루투스 코덱","de":"Bluetooth-Codecs","es":"Códecs Bluetooth","fr":"Codecs Bluetooth","it":"Codec Bluetooth","ru":"Bluetooth-кодеки","pt-BR":"Codecs Bluetooth"},
  "bpa_free": {"en":"BPA-free","ja":"BPAフリー","zh-CN":"不含BPA","ko":"BPA 무함유","de":"BPA-frei","es":"Sin BPA","fr":"Sans BPA","it":"Senza BPA","ru":"Без BPA","pt-BR":"Sem BPA"},
  "brew_time": {"en":"Brew time","ja":"抽出時間","zh-CN":"冲泡时间","ko":"추출 시간","de":"Brühzeit","es":"Tiempo de preparación","fr":"Temps d'infusion","it":"Tempo di preparazione","ru":"Время заваривания","pt-BR":"Tempo de preparo"},
  "brightness": {"en":"Brightness","ja":"明るさ","zh-CN":"亮度","ko":"밝기","de":"Helligkeit","es":"Brillo","fr":"Luminosité","it":"Luminosità","ru":"Яркость","pt-BR":"Brilho"},
  "bristle": {"en":"Bristle","ja":"ブリスル","zh-CN":"刷毛","ko":"브러시 모","de":"Borsten","es":"Cerdas","fr":"Poils","it":"Setole","ru":"Щетина","pt-BR":"Cerdas"},
  "build_material": {"en":"Build material","ja":"構造素材","zh-CN":"制造材料","ko":"본체 소재","de":"Material","es":"Material de construcción","fr":"Matériau de fabrication","it":"Materiale di costruzione","ru":"Материал корпуса","pt-BR":"Material de construção"},
  "c_wire_required": {"en":"C-wire required","ja":"Cワイヤー必要","zh-CN":"需要C线","ko":"C 와이어 필요","de":"C-Draht erforderlich","es":"Requiere cable C","fr":"Fil C requis","it":"Filo C richiesto","ru":"Требуется C-провод","pt-BR":"Requer fio C"},
  "cable_included": {"en":"Cable included","ja":"ケーブル付属","zh-CN":"含线缆","ko":"케이블 포함","de":"Kabel enthalten","es":"Cable incluido","fr":"Câble inclus","it":"Cavo incluso","ru":"Кабель в комплекте","pt-BR":"Cabo incluído"},
  "cable_options": {"en":"Cable options","ja":"ケーブルオプション","zh-CN":"线缆选项","ko":"케이블 옵션","de":"Kabeloptionen","es":"Opciones de cable","fr":"Options de câble","it":"Opzioni cavo","ru":"Варианты кабелей","pt-BR":"Opções de cabo"},
  "cable_type": {"en":"Cable type","ja":"ケーブルタイプ","zh-CN":"线缆类型","ko":"케이블 유형","de":"Kabeltyp","es":"Tipo de cable","fr":"Type de câble","it":"Tipo di cavo","ru":"Тип кабеля","pt-BR":"Tipo de cabo"},
  "caffeine": {"en":"Caffeine","ja":"カフェイン","zh-CN":"咖啡因","ko":"카페인","de":"Koffein","es":"Cafeína","fr":"Caféine","it":"Caffeina","ru":"Кофеин","pt-BR":"Cafeína"},
  "caffeine_per_serving": {"en":"Caffeine per serving","ja":"1食あたりのカフェイン","zh-CN":"每份咖啡因","ko":"1회분당 카페인","de":"Koffein pro Portion","es":"Cafeína por porción","fr":"Caféine par portion","it":"Caffeina per porzione","ru":"Кофеин на порцию","pt-BR":"Cafeína por porção"},
  "calories": {"en":"Calories","ja":"カロリー","zh-CN":"卡路里","ko":"칼로리","de":"Kalorien","es":"Calorías","fr":"Calories","it":"Calorie","ru":"Калории","pt-BR":"Calorias"},
  "capacity": {"en":"Capacity","ja":"容量","zh-CN":"容量","ko":"용량","de":"Kapazität","es":"Capacidad","fr":"Capacité","it":"Capacità","ru":"Объём","pt-BR":"Capacidade"},
  "capacity_l": {"en":"Capacity","ja":"容量","zh-CN":"容量","ko":"용량","de":"Kapazität","es":"Capacidad","fr":"Capacité","it":"Capacità","ru":"Объём","pt-BR":"Capacidade"},
  "carafe_type": {"en":"Carafe type","ja":"カラフェタイプ","zh-CN":"咖啡壶类型","ko":"카라페 유형","de":"Kannentyp","es":"Tipo de jarra","fr":"Type de verseuse","it":"Tipo di caraffa","ru":"Тип кофейника","pt-BR":"Tipo de jarra"},
  "carry_on_compliant": {"en":"Carry on compliant","ja":"機内持ち込み対応","zh-CN":"符合登机要求","ko":"기내 반입 가능","de":"Handgepäcktauglich","es":"Apto para equipaje de mano","fr":"Conforme bagage cabine","it":"Conforme bagaglio a mano","ru":"Подходит для ручной клади","pt-BR":"Compatível com bagagem de mão"},
  "certification": {"en":"Certification","ja":"認証","zh-CN":"认证","ko":"인증","de":"Zertifizierung","es":"Certificación","fr":"Certification","it":"Certificazione","ru":"Сертификация","pt-BR":"Certificação"},
  "certifications": {"en":"Certifications","ja":"認証","zh-CN":"认证","ko":"인증","de":"Zertifizierungen","es":"Certificaciones","fr":"Certifications","it":"Certificazioni","ru":"Сертификаты","pt-BR":"Certificações"},
  "churn_time": {"en":"Churn time","ja":"攪拌時間","zh-CN":"搅拌时间","ko":"교반 시간","de":"Rührzeit","es":"Tiempo de batido","fr":"Temps de barattage","it":"Tempo di zangolatura","ru":"Время взбивания","pt-BR":"Tempo de batimento"},
  "cleaning": {"en":"Cleaning","ja":"お手入れ","zh-CN":"清洁","ko":"세척","de":"Reinigung","es":"Limpieza","fr":"Nettoyage","it":"Pulizia","ru":"Очистка","pt-BR":"Limpeza"},
  "closure": {"en":"Closure","ja":"留め具","zh-CN":"闭合方式","ko":"여밈","de":"Verschluss","es":"Cierre","fr":"Fermeture","it":"Chiusura","ru":"Застёжка","pt-BR":"Fechamento"},
  "cocoa_percent": {"en":"Cocoa percentage","ja":"カカオ含有率","zh-CN":"可可含量","ko":"카카오 함량","de":"Kakaoanteil","es":"Porcentaje de cacao","fr":"Pourcentage de cacao","it":"Percentuale di cacao","ru":"Содержание какао","pt-BR":"Porcentagem de cacau"},
  "collar_height": {"en":"Collar height","ja":"襟の高さ","zh-CN":"领高","ko":"칼라 높이","de":"Kragenhöhe","es":"Altura del cuello","fr":"Hauteur du col","it":"Altezza del collo","ru":"Высота воротника","pt-BR":"Altura da gola"},
  "connectivity": {"en":"Connectivity","ja":"接続","zh-CN":"连接","ko":"연결","de":"Konnektivität","es":"Conectividad","fr":"Connectivité","it":"Connettività","ru":"Подключение","pt-BR":"Conectividade"},
  "contaminants_reduced": {"en":"Contaminants reduced","ja":"除去される汚染物質","zh-CN":"可去除污染物","ko":"제거되는 오염물질","de":"Reduzierte Schadstoffe","es":"Contaminantes reducidos","fr":"Contaminants réduits","it":"Contaminanti ridotti","ru":"Удаляемые загрязнения","pt-BR":"Contaminantes reduzidos"},
  "cooking_area": {"en":"Cooking area","ja":"調理面積","zh-CN":"烹饪面积","ko":"조리 면적","de":"Grillfläche","es":"Área de cocción","fr":"Surface de cuisson","it":"Area di cottura","ru":"Площадь готовки","pt-BR":"Área de cozimento"},
  "cooling_capacity": {"en":"Cooling capacity","ja":"冷却能力","zh-CN":"制冷能力","ko":"냉각 용량","de":"Kühlleistung","es":"Capacidad de enfriamiento","fr":"Capacité de refroidissement","it":"Capacità di raffreddamento","ru":"Мощность охлаждения","pt-BR":"Capacidade de resfriamento"},
  "cooling_features": {"en":"Cooling features","ja":"冷却機能","zh-CN":"冷却功能","ko":"냉각 기능","de":"Kühlfunktionen","es":"Funciones de enfriamiento","fr":"Fonctions de refroidissement","it":"Funzioni di raffreddamento","ru":"Функции охлаждения","pt-BR":"Recursos de resfriamento"},
  "cordless": {"en":"Cordless","ja":"コードレス","zh-CN":"无线","ko":"무선","de":"Kabellos","es":"Inalámbrico","fr":"Sans fil","it":"Senza filo","ru":"Беспроводной","pt-BR":"Sem fio"},
  "count": {"en":"Count","ja":"個数","zh-CN":"数量","ko":"개수","de":"Anzahl","es":"Cantidad","fr":"Quantité","it":"Quantità","ru":"Количество","pt-BR":"Quantidade"},
  "coverage_area": {"en":"Coverage area","ja":"カバー範囲","zh-CN":"覆盖范围","ko":"커버리지 범위","de":"Abdeckungsbereich","es":"Área de cobertura","fr":"Zone de couverture","it":"Area di copertura","ru":"Зона покрытия","pt-BR":"Área de cobertura"},
  "cruelty_free": {"en":"Cruelty free","ja":"動物実験なし","zh-CN":"无动物实验","ko":"동물실험 없음","de":"Tierversuchsfrei","es":"Sin crueldad animal","fr":"Sans cruauté","it":"Cruelty-free","ru":"Без тестов на животных","pt-BR":"Livre de crueldade"},
  "cup_sizes": {"en":"Cup sizes","ja":"カップサイズ","zh-CN":"杯量选项","ko":"컵 사이즈","de":"Tassengrößen","es":"Tamaños de taza","fr":"Tailles de tasse","it":"Formati tazza","ru":"Размеры чашек","pt-BR":"Tamanhos de xícara"},
  "cushioning": {"en":"Cushioning","ja":"クッション性","zh-CN":"缓震","ko":"쿠셔닝","de":"Dämpfung","es":"Amortiguación","fr":"Amorti","it":"Ammortizzazione","ru":"Амортизация","pt-BR":"Amortecimento"},
  "cut": {"en":"Cut","ja":"カット","zh-CN":"剪裁","ko":"컷","de":"Schnitt","es":"Corte","fr":"Coupe","it":"Taglio","ru":"Крой","pt-BR":"Corte"},
  "density": {"en":"Density","ja":"密度","zh-CN":"密度","ko":"밀도","de":"Dichte","es":"Densidad","fr":"Densité","it":"Densità","ru":"Плотность","pt-BR":"Densidade"},
  "devices_charged": {"en":"Devices charged","ja":"充電可能台数","zh-CN":"可充电设备数","ko":"충전 가능 기기 수","de":"Geladene Geräte","es":"Dispositivos cargados","fr":"Appareils chargés","it":"Dispositivi caricati","ru":"Заряжаемые устройства","pt-BR":"Dispositivos carregados"},
  "diameter": {"en":"Diameter","ja":"直径","zh-CN":"直径","ko":"지름","de":"Durchmesser","es":"Diámetro","fr":"Diamètre","it":"Diametro","ru":"Диаметр","pt-BR":"Diâmetro"},
  "dimensions": {"en":"Dimensions","ja":"寸法","zh-CN":"尺寸","ko":"크기","de":"Abmessungen","es":"Dimensiones","fr":"Dimensions","it":"Dimensioni","ru":"Размеры","pt-BR":"Dimensões"},
  "direct_deposit": {"en":"Direct deposit","ja":"給与振込","zh-CN":"直接存款","ko":"자동 입금","de":"Direkteinzahlung","es":"Depósito directo","fr":"Dépôt direct","it":"Deposito diretto","ru":"Прямое зачисление","pt-BR":"Depósito direto"},
  "dishwasher_safe": {"en":"Dishwasher safe","ja":"食洗機対応","zh-CN":"可用洗碗机","ko":"식기세척기 사용 가능","de":"Spülmaschinenfest","es":"Apto para lavavajillas","fr":"Lavable au lave-vaisselle","it":"Lavabile in lavastoviglie","ru":"Можно мыть в посудомойке","pt-BR":"Lavável na máquina"},
  "display": {"en":"Display","ja":"ディスプレイ","zh-CN":"显示屏","ko":"디스플레이","de":"Display","es":"Pantalla","fr":"Écran","it":"Display","ru":"Дисплей","pt-BR":"Tela"},
  "doorway_width_range": {"en":"Doorway width range","ja":"出入口幅範囲","zh-CN":"门口宽度范围","ko":"출입구 폭 범위","de":"Türbreitenbereich","es":"Rango de ancho de puerta","fr":"Plage de largeur de porte","it":"Intervallo larghezza porta","ru":"Диапазон ширины проёма","pt-BR":"Faixa de largura da porta"},
  "drip_tray": {"en":"Drip tray","ja":"ドリップトレイ","zh-CN":"滴水盘","ko":"물받이 트레이","de":"Tropfschale","es":"Bandeja de goteo","fr":"Bac d'égouttage","it":"Vassoio raccogligocce","ru":"Поддон для капель","pt-BR":"Bandeja coletora"},
  "dry_type": {"en":"Dry type","ja":"ドライタイプ","zh-CN":"干式类型","ko":"건식 유형","de":"Trockentyp","es":"Tipo en seco","fr":"Type sec","it":"Tipo a secco","ru":"Сухой тип","pt-BR":"Tipo seco"},
  "dual_ended": {"en":"Dual ended","ja":"両端タイプ","zh-CN":"双头","ko":"양쪽 사용","de":"Doppelseitig","es":"Doble punta","fr":"Double embout","it":"Doppia estremità","ru":"Двусторонний","pt-BR":"Ponta dupla"},
  "dual_voltage": {"en":"Dual voltage","ja":"デュアル電圧","zh-CN":"双电压","ko":"듀얼 볼티지","de":"Zweispannung","es":"Doble voltaje","fr":"Double voltage","it":"Doppio voltaggio","ru":"Двойное напряжение","pt-BR":"Voltagem dupla"},
  "early_withdrawal_penalty": {"en":"Early withdrawal penalty","ja":"早期解約ペナルティ","zh-CN":"提前支取罚金","ko":"중도 해지 수수료","de":"Vorfälligkeitsentschädigung","es":"Penalización por retiro anticipado","fr":"Pénalité de retrait anticipé","it":"Penale per ritiro anticipato","ru":"Штраф за досрочное снятие","pt-BR":"Multa por saque antecipado"},
  "energy_efficiency": {"en":"Energy efficiency","ja":"エネルギー効率","zh-CN":"能效","ko":"에너지 효율","de":"Energieeffizienz","es":"Eficiencia energética","fr":"Efficacité énergétique","it":"Efficienza energetica","ru":"Энергоэффективность","pt-BR":"Eficiência energética"},
  "entry_monthly_price": {"en":"Entry monthly price","ja":"初期月額料金","zh-CN":"入门月费","ko":"기본 월 요금","de":"Einstiegspreis pro Monat","es":"Precio mensual inicial","fr":"Prix mensuel d'entrée","it":"Prezzo mensile iniziale","ru":"Начальная месячная цена","pt-BR":"Preço mensal inicial"},
  "ethernet_ports": {"en":"Ethernet ports","ja":"イーサネットポート","zh-CN":"以太网端口","ko":"이더넷 포트","de":"Ethernet-Anschlüsse","es":"Puertos Ethernet","fr":"Ports Ethernet","it":"Porte Ethernet","ru":"Порты Ethernet","pt-BR":"Portas Ethernet"},
  "extra_pockets": {"en":"Extra pockets","ja":"追加ポケット","zh-CN":"额外口袋","ko":"추가 포켓","de":"Zusätzliche Taschen","es":"Bolsillos adicionales","fr":"Poches supplémentaires","it":"Tasche extra","ru":"Дополнительные карманы","pt-BR":"Bolsos extras"},
  "fabric": {"en":"Fabric","ja":"生地","zh-CN":"面料","ko":"원단","de":"Stoff","es":"Tejido","fr":"Tissu","it":"Tessuto","ru":"Ткань","pt-BR":"Tecido"},
  "fda_cleared": {"en":"FDA cleared","ja":"FDA認可","zh-CN":"FDA认证","ko":"FDA 승인","de":"FDA-zugelassen","es":"Aprobado por la FDA","fr":"Approuvé par la FDA","it":"Approvato dalla FDA","ru":"Одобрено FDA","pt-BR":"Aprovado pela FDA"},
  "fdic_insured": {"en":"FDIC insured","ja":"FDIC保険対象","zh-CN":"FDIC承保","ko":"FDIC 보험","de":"FDIC-versichert","es":"Asegurado por FDIC","fr":"Assuré FDIC","it":"Assicurato FDIC","ru":"Застраховано FDIC","pt-BR":"Segurado pelo FDIC"},
  "fiber": {"en":"Fiber","ja":"食物繊維","zh-CN":"纤维","ko":"식이섬유","de":"Ballaststoffe","es":"Fibra","fr":"Fibres","it":"Fibre","ru":"Клетчатка","pt-BR":"Fibra"},
  "filter_life": {"en":"Filter life","ja":"フィルター寿命","zh-CN":"滤芯寿命","ko":"필터 수명","de":"Filterlebensdauer","es":"Vida del filtro","fr":"Durée du filtre","it":"Durata del filtro","ru":"Срок службы фильтра","pt-BR":"Vida útil do filtro"},
  "filter_type": {"en":"Filter type","ja":"フィルタータイプ","zh-CN":"滤芯类型","ko":"필터 유형","de":"Filtertyp","es":"Tipo de filtro","fr":"Type de filtre","it":"Tipo di filtro","ru":"Тип фильтра","pt-BR":"Tipo de filtro"},
  "finger_style": {"en":"Finger style","ja":"指の形状","zh-CN":"指型","ko":"손가락 스타일","de":"Fingerstil","es":"Estilo de dedos","fr":"Style de doigts","it":"Stile dita","ru":"Тип пальцев","pt-BR":"Estilo de dedos"},
  "finish": {"en":"Finish","ja":"仕上げ","zh-CN":"表面处理","ko":"마감","de":"Oberfläche","es":"Acabado","fr":"Finition","it":"Finitura","ru":"Отделка","pt-BR":"Acabamento"},
  "firmness": {"en":"Firmness","ja":"硬さ","zh-CN":"硬度","ko":"단단함","de":"Festigkeit","es":"Firmeza","fr":"Fermeté","it":"Rigidità","ru":"Жёсткость","pt-BR":"Firmeza"},
  "fit": {"en":"Fit","ja":"フィット","zh-CN":"版型","ko":"핏","de":"Passform","es":"Ajuste","fr":"Coupe","it":"Vestibilità","ru":"Посадка","pt-BR":"Caimento"},
  "fits_size": {"en":"Fits size","ja":"対応サイズ","zh-CN":"适配尺寸","ko":"맞는 사이즈","de":"Passende Größe","es":"Talla compatible","fr":"Taille compatible","it":"Taglia compatibile","ru":"Подходящий размер","pt-BR":"Tamanho compatível"},
  "floor_space": {"en":"Floor space","ja":"設置面積","zh-CN":"占地面积","ko":"설치 면적","de":"Stellfläche","es":"Espacio de suelo","fr":"Encombrement au sol","it":"Spazio a terra","ru":"Занимаемая площадь","pt-BR":"Espaço de chão"},
  "flow_rate": {"en":"Flow rate","ja":"流量","zh-CN":"流量","ko":"유량","de":"Durchflussrate","es":"Caudal","fr":"Débit","it":"Portata","ru":"Расход","pt-BR":"Vazão"},
  "foot_cradles": {"en":"Foot cradles","ja":"フットクレードル","zh-CN":"脚托","ko":"발 받침대","de":"Fußschalen","es":"Soportes para pies","fr":"Repose-pieds","it":"Supporti per piedi","ru":"Опоры для ног","pt-BR":"Apoios para os pés"},
  "foot_pocket": {"en":"Foot pocket","ja":"フットポケット","zh-CN":"脚窝","ko":"풋포켓","de":"Fußtasche","es":"Calzante","fr":"Chausson","it":"Scarpetta","ru":"Калоша","pt-BR":"Sapata"},
  "footprint": {"en":"Footprint","ja":"設置面積","zh-CN":"占地面积","ko":"설치 면적","de":"Stellfläche","es":"Espacio ocupado","fr":"Encombrement","it":"Ingombro","ru":"Занимаемая площадь","pt-BR":"Área ocupada"},
  "form": {"en":"Form","ja":"形状","zh-CN":"形态","ko":"형태","de":"Form","es":"Forma","fr":"Forme","it":"Forma","ru":"Форма","pt-BR":"Forma"},
  "form_factor": {"en":"Form factor","ja":"フォームファクター","zh-CN":"外形规格","ko":"폼 팩터","de":"Formfaktor","es":"Formato","fr":"Format","it":"Formato","ru":"Форм-фактор","pt-BR":"Formato"},
  "formula": {"en":"Formula","ja":"成分処方","zh-CN":"配方","ko":"포뮬러","de":"Formel","es":"Fórmula","fr":"Formule","it":"Formula","ru":"Состав","pt-BR":"Fórmula"},
  "fragrance_free": {"en":"Fragrance free","ja":"無香料","zh-CN":"无香料","ko":"무향","de":"Parfümfrei","es":"Sin fragancia","fr":"Sans parfum","it":"Senza profumo","ru":"Без отдушек","pt-BR":"Sem fragrância"},
  "free_domain": {"en":"Free domain","ja":"無料ドメイン","zh-CN":"免费域名","ko":"무료 도메인","de":"Kostenlose Domain","es":"Dominio gratis","fr":"Domaine gratuit","it":"Dominio gratuito","ru":"Бесплатный домен","pt-BR":"Domínio grátis"},
  "free_ssl": {"en":"Free SSL","ja":"無料SSL","zh-CN":"免费SSL","ko":"무료 SSL","de":"Kostenloses SSL","es":"SSL gratis","fr":"SSL gratuit","it":"SSL gratuito","ru":"Бесплатный SSL","pt-BR":"SSL grátis"},
  "from_concentrate": {"en":"From concentrate","ja":"濃縮還元","zh-CN":"浓缩还原","ko":"농축액 사용","de":"Aus Konzentrat","es":"De concentrado","fr":"À base de concentré","it":"Da concentrato","ru":"Из концентрата","pt-BR":"De concentrado"},
  "gasket": {"en":"Gasket","ja":"ガスケット","zh-CN":"垫圈","ko":"개스킷","de":"Dichtung","es":"Junta","fr":"Joint","it":"Guarnizione","ru":"Прокладка","pt-BR":"Vedação"},
  "geofencing": {"en":"Geofencing","ja":"ジオフェンシング","zh-CN":"地理围栏","ko":"지오펜싱","de":"Geofencing","es":"Geovallado","fr":"Géorepérage","it":"Geofencing","ru":"Геозона","pt-BR":"Geofencing"},
  "gps": {"en":"GPS","ja":"GPS","zh-CN":"GPS","ko":"GPS","de":"GPS","es":"GPS","fr":"GPS","it":"GPS","ru":"GPS","pt-BR":"GPS"},
  "grade": {"en":"Grade","ja":"グレード","zh-CN":"等级","ko":"등급","de":"Güteklasse","es":"Grado","fr":"Qualité","it":"Grado","ru":"Класс","pt-BR":"Grau"},
  "grip_positions": {"en":"Grip positions","ja":"グリップ位置","zh-CN":"握把位置","ko":"그립 위치","de":"Griffpositionen","es":"Posiciones de agarre","fr":"Positions de prise","it":"Posizioni di presa","ru":"Положения хвата","pt-BR":"Posições de pega"},
  "grommets": {"en":"Grommets","ja":"ハトメ","zh-CN":"气眼","ko":"그로밋","de":"Ösen","es":"Ojales","fr":"Œillets","it":"Occhielli","ru":"Люверсы","pt-BR":"Ilhoses"},
  "hair_type": {"en":"Hair type","ja":"髪質","zh-CN":"发质","ko":"모발 유형","de":"Haartyp","es":"Tipo de cabello","fr":"Type de cheveux","it":"Tipo di capelli","ru":"Тип волос","pt-BR":"Tipo de cabelo"},
  "handle_diameter": {"en":"Handle diameter","ja":"ハンドル径","zh-CN":"手柄直径","ko":"손잡이 지름","de":"Griffdurchmesser","es":"Diámetro del mango","fr":"Diamètre du manche","it":"Diametro impugnatura","ru":"Диаметр ручки","pt-BR":"Diâmetro da pega"},
  "handle_material": {"en":"Handle material","ja":"ハンドル素材","zh-CN":"手柄材质","ko":"손잡이 소재","de":"Griffmaterial","es":"Material del mango","fr":"Matériau du manche","it":"Materiale impugnatura","ru":"Материал ручки","pt-BR":"Material da pega"},
  "handle_type": {"en":"Handle type","ja":"ハンドルタイプ","zh-CN":"手柄类型","ko":"손잡이 유형","de":"Grifftyp","es":"Tipo de mango","fr":"Type de poignée","it":"Tipo di impugnatura","ru":"Тип ручки","pt-BR":"Tipo de pega"},
  "handles_included": {"en":"Handles included","ja":"ハンドル付属","zh-CN":"含手柄","ko":"손잡이 포함","de":"Griffe enthalten","es":"Mangos incluidos","fr":"Poignées incluses","it":"Maniglie incluse","ru":"Ручки в комплекте","pt-BR":"Pegas incluídas"},
  "harvest_dated": {"en":"Harvest dated","ja":"収穫日表示","zh-CN":"标注采收日期","ko":"수확일 표기","de":"Mit Erntedatum","es":"Con fecha de cosecha","fr":"Date de récolte indiquée","it":"Con data di raccolta","ru":"С датой сбора","pt-BR":"Com data de colheita"},
  "health_sensors": {"en":"Health sensors","ja":"健康センサー","zh-CN":"健康传感器","ko":"건강 센서","de":"Gesundheitssensoren","es":"Sensores de salud","fr":"Capteurs de santé","it":"Sensori salute","ru":"Датчики здоровья","pt-BR":"Sensores de saúde"},
  "heat_protectant": {"en":"Heat protectant","ja":"ヒートプロテクト","zh-CN":"热防护","ko":"열 보호제","de":"Hitzeschutz","es":"Protector térmico","fr":"Protecteur thermique","it":"Protezione termica","ru":"Термозащита","pt-BR":"Protetor térmico"},
  "heat_settings": {"en":"Heat settings","ja":"温度設定","zh-CN":"温度档位","ko":"온도 설정","de":"Temperaturstufen","es":"Niveles de calor","fr":"Réglages de chaleur","it":"Livelli di calore","ru":"Режимы нагрева","pt-BR":"Níveis de calor"},
  "heat_up_time": {"en":"Heat up time","ja":"加熱時間","zh-CN":"加热时间","ko":"예열 시간","de":"Aufheizzeit","es":"Tiempo de calentamiento","fr":"Temps de chauffe","it":"Tempo di riscaldamento","ru":"Время нагрева","pt-BR":"Tempo de aquecimento"},
  "heel_drop": {"en":"Heel drop","ja":"ヒールドロップ","zh-CN":"跟差","ko":"힐 드롭","de":"Sprengung","es":"Drop","fr":"Drop","it":"Drop","ru":"Перепад (дроп)","pt-BR":"Drop"},
  "height": {"en":"Height","ja":"高さ","zh-CN":"高度","ko":"높이","de":"Höhe","es":"Altura","fr":"Hauteur","it":"Altezza","ru":"Высота","pt-BR":"Altura"},
  "height_in": {"en":"Height","ja":"高さ","zh-CN":"高度","ko":"높이","de":"Höhe","es":"Altura","fr":"Hauteur","it":"Altezza","ru":"Высота","pt-BR":"Altura"},
  "hole_spacing": {"en":"Hole spacing","ja":"穴間隔","zh-CN":"孔距","ko":"구멍 간격","de":"Lochabstand","es":"Distancia entre orificios","fr":"Entraxe","it":"Interasse fori","ru":"Шаг отверстий","pt-BR":"Distância entre furos"},
  "hvac_compatibility": {"en":"HVAC compatibility","ja":"HVAC対応","zh-CN":"HVAC兼容性","ko":"HVAC 호환성","de":"HVAC-Kompatibilität","es":"Compatibilidad HVAC","fr":"Compatibilité CVC","it":"Compatibilità HVAC","ru":"Совместимость с HVAC","pt-BR":"Compatibilidade HVAC"},
  "includes_anchors": {"en":"Includes anchors","ja":"アンカー付属","zh-CN":"含锚栓","ko":"앵커 포함","de":"Inkl. Dübel","es":"Incluye anclajes","fr":"Chevilles incluses","it":"Tasselli inclusi","ru":"Анкеры в комплекте","pt-BR":"Inclui buchas"},
  "increments": {"en":"Increments","ja":"刻み幅","zh-CN":"增量","ko":"증분 단위","de":"Schrittweite","es":"Incrementos","fr":"Incréments","it":"Incrementi","ru":"Шаг","pt-BR":"Incrementos"},
  "induction_compatible": {"en":"Induction compatible","ja":"IH対応","zh-CN":"电磁炉兼容","ko":"인덕션 호환","de":"Induktionsgeeignet","es":"Apto para inducción","fr":"Compatible induction","it":"Adatto a induzione","ru":"Для индукции","pt-BR":"Compatível com indução"},
  "ingredients": {"en":"Ingredients","ja":"原材料","zh-CN":"成分","ko":"성분","de":"Zutaten","es":"Ingredientes","fr":"Ingrédients","it":"Ingredienti","ru":"Состав","pt-BR":"Ingredientes"},
  "ipf_approved": {"en":"IPF approved","ja":"IPF公認","zh-CN":"IPF认证","ko":"IPF 공인","de":"IPF-zugelassen","es":"Homologado IPF","fr":"Homologué IPF","it":"Approvato IPF","ru":"Одобрено IPF","pt-BR":"Aprovado pela IPF"},
  "item_weight": {"en":"Item weight","ja":"商品重量","zh-CN":"商品重量","ko":"제품 무게","de":"Produktgewicht","es":"Peso del artículo","fr":"Poids de l'article","it":"Peso articolo","ru":"Вес товара","pt-BR":"Peso do item"},
  "key_ingredients": {"en":"Key ingredients","ja":"主要成分","zh-CN":"主要成分","ko":"주요 성분","de":"Hauptinhaltsstoffe","es":"Ingredientes clave","fr":"Ingrédients clés","it":"Ingredienti chiave","ru":"Ключевые компоненты","pt-BR":"Ingredientes principais"},
  "key_spec": {"en":"Key spec","ja":"主要スペック","zh-CN":"核心规格","ko":"주요 사양","de":"Hauptmerkmal","es":"Especificación clave","fr":"Caractéristique clé","it":"Specifica chiave","ru":"Ключевая характеристика","pt-BR":"Especificação principal"},
  "leave_on_time": {"en":"Leave on time","ja":"放置時間","zh-CN":"停留时间","ko":"방치 시간","de":"Einwirkzeit","es":"Tiempo de aplicación","fr":"Temps de pose","it":"Tempo di posa","ru":"Время выдержки","pt-BR":"Tempo de ação"},
  "led_count": {"en":"LED count","ja":"LED数","zh-CN":"LED数量","ko":"LED 개수","de":"LED-Anzahl","es":"Número de LED","fr":"Nombre de LED","it":"Numero di LED","ru":"Кол-во светодиодов","pt-BR":"Número de LEDs"},
  "length": {"en":"Length","ja":"長さ","zh-CN":"长度","ko":"길이","de":"Länge","es":"Longitud","fr":"Longueur","it":"Lunghezza","ru":"Длина","pt-BR":"Comprimento"},
  "lens_type": {"en":"Lens type","ja":"レンズタイプ","zh-CN":"镜片类型","ko":"렌즈 유형","de":"Linsentyp","es":"Tipo de lente","fr":"Type de verre","it":"Tipo di lente","ru":"Тип линз","pt-BR":"Tipo de lente"},
  "levels": {"en":"Levels","ja":"レベル数","zh-CN":"档位","ko":"단계","de":"Stufen","es":"Niveles","fr":"Niveaux","it":"Livelli","ru":"Уровни","pt-BR":"Níveis"},
  "light_source": {"en":"Light source","ja":"光源","zh-CN":"光源","ko":"광원","de":"Lichtquelle","es":"Fuente de luz","fr":"Source lumineuse","it":"Sorgente luminosa","ru":"Источник света","pt-BR":"Fonte de luz"},
  "light_wavelengths": {"en":"Light wavelengths","ja":"光波長","zh-CN":"光波长","ko":"광 파장","de":"Lichtwellenlängen","es":"Longitudes de onda","fr":"Longueurs d'onde","it":"Lunghezze d'onda","ru":"Длины волн","pt-BR":"Comprimentos de onda"},
  "machine_washable": {"en":"Machine washable","ja":"洗濯機可","zh-CN":"可机洗","ko":"세탁기 사용 가능","de":"Maschinenwaschbar","es":"Apto para lavadora","fr":"Lavable en machine","it":"Lavabile in lavatrice","ru":"Машинная стирка","pt-BR":"Lavável à máquina"},
  "material": {"en":"Material","ja":"素材","zh-CN":"材质","ko":"소재","de":"Material","es":"Material","fr":"Matériau","it":"Materiale","ru":"Материал","pt-BR":"Material"},
  "max_capacity": {"en":"Max capacity","ja":"最大容量","zh-CN":"最大容量","ko":"최대 용량","de":"Max. Kapazität","es":"Capacidad máx.","fr":"Capacité max","it":"Capacità max","ru":"Макс. ёмкость","pt-BR":"Capacidade máx."},
  "max_label_width": {"en":"Max label width","ja":"最大ラベル幅","zh-CN":"最大标签宽度","ko":"최대 라벨 폭","de":"Max. Etikettenbreite","es":"Ancho máx. de etiqueta","fr":"Largeur max d'étiquette","it":"Larghezza max etichetta","ru":"Макс. ширина этикетки","pt-BR":"Largura máx. da etiqueta"},
  "max_output": {"en":"Max output","ja":"最大出力","zh-CN":"最大输出","ko":"최대 출력","de":"Max. Leistung","es":"Salida máx.","fr":"Sortie max","it":"Uscita max","ru":"Макс. мощность","pt-BR":"Saída máx."},
  "max_speed": {"en":"Max speed","ja":"最高速度","zh-CN":"最大速度","ko":"최대 속도","de":"Max. Geschwindigkeit","es":"Velocidad máx.","fr":"Vitesse max","it":"Velocità max","ru":"Макс. скорость","pt-BR":"Velocidade máx."},
  "max_temp": {"en":"Max temp","ja":"最高温度","zh-CN":"最高温度","ko":"최고 온도","de":"Max. Temperatur","es":"Temp. máx.","fr":"Temp. max","it":"Temp. max","ru":"Макс. температура","pt-BR":"Temp. máx."},
  "max_user_weight": {"en":"Max user weight","ja":"最大使用者体重","zh-CN":"最大承重(用户)","ko":"최대 사용자 체중","de":"Max. Benutzergewicht","es":"Peso máx. del usuario","fr":"Poids max utilisateur","it":"Peso max utente","ru":"Макс. вес пользователя","pt-BR":"Peso máx. do utilizador"},
  "max_weight": {"en":"Max weight","ja":"最大重量","zh-CN":"最大重量","ko":"최대 중량","de":"Max. Gewicht","es":"Peso máx.","fr":"Poids max","it":"Peso max","ru":"Макс. вес","pt-BR":"Peso máx."},
  "mesh_compatible": {"en":"Mesh compatible","ja":"メッシュ対応","zh-CN":"支持Mesh组网","ko":"메시 호환","de":"Mesh-fähig","es":"Compatible con malla","fr":"Compatible mesh","it":"Compatibile mesh","ru":"Поддержка mesh","pt-BR":"Compatível com mesh"},
  "metrics": {"en":"Metrics","ja":"計測項目","zh-CN":"测量指标","ko":"측정 항목","de":"Messwerte","es":"Métricas","fr":"Métriques","it":"Metriche","ru":"Метрики","pt-BR":"Métricas"},
  "milk_frother": {"en":"Milk frother","ja":"ミルクフォーマー","zh-CN":"奶泡器","ko":"우유 거품기","de":"Milchaufschäumer","es":"Espumador de leche","fr":"Mousseur à lait","it":"Montalatte","ru":"Вспениватель молока","pt-BR":"Espumador de leite"},
  "min_deposit": {"en":"Min deposit","ja":"最低入金額","zh-CN":"最低入金","ko":"최소 입금액","de":"Mindesteinzahlung","es":"Depósito mínimo","fr":"Dépôt minimum","it":"Deposito minimo","ru":"Мин. депозит","pt-BR":"Depósito mín."},
  "mixing_mechanism": {"en":"Mixing mechanism","ja":"攪拌方式","zh-CN":"搅拌机制","ko":"혼합 방식","de":"Mischmechanismus","es":"Mecanismo de mezcla","fr":"Mécanisme de mélange","it":"Meccanismo di miscelazione","ru":"Механизм смешивания","pt-BR":"Mecanismo de mistura"},
  "monthly_fee": {"en":"Monthly fee","ja":"月額料金","zh-CN":"月费","ko":"월 요금","de":"Monatsgebühr","es":"Cuota mensual","fr":"Frais mensuels","it":"Canone mensile","ru":"Ежемесячная плата","pt-BR":"Mensalidade"},
  "mopping": {"en":"Mopping","ja":"拭き掃除","zh-CN":"拖地","ko":"물걸레 기능","de":"Wischfunktion","es":"Fregado","fr":"Lavage","it":"Lavaggio","ru":"Влажная уборка","pt-BR":"Passar pano"},
  "mother": {"en":"Mother","ja":"マザー(酢酸菌)","zh-CN":"醋母","ko":"초모","de":"Essigmutter","es":"Madre del vinagre","fr":"Mère de vinaigre","it":"Madre dell'aceto","ru":"Уксусная матка","pt-BR":"Mãe do vinagre"},
  "mount": {"en":"Mount","ja":"マウント","zh-CN":"安装方式","ko":"마운트","de":"Halterung","es":"Montaje","fr":"Support","it":"Montaggio","ru":"Крепление","pt-BR":"Suporte"},
  "mount_type": {"en":"Mount type","ja":"マウントタイプ","zh-CN":"安装类型","ko":"마운트 유형","de":"Halterungstyp","es":"Tipo de montaje","fr":"Type de fixation","it":"Tipo di montaggio","ru":"Тип крепления","pt-BR":"Tipo de montagem"},
  "multipoint": {"en":"Multipoint","ja":"マルチポイント","zh-CN":"多点连接","ko":"멀티포인트","de":"Multipoint","es":"Multipunto","fr":"Multipoint","it":"Multipoint","ru":"Multipoint","pt-BR":"Multipoint"},
  "mushrooms": {"en":"Mushrooms","ja":"きのこ","zh-CN":"菌菇","ko":"버섯","de":"Pilze","es":"Champiñones","fr":"Champignons","it":"Funghi","ru":"Грибы","pt-BR":"Cogumelos"},
  "native_resolution": {"en":"Native resolution","ja":"ネイティブ解像度","zh-CN":"原生分辨率","ko":"네이티브 해상도","de":"Native Auflösung","es":"Resolución nativa","fr":"Résolution native","it":"Risoluzione nativa","ru":"Родное разрешение","pt-BR":"Resolução nativa"},
  "navigation": {"en":"Navigation","ja":"ナビゲーション","zh-CN":"导航","ko":"내비게이션","de":"Navigation","es":"Navegación","fr":"Navigation","it":"Navigazione","ru":"Навигация","pt-BR":"Navegação"},
  "net_weight": {"en":"Net weight","ja":"正味重量","zh-CN":"净重","ko":"순중량","de":"Nettogewicht","es":"Peso neto","fr":"Poids net","it":"Peso netto","ru":"Вес нетто","pt-BR":"Peso líquido"},
  "network": {"en":"Network","ja":"ネットワーク","zh-CN":"网络","ko":"네트워크","de":"Netzwerk","es":"Red","fr":"Réseau","it":"Rete","ru":"Сеть","pt-BR":"Rede"},
  "noise_level": {"en":"Noise level","ja":"騒音レベル","zh-CN":"噪音水平","ko":"소음 수준","de":"Geräuschpegel","es":"Nivel de ruido","fr":"Niveau sonore","it":"Livello di rumore","ru":"Уровень шума","pt-BR":"Nível de ruído"},
  "non_sticky": {"en":"Non sticky","ja":"べたつかない","zh-CN":"不黏腻","ko":"끈적임 없음","de":"Nicht klebrig","es":"No pegajoso","fr":"Non collant","it":"Non appiccicoso","ru":"Не липкий","pt-BR":"Não pegajoso"},
  "nose_bridge": {"en":"Nose bridge","ja":"ノーズブリッジ","zh-CN":"鼻梁","ko":"코 브리지","de":"Nasensteg","es":"Puente nasal","fr":"Pont de nez","it":"Ponte nasale","ru":"Переносица","pt-BR":"Ponte nasal"},
  "organic": {"en":"Organic","ja":"オーガニック","zh-CN":"有机","ko":"유기농","de":"Bio","es":"Orgánico","fr":"Bio","it":"Biologico","ru":"Органический","pt-BR":"Orgânico"},
  "origin": {"en":"Origin","ja":"原産地","zh-CN":"产地","ko":"원산지","de":"Herkunft","es":"Origen","fr":"Origine","it":"Origine","ru":"Происхождение","pt-BR":"Origem"},
  "os": {"en":"OS","ja":"OS","zh-CN":"操作系统","ko":"OS","de":"Betriebssystem","es":"SO","fr":"OS","it":"OS","ru":"ОС","pt-BR":"SO"},
  "outsole": {"en":"Outsole","ja":"アウトソール","zh-CN":"大底","ko":"아웃솔","de":"Außensohle","es":"Suela","fr":"Semelle extérieure","it":"Suola","ru":"Подошва","pt-BR":"Sola"},
  "oven_safe": {"en":"Oven safe","ja":"オーブン対応","zh-CN":"可入烤箱","ko":"오븐 사용 가능","de":"Backofengeeignet","es":"Apto para horno","fr":"Va au four","it":"Adatto al forno","ru":"Можно в духовку","pt-BR":"Apto para forno"},
  "package_size": {"en":"Package size","ja":"パッケージサイズ","zh-CN":"包装尺寸","ko":"패키지 크기","de":"Verpackungsgröße","es":"Tamaño del paquete","fr":"Taille de l'emballage","it":"Dimensioni confezione","ru":"Размер упаковки","pt-BR":"Tamanho da embalagem"},
  "packaging": {"en":"Packaging","ja":"パッケージ","zh-CN":"包装","ko":"포장","de":"Verpackung","es":"Embalaje","fr":"Emballage","it":"Confezione","ru":"Упаковка","pt-BR":"Embalagem"},
  "pad_dimensions": {"en":"Pad dimensions","ja":"パッド寸法","zh-CN":"垫片尺寸","ko":"패드 크기","de":"Pad-Abmessungen","es":"Dimensiones de la almohadilla","fr":"Dimensions du pad","it":"Dimensioni del pad","ru":"Размеры коврика","pt-BR":"Dimensões da almofada"},
  "padding": {"en":"Padding","ja":"パッド","zh-CN":"衬垫","ko":"패딩","de":"Polsterung","es":"Acolchado","fr":"Rembourrage","it":"Imbottitura","ru":"Набивка","pt-BR":"Enchimento"},
  "panel": {"en":"Panel","ja":"パネル","zh-CN":"面板","ko":"패널","de":"Panel","es":"Panel","fr":"Panneau","it":"Pannello","ru":"Панель","pt-BR":"Painel"},
  "ph": {"en":"pH","ja":"pH","zh-CN":"pH值","ko":"pH","de":"pH-Wert","es":"pH","fr":"pH","it":"pH","ru":"pH","pt-BR":"pH"},
  "pieces": {"en":"Pieces","ja":"個数","zh-CN":"件数","ko":"개수","de":"Stückzahl","es":"Piezas","fr":"Pièces","it":"Pezzi","ru":"Кол-во","pt-BR":"Peças"},
  "pieces_in_set": {"en":"Pieces in set","ja":"セット内点数","zh-CN":"套装件数","ko":"세트 구성 수","de":"Teile im Set","es":"Piezas por juego","fr":"Pièces par lot","it":"Pezzi nel set","ru":"Предметов в наборе","pt-BR":"Peças no conjunto"},
  "plate_material": {"en":"Plate material","ja":"プレート素材","zh-CN":"板材","ko":"플레이트 소재","de":"Plattenmaterial","es":"Material de las placas","fr":"Matériau des plaques","it":"Materiale piastre","ru":"Материал пластин","pt-BR":"Material das placas"},
  "plate_type": {"en":"Plate type","ja":"プレートタイプ","zh-CN":"板型","ko":"플레이트 유형","de":"Plattentyp","es":"Tipo de placas","fr":"Type de plaques","it":"Tipo di piastre","ru":"Тип пластин","pt-BR":"Tipo de placas"},
  "plate_width": {"en":"Plate width","ja":"プレート幅","zh-CN":"板宽","ko":"플레이트 폭","de":"Plattenbreite","es":"Ancho de las placas","fr":"Largeur des plaques","it":"Larghezza piastre","ru":"Ширина пластин","pt-BR":"Largura das placas"},
  "polyphenols": {"en":"Polyphenols","ja":"ポリフェノール","zh-CN":"多酚","ko":"폴리페놀","de":"Polyphenole","es":"Polifenoles","fr":"Polyphénols","it":"Polifenoli","ru":"Полифенолы","pt-BR":"Polifenóis"},
  "ports": {"en":"Ports","ja":"ポート","zh-CN":"接口","ko":"포트","de":"Anschlüsse","es":"Puertos","fr":"Ports","it":"Porte","ru":"Порты","pt-BR":"Portas"},
  "potassium": {"en":"Potassium","ja":"カリウム","zh-CN":"钾","ko":"칼륨","de":"Kalium","es":"Potasio","fr":"Potassium","it":"Potassio","ru":"Калий","pt-BR":"Potássio"},
  "power": {"en":"Power","ja":"電力","zh-CN":"功率","ko":"전력","de":"Leistung","es":"Potencia","fr":"Puissance","it":"Potenza","ru":"Мощность","pt-BR":"Potência"},
  "power_source": {"en":"Power source","ja":"電源","zh-CN":"电源","ko":"전원","de":"Stromquelle","es":"Fuente de alimentación","fr":"Source d'alimentation","it":"Alimentazione","ru":"Источник питания","pt-BR":"Fonte de alimentação"},
  "preseasoned": {"en":"Preseasoned","ja":"シーズニング済み","zh-CN":"已开锅","ko":"시즈닝 완료","de":"Eingebrannt","es":"Precurado","fr":"Préculottée","it":"Precondizionata","ru":"С заводской обработкой","pt-BR":"Pré-temperado"},
  "print_tech": {"en":"Print tech","ja":"印刷方式","zh-CN":"打印技术","ko":"인쇄 기술","de":"Drucktechnik","es":"Tecnología de impresión","fr":"Technologie d'impression","it":"Tecnologia di stampa","ru":"Технология печати","pt-BR":"Tecnologia de impressão"},
  "programmable": {"en":"Programmable","ja":"プログラム機能","zh-CN":"可编程","ko":"프로그래밍 가능","de":"Programmierbar","es":"Programable","fr":"Programmable","it":"Programmabile","ru":"Программируемый","pt-BR":"Programável"},
  "protein": {"en":"Protein","ja":"タンパク質","zh-CN":"蛋白质","ko":"단백질","de":"Protein","es":"Proteína","fr":"Protéines","it":"Proteine","ru":"Белки","pt-BR":"Proteína"},
  "protein_source": {"en":"Protein source","ja":"タンパク質源","zh-CN":"蛋白质来源","ko":"단백질 공급원","de":"Proteinquelle","es":"Fuente de proteína","fr":"Source de protéines","it":"Fonte proteica","ru":"Источник белка","pt-BR":"Fonte de proteína"},
  "qi_standard": {"en":"Qi standard","ja":"Qi規格","zh-CN":"Qi 标准","ko":"Qi 표준","de":"Qi-Standard","es":"Estándar Qi","fr":"Norme Qi","it":"Standard Qi","ru":"Стандарт Qi","pt-BR":"Padrão Qi"},
  "raw": {"en":"Raw","ja":"生","zh-CN":"生","ko":"생","de":"Roh","es":"Crudo","fr":"Cru","it":"Crudo","ru":"Сырой","pt-BR":"Cru"},
  "refresh_rate": {"en":"Refresh rate","ja":"リフレッシュレート","zh-CN":"刷新率","ko":"주사율","de":"Bildwiederholrate","es":"Tasa de refresco","fr":"Taux de rafraîchissement","it":"Frequenza di aggiornamento","ru":"Частота обновления","pt-BR":"Taxa de atualização"},
  "reload_options": {"en":"Reload options","ja":"チャージ方法","zh-CN":"充值方式","ko":"충전 옵션","de":"Aufladeoptionen","es":"Opciones de recarga","fr":"Options de recharge","it":"Opzioni di ricarica","ru":"Варианты пополнения","pt-BR":"Opções de recarga"},
  "resistance": {"en":"Resistance","ja":"負荷","zh-CN":"阻力","ko":"저항","de":"Widerstand","es":"Resistencia","fr":"Résistance","it":"Resistenza","ru":"Сопротивление","pt-BR":"Resistência"},
  "resistance_range": {"en":"Resistance range","ja":"負荷範囲","zh-CN":"阻力范围","ko":"저항 범위","de":"Widerstandsbereich","es":"Rango de resistencia","fr":"Plage de résistance","it":"Gamma di resistenza","ru":"Диапазон сопротивления","pt-BR":"Faixa de resistência"},
  "resolution": {"en":"Resolution","ja":"解像度","zh-CN":"分辨率","ko":"해상도","de":"Auflösung","es":"Resolución","fr":"Résolution","it":"Risoluzione","ru":"Разрешение","pt-BR":"Resolução"},
  "resolution_dpi": {"en":"Resolution","ja":"解像度","zh-CN":"分辨率","ko":"해상도","de":"Auflösung","es":"Resolución","fr":"Résolution","it":"Risoluzione","ru":"Разрешение","pt-BR":"Resolução"},
  "rise": {"en":"Rise","ja":"ライズ","zh-CN":"裤腰高度","ko":"라이즈","de":"Bundhöhe","es":"Tiro","fr":"Hauteur de taille","it":"Vita","ru":"Высота посадки","pt-BR":"Cós"},
  "roast": {"en":"Roast","ja":"焙煎度","zh-CN":"烘焙度","ko":"로스팅","de":"Röstung","es":"Tueste","fr":"Torréfaction","it":"Tostatura","ru":"Степень обжарки","pt-BR":"Torra"},
  "screen_size": {"en":"Screen size","ja":"画面サイズ","zh-CN":"屏幕尺寸","ko":"화면 크기","de":"Bildschirmgröße","es":"Tamaño de pantalla","fr":"Taille d'écran","it":"Dimensione schermo","ru":"Размер экрана","pt-BR":"Tamanho da tela"},
  "sensors_included": {"en":"Sensors included","ja":"搭載センサー","zh-CN":"内置传感器","ko":"포함 센서","de":"Enthaltene Sensoren","es":"Sensores incluidos","fr":"Capteurs inclus","it":"Sensori inclusi","ru":"Встроенные датчики","pt-BR":"Sensores incluídos"},
  "server_spec": {"en":"Server spec","ja":"サーバー仕様","zh-CN":"服务器规格","ko":"서버 사양","de":"Server-Spezifikation","es":"Especificación del servidor","fr":"Spécifications serveur","it":"Specifiche server","ru":"Характеристики сервера","pt-BR":"Especificação do servidor"},
  "serving_calories": {"en":"Serving calories","ja":"1食あたりカロリー","zh-CN":"每份热量","ko":"1회분 칼로리","de":"Kalorien pro Portion","es":"Calorías por porción","fr":"Calories par portion","it":"Calorie per porzione","ru":"Калорий на порцию","pt-BR":"Calorias por porção"},
  "serving_size": {"en":"Serving size","ja":"1食分量","zh-CN":"每份分量","ko":"1회 제공량","de":"Portionsgröße","es":"Tamaño de porción","fr":"Taille de portion","it":"Dimensione porzione","ru":"Размер порции","pt-BR":"Porção"},
  "servings_per_container": {"en":"Servings per container","ja":"内容量（食数）","zh-CN":"每瓶份数","ko":"용기당 제공 횟수","de":"Portionen pro Packung","es":"Porciones por envase","fr":"Portions par contenant","it":"Porzioni per confezione","ru":"Порций в упаковке","pt-BR":"Porções por embalagem"},
  "servings_per_pack": {"en":"Servings per pack","ja":"1袋の食数","zh-CN":"每包份数","ko":"팩당 제공 횟수","de":"Portionen pro Beutel","es":"Porciones por paquete","fr":"Portions par paquet","it":"Porzioni per confezione","ru":"Порций в пачке","pt-BR":"Porções por pacote"},
  "session_frequency": {"en":"Session frequency","ja":"使用頻度","zh-CN":"使用频率","ko":"사용 빈도","de":"Anwendungshäufigkeit","es":"Frecuencia de sesión","fr":"Fréquence des séances","it":"Frequenza delle sessioni","ru":"Частота сеансов","pt-BR":"Frequência de uso"},
  "shade_count": {"en":"Shade count","ja":"カラー数","zh-CN":"色号数量","ko":"셰이드 수","de":"Anzahl Farbtöne","es":"Número de tonos","fr":"Nombre de teintes","it":"Numero di tonalità","ru":"Количество оттенков","pt-BR":"Número de tons"},
  "shell": {"en":"Shell","ja":"シェル","zh-CN":"外壳","ko":"셸","de":"Schale","es":"Carcasa","fr":"Coque","it":"Guscio","ru":"Корпус","pt-BR":"Casco"},
  "silicone_free": {"en":"Silicone free","ja":"シリコンフリー","zh-CN":"无硅油","ko":"실리콘 무첨가","de":"Silikonfrei","es":"Sin silicona","fr":"Sans silicone","it":"Senza silicone","ru":"Без силикона","pt-BR":"Sem silicone"},
  "sizing": {"en":"Sizing","ja":"サイズ感","zh-CN":"尺码","ko":"사이즈","de":"Größe","es":"Tallaje","fr":"Taille","it":"Vestibilità","ru":"Размерность","pt-BR":"Tamanho"},
  "skin_type": {"en":"Skin type","ja":"肌タイプ","zh-CN":"肤质","ko":"피부 타입","de":"Hauttyp","es":"Tipo de piel","fr":"Type de peau","it":"Tipo di pelle","ru":"Тип кожи","pt-BR":"Tipo de pele"},
  "smart_os": {"en":"Smart os","ja":"スマートOS","zh-CN":"智能系统","ko":"스마트 OS","de":"Smart-OS","es":"Sistema operativo","fr":"Système d'exploitation","it":"Sistema operativo","ru":"Smart OS","pt-BR":"Sistema operacional"},
  "sodium": {"en":"Sodium","ja":"ナトリウム","zh-CN":"钠","ko":"나트륨","de":"Natrium","es":"Sodio","fr":"Sodium","it":"Sodio","ru":"Натрий","pt-BR":"Sódio"},
  "speeds": {"en":"Speeds","ja":"速度段階","zh-CN":"速度档位","ko":"속도 단계","de":"Geschwindigkeitsstufen","es":"Velocidades","fr":"Vitesses","it":"Velocità","ru":"Скорости","pt-BR":"Velocidades"},
  "spray_settings": {"en":"Spray settings","ja":"散水パターン","zh-CN":"喷水模式","ko":"분사 모드","de":"Sprüheinstellungen","es":"Modos de pulverización","fr":"Modes de jet","it":"Modalità di getto","ru":"Режимы распыления","pt-BR":"Modos de jato"},
  "stability_features": {"en":"Stability features","ja":"安定性機能","zh-CN":"稳定性功能","ko":"안정성 기능","de":"Stabilitätsmerkmale","es":"Funciones de estabilidad","fr":"Fonctions de stabilité","it":"Funzioni di stabilità","ru":"Функции стабильности","pt-BR":"Recursos de estabilidade"},
  "stack_height": {"en":"Stack height","ja":"スタックハイト","zh-CN":"堆叠高度","ko":"스택 높이","de":"Stapelhöhe","es":"Altura de stack","fr":"Hauteur de stack","it":"Altezza stack","ru":"Высота стека","pt-BR":"Altura do stack"},
  "steel_gauge": {"en":"Steel gauge","ja":"鋼板厚","zh-CN":"钢材厚度","ko":"강판 두께","de":"Stahlstärke","es":"Calibre del acero","fr":"Épaisseur d'acier","it":"Spessore acciaio","ru":"Толщина стали","pt-BR":"Espessura do aço"},
  "stiffness": {"en":"Stiffness","ja":"硬さ","zh-CN":"硬度","ko":"강성","de":"Steifigkeit","es":"Rigidez","fr":"Rigidité","it":"Rigidità","ru":"Жёсткость","pt-BR":"Rigidez"},
  "storage": {"en":"Storage","ja":"容量","zh-CN":"存储","ko":"저장 용량","de":"Speicher","es":"Almacenamiento","fr":"Stockage","it":"Memoria","ru":"Память","pt-BR":"Armazenamento"},
  "storage_compartment": {"en":"Storage compartment","ja":"収納スペース","zh-CN":"储物空间","ko":"수납 공간","de":"Stauraum","es":"Compartimento","fr":"Compartiment","it":"Vano portaoggetti","ru":"Отделение для хранения","pt-BR":"Compartimento"},
  "strap": {"en":"Strap","ja":"ストラップ","zh-CN":"表带","ko":"스트랩","de":"Armband","es":"Correa","fr":"Bracelet","it":"Cinturino","ru":"Ремешок","pt-BR":"Pulseira"},
  "strap_type": {"en":"Strap type","ja":"ストラップ種類","zh-CN":"表带类型","ko":"스트랩 유형","de":"Armbandtyp","es":"Tipo de correa","fr":"Type de bracelet","it":"Tipo di cinturino","ru":"Тип ремешка","pt-BR":"Tipo de pulseira"},
  "stretch": {"en":"Stretch","ja":"ストレッチ性","zh-CN":"弹力","ko":"신축성","de":"Dehnbarkeit","es":"Elasticidad","fr":"Extensibilité","it":"Elasticità","ru":"Эластичность","pt-BR":"Elasticidade"},
  "stud_pattern": {"en":"Stud pattern","ja":"スタッドパターン","zh-CN":"鞋钉布局","ko":"스터드 패턴","de":"Stollenmuster","es":"Patrón de tacos","fr":"Configuration des crampons","it":"Configurazione tacchetti","ru":"Расположение шипов","pt-BR":"Padrão de travas"},
  "suction_pa": {"en":"Suction","ja":"吸引力","zh-CN":"吸力","ko":"흡입력","de":"Saugleistung","es":"Succión","fr":"Aspiration","it":"Aspirazione","ru":"Сила всасывания","pt-BR":"Sucção"},
  "sugars": {"en":"Sugars","ja":"糖質","zh-CN":"糖分","ko":"당류","de":"Zucker","es":"Azúcares","fr":"Sucres","it":"Zuccheri","ru":"Сахара","pt-BR":"Açúcares"},
  "suitable_for": {"en":"Suitable for","ja":"適応対象","zh-CN":"适用人群","ko":"적합 대상","de":"Geeignet für","es":"Apto para","fr":"Convient à","it":"Adatto a","ru":"Подходит для","pt-BR":"Adequado para"},
  "sulfate_free": {"en":"Sulfate free","ja":"サルフェートフリー","zh-CN":"无硫酸盐","ko":"황산염 무첨가","de":"Sulfatfrei","es":"Sin sulfatos","fr":"Sans sulfates","it":"Senza solfati","ru":"Без сульфатов","pt-BR":"Sem sulfatos"},
  "support_type": {"en":"Support type","ja":"サポートタイプ","zh-CN":"支撑类型","ko":"지지 유형","de":"Stützart","es":"Tipo de soporte","fr":"Type de soutien","it":"Tipo di supporto","ru":"Тип поддержки","pt-BR":"Tipo de suporte"},
  "surface": {"en":"Surface","ja":"表面","zh-CN":"表面","ko":"표면","de":"Oberfläche","es":"Superficie","fr":"Surface","it":"Superficie","ru":"Поверхность","pt-BR":"Superfície"},
  "surface_type": {"en":"Surface type","ja":"表面タイプ","zh-CN":"表面类型","ko":"표면 유형","de":"Oberflächenart","es":"Tipo de superficie","fr":"Type de surface","it":"Tipo di superficie","ru":"Тип поверхности","pt-BR":"Tipo de superfície"},
  "system": {"en":"System","ja":"システム","zh-CN":"系统","ko":"시스템","de":"System","es":"Sistema","fr":"Système","it":"Sistema","ru":"Система","pt-BR":"Sistema"},
  "tape_type": {"en":"Tape type","ja":"テープ種類","zh-CN":"胶带类型","ko":"테이프 유형","de":"Bandtyp","es":"Tipo de cinta","fr":"Type de bande","it":"Tipo di nastro","ru":"Тип ленты","pt-BR":"Tipo de fita"},
  "target_area": {"en":"Target area","ja":"対象部位","zh-CN":"目标部位","ko":"타깃 부위","de":"Zielbereich","es":"Zona objetivo","fr":"Zone ciblée","it":"Zona target","ru":"Целевая зона","pt-BR":"Área-alvo"},
  "temp_range": {"en":"Temp range","ja":"温度範囲","zh-CN":"温度范围","ko":"온도 범위","de":"Temperaturbereich","es":"Rango de temperatura","fr":"Plage de température","it":"Intervallo di temperatura","ru":"Диапазон температур","pt-BR":"Faixa de temperatura"},
  "temperature_range": {"en":"Temperature range","ja":"温度範囲","zh-CN":"温度范围","ko":"온도 범위","de":"Temperaturbereich","es":"Rango de temperatura","fr":"Plage de température","it":"Intervallo di temperatura","ru":"Диапазон температур","pt-BR":"Faixa de temperatura"},
  "term_range": {"en":"Term range","ja":"期間範囲","zh-CN":"期限范围","ko":"기간 범위","de":"Laufzeitbereich","es":"Rango de plazo","fr":"Plage de durée","it":"Intervallo di durata","ru":"Диапазон срока","pt-BR":"Faixa de prazo"},
  "throw_type": {"en":"Throw type","ja":"投影方式","zh-CN":"投影方式","ko":"투사 방식","de":"Projektionsart","es":"Tipo de proyección","fr":"Type de projection","it":"Tipo di proiezione","ru":"Тип проекции","pt-BR":"Tipo de projeção"},
  "timer": {"en":"Timer","ja":"タイマー","zh-CN":"定时器","ko":"타이머","de":"Timer","es":"Temporizador","fr":"Minuteur","it":"Timer","ru":"Таймер","pt-BR":"Temporizador"},
  "total_fat": {"en":"Total fat","ja":"脂質","zh-CN":"脂肪总量","ko":"총 지방","de":"Fett gesamt","es":"Grasas totales","fr":"Lipides totaux","it":"Grassi totali","ru":"Всего жиров","pt-BR":"Gorduras totais"},
  "touchscreen": {"en":"Touchscreen","ja":"タッチスクリーン","zh-CN":"触摸屏","ko":"터치스크린","de":"Touchscreen","es":"Pantalla táctil","fr":"Écran tactile","it":"Touchscreen","ru":"Сенсорный экран","pt-BR":"Tela sensível ao toque"},
  "traction": {"en":"Traction","ja":"グリップ力","zh-CN":"抓地力","ko":"접지력","de":"Grip","es":"Tracción","fr":"Adhérence","it":"Aderenza","ru":"Сцепление","pt-BR":"Tração"},
  "treatment_time": {"en":"Treatment time","ja":"施術時間","zh-CN":"治疗时间","ko":"트리트먼트 시간","de":"Behandlungsdauer","es":"Tiempo de tratamiento","fr":"Durée du traitement","it":"Tempo di trattamento","ru":"Время процедуры","pt-BR":"Tempo de tratamento"},
  "trial_period": {"en":"Trial period","ja":"試用期間","zh-CN":"试用期","ko":"체험 기간","de":"Testzeitraum","es":"Periodo de prueba","fr":"Période d'essai","it":"Periodo di prova","ru":"Пробный период","pt-BR":"Período de teste"},
  "type": {"en":"Type","ja":"タイプ","zh-CN":"类型","ko":"유형","de":"Typ","es":"Tipo","fr":"Type","it":"Tipo","ru":"Тип","pt-BR":"Tipo"},
  "upper_material": {"en":"Upper material","ja":"アッパー素材","zh-CN":"鞋面材质","ko":"갑피 소재","de":"Obermaterial","es":"Material del empeine","fr":"Matière de la tige","it":"Materiale tomaia","ru":"Материал верха","pt-BR":"Material do cabedal"},
  "use": {"en":"Use","ja":"用途","zh-CN":"用途","ko":"용도","de":"Verwendung","es":"Uso","fr":"Usage","it":"Uso","ru":"Применение","pt-BR":"Uso"},
  "use_frequency": {"en":"Use frequency","ja":"使用頻度","zh-CN":"使用频率","ko":"사용 빈도","de":"Anwendungshäufigkeit","es":"Frecuencia de uso","fr":"Fréquence d'utilisation","it":"Frequenza d'uso","ru":"Частота использования","pt-BR":"Frequência de uso"},
  "use_position": {"en":"Use position","ja":"使用姿勢","zh-CN":"使用位置","ko":"사용 자세","de":"Anwendungsposition","es":"Posición de uso","fr":"Position d'utilisation","it":"Posizione d'uso","ru":"Положение при использовании","pt-BR":"Posição de uso"},
  "use_type": {"en":"Use type","ja":"使用タイプ","zh-CN":"使用类型","ko":"사용 유형","de":"Anwendungsart","es":"Tipo de uso","fr":"Type d'utilisation","it":"Tipo d'uso","ru":"Тип использования","pt-BR":"Tipo de uso"},
  "user_profiles": {"en":"User profiles","ja":"ユーザープロファイル","zh-CN":"用户档案","ko":"사용자 프로필","de":"Benutzerprofile","es":"Perfiles de usuario","fr":"Profils utilisateur","it":"Profili utente","ru":"Профили пользователей","pt-BR":"Perfis de usuário"},
  "uv_protection": {"en":"UV protection","ja":"UVカット","zh-CN":"UV 防护","ko":"UV 차단","de":"UV-Schutz","es":"Protección UV","fr":"Protection UV","it":"Protezione UV","ru":"UV-защита","pt-BR":"Proteção UV"},
  "vibrating": {"en":"Vibrating","ja":"振動機能","zh-CN":"振动","ko":"진동","de":"Vibrierend","es":"Vibración","fr":"Vibration","it":"Vibrazione","ru":"Вибрация","pt-BR":"Vibração"},
  "voice_assistants": {"en":"Voice assistants","ja":"音声アシスタント","zh-CN":"语音助手","ko":"음성 비서","de":"Sprachassistenten","es":"Asistentes de voz","fr":"Assistants vocaux","it":"Assistenti vocali","ru":"Голосовые помощники","pt-BR":"Assistentes de voz"},
  "volume": {"en":"Volume","ja":"容量","zh-CN":"容量","ko":"용량","de":"Volumen","es":"Volumen","fr":"Volume","it":"Volume","ru":"Объём","pt-BR":"Volume"},
  "warranty": {"en":"Warranty","ja":"保証","zh-CN":"保修","ko":"보증","de":"Garantie","es":"Garantía","fr":"Garantie","it":"Garanzia","ru":"Гарантия","pt-BR":"Garantia"},
  "wash_options": {"en":"Wash options","ja":"洗濯コース","zh-CN":"洗涤选项","ko":"세탁 옵션","de":"Waschoptionen","es":"Opciones de lavado","fr":"Options de lavage","it":"Opzioni di lavaggio","ru":"Режимы стирки","pt-BR":"Opções de lavagem"},
  "washable": {"en":"Washable","ja":"洗濯可能","zh-CN":"可水洗","ko":"세척 가능","de":"Waschbar","es":"Lavable","fr":"Lavable","it":"Lavabile","ru":"Можно стирать","pt-BR":"Lavável"},
  "water_resistance": {"en":"Water resistance","ja":"防水性能","zh-CN":"防水性能","ko":"방수 성능","de":"Wasserbeständigkeit","es":"Resistencia al agua","fr":"Résistance à l'eau","it":"Resistenza all'acqua","ru":"Водостойкость","pt-BR":"Resistência à água"},
  "water_resistant": {"en":"Water resistant","ja":"防水","zh-CN":"防水","ko":"방수","de":"Wasserabweisend","es":"Resistente al agua","fr":"Résistant à l'eau","it":"Resistente all'acqua","ru":"Водостойкий","pt-BR":"Resistente à água"},
  "water_tank": {"en":"Water tank","ja":"水タンク","zh-CN":"水箱","ko":"물탱크","de":"Wassertank","es":"Depósito de agua","fr":"Réservoir d'eau","it":"Serbatoio acqua","ru":"Резервуар для воды","pt-BR":"Reservatório de água"},
  "waterproof": {"en":"Waterproof","ja":"完全防水","zh-CN":"防水","ko":"완전 방수","de":"Wasserdicht","es":"Impermeable","fr":"Imperméable","it":"Impermeabile","ru":"Водонепроницаемый","pt-BR":"À prova d'água"},
  "waterproofing": {"en":"Waterproofing","ja":"防水加工","zh-CN":"防水处理","ko":"방수 처리","de":"Imprägnierung","es":"Impermeabilización","fr":"Imperméabilisation","it":"Impermeabilizzazione","ru":"Водозащита","pt-BR":"Impermeabilização"},
  "wear_time_claim": {"en":"Wear time claim","ja":"持続時間","zh-CN":"持妆时长","ko":"지속 시간","de":"Tragedauer","es":"Duración declarada","fr":"Tenue annoncée","it":"Durata dichiarata","ru":"Заявленная стойкость","pt-BR":"Duração declarada"},
  "weight_capacity": {"en":"Weight capacity","ja":"耐荷重","zh-CN":"承重","ko":"허용 하중","de":"Tragfähigkeit","es":"Capacidad de peso","fr":"Capacité de charge","it":"Portata massima","ru":"Грузоподъёмность","pt-BR":"Capacidade de peso"},
  "weight_increments": {"en":"Weight increments","ja":"重量刻み","zh-CN":"重量增量","ko":"중량 단위","de":"Gewichtsstufen","es":"Incrementos de peso","fr":"Incréments de poids","it":"Incrementi di peso","ru":"Шаг веса","pt-BR":"Incrementos de peso"},
  "weight_options": {"en":"Weight options","ja":"重量バリエーション","zh-CN":"重量选项","ko":"중량 옵션","de":"Gewichtsoptionen","es":"Opciones de peso","fr":"Options de poids","it":"Opzioni di peso","ru":"Варианты веса","pt-BR":"Opções de peso"},
  "weight_range": {"en":"Weight range","ja":"重量範囲","zh-CN":"重量范围","ko":"중량 범위","de":"Gewichtsbereich","es":"Rango de peso","fr":"Plage de poids","it":"Gamma di peso","ru":"Диапазон веса","pt-BR":"Faixa de peso"},
  "weight_range_or_resistance": {"en":"Weight range or resistance","ja":"重量・負荷範囲","zh-CN":"重量或阻力范围","ko":"중량 또는 저항 범위","de":"Gewichts- oder Widerstandsbereich","es":"Rango de peso o resistencia","fr":"Plage de poids ou résistance","it":"Gamma di peso o resistenza","ru":"Диапазон веса или сопротивления","pt-BR":"Faixa de peso ou resistência"},
  "weighted": {"en":"Weighted","ja":"加重式","zh-CN":"加重","ko":"중량 적용","de":"Gewichtet","es":"Con peso","fr":"Lesté","it":"Appesantito","ru":"С утяжелением","pt-BR":"Com peso"},
  "weighted_hem": {"en":"Weighted hem","ja":"裾ウェイト","zh-CN":"加重下摆","ko":"밑단 무게추","de":"Gewichteter Saum","es":"Dobladillo con peso","fr":"Ourlet lesté","it":"Orlo appesantito","ru":"Утяжелённый низ","pt-BR":"Barra com peso"},
  "wheels": {"en":"Wheels","ja":"キャスター","zh-CN":"滚轮","ko":"바퀴","de":"Räder","es":"Ruedas","fr":"Roues","it":"Ruote","ru":"Колёса","pt-BR":"Rodas"},
  "wifi_standard": {"en":"Wifi standard","ja":"Wi-Fi規格","zh-CN":"Wi-Fi 标准","ko":"Wi-Fi 표준","de":"WLAN-Standard","es":"Estándar wifi","fr":"Norme Wi-Fi","it":"Standard Wi-Fi","ru":"Стандарт Wi-Fi","pt-BR":"Padrão Wi-Fi"},
  "wordpress_quick_install": {"en":"WordPress quick install","ja":"WordPress簡単インストール","zh-CN":"WordPress 快速安装","ko":"WordPress 빠른 설치","de":"WordPress-Schnellinstallation","es":"Instalación rápida de WordPress","fr":"Installation rapide de WordPress","it":"Installazione rapida di WordPress","ru":"Быстрая установка WordPress","pt-BR":"Instalação rápida do WordPress"},
  "wrist_support": {"en":"Wrist support","ja":"リストサポート","zh-CN":"腕部支撑","ko":"손목 지지","de":"Handgelenkstütze","es":"Soporte de muñeca","fr":"Soutien du poignet","it":"Supporto al polso","ru":"Поддержка запястья","pt-BR":"Suporte de pulso"},
};

export function specLabel(fieldKey: string, locale: string): string {
  const m = SPEC_LABELS[fieldKey];
  if (!m) return fieldKey.replace(/_/g, " ").replace(/^./, (c) => c.toUpperCase());
  return m[locale] ?? m.en ?? fieldKey;
}
